Repository apache/dolphinscheduler, pull requests merged in 2019-07, with the labels that each got.

#288 Feature/qiye_weixin
  escheduler-alert/pom.xml
  escheduler-alert/src/main/java/cn/escheduler/alert/utils/Constants.java
  escheduler-alert/src/main/java/cn/escheduler/alert/utils/EnterpriseWeChatUtils.java
  escheduler-alert/src/main/java/cn/escheduler/alert/utils/FuncUtils.java
  escheduler-alert/src/main/resources/alert.properties
  escheduler-alert/src/test/java/cn/escheduler/alert/utils/EnterpriseWeChatUtilsTest.java
Labels: new feature

#543 optimize datasource connection params safety
  escheduler-api/src/main/java/cn/escheduler/api/service/DataSourceService.java
  escheduler-common/src/main/java/cn/escheduler/common/Constants.java
Labels: enhancement

#606 double check 变量需要volatile修饰
  escheduler-common/src/main/java/cn/escheduler/common/queue/TaskQueueZkImpl.java
Labels: enhancement

#629 update i18n, delete zk links
  escheduler-api/src/main/java/cn/escheduler/api/service/MonitorService.java
  escheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
  escheduler-ui/src/js/module/i18n/locale/en_US.js
  escheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: bug
