Repository apache/dolphinscheduler, pull requests merged in 2019-09, with the labels that each got.

#752 fix bug #734
  escheduler-api/src/main/java/cn/escheduler/api/controller/ExecutorController.java
Labels: bug

#680 bug fixed and support for properies file type editing
  escheduler-common/src/main/java/cn/escheduler/common/zk/AbstractZKClient.java
  escheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/_source/common.js
  escheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/details/_source/utils.js
Labels: enhancement

#746 issue#728
  escheduler-alert/src/main/java/cn/escheduler/alert/utils/Constants.java
  escheduler-alert/src/main/java/cn/escheduler/alert/utils/MailUtils.java
  escheduler-alert/src/main/resources/alert.properties
Labels: enhancement

#818 Fix singleton with volatile
  escheduler-alert/src/main/java/cn/escheduler/alert/AlertServer.java
  escheduler-common/src/main/java/cn/escheduler/common/thread/ThreadPoolExecutors.java
Labels: enhancement

#816 Replace StringBuffer with StringBuilder inside the method
  escheduler-common/src/main/java/cn/escheduler/common/shell/AbstractShell.java
  escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ProcessInstanceMapperProvider.java
  escheduler-dao/src/main/java/cn/escheduler/dao/mapper/ScheduleMapperProvider.java
  escheduler-dao/src/main/java/cn/escheduler/dao/mapper/TaskInstanceMapperProvider.java
Labels: enhancement

#711 flink task support(flink 任务支持)
  escheduler-common/src/main/java/cn/escheduler/common/Constants.java
  escheduler-common/src/main/java/cn/escheduler/common/enums/TaskType.java
  escheduler-common/src/main/java/cn/escheduler/common/task/flink/FlinkParameters.java
  escheduler-common/src/main/java/cn/escheduler/common/utils/TaskParametersUtils.java
  escheduler-server/src/main/java/cn/escheduler/server/utils/FlinkArgsUtils.java
  escheduler-server/src/main/java/cn/escheduler/server/worker/task/AbstractTask.java
  escheduler-server/src/main/java/cn/escheduler/server/worker/task/TaskManager.java
  escheduler-server/src/main/java/cn/escheduler/server/worker/task/flink/FlinkTask.java
  escheduler-ui/src/js/conf/home/pages/dag/_source/config.js
  escheduler-ui/src/js/conf/home/pages/dag/_source/dag.scss
  escheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
  escheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
  escheduler-ui/src/js/conf/home/pages/dag/img/toobar_flink.svg
  escheduler-ui/src/js/module/i18n/locale/zh_CN.js
  escheduler-ui/src/view/docs/zh_CN/_book/images/flink_edit.png
  script/env/.escheduler_env.sh
Labels: new feature

#886 #885 Fix comment error in taskZkInfo function
  escheduler-dao/src/main/java/cn/escheduler/dao/ProcessDao.java
Labels: enhancement

#873 Delete the'babel-plugin-transform-remove-console'dependency package
  escheduler-ui/package.json
  escheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/timing.vue
  escheduler-ui/src/js/conf/home/pages/projects/pages/index/_source/defineUserCount.vue
  escheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
  escheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/_source/list.vue
  escheduler-ui/src/js/module/i18n/locale/en_US.js
  escheduler-ui/src/js/module/i18n/locale/zh_CN.js
  escheduler-ui/src/lib/@analysys/ans-ui/package.json
Labels: enhancement
