Repository apache/dolphinscheduler, pull requests merged in 2020-10, with the labels that each got.

#3847 [Feature][api]Export and import workflow add processDefinitionDescription #3808
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
Labels: enhancement

#3996 [Fix-#3994 ][sql-script] Pull Request fix import dolphinscheduler_mysql.sql insert admin user data
  sql/dolphinscheduler_mysql.sql
Labels: First-time contributor

#3949 [Feature-3941][ui] Remove tenant name
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TenantController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TenantService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/resources/i18n/messages.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_en_US.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_zh_CN.properties
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TenantControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Tenant.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/User.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TenantMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ResourceMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TenantMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UserMapperTest.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumerTest.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/_source/selectTenant.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/createTenement.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/user/pages/account/_source/info.vue
  dolphinscheduler-ui/src/js/conf/home/store/security/actions.js
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
  e2e/src/test/java/org/apache/dolphinscheduler/locator/security/TenantManageLocator.java
  e2e/src/test/java/org/apache/dolphinscheduler/page/security/TenantManagePage.java
  e2e/src/test/resources/testData/security_zh_cn.yml
  pom.xml
  sql/create/release-1.0.0_schema/mysql/dolphinscheduler_ddl.sql
  sql/create/release-1.2.0_schema/postgresql/dolphinscheduler_ddl.sql
  sql/dolphinscheduler-postgre.sql
  sql/dolphinscheduler_mysql.sql
Labels: First-time contributor

#3968 [Improvement][script] daemon script usage
  script/dolphinscheduler-daemon.sh
Labels: First-time contributor, Waiting for user feedback
