Repository apache/dolphinscheduler, pull requests merged in 2020-11, with the labels that each got.

#4006 [Improvement-4005][UI] Enhance user experience, add close button, return to the previous page
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/tree/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/timing/index.vue
  dolphinscheduler-ui/src/js/module/components/listConstruction/listConstruction.vue
Labels: UI

#4081 [Fix-4054][Api] Fix The last week of the month for adding/editing tim…
  dolphinscheduler-ui/src/js/module/components/crontab/source/_times/day.vue
Labels: First-time contributor, UI

#4088 [Fix-4090][dao] Add null judgment
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java
Labels: First-time contributor

#3995 [Improvement-3988][UI] Enhance user experience, add close button to file details page
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/details/index.vue
Labels: UI

#4121 [Feature][API]enable response resources gzip compression
  dolphinscheduler-api/src/main/resources/application-api.properties
Labels: First-time contributor
