Repository apache/dolphinscheduler, pull requests merged in 2020-12, with the labels that each got.

#4110 [Improvement][UI] download url resolve and security page disappear delay problem under GENERAL_USER
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/log.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/details/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/subdirectory/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/function/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/resource/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/subUdfDirectory/_source/list.vue
  dolphinscheduler-ui/src/js/module/download/index.js
  dolphinscheduler-ui/src/js/module/permissions/index.js
Labels: UI

#4150 [Fix-4143][jar upgrade]upgrade quartz version to 2.3.0
  dolphinscheduler-api/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-service/pom.xml
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: First-time contributor

#4186 [FIX-#4184][server-api] load TaskInstance slow
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
Labels: First-time contributor

#4127 fix bug #4125
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/DBTaskAckCommand.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/DBTaskResponseCommand.java
Labels: First-time contributor, Waiting for user feedback

#4221 deleted invalid code as assigned in issue 4215
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
Labels: First-time contributor

#4162 [Fix][UI]: fix re-login problem in new tab and state synchronization problem in multiple tabs
  dolphinscheduler-ui/src/js/conf/home/App.vue
  dolphinscheduler-ui/src/js/module/io/index.js
  dolphinscheduler-ui/src/js/module/visibility/index.js
Labels: UI

#4262 remove AbstractTask.getCurTaskParamsClass()and replace with TaskParametersUtils.getParameters()
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractTask.java
Labels: First-time contributor

#4265 [fix-4264][UI]The deletion function of version information in DAG diagram cannot work normally
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
Labels: UI

#4266 [improvement][config] Update datasource.properties，add mysql meta data template
  dolphinscheduler-dao/src/main/resources/datasource.properties
Labels: First-time contributor

#4285 [Improvement] Add Flink job name
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: First-time contributor

#4290 [Fix-4289][*] Flink name with disappeared and unescaped problem
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ArgsUtils.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtils.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/LogUtils.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: UI

#4263 Dev imp server process utils
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
Labels: First-time contributor

#4344 [Fix][common] only two yarns can be selected(#4314)
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
Labels: First-time contributor
