Repository apache/dolphinscheduler, pull requests merged in 2020-07, with the labels that each got.

#3136 optimize SchedulerService.setScheduleState code
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SchedulerService.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/SchedulerServiceTest.java
Labels: enhancement

#3196 [Improvement][Server]Code Clean
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/registry/ZookeeperNodeManager.java
Labels: enhancement

#2761 simply doExecute using RetryerUtils.retryCall
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManager.java
Labels: enhancement

#3209 resolve #3096 fixbug ambari plugin the config options which has unit …
  ambari_plugin/common-services/DOLPHIN/1.3.0/package/scripts/params.py
Labels: bug

#2710 Feature add user state
  sql/dolphinscheduler-postgre.sql
  sql/dolphinscheduler_mysql.sql
  sql/upgrade/1.3.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: enhancement

#3215 fix and update k8s deploy
  ambari_plugin/common-services/DOLPHIN/1.2.1/package/scripts/params.py
  ambari_plugin/common-services/DOLPHIN/1.3.0/package/scripts/params.py
  docker/build/Dockerfile
  docker/build/README.md
  docker/build/README_zh_CN.md
  docker/build/conf/dolphinscheduler/alert.properties.tpl
  docker/build/conf/dolphinscheduler/common.properties.tpl
  docker/build/conf/dolphinscheduler/datasource.properties.tpl
  docker/build/conf/dolphinscheduler/logback/logback-alert.xml
  docker/build/conf/dolphinscheduler/zookeeper.properties.tpl
  docker/build/startup-init-conf.sh
  docker/build/startup.sh
  docker/docker-swarm/docker-compose.yml
  docker/docker-swarm/docker-stack.yml
  docker/kubernetes/dolphinscheduler/Chart.yaml
  docker/kubernetes/dolphinscheduler/README.md
  docker/kubernetes/dolphinscheduler/requirements.yaml
  docker/kubernetes/dolphinscheduler/templates/NOTES.txt
  docker/kubernetes/dolphinscheduler/templates/_helpers.tpl
  docker/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-alert.yaml
  docker/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-common.yaml
  docker/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  docker/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  docker/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-frontend.yaml
  docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  docker/kubernetes/dolphinscheduler/values.yaml
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
  dolphinscheduler-alert/src/main/resources/alert.properties
  dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtilsTest.java
  dolphinscheduler-ui/package.json
  script/dolphinscheduler-daemon.sh
Labels: enhancement

#3249 [Fix-3236][DagHelper]getFlowNodeListPost/getFlowNodeListPre time complexity O(N^N)
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java
Labels: enhancement

#3349 [Fix-3338][ui] Fix the warning when user do not fill the node blank
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: enhancement

#3350 [Improvement][common] HttpClient singleton mode #3332
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/HttpUtilsTest.java
Labels: enhancement

#3304 [Test][server] Fix Test ContextConfiguration error.
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumerTest.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/registry/ZookeeperNodeManagerTest.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/processor/TaskCallbackServiceTest.java
  pom.xml
Labels: bug

#3073 adds waterdrop plugin
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/TaskType.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/TaskParametersUtils.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/config.js
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.scss
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/waterdrop.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/img/toolbar_WATERDROP.png
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: new feature
