Repository apache/dolphinscheduler, pull requests merged in 2021-02, with the labels that each got.

#4569 [Improvement-4568][API] When the workflow definition name validation API fails, the system prompts that the workflow definition name already exists
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
Labels: improvement

#4559 [Improvement][Api] Use WebUtils.getCookie instead of BaseService.getCookie
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/interceptor/LocaleChangeInterceptor.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/BaseService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SessionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/BaseServiceTest.java
Labels: improvement

#4316 Improvement/UI no #3725
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/_source/list.vue
Labels: First-time contributor, UI, Waiting for user feedback, discussion

#4688 [Fix-4640][UI] Fixed a 404 error when the project name contains "http"
  dolphinscheduler-ui/src/js/module/io/index.js
Labels: First-time contributor

#4692 [Fix][UDF] Fix udf jar path not exist when fs.defaultFS starts with file:///
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/UDFUtils.java
Labels: bug

#4699 [Improvement][server]Add comment
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java
Labels: First-time contributor

#4593 [Improvement-4450][datasource] Hive/Spark data sources do not support multi-tenancy when Kerberos authentication is enabled
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataSourceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
  dolphinscheduler-api/src/main/resources/i18n/messages.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_en_US.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_zh_CN.properties
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CommonUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StringUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/StringUtilsTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/BaseDataSource.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/HiveDataSource.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SparkDataSource.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/datasource/BaseDataSourceTest.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
  dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/createDataSource.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: UI, backend, improvement, new feature

#4678 [Feature-#3805][server-master] global params of master
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskExecuteResponseCommand.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/TaskResponseProcessor.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseEvent.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseService.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseServiceTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: backend, new feature

#4680 [Feature-#3805][server-UI] global params of UI
  dolphinscheduler-ui.zip
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/localParams.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/shell.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
  dolphinscheduler-ui/src/js/conf/home/store/dag/mutations.js
Labels: First-time contributor, UI, new feature

#4728 [Fix-4723][UI]:Fix tips error when login with username and without password.
  dolphinscheduler-ui/src/js/conf/login/App.vue
Labels: First-time contributor, UI

#4739 [Fix-4738][Mail] Fix send mail failed instead of execute sql error
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
Labels: improvement

#4763 [Fix-4760][api][Repair dolphinscheduler-postgre.sql error sql]
  sql/dolphinscheduler-postgre.sql
Labels: First-time contributor

#4742 [Improvement-4740][UI] Set the default Tenant as default or the first exist tenant in save process
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
Labels: UI, improvement

#4744 [Fix-4741][UI] Fix task instance log not change
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/_source/list.vue
Labels: UI

#4767 [Fix-4674][UI] create warning instance and click Submit , without validate the required parameters
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/warningInstance/_source/createWarningInstance.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: UI

#4808 [Improvement][Api] add @Override on the Override method
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AccessTokenServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/MonitorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionVersionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SessionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskRecordServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UdfFuncServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkFlowLineageServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/PeerTaskInstancePriorityQueue.java
Labels: First-time contributor

#4797 [Fix-4796][UI] Fix child file upload failure and file id mixed problem
  dolphinscheduler-ui/src/js/module/components/fileUpdate/definitionUpdate.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/fileChildReUpdate.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/fileChildUpdate.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/fileReUpload.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/fileUpdate.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/resourceChildUpdate.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/udfUpdate.vue
  dolphinscheduler-ui/src/js/module/components/nav/nav.vue
Labels: UI, bug

#4618 [FIX-#4617][LoggerServer] task log can not refresh in time
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/shell/ShellCommandExecutorTest.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTaskTest.java
Labels: discussion

#4779 [Fix] while repeat running, the global parameters will not set to the user specified start parameters.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorService2Test.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
Labels: First-time contributor

#4856 [Fix-4843] Rename WORKER_GROUP to WORKER_GROUPS (#4843)
  docker/build/README.md
  docker/build/README_zh_CN.md
  docker/build/conf/dolphinscheduler/worker.properties.tpl
  docker/build/startup-init-conf.sh
  docker/docker-swarm/docker-compose.yml
  docker/docker-swarm/docker-stack.yml
  docker/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-worker.yaml
  docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  docker/kubernetes/dolphinscheduler/values.yaml
Labels: First-time contributor, bug

#4882 [Improvement-4881][Docker] Add Default Login Credentials For the Web UI are not listed in the README
  docker/build/README.md
Labels: First-time contributor

#4896 [Improvement][Common] Optimize HashMap Initial Capacity
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/BaseController.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CollectionUtils.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/quartz/QuartzExecutors.java
Labels: improvement

#4901 [Improvement][API] successful project creation returns results directly, reducing database queries
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
Labels: improvement

#4875 [Improvement][Docker/K8s] Add FAQ in docker/k8s and update outdated readme
  docker/build/README.md
  docker/build/README_zh_CN.md
  docker/build/conf/dolphinscheduler/worker.properties.tpl
  docker/docker-swarm/docker-compose.yml
  docker/docker-swarm/docker-stack.yml
  docker/kubernetes/dolphinscheduler/README.md
  dolphinscheduler-server/src/main/resources/worker.properties
Labels: Waiting for review
