Repository apache/dolphinscheduler, pull requests merged in 2021-03, with the labels that each got.

#4933 [Improvement-4925][server] need to remove unused comments in ZKMasterClient.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/zk/ZKMasterClient.java
Labels: First-time contributor

#4937 [Feature][Flink] Support parallelism input
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/flink/FlinkParameters.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtils.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtilsTest.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: UI, backend, new feature

#4906 [Fix-4905][K8s] Fix incorrect host problem in minikube
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/CommonTest.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java
Labels: bug, k8s

#4956 [Fix][Worker] Fix worker cannot start and alertClientService NullPointerException
  .github/workflows/ci_ut.yml
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/zk/ZKMasterClient.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/zk/ZookeeperOperator.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/zk/RegisterOperatorTest.java
Labels: Waiting for review

#5002 [Improvement-4837][Docker] Support docker compose file 3.1+ version and Optimize k8s template
  docker/build/README.md
  docker/build/README_zh_CN.md
  docker/docker-swarm/docker-compose.yml
  docker/docker-swarm/docker-stack.yml
  docker/kubernetes/dolphinscheduler/README.md
  docker/kubernetes/dolphinscheduler/templates/_helpers.tpl
  docker/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  docker/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  docker/kubernetes/dolphinscheduler/templates/ingress.yaml
  docker/kubernetes/dolphinscheduler/templates/secret-external-database.yaml
  docker/kubernetes/dolphinscheduler/templates/secret-external-fs-s3a.yaml
  docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  docker/kubernetes/dolphinscheduler/templates/svc-dolphinscheduler-master-headless.yaml
  docker/kubernetes/dolphinscheduler/templates/svc-dolphinscheduler-worker-headless.yaml
  docker/kubernetes/dolphinscheduler/values.yaml
Labels: docker, k8s

#4959 [Feature-4960][Spark] Add name input for Spark and improve Spark & MR args
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/spark/SparkParameters.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtils.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/SparkArgsUtils.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/mr/MapReduceTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/spark/SparkTask.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtilsTest.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/SparkArgsUtilsTest.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/spark.vue
Labels: UI, backend, improvement

#5017 [1.3.6-prepare][Feature-4960][Spark] Add name input for Spark and improve Spark & MR args #4959
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/BaseService.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/spark/SparkParameters.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/SparkArgsUtils.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/mr/MapReduceTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/spark/SparkTask.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtilsTest.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/SparkArgsUtilsTest.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/spark.vue
Labels: UI, backend

#5021 Grammar changes for README
  README.md
Labels: First-time contributor

#4943 [Improvement][worker] Optimize KillYarnJob (4939)
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/LoggerUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/LoggerUtilsTest.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessorTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogClientService.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/LogClientServiceTest.java
  pom.xml
Labels: improvement

#5016 [1.3.6-prepare][Improvement][Server&UI] Update worker group ip and unify form model #4982
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkerGroupService.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/conditions.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/dependent.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/mr.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/procedure.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/python.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sqoop.vue
Labels: UI, Waiting for review, backend

#4990 [Improvement-4988][docs] Uppercase the first letter the state of Process Instance
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/config.js
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/commcon.js
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/dependItemList.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/httpParams.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/localParams.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/nodeStatus.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/statementList.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/conditions.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/dependent.vue
  dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/_source/conditions/instance/common.js
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/_source/conditions/instance/processInstance.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/_source/conditions/instance/taskInstance.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/_source/taskRecordList/_source/conditions.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/timing.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/versions.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/timing/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/subdirectory/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/function/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/resource/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/subUdfDirectory/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/warningGroups/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/warningInstance/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/user/pages/token/_source/list.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: First-time contributor, UI, improvement

#5036 [Improvement][Worker-Task] Python Command
  docker/build/README.md
  docker/build/README_zh_CN.md
  docker/build/conf/dolphinscheduler/env/dolphinscheduler_env.sh.tpl
  docker/build/startup-init-conf.sh
  docker/docker-swarm/docker-compose.yml
  docker/docker-swarm/docker-stack.yml
  docker/kubernetes/dolphinscheduler/values.yaml
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/PythonCommandExecutor.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/EnvFileTest.java
  script/env/dolphinscheduler_env.sh
Labels: First-time contributor, improvement

#5019 [Improvement-5018][Datax] Re-assign DATAX_HOME to /opt/soft/datax instead of /opt/soft/datax/bin/datax.py
  ambari_plugin/common-services/DOLPHIN/1.3.0/configuration/dolphin-env.xml
  ambari_plugin/common-services/DOLPHIN/1.3.3/configuration/dolphin-env.xml
  docker/build/README.md
  docker/build/README_zh_CN.md
  docker/build/conf/dolphinscheduler/env/dolphinscheduler_env.sh.tpl
  docker/build/startup-init-conf.sh
  docker/docker-swarm/docker-compose.yml
  docker/docker-swarm/docker-stack.yml
  docker/kubernetes/dolphinscheduler/values.yaml
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/task/DataxParametersTest.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/datax/DataxTask.java
  script/env/dolphinscheduler_env.sh
Labels: Waiting for review, improvement

#5020 [Improvement-4971][alert|dao|service]Remove redundant PropertyUtils.class
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/PropertyUtils.java
  dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/plugin/AlertPluginManagerTest.java
  dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/plugin/EmailAlertPluginTest.java
  dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/PropertyUtilsTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/TaskRecordDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/PropertyUtils.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/quartz/QuartzExecutors.java
Labels: First-time contributor, Waiting for review, improvement

#5070 [Improvement][Dao] SQL optimization - check exist #5069
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertPluginInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkFlowLineageServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertGroupServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertPluginInstanceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/QueueServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/BooleanUtils.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/PluginDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertGroupMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertPluginInstanceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/QueueMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TenantMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/UserMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertGroupMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertPluginInstanceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/QueueMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TenantMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/AlertGroupMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/AlertPluginInstanceMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/QueueMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ResourceMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TenantMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UserMapperTest.java
Labels: improvement

#5090 [Fix-5089][UI] Fix code mirror cannot be displayed normally in sqoop task
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.scss
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/jsonBox.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/scriptBox.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/datax.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/python.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/shell.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sql.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sqoop.vue
  dolphinscheduler-ui/src/js/module/components/conditions/conditions.vue
  dolphinscheduler-ui/src/sass/common/index.scss
Labels: UI, bug

#5088 [Feature-5087][SqlTask] Add a switch to send mail and print head logs in SqlTask
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/sql/SqlParameters.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/task/SqlParametersTest.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sql.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
  pom.xml
Labels: UI, Waiting for review, backend, new feature

#5167 [Improvement-4891][docs] update DolphinScheduler slack invitation url
  README.md
  README_zh_CN.md
Labels: First-time contributor

#4722 [Fix-4721][worker]The shell background starts the YARN task scenario, and the kill function is abnormal
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StringUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/StringUtilsTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertGroupMapper.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
Labels: bug
