Repository apache/dolphinscheduler, pull requests merged in 2021-08, with the labels that each got.

#5924 [Improvement-5921][CI] Improve maven connection in CI builds
  .github/workflows/ci_backend.yml
  .github/workflows/ci_ut.yml
  docker/build/hooks/build
  docker/build/hooks/build.bat
Labels: CI&CD

#5912 [NEW FEATURE][FIX-4385] compensation task add the ability to configure parallelism
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/resources/i18n/messages_en_US.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_zh_CN.properties
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorService2Test.java
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/start.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: new feature, UI, backend

#5952 [Improvement][dao]When I search for the keyword description, the web UI shows empty
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
Labels: improvement

#5998 fix the readme typing issue
  README.md
Labels: First-time contributor

#6022 Add standalone server module to make it easier to develop and run
  docker/build/hooks/build
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/DbType.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.xml
  dolphinscheduler-dist/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-standalone-server/pom.xml
  dolphinscheduler-standalone-server/src/main/java/org/apache/dolphinscheduler/server/StandaloneServer.java
  dolphinscheduler-standalone-server/src/main/resources/registry.properties
  pom.xml
  script/dolphinscheduler-daemon.sh
  sql/dolphinscheduler_h2.sql
  tools/dependencies/known-dependencies.txt
Labels: enhancement

#5939 [Feature-#5273][UI] Task node of SWITCH
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/config.js
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.scss
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/switch.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/img/toolbar_SWITCH.png
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: new feature, UI

#5941 [Improvement][Api Module]split alert group list-paging interface
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AlertGroupController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/AlertGroupService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertGroupServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/AlertGroupControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertGroupServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertGroupMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/vo/AlertGroupVo.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertGroupMapper.xml
Labels: First-time contributor, improvement

#6026 [FIX-#6007]Wrong complement date
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/entity/TaskExecutionContext.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/datax/DataxTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/flink/FlinkTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/http/HttpTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/mr/MapReduceTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/python/PythonTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/spark/SparkTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sqoop/SqoopTask.java
Labels: bug

#6042 Enhancement Translation
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formLineModel.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
  dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/createDataSource.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/start.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/timing.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/create/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/createFolder/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/createUdfFolder/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/edit/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/subFile/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/subFileFolder/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/createUdfFolder/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/subUdfFolder/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/user/pages/password/_source/info.vue
  dolphinscheduler-ui/src/js/conf/login/App.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/udfUpdate.vue
  dolphinscheduler-ui/src/js/module/components/popup/popover.vue
  dolphinscheduler-ui/src/js/module/components/popup/popup.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: First-time contributor

#6040 [Fix-6038][ui] width of "SQL Statement" in Dag FormLineModal will be …
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.scss
Labels: First-time contributor, UI

#6004 [Improvement] Fix inefficient map iterator
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/AbstractParameters.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/sql/SqlParameters.java
Labels: First-time contributor
