Repository apache/dolphinscheduler, pull requests merged in 2021-06, with the labels that each got.

#5574 [Improvement-5569][dolphinscheduler-api] verify proccess definition name fail
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
Labels: First-time contributor, improvement

#5588 [Fix-5559][Master Server] Master Server was shutdown but the process still in system
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/bean/SpringApplicationContext.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/zk/CuratorZookeeperClient.java
Labels: First-time contributor

#5606 [Fix-5583][sql] fix table name error in sql upgrade script
  sql/upgrade/1.4.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: First-time contributor

#5572 [Improvement-5539][Master] Check status of taskInstance from cache
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/cache/impl/TaskInstanceCacheManagerImpl.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThread.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/cache/impl/TaskInstanceCacheManagerImplTest.java
  pom.xml
Labels: First-time contributor, improvement

#5568 [Improvement-5567][UI] Add project id in web ui url for sharing and project name in project page
  dolphinscheduler-ui/.babelrc
  dolphinscheduler-ui/package.json
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/tree/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/index/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/kinship/_source/graphGrid.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/index.vue
  dolphinscheduler-ui/src/js/conf/home/router/index.js
  dolphinscheduler-ui/src/js/conf/home/store/dag/mutations.js
  dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
  dolphinscheduler-ui/src/js/conf/home/store/projects/actions.js
  dolphinscheduler-ui/src/js/module/components/secondaryMenu/secondaryMenu.vue
Labels: UI, improvement

#5631 [Fix-5483] [Bug][API] Can't view variables in the page of Process Instance
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/JSONUtilsTest.java
Labels: First-time contributor, bug

#5611 [Fix-5540][JSON Split] Fix some new tables and fields are missing in the sql upgrade script
  sql/dolphinscheduler_mysql.sql
  sql/dolphinscheduler_postgre.sql
  sql/upgrade/1.4.0_schema/mysql/dolphinscheduler_ddl.sql
  sql/upgrade/1.4.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: First-time contributor, bug

#5632 [Improvement][SQL] Query return number In SQL should be configurable
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/sql/SqlParameters.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/task/SqlParametersTest.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTaskTest.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/sql.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: UI, backend, improvement

#5627 Fix the bug `Edit User Info will always shows failed.`
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
Labels: First-time contributor, UI

#5556 [Bug][WorkerServer] SqlTask NullPointerException
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTaskTest.java
Labels: First-time contributor, improvement

#5652 [Improvement] The newly introduced spi pugin support work in windows os.
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/plugin/DolphinPluginDiscovery.java
Labels: enhancement, plug-in

#5453 [Improvement-5452][Task] ds flink task support submit a PyFlink job via the CLI
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/FlinkArgsUtils.java
Labels: enhancement

#5656 [Bug-Fix: 5655]Update TaskInstanceCacheManagerImpl.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/cache/impl/TaskInstanceCacheManagerImpl.java
Labels: First-time contributor, bug

#5628 [Feature-#5565][UI] Global Param passed by sense dependencies
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/commcon.js
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
Labels: First-time contributor, UI

#5664 docker-compose wrong env
  docker/build/conf/dolphinscheduler/registry.properties.tpl
  docker/docker-swarm/config.env.sh
Labels: First-time contributor, docker

#5666 [Improvement][API] Simplify the Check of Result by introducing several new methods.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/Result.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/AccessTokenControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/AlertGroupControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/DataAnalysisControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/DataSourceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ExecutorControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/LoggerControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/LoginControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/MonitorControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProjectControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/QueueControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ResourcesControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/SchedulerControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TaskInstanceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TenantControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/UsersControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/WorkFlowLineageControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/WorkerGroupControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/exceptions/ApiExceptionHandlerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/LoggerServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/QueueServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/ResultTest.java
Labels: improvement

#5663 [Improvement] Version Info list cannot jump to a page greater than 1st
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/versions.vue
Labels: UI, improvement

#5681 [Improvement-5405][Docker/K8s] Adapt to registry SPI
  docker/build/conf/dolphinscheduler/registry.properties.tpl
  docker/build/startup-init-conf.sh
  docker/docker-swarm/config.env.sh
  docker/kubernetes/dolphinscheduler/templates/_helpers.tpl
  docker/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  docker/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  docker/kubernetes/dolphinscheduler/values.yaml
  dolphinscheduler-alert/src/main/resources/logback-alert.xml
  dolphinscheduler-server/src/main/resources/logback-master.xml
  dolphinscheduler-service/src/main/resources/registry.properties
Labels: docker, k8s

#5684 [Improvement][UI] Update the update time after the user information is successfully modified
  dolphinscheduler-ui/src/js/conf/home/pages/user/pages/account/_source/info.vue
Labels: UI, improvement

#5691 Improved shell task execution result log information, adding process.…
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
Labels: First-time contributor

#5696 【Improvement】Enhanced parameter verification when creating warning group and alarm plugin
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/warningGroups/_source/createWarning.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/warningInstance/_source/createWarningInstance.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: UI, plug-in

#5707 [Improvement][common] Upgrade the version of fastjson from 1.2.61 to 1.2.75
  dolphinscheduler-dist/release-docs/LICENSE
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: improvement

#5700 [Fix-5699][UI] Fix update user error in user information
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/createUser.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/user/pages/account/_source/info.vue
Labels: UI, bug

#5676 [Improvement] the automatically generated spi service name in alert-plugin is wrong
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/plugin/DolphinPluginDiscovery.java
Labels: plug-in, win-os

#5723 [Improvement-5622][project management] Modify the title
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: First-time contributor, UI
