Repository apache/dolphinscheduler, pull requests merged in 2021-05, with the labels that each got.

#5421 [Improvement] [UI]Change the status box text
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/_source/conditions/instance/common.js
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: improvement

#5409 [Improvement][Dao] Database add connection check (#5408)
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/ConnectionFactory.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.java
Labels: improvement

#5400 [Improvement][Alert] Replace HSSFWorkbook
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailConstants.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/MailSender.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/NOTICE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-SparseBitSet.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-curvesapi.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-poi-ooxml-schemas.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-poi-ooxml.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-xmlbeans.txt
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: improvement

#5442 [Bug][Service] All tasks that need to send attachment will fail due to chennel idle
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/handler/NettyClientHandler.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/handler/NettyServerHandler.java
Labels: bug

#5426 [Feature][Plugin-Email] Numeric data type support in email attachment #5424
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java
Labels: improvement

#5476 [Improvement][Api] Upload resource to remote failed, the local tmp file need to be cleared
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
Labels: improvement

#5492 [Improvement][Task] Remove deprecated TaskRecordDao and simply the after() method in the AbstractTask class
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskRecordController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TaskRecordService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskRecordServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TaskRecordControllerTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/TaskRecordDao.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractTask.java
Labels: First-time contributor, improvement

#5441 [Improvement-5440][Maven] Project module maven dependency optimization
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-dingtalk/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-script/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-slack/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-wechat/pom.xml
  dolphinscheduler-alert-plugin/pom.xml
  dolphinscheduler-alert/pom.xml
  dolphinscheduler-api/pom.xml
  dolphinscheduler-common/pom.xml
  dolphinscheduler-dao/pom.xml
  dolphinscheduler-remote/pom.xml
  dolphinscheduler-server/pom.xml
  dolphinscheduler-service/pom.xml
  dolphinscheduler-spi/pom.xml
  pom.xml
Labels: improvement

#5533 [Improvement-5527][api-server] failed find any kerberos
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CommonUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/CommonUtilsTest.java
Labels: improvement

#5211 [Improvement][Server] Must restart master if Zk reconnect (#5210)
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistry.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistry.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/zk/ZookeeperOperator.java
Labels: bug

#5552 [Bug][Master] remove check with executePath when kill yarn job
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
Labels: bug
