Repository apache/dolphinscheduler, pull requests merged in 2021-07, with the labels that each got.

#5768 [#5748][refactor]get more reasonable monitoring indexes of the zk cluster
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/FourLetterWordMain.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/ZooKeeperState.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/ZookeeperMonitor.java
  dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/_source/zookeeperList.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: improvement

#5776 [Improvement#5741][Worker] Improve task process status log
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
Labels: improvement

#5774 [Improvement-5773][server] need to support two parameters related to task
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/LoggerUtils.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ParamUtils.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/ShellCommandExecutor.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/shell/ShellTask.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/ParamUtilsTest.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/worker/shell/ShellCommandExecutorTest.java
Labels: First-time contributor, improvement

#5787 [FIX-5786][Improvement][Server] When the Worker turns down, the MasterServer cannot handle the Remove event correctly and throws NPE
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryDataListener.java
Labels: bug

#5797 [Imporvement-5621][job instance] start-time and end-time
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
Labels: First-time contributor, improvement

#5735 [Fix-5699][UI] Fix create user error in user information introduced by #5700
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/index.vue
Labels: UI

#5727 [Fix-5726] When we used the UI page, we found some problems such as parameter validation, parameter update shows success but actually work
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
  dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/createDataSource.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/warningGroups/_source/createWarning.vue
  dolphinscheduler-ui/src/js/conf/home/pages/user/pages/token/_source/createToken.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: UI

#5828 [Feature][JsonSplit-api]taskDefinition save interface
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/CheckUtils.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskDefinitionServiceImplTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskDefinition.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionLogMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionLogMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.xml
Labels: First-time contributor

#5835 [fix-5737] [Bug][Datasource] datsource other param check error
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/datasource/AbstractDatasourceProcessor.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/datasource/DatasourceUtilTest.java
Labels: improvement

#5718 [Fix-5719][K8s] Fix Ingress tls: got map expected array On TLS enabled On Kubernetes
  docker/kubernetes/dolphinscheduler/templates/ingress.yaml
Labels: First-time contributor, bug

#5826 [Fix-5825][BUG][WEB] the resource tree in the process definition of latest dev branch can't display correctly
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/resourceTree.js
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/flink.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/mr.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/python.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/shell.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/spark.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/waterdrop.vue
Labels: UI

#5770 [Improvement][Fix-5769][UI]When we try to delete the existing dag, the console in web browser would shows exception
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.js
Labels: UI

#5817 [Fix-5781][UT] Fix test coverage in sonar
  .github/workflows/ci_ut.yml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-dingtalk/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-email/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-http/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-script/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-slack/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-wechat/pom.xml
  dolphinscheduler-alert/pom.xml
  dolphinscheduler-api/pom.xml
  dolphinscheduler-common/pom.xml
  dolphinscheduler-dao/pom.xml
  dolphinscheduler-registry-plugin/dolphinscheduler-registry-zookeeper/pom.xml
  dolphinscheduler-remote/pom.xml
  dolphinscheduler-server/pom.xml
  dolphinscheduler-service/pom.xml
  dolphinscheduler-spi/pom.xml
  pom.xml
Labels: CI&CD, First-time contributor

#5829 [Fix-5830][Improvement][UI] Improve the selection style in dag edit dialog
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
Labels: UI, improvement
