Repository apache/dolphinscheduler, pull requests merged in 2021-12, with the labels that each got.

#7089 [Fix-6809][dolphinscheduler-task-sql] Fix sql task can't send alert
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
Labels: bug, First-time contributor

#7152 [2.0.1-prepare][API]Fix file upload exception.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/FileUtils.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/FileUtilsTest.java
Labels: bug

#7116 [Fix-7093][dolphincheduler-server] fix dependent node stuck in running
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
Labels: First-time contributor

#7140 [Fix-7037][dolphincheduler-server] process instance can not be killed when complement data
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
Labels: First-time contributor

#7353 Adjust Helm Chart templates in dev branch
  deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/job-dolphinscheduler-schema-initializer.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/templates/svc-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  dolphinscheduler-meter/pom.xml
Labels: cloud native

#7377 Fix E2E workflow
  dolphinscheduler-standalone-server/src/main/docker/Dockerfile
Labels: e2e

#7454 Build and publish snapshot Docker images for testing
  .github/workflows/publish-docker.yaml
  deploy/docker/.env
  dolphinscheduler-dist/pom.xml
  dolphinscheduler-dist/src/main/provisio/dolphinscheduler.xml
  pom.xml
Labels: docker

#7453 Adjust logging levels for third party libraries
  dolphinscheduler-standalone-server/src/main/resources/logback-spring.xml
Labels: Chore

#7456 [Feature][UI Next] Added login pages and functions
  dolphinscheduler-ui-next/package.json
  dolphinscheduler-ui-next/src/assets/images/logo.svg
  dolphinscheduler-ui-next/src/env.d.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/utils/classification.ts
  dolphinscheduler-ui-next/src/views/login/index.module.scss
  dolphinscheduler-ui-next/src/views/login/index.tsx
  dolphinscheduler-ui-next/tsconfig.json
Labels: UI

#7470 Update ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
Labels: First-time contributor

#7486 [Fix-7349][Dolphinscheduler] Fix Dolphinscheduler/pom.xml remove redundant parameters [zookeeper.version]
  pom.xml
Labels: Chore

#7506 [DS-7227][refactor] optimize alert plugin instance list order
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertPluginInstanceMapper.xml
Labels: First-time contributor

#7458 Add new version 2.0.1 to issue bug template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Chore

#7489 [Fix-7485][datasource-plugin] Fix failed to create hive datasource using ZooKeeper way in 2.0.1
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/provider/JDBCDataSourceProvider.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/provider/JDBCDataSourceProviderTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/HiveDataSourceClient.java
Labels: First-time contributor

#7523 [Fix-7522] [Alert] http alarm msg ignored
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSender.java
Labels: First-time contributor

#7409 Unify the element selector rules for E2E
  dolphinscheduler-e2e/README.md
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/LoginPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/common/NavBarPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/ProjectDetailPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/ProjectPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowDefinitionTab.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowInstanceTab.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowRunDialog.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowSaveDialog.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/TaskNodeForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/canvas/toolbar.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/formModel.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/_source/selectTenant.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/start.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/list/_source/createProject.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/list/index.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/createTenement.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/index.vue
  dolphinscheduler-ui/src/js/conf/login/App.vue
  dolphinscheduler-ui/src/js/module/components/nav/nav.vue
  dolphinscheduler-ui/src/js/module/components/secondaryMenu/_source/menu.js
Labels: e2e

#7556 [BUG-7554] Fix database lose data in standalone
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/aspect/AccessLogAnnotation.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: bug

#7552 Modify contribution document
  CONTRIBUTING.md
Labels: First-time contributor

#7550 [Improvement] Merge redundant codes
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractYarnTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mr/src/main/java/org/apache/dolphinscheduler/plugin/task/mr/MapReduceTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTask.java
Labels: First-time contributor

#7612 Required E2E to pass before PR can be merged
  .asf.yaml
  .github/workflows/e2e.yml
Labels: Chore

#7603 Fix init script is executed every time a new connection is obtained in standalone server
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/PluginDao.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: bug

#7620 [BUG-7554] Fix database lose data in standalone
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/aspect/AccessLogAnnotation.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/plugin/TaskPluginManager.java
Labels: bug

#7628 [python] Fix task relation wrong hashable function
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/constants.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/task.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_task.py
Labels: bug, Python

#7626 [Feature-7569]Optimize Dependent node loading times
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.1.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.1.0_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.1.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.1.0_schema/postgresql/dolphinscheduler_dml.sql
Labels: improvement

#7648 Fix python gateway will start each time others server start
  dolphinscheduler-python/src/main/java/org/apache/dolphinscheduler/server/PythonGatewayServer.java
  dolphinscheduler-python/src/main/resources/logback-python-gateway.xml
  dolphinscheduler-standalone-server/src/main/java/org/apache/dolphinscheduler/server/StandaloneServer.java
Labels: bug

#7650 [python] Fix task condition set wrong deps
  dolphinscheduler-python/pydolphinscheduler/examples/task_conditions_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/condition.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_condition.py
Labels: bug, Python

#7655 [python] Fix task condition set wrong deps (#7650)
  dolphinscheduler-python/pydolphinscheduler/examples/task_conditions_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/condition.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_condition.py
Labels: bug, Python

#7666 [Feature][Workflow Move] Delete workflow move btn.
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
Labels: bug, UI

#7613 [Fix-7538] [server] Fix when there is a forbidden node in dag, the execution flow is abnormal
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
Labels: bug, First-time contributor

#7676 [Refactor] Canonical enum naming
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/ShowType.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/MailSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannelTest.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/MailUtilsTest.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
Labels: First-time contributor

#7687 [Fix-7062][MasterServer] NPE when run switch conditions sub-process
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/ConditionTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SubTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SwitchTaskProcessor.java
Labels: First-time contributor

#7662 [UI] Fix wrong dialogs for process definition's version info
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/versions.vue
Labels: bug, UI

#7723 Remove fast return for alert plugins due to bean initialization lifecycle is not determinged
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java
Labels: bug

#6894 [Improvement][Logger]Logger server integrate into worker server
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-log-server/pom.xml
  dolphinscheduler-log-server/src/main/assembly/dolphinscheduler-log-server.xml
  dolphinscheduler-log-server/src/main/bin/start.sh
  dolphinscheduler-log-server/src/main/docker/Dockerfile
  dolphinscheduler-log-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerServer.java
  dolphinscheduler-log-server/src/test/java/org/apache/dolphinscheduler/server/log/LoggerServerTest.java
  dolphinscheduler-master/pom.xml
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-standalone-server/src/main/java/org/apache/dolphinscheduler/StandaloneServer.java
  dolphinscheduler-worker/pom.xml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
Labels: Waiting for review

#7748 Remove init script when gaining a new DB connection
  dolphinscheduler-server/src/main/resources/config/install_config.conf
Labels: bug

#7741 The sql has a syntax error, and because it is a function, the excepti…
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: First-time contributor

#7761 fix-#7740-upgrade_sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: First-time contributor
