Repository apache/dolphinscheduler, pull requests merged in 2021-01, with the labels that each got.

#4362 [Improvement-4326][ui] Add description field to data source list
  dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/list.vue
Labels: First-time contributor

#4320 [Feature-4318][API] Rename tenant code
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TenantController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/resources/i18n/messages.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_en_US.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_zh_CN.properties
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TenantControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/createTenement.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/list.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: First-time contributor

#4312 [Fix-3233][api-server] Fix the bug when compile the code in Java9 env
  dolphinscheduler-api/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-ant-1.6.5.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-core-3.1.1.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-jsp-api-2.1-6.1.14.txt
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: First-time contributor

#4374 readme file fixed
  README.md
  README_zh_CN.md
Labels: First-time contributor

#4160 [Feature][ui] Resume from force success
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/instance/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: UI, Waiting for user feedback

#4372 [Feature-#130] pass global param values when starting new process instance
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorService2Test.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/ParameterUtilsTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: First-time contributor

#4413 [DS-4396][feat] Add project information to email alert message
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessAlertContent.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterExecThread.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/AlertManager.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/master/AlertManagerTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
Labels: First-time contributor

#4442 [Feature-4428][dao、UI] It is recommended to add an owner in the data source center and the Resource Center to make it easier to manage
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/DataSourceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.xml
  dolphinscheduler-ui/src/js/conf/home/pages/datasource/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: First-time contributor

#4459 fix the exception of update null point of workflow instance due to no…
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
Labels: First-time contributor

#4434 [Improvement][alert] Refactor alert module to fix code smell
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/manager/DingTalkManager.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/plugin/EmailAlertPlugin.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/template/AlertTemplateFactory.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/template/impl/DefaultHTMLTemplate.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/Constants.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/DingTalkUtils.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/EnterpriseWeChatUtils.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/ExcelUtils.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/FuncUtils.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/MailUtils.java
  dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/PropertyUtils.java
  dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/DingTalkUtilsTest.java
  dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/ExcelUtilsTest.java
  dolphinscheduler-alert/src/test/java/org/apache/dolphinscheduler/alert/utils/PropertyUtilsTest.java
Labels: First-time contributor

#3692 fix: use shellformat(shfmt) and shellcheck fix mvnw
  docker/build/hooks/build
  docker/build/hooks/push
  mvnw
Labels: Waiting for review

#4474 [Feature-4463][UI]: Add an option to the UI page for saving the workflow definition: whether to go online?
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
  dolphinscheduler-ui/src/js/conf/home/store/dag/actions.js
  dolphinscheduler-ui/src/js/conf/home/store/dag/mutations.js
  dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: First-time contributor

#4471 [FIX-4247][Api]Fixed the problem that the global parameters are not updated after the workflow instance click rerun
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
Labels: bug

#4491 [Improvement-#4481][API] ProcessDefinitionController save API optimization
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
Labels: First-time contributor, improvement

#4433 [Feature-4423][UI] When the process definition is running, the pop-up box can manually set the global parameters.
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/localParams.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/start.vue
Labels: Waiting for review

#4508 [FIX-#4468] [UI] Workflow relationships Name filtering invalidated
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/kinship/index.vue
Labels: First-time contributor, UI

#4497 [feat-4496][server] Add to! {} is used to mark the custom parameters to be output as-is in sql
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
Labels: First-time contributor

#4522 [Improvement-#4503][dolphinscheduler-dist]Jackson version upgraded to 2.10.5 from 2.9.10
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
  dolphinscheduler-dist/release-docs/LICENSE
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: First-time contributor

#4539 [Improvement][API] ProjectService queryAllProjectList API optimization
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapperTest.java
Labels: First-time contributor

#4494 [Improvement-4493][api] The Process Definition interface parameter releaseState is changed to an enumeration type
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/store/dag/state.js
Labels: UI, backend, improvement

#4524 [BUG-#4526][common]calculate cpu usage to support application running in container
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
Labels: First-time contributor

#4599 [1.3.5-prepare][cherry-pick]#4272 Fix IOException or NoSuchFileException in logger server
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java
Labels: bug

#4601 [1.3.5-prepare][cherry-pick]#4121 enable response resources gzip compression
  dolphinscheduler-api/src/main/resources/application-api.properties
Labels: improvement

#4603 [1.3.5-prepare][cherry-pick]#4247 Fixed the problem that the global p…
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
Labels: bug

#4529 [Feature-#3291][Improvement][Docker] Reduce docker image size, remove nginx and improve log out
  .gitignore
  docker/build/Dockerfile
  docker/build/README.md
  docker/build/README_zh_CN.md
  docker/build/checkpoint.sh
  docker/build/conf/dolphinscheduler/env/dolphinscheduler_env.sh
  docker/build/conf/dolphinscheduler/logback/logback-alert.xml
  docker/build/conf/dolphinscheduler/logback/logback-api.xml
  docker/build/conf/dolphinscheduler/logback/logback-master.xml
  docker/build/conf/dolphinscheduler/logback/logback-worker.xml
  docker/build/conf/nginx/dolphinscheduler.conf
  docker/build/hooks/build
  docker/build/hooks/push
  docker/build/startup-init-conf.sh
  docker/build/startup.sh
  docker/docker-swarm/check
  docker/docker-swarm/docker-compose.yml
  docker/docker-swarm/docker-stack.yml
  docker/docker-swarm/dolphinscheduler_env.sh
  dolphinscheduler-ui/install-dolphinscheduler-ui.sh
  e2e/src/test/resources/config/config.properties
  install.sh
  script/create-dolphinscheduler.sh
  script/dolphinscheduler-daemon.sh
  script/env/dolphinscheduler_env.sh
  script/monitor-server.sh
  script/remove-zk-node.sh
  script/scp-hosts.sh
  script/start-all.sh
  script/stop-all.sh
  script/upgrade-dolphinscheduler.sh
Labels: docker, improvement

#4594 [Feature-#4350][Alert]support feishu plugin
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/pom.xml
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertChannel.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertChannelFactory.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertPlugin.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuParamsConstants.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuSender.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/HttpRequestUtil.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/test/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertChannelFactoryTest.java
  dolphinscheduler-alert-plugin/dolphinscheduler-alert-feishu/src/test/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuSenderTest.java
  dolphinscheduler-alert-plugin/pom.xml
  dolphinscheduler-dist/src/main/provisio/dolphinscheduler.xml
  pom.xml
Labels: new feature, plug-in
