Repository apache/dolphinscheduler, pull requests merged in 2021-09, with the labels that each got.

#6016 [Feature][JsonSplit-api] modify API to Restful-01
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TaskDefinitionService.java
  dolphinscheduler-ui/src/js/conf/home/store/dag/actions.js
  dolphinscheduler-ui/src/js/conf/home/store/projects/actions.js
Labels: soc2021

#6136 [BUG][API] the interface of 'authed project' is missed
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataSourceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectController.java
  sql/dolphinscheduler_mysql.sql
Labels: bug

#6363 [Fix-6362][api] Fix switch process definition version failed
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
Labels: First-time contributor

#6368 [Bug][API]Resource Check error
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
Labels: bug

#6375 [BUG-6353][MasterServer] fix event handle slowly
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
Labels: bug

#6381 [#6380][Improvement] the automatically generated spi service name in alert-plugin is wrong
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/plugin/DolphinPluginDiscovery.java
Labels: win-os

#6104 [Feature] workflow level task dry run
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Command.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ErrorCommand.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessInstance.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/CommandMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
  sql/dolphinscheduler_mysql.sql
  sql/dolphinscheduler_postgre.sql
Labels: soc2021
