Repository apache/dolphinscheduler, pull requests merged in 2022-09, with the labels that each got.

#11731 [Improvement] Reduce task dependencies
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/BaseTaskProcessor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/K8sTaskParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/dataquality/DataQualityParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/dataquality/spark/ProgramType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/dataquality/spark/SparkConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/dataquality/spark/SparkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/DataQualityTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/DataQualityTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/utils/SparkArgsUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/test/java/org/apache/dolphinscheduler/plugin/task/dq/DataQualityParameterTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sParametersTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskTest.java
Labels: backend

#11727 [feature][API]feature: add task type list and enable user to add task type to fav
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/TaskTypeConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/FavTaskDto.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/FavTaskService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/FavTaskServiceImpl.java
  dolphinscheduler-api/src/main/resources/task-type-config.yaml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/config/YamlPropertySourceFactory.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/FavTask.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/FavTaskMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/FavTaskMapper.xml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-standalone-server/src/main/assembly/dolphinscheduler-standalone-server.xml
Labels: backend, miss:docs, miss:ui

#11755 Update doc according to recent update of Spring / Swagger
  docs/docs/en/contribute/development-environment-setup.md
  docs/docs/en/faq.md
  docs/docs/en/guide/open-api.md
  docs/docs/zh/contribute/development-environment-setup.md
  docs/docs/zh/faq.md
  docs/docs/zh/guide/open-api.md
Labels: document

#11761 [Fix][UI] Add the task name entry when the workflow instance detail page goes to the task instance page.
  dolphinscheduler-ui/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui/src/views/projects/task/instance/use-table.ts
Labels: bug, UI

#11697 [fix-#11691] Add lz4-java in clickhouse datasource.
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-clickhouse/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  tools/dependencies/known-dependencies.txt
Labels: bug, dependencies, backend

#11696 [fix-#11689] change replaceAll to replace in method of tryExecuteSqlResolveColumnNames
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
Labels: bug, backend

#11326 [Fix-11217] [Doc] add postgresql config in doc: datasource-setting
  docs/docs/en/guide/howto/datasource-setting.md
  docs/docs/zh/guide/howto/datasource-setting.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
Labels: document

#11642 [Fix-11583][UI] Fix the API usage of gantt graph
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx
  dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/use-gantt.ts
Labels: bug, UI, backend

#11775 [fix][API]fix task types sequence
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/TaskTypeConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/FavTaskDto.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/FavTaskServiceImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/FavTaskMapper.xml
Labels: backend

#11763 [Feature][python] Add parameter environment to task
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/task.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/java_gateway.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_engine.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_task.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_condition.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_datax.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_dependent.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_flink.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_http.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_map_reduce.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_procedure.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_python.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_sagemaker.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_shell.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_spark.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_sql.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_sub_process.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_switch.py
Labels: new feature, backend, Python

#11611 [DSIP-11][Feature][python] Use the pydolphinscheduler to dynamically generate workflows from the configuration file
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/condition.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/datax.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/dependent.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/flink.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/func_wrap.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/http.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/map_reduce.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/procedure.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/python.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/shell.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/spark.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/sql.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/sub_process.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/switch.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tutorial.rst
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Condition.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/DataX.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Dependent.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Dependent_External.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Flink.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Http.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/MapReduce.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/MoreConfiguration.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Procedure.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Python.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Shell.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Spark.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Sql.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/SubProcess.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Switch.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/example_datax.json
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/example_sql.sql
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/example_sub_workflow.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/tutorial.yaml
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/cli/commands.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/yaml_process_define.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/__init__.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_yaml_process_define.py
  dolphinscheduler-python/pydolphinscheduler/tests/testing/path.py
Labels: new feature, Python, document

#11668 [Bug-11650][worker] #11650 fix SQL type task, stop task does not take effect
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
Labels: bug, discussion, first time contributor, backend

#11783 [python] Fix permission error when create related objects
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
Labels: improvement, backend

#11794 [doc] Correct Docker README URL
  docker/README.md
Labels: document

#11795 [fix-#11784] The mysql init script error
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/mysql/dolphinscheduler_ddl.sql
Labels: bug, backend

#11804 [Doc][Fille-Manage] Remove re upload file function in the 3.0.0's doc
  docs/docs/en/guide/resource/file-manage.md
  docs/docs/zh/guide/resource/file-manage.md
  docs/img/reupload_file_en.png
Labels: bug, document

#11810 [Improvement] Replace commons-lang 2 function invocations with commons-lang3
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ClusterServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/K8SNamespaceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessTaskRelationServiceImpl.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/ConstantsTest.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/os/OSUtilsTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-chunjun/src/main/java/org/apache/dolphinscheduler/plugin/task/chunjun/ChunJunTask.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionCheckerUtils.java
Labels: backend

#11819 Remove `not use web service` comment in alert server
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java
Labels: improvement, backend

#11823 [Bug] [Resource Center] Fix hdfs can only use local mode, not cluster mode
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HadoopUtils.java
Labels: bug, backend

#11734 [Bug](dependent) Dependent downstream trigger error when schedule cycle not day.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentProcessDefinition.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.xml
Labels: bug, backend

#11818 [fix-#11815] fix ck column names contain special characters
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxUtils.java
Labels: bug, backend

#11817 [Doc][Python] yaml_define examples link error
  dolphinscheduler-python/pydolphinscheduler/docs/source/tutorial.rst
Labels: Python, document

#11862 [Fix][UI] Fix workflow name overlaps bug
  dolphinscheduler-ui/src/common/column-width-config.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: bug, UI

#11881 Remove htrace dependencies
  docs/docs/en/faq.md
  docs/docs/zh/faq.md
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-data-quality/pom.xml
  dolphinscheduler-dist/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/NOTICE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-htrace-core4.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-slf4j-reload4j.txt
  dolphinscheduler-master/pom.xml
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: backend, document

#11836 Add codeql to scan codes
  .github/workflows/codeql.yaml
Labels: CI&CD

#11870 [Fix][Monitor]Monitor UI not show DisakAvailable and MemoryUsage corr…
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/MasterHeartBeat.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/WorkerHeartBeat.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/task/MasterHeartBeatTask.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/task/WorkerHeartBeatTask.java
Labels: new feature, backend, miss:ui

#11858 [Bug] [dolphinscheduler-api] Data Analysis Service API responds with jackson deserialization exception
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/TaskCountDto.java
Labels: bug, backend

#11375 [fix-11295] add chunjun plugin in dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
Labels: first time contributor, backend

#11248 [Improvement][deploy] worker template persistentVolumeClaim link Improvement-11247
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
Labels: first time contributor, improvement

#11899 Remove duplicate Spring version management
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/ldap/LdapService.java
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/NOTICE
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/pom.xml
  tools/dependencies/known-dependencies.txt
Labels: backend

#11721 [Bug] [spark-sql] In spark-sql, select both SPARK1 and SPARK2 versions and execute ${SPARK_HOME2}/bin/spark-sql
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkCommand.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkVersion.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/test/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTaskTest.java
  dolphinscheduler-worker/src/main/bin/start.sh
Labels: bug, first time contributor, backend

#11837 [fix-#11830]fix doc about sub-process's child node describe
  docs/docs/en/guide/task/sub-process.md
  docs/docs/zh/guide/task/sub-process.md
Labels: improvement, document

#11888 Fix listing processDefinition the schedulerReleaseState will never be null
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/BaseController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProjectService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SchedulerService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/model/PageListingResult.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/ProcessDefinitionDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/ProcessDefinitionDaoImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapperTest.java
Labels: bug, backend

#11878 [Fix-11877][UI] Fix the problem that the environment cannot be deleted on the UI of some tasks
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-chunjun.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-datax.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-dinky.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-dvc.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-emr.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-hive-cli.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-java.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-jupyter.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-k8s.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-mlflow.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-openmldb.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-procedure.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-python.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-pytorch.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sagemaker.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sea-tunnel.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sql.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-zeppelin.ts
Labels: bug, UI

#11851 [Fix] [Quartz] cron did not work as expected
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: bug, backend

#11905 [Doc][Task Plugin] Fix MLflow task plugin doc
  docs/docs/en/guide/task/mlflow.md
  docs/docs/zh/guide/task/mlflow.md
Labels: document

#11893 [3.0.1-prepare]cherry-pick Process definition length too long when copy or import #…
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
Labels: bug, backend

#11835 [Improvement-11834] Upgrade docker base image to support python3.9
  .github/workflows/cluster-test/mysql/Dockerfile
  .github/workflows/cluster-test/postgresql/Dockerfile
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/docker/Dockerfile
  dolphinscheduler-api/src/main/docker/Dockerfile
  dolphinscheduler-master/src/main/docker/Dockerfile
  dolphinscheduler-standalone-server/src/main/docker/Dockerfile
  dolphinscheduler-tools/src/main/docker/Dockerfile
  dolphinscheduler-worker/src/main/docker/Dockerfile
Labels: first time contributor, improvement, backend, CI&CD

#11919 [Bug] Fix procedure task param pass
  docs/docs/en/guide/task/stored-procedure.md
  docs/docs/zh/guide/task/stored-procedure.md
  docs/img/procedure-en.png
  docs/img/procedure_edit.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java
Labels: backend, document

#11777 Refactor LogServiceClient Singleton to avoid repeat creation of NettyClient
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/exceptions/ServiceException.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/exceptions/ServiceExceptionTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/LoggerServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskInstanceServiceTest.java
  dolphinscheduler-log-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/WorkerFailoverService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DataQualityResultOperator.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClientTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/service/FailoverServiceTest.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/NettyRemotingClient.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/config/NettyClientConfig.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogClient.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogPromise.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/LogClientTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractRemoteTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractYarnTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/LogUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/LogUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrAddStepsTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrJobFlowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink-stream/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkStreamTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-hivecli/src/main/java/org/apache/dolphinscheduler/plugin/task/hivecli/HiveCliTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTask.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnable.java
Labels: improvement, backend

#11911 [Improvement-Dao] optimize date range condition
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
Labels: improvement, backend

#11930 [Bug] fix workflow keep running when task fail
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend

#11864 [Bug] [Master] WorkflowExecuteRunnable will face a infinite loop #11838
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, priority:high

#11929 [Bug][Dependent]: Id also clone due to duplicate when use dependent mode.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorServiceTest.java
Labels: bug, backend

#11776 [Improvement] [Doc] Put default task parameters in a new file
  docs/configs/docsdev.js
  docs/docs/en/guide/task/appendix.md
  docs/docs/en/guide/task/chunjun.md
  docs/docs/en/guide/task/conditions.md
  docs/docs/en/guide/task/datax.md
  docs/docs/en/guide/task/dependent.md
  docs/docs/en/guide/task/dinky.md
  docs/docs/en/guide/task/dvc.md
  docs/docs/en/guide/task/emr.md
  docs/docs/en/guide/task/flink.md
  docs/docs/en/guide/task/hive-cli.md
  docs/docs/en/guide/task/http.md
  docs/docs/en/guide/task/jupyter.md
  docs/docs/en/guide/task/kubernetes.md
  docs/docs/en/guide/task/map-reduce.md
  docs/docs/en/guide/task/mlflow.md
  docs/docs/en/guide/task/openmldb.md
  docs/docs/en/guide/task/pigeon.md
  docs/docs/en/guide/task/python.md
  docs/docs/en/guide/task/pytorch.md
  docs/docs/en/guide/task/sagemaker.md
  docs/docs/en/guide/task/seatunnel.md
  docs/docs/en/guide/task/shell.md
  docs/docs/en/guide/task/spark.md
  docs/docs/en/guide/task/sql.md
  docs/docs/en/guide/task/stored-procedure.md
  docs/docs/en/guide/task/sub-process.md
  docs/docs/en/guide/task/switch.md
  docs/docs/en/guide/task/zeppelin.md
  docs/docs/zh/guide/task/appendix.md
  docs/docs/zh/guide/task/chunjun.md
  docs/docs/zh/guide/task/conditions.md
  docs/docs/zh/guide/task/datax.md
  docs/docs/zh/guide/task/dependent.md
  docs/docs/zh/guide/task/dinky.md
  docs/docs/zh/guide/task/dvc.md
  docs/docs/zh/guide/task/emr.md
  docs/docs/zh/guide/task/flink.md
  docs/docs/zh/guide/task/hive-cli.md
  docs/docs/zh/guide/task/http.md
  docs/docs/zh/guide/task/java.md
  docs/docs/zh/guide/task/jupyter.md
  docs/docs/zh/guide/task/kubernetes.md
  docs/docs/zh/guide/task/map-reduce.md
  docs/docs/zh/guide/task/mlflow.md
  docs/docs/zh/guide/task/openmldb.md
  docs/docs/zh/guide/task/pigeon.md
  docs/docs/zh/guide/task/python.md
  docs/docs/zh/guide/task/pytorch.md
  docs/docs/zh/guide/task/sagemaker.md
  docs/docs/zh/guide/task/seatunnel.md
  docs/docs/zh/guide/task/shell.md
  docs/docs/zh/guide/task/spark.md
  docs/docs/zh/guide/task/sql.md
  docs/docs/zh/guide/task/stored-procedure.md
  docs/docs/zh/guide/task/sub-process.md
  docs/docs/zh/guide/task/switch.md
  docs/docs/zh/guide/task/zeppelin.md
Labels: improvement, document

#11910 Print property loaded from common.properties
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
Labels: improvement, backend

#11625 [fix-10938]: use dot to replace source and make the default env work in shell
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java
Labels: discussion, improvement, backend

#11934 [3.0.1-prepare][cherry-pick][Fix-11877][UI] Fix the problem that the environment cannot be delete
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-datax.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-emr.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-procedure.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-python.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sea-tunnel.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sql.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-zeppelin.ts
Labels: bug, UI, priority:high

#11917 Remove sensitive configs from dolphinscheduler_env.sh
  docs/docs/en/architecture/configuration.md
  docs/docs/en/guide/howto/datasource-setting.md
  docs/docs/en/guide/upgrade/upgrade.md
  docs/docs/zh/architecture/configuration.md
  docs/docs/zh/guide/howto/datasource-setting.md
  docs/docs/zh/guide/howto/general-setting.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/guide/upgrade/upgrade.md
  script/env/dolphinscheduler_env.sh
Labels: backend, document

#11157 [Feature-10273][Datasource] Add dataSource for AWS Athena
  docs/configs/docsdev.js
  docs/docs/en/guide/datasource/athena.md
  docs/docs/zh/guide/datasource/athena.md
  docs/img/new_ui/dev/datasource/athena.png
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-all/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/main/java/org/apache/dolphinscheduler/plugin/datasource/athena/AthenaDataSourceChannel.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/main/java/org/apache/dolphinscheduler/plugin/datasource/athena/AthenaDataSourceChannelFactory.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/main/java/org/apache/dolphinscheduler/plugin/datasource/athena/AthenaDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/main/java/org/apache/dolphinscheduler/plugin/datasource/athena/param/AthenaConnectionParam.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/main/java/org/apache/dolphinscheduler/plugin/datasource/athena/param/AthenaDataSourceParamDTO.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/main/java/org/apache/dolphinscheduler/plugin/datasource/athena/param/AthenaDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/test/java/org/apache/dolphinscheduler/plugin/datasource/athena/param/AthenaDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/enums/DbType.java
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/utils/Constants.java
  dolphinscheduler-ui/src/locales/en_US/datasource.ts
  dolphinscheduler-ui/src/locales/zh_CN/datasource.ts
  dolphinscheduler-ui/src/service/modules/data-source/types.ts
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasource.ts
Labels: UI, backend, document, miss:docs

#11444 [Fix-11434][Doc] Update the registry related configuration in values.yaml
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: bug, document

#11973 [3.0.1-prepare] [cherry-pick]fix ck column names contain special characters
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxUtils.java
Labels: release cherry-pick

#11974 [3.0.1 -prepare][cherry-pick]The mysql init script error
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/mysql/dolphinscheduler_ddl.sql
Labels: release cherry-pick

#11972 [3.0.1 prepare] [cherry-pick ]fix doc about sub-process's child node describe
  docs/docs/en/guide/task/sub-process.md
  docs/docs/zh/guide/task/sub-process.md
Labels: release cherry-pick

#11969 cherry-pick [Bug] [API] The task priority and process instance priori…
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
Labels: release cherry-pick

#11968 [3.0.1-prepare][cherry-pick]Remove logger header in task log file (#11555)
  dolphinscheduler-master/src/main/resources/logback-spring.xml
  dolphinscheduler-standalone-server/src/main/resources/logback-spring.xml
  dolphinscheduler-worker/src/main/resources/logback-spring.xml
Labels: release cherry-pick

#11953 Fix alert_send_status may throw duplicate key exception and add limit for query alert
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/test/java/org/apache/dolphinscheduler/alert/runner/AlertSenderServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Alert.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/AlertSendStatus.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertSendStatusMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertSendStatusMapper.xml
Labels: backend

#11966 Add validations of possible malicious keys
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java
Labels: improvement, backend

#11459 [fix-11452][Bug] [Logger Server] Incorrect password regular expression
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-log-server/src/test/java/org/apache/dolphinscheduler/server/log/SensitiveDataConverterTest.java
Labels: bug, backend

#11931 Fix cannot save processDefinition
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CodeGenerateUtils.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Command.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessDefinition.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessTaskRelation.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapperTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend

#11982 [3.0.1-prepare][cherry-pick][doc] Add how obtain IP address from network card in FAQ (#11311)
  docs/docs/en/faq.md
  docs/docs/zh/faq.md
Labels: release cherry-pick

#11471 Fix insertOrUpdate plugin may failed due to concurrent operation
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/ApiApplicationServer.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/PluginDao.java
Labels: bug, backend

#11967 [3.0.1-prepare]cherry-pick[fix-11404]: make the common.properties to configurable on values.yam…
  deploy/kubernetes/dolphinscheduler/resources/config/common.properties
  deploy/kubernetes/dolphinscheduler/templates/configmap.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: release cherry-pick

#11983 [3.0.1-prepare][cherry-pick][Fix-11051][Task]Fix the process exitValue exception when the process…
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
Labels: release cherry-pick

#11984 [3.0.1-prepare][cherry-pick][Doc] Remove re-upload file function in the 3.0.0's doc (#11804)
  docs/docs/en/guide/resource/file-manage.md
  docs/docs/zh/guide/resource/file-manage.md
  docs/img/reupload_file_en.png
Labels: release cherry-pick

#11985 [3.0.1-prepare][cherry-pick][CI] Fix cluster test abnormal (#11688)
  .github/workflows/cluster-test/mysql/Dockerfile
  .github/workflows/cluster-test/mysql/deploy.sh
  .github/workflows/cluster-test/mysql/start-job.sh
  .github/workflows/cluster-test/postgresql/Dockerfile
  .github/workflows/cluster-test/postgresql/deploy.sh
  .github/workflows/cluster-test/postgresql/start-job.sh
Labels: release cherry-pick

#11988 [3.1.0-prepare][cherry-pick][DSIP-11][python] create workflows from YAML configuration
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/condition.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/datax.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/dependent.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/flink.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/func_wrap.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/http.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/map_reduce.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/procedure.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/python.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/shell.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/spark.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/sql.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/sub_process.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/switch.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tutorial.rst
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Condition.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/DataX.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Dependent.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Dependent_External.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Flink.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Http.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/MapReduce.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/MoreConfiguration.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Procedure.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Python.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Shell.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Spark.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Sql.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/SubProcess.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Switch.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/example_datax.json
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/example_sql.sql
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/example_sub_workflow.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/tutorial.yaml
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/cli/commands.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/yaml_process_define.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/__init__.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_yaml_process_define.py
  dolphinscheduler-python/pydolphinscheduler/tests/testing/path.py
Labels: Python, document, release cherry-pick

#11996 [Cherry-pick-3.1.0]Fix insertOrUpdate plugin may failed due to concurrent operation (#11471)
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/ApiApplicationServer.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/PluginDao.java
Labels: backend, release cherry-pick

#11987 [Cherry-pick-3.0.1] [Bug](dependent) Dependent downstream trigger error when schedule cycle not day.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentProcessDefinition.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.xml
Labels: release cherry-pick

#11989 [3.1.0-prepare][cherry-pick][Feat][python] Add parameter environment to task
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/task.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/java_gateway.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_engine.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_task.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_condition.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_datax.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_dependent.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_flink.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_http.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_map_reduce.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_procedure.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_python.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_sagemaker.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_shell.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_spark.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_sql.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_sub_process.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_switch.py
Labels: backend, Python, release cherry-pick

#11925 [Feature][PyDolphinScheduler] Add Sagemaker YAML example define in pyds
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/sagemaker.rst
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Sagemaker.yaml
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/example_sagemaker_params.json
Labels: new feature, Python, document

#11782 [Improvement-11773][api] Optimize the log printing of the api module according…
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/AuditPublishService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TenantController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/k8s/K8sManager.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/PermissionCheck.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/AbstractAuthenticator.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AccessTokenServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertPluginInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ClusterServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DqExecuteResultServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DqRuleServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/EnvironmentServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/K8SNamespaceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessTaskRelationServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SessionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UdfFuncServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UiPluginServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkFlowLineageServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/FileUtils.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskGroupServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/DataSourceUtils.java
Labels: improvement, backend, miss:docs

#11986 [3.0.1-prepare][cherry-pick]CP Workflow Definition Name Change Validation Optimization.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-ui/src/service/modules/process-definition/index.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-save-modal.tsx
Labels: release cherry-pick

#12013 [3.0.1-prepare]cherry-pick Fix kill task failed will cause the taskGroup cannot release and add taskGroup log (#11469)
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-clickhouse/pom.xml
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/CommonTaskProcessor.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: release cherry-pick

#12024 [Cherry-pick-11232]fix heartBeatTaskCount bug
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterHeartBeatTask.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerHeartBeatTask.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistryClient.java
Labels: release cherry-pick

#11946 correct post body for http alert plugin
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSenderTest.java
Labels: bug, backend

#11963 [Improvement] and task instance date range search
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
Labels: improvement, backend

#12049 [Fix][doc] Fix link errors in release documentation.
  docs/docs/en/contribute/release/release.md
  docs/docs/zh/contribute/release/release.md
Labels: document

#12046 [Feat][UI] Update package.
  docs/docs/en/contribute/development-environment-setup.md
  docs/docs/zh/contribute/development-environment-setup.md
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-ui/package.json
  dolphinscheduler-ui/pnpm-lock.yaml
Labels: dependencies, UI, backend, document

#11292 [Improvement-11291][sql] Improvement the log output while executing multiple sql statements
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
Labels: improvement, backend

#11588 [Improvement][Test] Give an example on replacing Powermock with Mockito
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/test/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/test/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskTest.java
  dolphinscheduler-task-plugin/pom.xml
Labels: improvement, backend

#12037 [Bug][ApiServer] When modifying the task definition, inserting the task definition log table will report the bug of primary key conflict
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
Labels: first time contributor, backend

#12062 [Improve] Improve support test tasks UT
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/DataSourceControllerTest.java
Labels: bug, backend

#10694 to #10692: fix Parameter transfer problem when recover failed task an…
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SubTaskProcessor.java
Labels: bug, backend

#12058 [improvement]Add Set cluster name
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/K8SNamespaceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/K8SNamespaceServiceTest.java
Labels: bug, backend

#12060 Fix update TaskDefinition error
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend, release cherry-pick

#12064 [Cherry-pick-3.1.0][Fix-12060] Fix update TaskDefinition error
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend

#12068 [Cherry-pick-3.1.0][Fix-12067] Script cannot contains ''' in params
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/test/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSenderTest.java
Labels: backend

#12067 Script cannot contains ''' in params
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/test/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSenderTest.java
Labels: backend, release cherry-pick

#12073 [Improvement][Dependent] The project list in dependent node's permissions should not be restricted
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProjectService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/main/resources/i18n/messages.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_en_US.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_zh_CN.properties
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProjectControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProjectV2ControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
  dolphinscheduler-ui/src/service/modules/projects/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
Labels: UI, improvement, backend

#12074 [improvement]Add Set cluster name
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-namespace.ts
Labels: UI, improvement

#11332 [Improvement][UT] Upgrade jUnit to 5.+ (#10976)
  dolphinscheduler-alert/dolphinscheduler-alert-server/pom.xml
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/test/java/org/apache/dolphinscheduler/alert/AlertServerTest.java
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TaskInstanceControllerTest.java
  pom.xml
Labels: improvement, backend

#12071 [Improvement][Task Plugin] Optimize MLFlow task plugin for ease of use
  docs/docs/en/guide/task/mlflow.md
  docs/docs/zh/guide/task/mlflow.md
  docs/img/tasks/demo/mlflow-models-docker-compose.png
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/mlflow.yaml
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/task_mlflow_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/mlflow.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_mlflow.py
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/resources/docker-compose.yml
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/test/java/org/apache/dolphinler/plugin/task/mlflow/MlflowTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-mlflow-models.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-mlflow-projects.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-mlflow.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-mlflow.ts
Labels: UI, backend, Python, document

#11860 [Improvement-11857][Spark] Remove the spark version of spark task
  .github/workflows/cluster-test/mysql/dolphinscheduler_env.sh
  .github/workflows/cluster-test/postgresql/dolphinscheduler_env.sh
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/docs/en/architecture/configuration.md
  docs/docs/en/architecture/task-structure.md
  docs/docs/en/faq.md
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/task/spark.md
  docs/docs/en/guide/upgrade/incompatible.md
  docs/docs/zh/architecture/configuration.md
  docs/docs/zh/architecture/task-structure.md
  docs/docs/zh/faq.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/task/spark.md
  docs/docs/zh/guide/upgrade/incompatible.md
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/EnvironmentServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/SparkVersion.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ClusterMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/EnvironmentMapperTest.java
  dolphinscheduler-python/pydolphinscheduler/UPDATING.md
  dolphinscheduler-python/pydolphinscheduler/examples/yaml_define/Spark.yaml
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/spark.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_spark.py
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/dataquality/spark/SparkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/DataQualityTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkCommand.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkVersion.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/test/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-spark.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-spark.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  script/env/dolphinscheduler_env.sh
Labels: UI, improvement, backend, CI&CD, Python, document, miss:docs, incompatible

#12059 [Bug-#12057][task-plugin] fix when the sql query result is empty, the email fails to send the attachment, and an exception will be reported
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
Labels: bug, backend

#11162 [Feature] Add CURD to the project/tenant/user section of the python-DS
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/java_gateway.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/base_side.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/project.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/tenant.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/user.py
  dolphinscheduler-python/pydolphinscheduler/tests/integration/conftest.py
  dolphinscheduler-python/pydolphinscheduler/tests/integration/test_project.py
  dolphinscheduler-python/pydolphinscheduler/tests/integration/test_tenant.py
  dolphinscheduler-python/pydolphinscheduler/tests/integration/test_user.py
Labels: backend, Python

#12096 [BUG]Delete Setting ID
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
Labels: bug, backend

#12093 [Bug][Timezone][3.0.1] fix timezone when complement data and preview
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/quartz/cron/CronUtils.java
Labels: bug, backend

#12098 [Cherry-Pick][3.1.0-Prepare] Fix insert command error due to the id is not null (#12092)
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend

#12099 [Improvement][UI] Add filterable for `src_table` and `target_table` i…
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-rules.ts
Labels: UI, improvement

#12112 [Bug] [Pytorch Task Plugin] Python home conflict when create conda env
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PythonEnvManager.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/test/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTaskTest.java
Labels: backend

#12125 [Fix][UI] Fix workflow name overlaps bug (#11862)
  dolphinscheduler-ui/src/common/column-width-config.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: bug, UI

#12080 [fix] Also auto formatter workflow instance if location is null
  dolphinscheduler-ui/src/views/projects/workflow/instance/detail/index.tsx
Labels: UI

#12120 [fix][python] Task switch branch not show in webui
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/task.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/switch.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_task.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_switch.py
Labels: bug, Python, priority:high

#12121 [Doc][Improvement] Add instructions for process execution type and data complement
  docs/docs/en/guide/project/workflow-definition.md
  docs/docs/zh/guide/project/workflow-definition.md
  docs/img/new_ui/dev/project/workflow-execution-type.png
Labels: document

#12050 [fix#12000]Cannot remove the WorkerGroup from the master service
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java
Labels: backend

#11762 [Bug] [Common] update IPv4 Pattern
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java
Labels: bug, backend

#12137 [Bug][Upgrade][3.1.0] fix upgrade sql for 3.1.0
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/postgresql/dolphinscheduler_dml.sql
Labels: backend

#11965 refactor: dag-menu refactor
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/TaskTypeConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/FavTaskServiceImpl.java
  dolphinscheduler-api/src/main/resources/task-type-config.yaml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowDefinitionTab.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/service/modules/dag-menu/index.ts
  dolphinscheduler-ui/src/store/project/index.ts
  dolphinscheduler-ui/src/store/project/task-type.ts
  dolphinscheduler-ui/src/store/project/types.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-java-task-main-jar.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-java.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-task-type.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-java.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/use-task.ts
  dolphinscheduler-ui/src/views/projects/task/definition/batch-task.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-sidebar.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/types.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-cell-update.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-custom-cell-builder.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-dag-drag-drop.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: UI, backend, e2e, sql not sync, refactor

#10869 [Improvement][SQL Task]use default sql segment separator
  docs/docs/en/guide/upgrade/incompatible.md
  docs/docs/zh/guide/task/sql.md
  docs/docs/zh/guide/upgrade/incompatible.md
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/enums/DbType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/SqlParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlSplitter.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sql-type.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sql.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, improvement, backend, document, incompatible

#12126 [BUG][BE-12113]fix htrace dependency conflicts
  dolphinscheduler-api/pom.xml
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-hbase-noop-htrace.txt
  dolphinscheduler-master/pom.xml
  dolphinscheduler-server/pom.xml
  tools/dependencies/known-dependencies.txt
Labels: backend

#12141 [Bug][Upgrade] fix upgrade sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/postgresql/dolphinscheduler_dml.sql
Labels: backend

#12139 [release][doc]add release 3.0.1
  .github/ISSUE_TEMPLATE/bug-report.yml
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/contribute/release/release.md
  docs/docs/en/history-versions.md
  docs/docs/zh/contribute/release/release.md
  docs/docs/zh/history-versions.md
Labels: CI&CD, document

#12143 [Improvement][Test] Remove powermock in dolphinscheduler-master module
  dolphinscheduler-master/pom.xml
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/SubProcessTaskTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/processor/CacheProcessorTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/processor/TaskAckProcessorTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/processor/TaskKillResponseProcessorTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClientTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThreadTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnableTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/service/FailoverServiceTest.java
Labels: improvement, backend

#12146 [3.1.0-prepare] Update version to 310
  deploy/docker/.env
  deploy/kubernetes/dolphinscheduler/Chart.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/configs/docsdev.js
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/history-versions.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/history-versions.md
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
  dolphinscheduler-python/pydolphinscheduler/setup.py
Labels: backend, Python, document

#12147 [Fix][UI] Fix env config space bug
  dolphinscheduler-ui/src/views/security/environment-manage/components/environment-modal.tsx
  dolphinscheduler-ui/src/views/security/environment-manage/components/use-modal.ts
Labels: UI

#12151 [fix][doc] Do not change docsdev.js during releasing
  docs/docs/en/contribute/release/release-prepare.md
  docs/docs/zh/contribute/release/release-prepare.md
Labels: bug, document

#12056 [Improvement][Master] Construct processInstance may NPE when master handling command
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend

#12160 [hotfix][UI] Remove SURVEIL and NEXT_LOOP in ui
  dolphinscheduler-api/src/main/resources/task-type-config.yaml
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/BlockingTaskTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/SubProcessTaskTest.java
Labels: backend

#12017 [test] fix flaky test in CI
  .licenserc.yaml
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelTest.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSenderTest.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: backend

#12153 [Improvement][Test] Remove Powermock in dolphinscheduler-task-plugin
  dolphinscheduler-task-plugin/dolphinscheduler-task-dvc/src/test/java/org/apache/dolphinscheduler/plugin/task/dvc/DvcTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/AbstractEmrTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrAddStepsTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrJobFlowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/java/org/apache/dolphinscheduler/plugin/task/emr/EmrAddStepsTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/java/org/apache/dolphinscheduler/plugin/task/emr/EmrJobFlowTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/test/java/org/apache/dolphinscheduler/plugin/task/http/HttpTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/test/java/org/apache/dolphinler/plugin/task/mlflow/MlflowTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/test/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/test/java/org/apache/dolphinscheduler/plugin/task/python/PythonTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/test/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/test/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/test/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTaskTest.java
Labels: improvement, backend

#12175 [Feature][doc] Add a guide to nominate new committer
  docs/docs/en/contribute/join/become-a-committer.md
  docs/docs/zh/contribute/join/become-a-committer.md
Labels: document

#12172 [Bug] [UI] UI miss machine learning task group
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-sidebar.tsx
Labels: UI

#12181 [Document][Improvement] Polish docs for standalone deployment
  docs/docs/en/guide/installation/standalone.md
Labels: first time contributor, document

#12164 [Improvement][Test] Remove powermock in service and server modules
  dolphinscheduler-server/pom.xml
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
  dolphinscheduler-server/src/test/java/org/apache/dolphinscheduler/server/utils/ProcessUtilsTest.java
  dolphinscheduler-service/pom.xml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/AlertClientService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/factory/NettyRemotingClientFactory.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogClient.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/alert/AlertClientServiceTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManagerTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/LogClientTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: improvement, backend

#12192 [feat][ci] Add pre-commit for easy spotless config
  .pre-commit-config.yaml
  docs/docs/en/contribute/development-environment-setup.md
  docs/docs/zh/contribute/development-environment-setup.md
  style/pre-commit
Labels: CI&CD, document

#12200 [improvement] improve relation between notification strategy and alarm group on ui
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/timing-modal.tsx
Labels: UI

#12169 [Improvement-12144] Remove powermock in dolphinschduler-api
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/DataAnalysisControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessTaskRelationControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ResourcesControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/WorkerGroupControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/interceptor/RateLimitInterceptorTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/BaseServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/LoggerServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/SchedulerServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UdfFuncServiceTest.java
Labels: improvement, backend

#11774 [fix-#11753] send alert error alert data id
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ExecutorControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessDefinition.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java
Labels: bug, backend

#12183 [DS-12154][worker] Optimize the log printing of the worker module acc…
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskDispatchProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteResultAckProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskRejectAckProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskSavePointProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerManagerThread.java
Labels: improvement, backend, soc

#11682 [Improvement-11678][API] Improvement the error message when batch delete workflow
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
Labels: bug, backend

#11868 [Feature][TASK-PLUGIN] AWS Database Migration Service (DMS)
  docs/configs/docsdev.js
  docs/docs/en/guide/task/dms.md
  docs/docs/zh/guide/task/dms.md
  docs/img/tasks/demo/dms_create_and_start.png
  docs/img/tasks/demo/dms_create_and_start_json.png
  docs/img/tasks/demo/dms_restart.png
  docs/img/tasks/demo/dms_restart_json.png
  docs/img/tasks/icons/dms.png
  dolphinscheduler-api/src/main/resources/task-type-config.yaml
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-aws-java-sdk-dms.txt
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/src/main/java/org/apache/dolphinscheduler/plugin/task/dms/DmsHook.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/src/main/java/org/apache/dolphinscheduler/plugin/task/dms/DmsParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/src/main/java/org/apache/dolphinscheduler/plugin/task/dms/DmsTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/src/main/java/org/apache/dolphinscheduler/plugin/task/dms/DmsTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/src/main/java/org/apache/dolphinscheduler/plugin/task/dms/DmsTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/src/test/java/org/apache/dolphinscheduler/plugin/task/dms/DmsHookTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/src/test/java/org/apache/dolphinscheduler/plugin/task/dms/DmsTaskTest.java
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/dms.png
  dolphinscheduler-ui/public/images/task-icons/dms_hover.png
  dolphinscheduler-ui/src/store/project/task-type.ts
  dolphinscheduler-ui/src/store/project/types.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dms.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-dms.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
  tools/dependencies/known-dependencies.txt
Labels: UI, backend, document

#12227 [Release][Doc] add 3.1.0 release
  .github/ISSUE_TEMPLATE/bug-report.yml
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: CI&CD, document

#12217 [Improvement][WorkerGroup]Remove workerGroup in registry
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/WorkerGroupControllerTest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/registry/RegistryClient.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistryClient.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/task/WorkerHeartBeatTask.java
  dolphinscheduler-worker/src/main/resources/application.yaml
  dolphinscheduler-worker/src/test/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistryClientTest.java
Labels: improvement, backend, document

#12225 [Improvement][UI] Set the `required` to be reactive in the task modal.
  dolphinscheduler-ui/src/components/form/fields/custom-parameters.ts
  dolphinscheduler-ui/src/components/form/fields/get-field.ts
  dolphinscheduler-ui/src/components/form/fields/multi-condition.ts
  dolphinscheduler-ui/src/components/form/get-elements-by-json.ts
  dolphinscheduler-ui/src/components/form/index.tsx
  dolphinscheduler-ui/src/components/form/types.ts
  dolphinscheduler-ui/src/components/form/utils.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-resources.ts
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/detail.tsx
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/types.ts
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/use-form.ts
Labels: UI, improvement

#12206 [Improvement] remove log-server and server module
  .github/CODEOWNERS
  .github/actions/labeler/labeler.yml
  .github/workflows/backend.yml
  .gitignore
  docs/docs/en/about/glossary.md
  docs/docs/en/architecture/design.md
  docs/docs/zh/about/glossary.md
  docs/docs/zh/architecture/design.md
  dolphinscheduler-dist/pom.xml
  dolphinscheduler-log-server/pom.xml
  dolphinscheduler-master/pom.xml
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/MasterRPCServer.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/BlockingTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/ConditionTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/DependentTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SubTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SwitchTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/WorkerFailoverService.java
  dolphinscheduler-master/src/main/resources/logback-spring.xml
  dolphinscheduler-server/pom.xml
  dolphinscheduler-server/src/test/resources/master.properties
  dolphinscheduler-service/pom.xml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LoggerRequestProcessor.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/MasterLogFilter.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/SensitiveDataConverter.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/TaskLogDiscriminator.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/TaskLogFilter.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/WorkerLogFilter.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/LogUtils.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/ProcessUtils.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/LoggerRequestProcessorTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/MasterLogFilterTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/SensitiveDataConverterTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/TaskLogDiscriminatorTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/TaskLogFilterTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/WorkerLogFilterTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/LogUtilsTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/ProcessUtilsTest.java
  dolphinscheduler-standalone-server/pom.xml
  dolphinscheduler-standalone-server/src/main/resources/logback-spring.xml
  dolphinscheduler-worker/pom.xml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskDispatchProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/rpc/WorkerRpcServer.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnable.java
  dolphinscheduler-worker/src/main/resources/logback-spring.xml
  pom.xml
Labels: improvement, backend, CI&CD, document

#12194 [Improvement][Test] Remove the usage of powermock in datasource-plugin module
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/provider/JDBCDataSourceProvider.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/PasswordUtils.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/client/CommonDataSourceClientTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtilsTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/test/java/org/apache/dolphinscheduler/plugin/datasource/athena/param/AthenaDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-clickhouse/src/test/java/org/apache/dolphinscheduler/plugin/datasource/clickhouse/ClickHouseDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-db2/src/test/java/org/apache/dolphinscheduler/plugin/datasource/db2/DB2DataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-db2/src/test/java/org/apache/dolphinscheduler/plugin/datasource/db2/param/Db2DataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/HiveDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/utils/CommonUtil.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/test/java/org/apache/dolphinscheduler/plugin/datasource/hive/HiveDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/test/java/org/apache/dolphinscheduler/plugin/datasource/hive/param/HiveDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/mysql/MySQLDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/mysql/param/MySQLDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/mysql/provider/JDBCDataSourceProviderTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/mysql/utils/DataSourceUtilsTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oracle/src/test/java/org/apache/dolphinscheduler/plugin/datasource/oracle/OracleDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oracle/src/test/java/org/apache/dolphinscheduler/plugin/datasource/oracle/param/OracleDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-postgresql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/postgresql/PostgreSQLDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-postgresql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/postgresql/param/PostgreSQLDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-presto/src/test/java/org/apache/dolphinscheduler/plugin/datasource/presto/PrestoDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-presto/src/test/java/org/apache/dolphinscheduler/plugin/datasource/presto/param/PrestoDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-redshift/src/test/java/org/apache/dolphinscheduler/plugin/datasource/redshift/param/RedshiftDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-spark/src/test/java/org/apache/dolphinscheduler/plugin/datasource/spark/SparkDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-spark/src/test/java/org/apache/dolphinscheduler/plugin/datasource/spark/param/SparkDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/src/test/java/org/apache/dolphinscheduler/plugin/datasource/sqlserver/SQLServerDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/src/test/java/org/apache/dolphinscheduler/plugin/datasource/sqlserver/param/SQLServerDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/pom.xml
Labels: improvement, backend

#12159 [Improvement][Master] LowerWeightRoundRobin doSelect may be null
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobin.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobinTest.java
Labels: backend

#12226 Fix hive datasource connection leak
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/HiveDataSourceClient.java
Labels: backend
