Repository apache/dolphinscheduler, pull requests merged in 2022-11, with the labels that each got.

#12628 [Feature][UI] Add a method for adding a single node to the dag.
  dolphinscheduler-ui/package.json
  dolphinscheduler-ui/pnpm-lock.yaml
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/dag-canvas.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/dag-node.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/dag-setting.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/dag-sidebar.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/use-add-dag-shape.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/use-dag-node.ts
  dolphinscheduler-ui/vite.config.ts
Labels: feature, UI, refactor

#12631 [3.0.2-prepare][cherry-pick] Fix the API usage of gantt graph
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx
  dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/use-gantt.ts
Labels: bug

#12632 [3.0.2-prepare][cherry-pick] Fix list param error when use sql task
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parser/ParameterUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/parser/ParameterUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
Labels: bug

#12633 [3.0.2-prepare][cherry-pick] fix when the sql query result is empty, the email fails to send the attachment, and an exception will be reported
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
Labels: bug

#12634 [3.0.2-prepare][cherry-pick] Easier release: cherry-pick, changelog, contributor
  tools/release/README.md
  tools/release/github/__init__.py
  tools/release/github/changelog.py
  tools/release/github/git.py
  tools/release/github/pull_request.py
  tools/release/github/resp_get.py
  tools/release/github/user.py
  tools/release/release.py
  tools/release/requirements.txt
Labels: feature

#12635 [3.0.2-prepare][cherry-picl] fix wrong env var name for alert in K8S (#12369)
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
Labels: bug

#12118 [Fix-12109] Fix the errors when starting 2 times with dolphinscheduler-daemon.sh
  script/dolphinscheduler-daemon.sh
  script/status-all.sh
Labels: bug, backend, 3.0.x, 3.1.x

#12646 [3.0.2-prepare][cherry-pick] If the worker's clock early than master node, will ignore dispatch time.
  docs/docs/en/about/hardware.md
  docs/docs/zh/about/glossary.md
  docs/docs/zh/about/hardware.md
Labels: improvement

#12648 [3.0.2-prepare][cherry-pick] Fix datax task data instance replay error
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasource.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datax.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: bug

#12647 [Fix][UI] Fix the line break problem in navbar.
  dolphinscheduler-ui/src/layouts/content/components/navbar/index.module.scss
  dolphinscheduler-ui/src/layouts/content/components/navbar/index.tsx
Labels: bug, UI

#12645 [Feature][UI] Add a popup component based on dynamic form.
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task-form.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/use-task-form.ts
Labels: feature, UI, refactor

#12624 [Improvement-12623][Permission]Remove the unused projectIds in operationPermissionCheck()
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AccessTokenServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertGroupServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertPluginInstanceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DqExecuteResultServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DqRuleServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/EnvironmentServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/MonitorServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/QueueServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskGroupServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UdfFuncServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/WorkerGroupServiceTest.java
Labels: improvement, backend

#12570 [Bugfix-12568] [Master] The retry task was submitted in advance will block other task
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
Labels: bug, backend

#12651 Fix the waiting strategy cannot recovery if the serverstate is already in running
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/lifecycle/ServerLifeCycleManager.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterWaitingStrategy.java
Labels: bug, backend, 3.1.x

#12666 [Feat][UI] Add language parser.
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/types.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-dynamic-locales.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-task-form.ts
Labels: feature, UI, refactor

#12663 Splite cpu/memory info in OSUtils#isOverload
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
Labels: improvement, backend

#12668 [Improvement][UI] Support to use the clearable button of components to search for new results.
  dolphinscheduler-ui/src/views/projects/list/index.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/batch-task.tsx
  dolphinscheduler-ui/src/views/projects/task/instance/batch-task.tsx
  dolphinscheduler-ui/src/views/projects/task/instance/stream-task.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/instance/components/process-instance-condition.tsx
Labels: UI, improvement, 3.1.x

#12670 [3.0.2-prepare][cherry-pick] Add unique key to process_definition_log avoid TooManyResultExpection
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.2_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.2_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.2_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.2_schema/postgresql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: bug

#12669 [Feature][UI] Added form value parser.
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-form-field.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-task-form.ts
Labels: feature, UI, refactor

#12652 [Improvement-12650][Permission] Improve the check of resourcePermissionCheck()
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceImpl.java
Labels: improvement, backend

#12506 [Improvement][BatchQuery] Batch query ProcessDefinitions belongs to need failover ProcessInstance.
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/ProcessDefinitionDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/ProcessDefinitionDaoImpl.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/service/FailoverServiceTest.java
Labels: first time contributor, improvement, backend

#12660 [Improvement-12658][Permission] Improve the readability of setPerm() in grantProjectbyCode()
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
Labels: improvement, backend

#12685 [Fix] [K8s] Add pythonNodePort in values.yaml
  deploy/kubernetes/dolphinscheduler/templates/svc-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: improvement

#12686 [Feature][UI] Added form structure parser.
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-form-structure.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-task-form.ts
Labels: feature, UI, refactor

#12678 Change command file permission to 755
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/FileUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java
Labels: improvement, backend

#12681 when delete workflow, delete related task
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.xml
Labels: bug, backend

#12705 Fix flink sql cannot run due to missing main jar
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTask.java
Labels: bug, backend, 3.0.x, 3.1.x

#12707 [Fix]Fix and enhance helm db config
  deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: bug, backend

#12724 [Bug] fix same status code definition
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
Labels: bug, backend

#12717 [fix-12716]modify processTaskRelationMapper sql error
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
Labels: bug, backend, 3.0.x

#12730 [3.0.2-prepare][cherry-pick] Fix vulnerability in LDAP login
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/ldap/LdapService.java
  tools/dependencies/known-dependencies.txt
Labels: improvement

#12731 [3.0.2-prepare][cherry-pick] Delete workflow or task used by other tasks
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkFlowLineageController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkFlowLineageService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkFlowLineageServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskMainInfo.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskRecord.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.xml
Labels: improvement

#12732 [3.0.2-prepare][cherry-pick] Fix link errors in release documentation
  docs/docs/en/contribute/release/release.md
  docs/docs/zh/contribute/release/release.md
Labels: bug

#12701 [Feature][UI] Added form input parser.
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-form-field.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-form-request.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-form-structure.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-form-validate.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-task-form.ts
Labels: feature, UI, refactor

#12728 [Improvement][UI] Beautify the nodes and edges in the DAG.
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-config.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-canvas-init.ts
Labels: UI, improvement, 3.1.x

#12692 [fix-12675]edit workflow related task, workflow's task version change
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskDefinitionServiceImplTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
Labels: bug, backend, 3.1.x

#12467 [Bug] Resource default auth function disabled false.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
Labels: bug, backend, 3.1.x

#12739 [3.0.2-prepare][cherry-pick] Update IPv4 Pattern
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java
Labels: bug

#12738 [Improve-5918]Remove the code logger.isInfoEnabled()
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: first time contributor, improvement, backend

#12699 [Document][Improvement] Add instructions on how to configure logging level for debugging purpose
  docs/docs/en/contribute/log-specification.md
  docs/docs/zh/contribute/log-specification.md
  dolphinscheduler-api/src/main/resources/logback-spring.xml
  dolphinscheduler-standalone-server/src/main/resources/logback-spring.xml
Labels: improvement, document

#12740 [3.0.2-prepare][cherry-pick] Do not change docsdev.js during releasing
  docs/docs/en/contribute/release/release-prepare.md
  docs/docs/zh/contribute/release/release-prepare.md
Labels: bug

#12743 [3.0.2-prepare][cherry-pick] Polish docs for standalone deployment (#12181)
  docs/docs/en/guide/installation/standalone.md
Labels: improvement

#12729 [3.1.1-prepare][Test] test ut
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/BlockingTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/test/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/test/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTaskTest.java
Labels: backend

#12742 [Bug] use dot to replace source and make the default env work in shell
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java
Labels: bug, backend, 3.1.x

#12747 [3.0.2-prepare][cherry-pick] Improvement the error message when batch delete workflow (#11682)
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
Labels: improvement

#12748 [3.0.2-prepare][cherry-pick] Set the `required` to be reactive in the task model
  dolphinscheduler-ui/src/components/form/fields/custom-parameters.ts
  dolphinscheduler-ui/src/components/form/fields/get-field.ts
  dolphinscheduler-ui/src/components/form/fields/multi-condition.ts
  dolphinscheduler-ui/src/components/form/get-elements-by-json.ts
  dolphinscheduler-ui/src/components/form/index.tsx
  dolphinscheduler-ui/src/components/form/types.ts
  dolphinscheduler-ui/src/components/form/utils.ts
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/detail.tsx
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/types.ts
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/use-form.ts
Labels: improvement

#12751 [3.0.2-prepare][cherry-pick] Correct release export key step
  docs/docs/en/contribute/release/release.md
  docs/docs/zh/contribute/release/release.md
Labels: bug

#12752 [3.0.2-prepare][cherry-pick] Add chmod command after unzip DS tar.gz
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/standalone.md
Labels: improvement

#12754 [3.0.2-prepare][cherry-pick] Update slack invitation link (#12258)
  docs/configs/site.js
Labels: improvement

#12759 [Improvement][UI] Adjust the args of router to allow the edge to be connected with node at its different positions
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-config.ts
Labels: UI, improvement, 3.1.x

#12761 [3.0.2-prepare][cherry-pick] Delete useless exclusions (#12273)
  dolphinscheduler-bom/pom.xml
Labels: improvement

#12753 [Feature][UI] Added form select parser.
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-task-form.ts
Labels: feature, UI, refactor

#12762 [3.0.2-prepare][cherry-pick] send alert error alert data id (#11774)
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ExecutorControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessDefinition.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java
Labels: bug

#12756 [Bug] [dolphinscheduler-aop] aspectj-maven-plugin version undefined
  dolphinscheduler-aop/pom.xml
  pom.xml
Labels: improvement, backend

#12766 [3.0.2-prepare][cherry-pick] fix this issue
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
Labels: bug

#12767 [3.0.2-prepare][cherry-pick] fix the bug which some scheduled tasks are not triggered on time
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/quartz/impl/QuartzExecutorImpl.java
Labels: bug

#12769 [3.0.2-prepare][cherry-pick] Update ZooKeeper minimum version requirements
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
Labels: improvement

#12770 [3.0.2-prepare][cherry-pick] Fix the bugs when upgrading ds from v1.3.9 to v3.0.0 ,such as file cannot be found or column not found etc
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/mysql/dolphinscheduler_ddl_post.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/postgresql/dolphinscheduler_ddl_post.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.0_schema/postgresql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.1_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.1_schema/postgresql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/mysql/dolphinscheduler_ddl.sql
Labels: release cherry-pick 3.0.x

#12773 [3.0.2-prepare][cherry-pick] Avoid using search in for and start using testSaveTaskDefine
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: improvement

#12780 [3.0.2-prepare][cherry-pick] Correct typos in comments (#12174)
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/WorkerGroupMapper.java
Labels: bug

#12765 [FIX][DOC-12764]fix sql-hive and hive-cli doc
  docs/docs/en/guide/task/hive-cli.md
  docs/docs/en/guide/task/sql.md
  docs/docs/zh/guide/task/hive-cli.md
  docs/docs/zh/guide/task/sql.md
  docs/img/tasks/demo/hive_cli_from_script.png
  docs/img/tasks/demo/pre_post_sql.png
Labels: document

#12781 [3.0.2-prepare][cherry-pick] Fix error problem on h2 startup data quality rule management page
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/DqRuleInputEntryMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/DqRuleInputEntryMapperTest.java
Labels: bug, release cherry-pick 3.0.x

#12783 [3.0.2-prepare][cherry-pick] Change release process base on new tool (#12324)
  docs/docs/en/contribute/release/release-post.md
  docs/docs/en/contribute/release/release.md
  docs/docs/zh/contribute/release/release-post.md
  docs/docs/zh/contribute/release/release.md
Labels: improvement

#12788 [3.0.2-prepare][cherry-pick] Fix the duration in Workflow Instance page. (#12264)
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/DateUtilsTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/WorkflowUtils.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/utils/WorkflowUtilsTest.java
Labels: bug

#12336 [Improvement-12335][ui] Make the resources to be reactive in hivecli task
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-hive-cli.ts
Labels: UI, improvement

#12757 [3.1.1][release] test ut
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskDefinitionServiceImplTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/LogClientTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/storage/impl/HadoopUtilsTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/ProcessUtilsTest.java
Labels: backend

#12775 fix: Fix some mistakes in the datasource
  dolphinscheduler-ui/src/locales/en_US/datasource.ts
  dolphinscheduler-ui/src/locales/zh_CN/datasource.ts
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/index.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-columns.ts
Labels: bug, UI

#12790 [3.0.2-prepare][cherry-pick] Fix python class description error
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/python.py
Labels: bug

#12791 [3.0.2-prepare][cherry-pick] Fix spark task plugin optional parameters
  docs/docs/zh/guide/task/spark.md
Labels: bug

#12792 [3.0.2-prepare][cherry-pick] Fix dependent task can not predicate the status of the corresponding task correctly
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/DependentDateUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/DependentUtils.java
Labels: bug

#12793 [3.0.2-prepare][cherry-pick] Add http header to avoid github 403 in dlc (#12509)
  .dlc.json
Labels: bug

#12794 [3.0.2-prepare][cherry-pick] Only expose necessary actuator endpoints (#12571)
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/resources/application.yaml
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: improvement

#12795 [3.0.2-prepare][cherry-pick] Add configmap resource permissions so config hot reload can work
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/rbac.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
Labels: improvement

#12797 [3.0.2-prepare][cherry-pick] Add new alert doc Slack (#12567)
  docs/configs/docs3-0-1.js
  docs/docs/en/guide/alert/slack.md
  docs/docs/zh/guide/alert/feishu.md
  docs/docs/zh/guide/alert/slack.md
  docs/img/new_ui/dev/alert/alert_slack.png
  docs/img/new_ui/dev/alert/alert_slack_enable.png
  docs/img/new_ui/dev/alert/alert_slack_new.png
  docs/img/new_ui/dev/alert/alert_slack_webhook_addr.png
Labels: improvement

#12798 [3.0.2-prepare][cherry-pick] If the worker's clock early than master node, will ignore dispatch time.
  docs/docs/zh/about/glossary.md
Labels: improvement

#12799 [3.0.2-prepare][cherry-pick] Fix minor sql error (#12717)
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
Labels: bug

#12800 [3.0.2-prepare][cherry-pick] Fix flink sql cannot run due to missing main jar (#12705)
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTask.java
Labels: bug

#12801 [Feature][UI] Added form stadio parser.
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-form-validate.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dynamic-dag/task/use-task-form.ts
Labels: feature, UI, refactor

#12462 [typo] Update use-dependent.ts typo
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
Labels: first time contributor, UI, improvement

#12803 Add switch for checkOwn (#197)
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/CommonUtils.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionCheckerUtils.java
Labels: improvement, backend, 3.1.x

#12695 [Bug] [dolphinscheduler-api] in the task define list, when edit task, should show pre node list
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/vo/TaskDefinitionVo.java
Labels: bug, backend

#12807 [fix][doc] Fix sql-hive and hive-cli doc (#12765)
  docs/docs/en/guide/task/hive-cli.md
  docs/docs/en/guide/task/sql.md
  docs/docs/zh/guide/task/hive-cli.md
  docs/docs/zh/guide/task/sql.md
  docs/img/tasks/demo/hive_cli_from_script.png
  docs/img/tasks/demo/pre_post_sql.png
Labels: document

#12813 [Bug][Api] Added param description.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
Labels: improvement, backend

#12689 [fix-12687]when timeout_notify_strategy is null, modify timeout_notify_strategy
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/vo/TaskDefinitionVo.java
Labels: bug, backend

#12523 [Improvement][script] Add installPath verification for install.sh
  script/install.sh
Labels: first time contributor, improvement, backend

#12848 [fix][doc] Dead link for python api
  README.md
  docs/configs/docsdev.js
Labels: document

#12829 [Feature-12827] add icon in idea
  .gitignore
  .idea/icon.png
Labels: feature, improvement, backend

#12861 Add minio as demo storage for helm charts
  deploy/kubernetes/dolphinscheduler/Chart.yaml
  deploy/kubernetes/dolphinscheduler/resources/config/common.properties
  deploy/kubernetes/dolphinscheduler/templates/NOTES.txt
  deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl
  deploy/kubernetes/dolphinscheduler/templates/configmap.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/docs/en/guide/installation/kubernetes.md
Labels: feature, document, 3.2.0

#12726 [Improvement-12029][dolphinscheduler-api] Upgrade the snakeyaml version to avoid vulnerabilities
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  tools/dependencies/known-dependencies.txt
Labels: improvement, backend

#12639 Upgrade clickhouse jdbc driver
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/DataSourceConstants.java
  dolphinscheduler-data-quality/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-clickhouse/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  tools/dependencies/known-dependencies.txt
Labels: improvement, backend

#12864 [Doc][release][3.1.1] add 3.1.1 release doc
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/contribute/release/release.md
  docs/docs/en/history-versions.md
  docs/docs/zh/contribute/release/release.md
  docs/docs/zh/history-versions.md
Labels: document

#12869 [Doc][release][3.1.1] The new Chinese document latest version is 3.1.1
  docs/configs/site.js
Labels: document

#12808 [3.0.2-prepare] Fix issues after cherry-pick and run CI
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/DateUtilsTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessDefinition.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/WorkflowUtils.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/utils/WorkflowUtilsTest.java
Labels: improvement

#12815 [Improvement][CI] Update github mergeable label regex
  .github/mergeable.yml
Labels: improvement, CI&CD, 3.2.0

#12851 [Improvement-12850][UT] Improve the ut of DataSourceMapperTest
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/DataSourceMapperTest.java
Labels: improvement, backend

#12855 [Feature-8030][docs] Add sqoop task doc
  docs/docs/en/guide/task/sqoop.md
  docs/docs/zh/guide/task/sqoop.md
  docs/img/tasks/demo/sqoop_task01.png
  docs/img/tasks/demo/sqoop_task02.png
  docs/img/tasks/demo/sqoop_task03.png
  docs/img/tasks/icons/sqoop.png
Labels: first time contributor, document

#12877 [3.1.2-prepare][cherry-pick] [Doc][Bug] Fix dead link caused by markdown cross-files a…
  docs/docs/en/contribute/join/pull-request.md
  docs/docs/en/guide/task/chunjun.md
  docs/docs/en/guide/task/conditions.md
  docs/docs/en/guide/task/datax.md
  docs/docs/en/guide/task/dependent.md
  docs/docs/en/guide/task/dinky.md
  docs/docs/en/guide/task/dvc.md
  docs/docs/en/guide/task/emr.md
  docs/docs/en/guide/task/flink.md
  docs/docs/en/guide/task/hive-cli.md
  docs/docs/en/guide/task/http.md
  docs/docs/en/guide/task/java.md
  docs/docs/en/guide/task/jupyter.md
  docs/docs/en/guide/task/kubernetes.md
  docs/docs/en/guide/task/map-reduce.md
  docs/docs/en/guide/task/mlflow.md
  docs/docs/en/guide/task/openmldb.md
  docs/docs/en/guide/task/pigeon.md
  docs/docs/en/guide/task/python.md
  docs/docs/en/guide/task/pytorch.md
  docs/docs/en/guide/task/sagemaker.md
  docs/docs/en/guide/task/seatunnel.md
  docs/docs/en/guide/task/shell.md
  docs/docs/en/guide/task/spark.md
  docs/docs/en/guide/task/sql.md
  docs/docs/en/guide/task/stored-procedure.md
  docs/docs/en/guide/task/sub-process.md
  docs/docs/en/guide/task/switch.md
  docs/docs/en/guide/task/zeppelin.md
  docs/docs/zh/contribute/join/pull-request.md
  docs/docs/zh/guide/task/chunjun.md
  docs/docs/zh/guide/task/conditions.md
  docs/docs/zh/guide/task/datax.md
  docs/docs/zh/guide/task/dependent.md
  docs/docs/zh/guide/task/dinky.md
  docs/docs/zh/guide/task/dvc.md
  docs/docs/zh/guide/task/emr.md
  docs/docs/zh/guide/task/flink.md
  docs/docs/zh/guide/task/hive-cli.md
  docs/docs/zh/guide/task/http.md
  docs/docs/zh/guide/task/java.md
  docs/docs/zh/guide/task/jupyter.md
  docs/docs/zh/guide/task/kubernetes.md
  docs/docs/zh/guide/task/map-reduce.md
  docs/docs/zh/guide/task/mlflow.md
  docs/docs/zh/guide/task/openmldb.md
  docs/docs/zh/guide/task/pigeon.md
  docs/docs/zh/guide/task/python.md
  docs/docs/zh/guide/task/pytorch.md
  docs/docs/zh/guide/task/sagemaker.md
  docs/docs/zh/guide/task/seatunnel.md
  docs/docs/zh/guide/task/shell.md
  docs/docs/zh/guide/task/spark.md
  docs/docs/zh/guide/task/sql.md
  docs/docs/zh/guide/task/stored-procedure.md
  docs/docs/zh/guide/task/sub-process.md
  docs/docs/zh/guide/task/switch.md
  docs/docs/zh/guide/task/zeppelin.md
Labels: document

#12876 [fix-#12875]command line that ``` -Dmaven.test.skip=true``` have no effect
  pom.xml
Labels: chore, 3.2.0

#12878 Fix memory leak in worker due to message retry map
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/message/MessageRetryRunner.java
Labels: bug, 3.0.x, 3.1.x, 3.2.0

#12879 [bug][alert-12865] translate alert input field tips to chinese when using chinese
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertInputTips.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-dingtalk/src/main/java/org/apache/dolphinscheduler/plugin/alert/dingtalk/DingTalkAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-slack/src/main/java/org/apache/dolphinscheduler/plugin/alert/slack/SlackAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-telegram/src/main/java/org/apache/dolphinscheduler/plugin/alert/telegram/TelegramAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-webexteams/src/main/java/org/apache/dolphinscheduler/plugin/alert/webexteams/WebexTeamsAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-wechat/src/main/java/org/apache/dolphinscheduler/plugin/alert/wechat/WeChatAlertChannelFactory.java
Labels: bug, backend, 3.1.x

#12874 [Fix-12832][API] Fix update worker group exception group name already exists.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/WorkerGroupServiceTest.java
Labels: bug, backend, 3.1.x

#12839 [Improvement-12838][UT] Improve the ut of datasource
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
Labels: improvement, backend, 3.2.0

#12840 [Feature-12526][Api] add dynamic task function: shell task
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/DynamicTaskTypeConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DynamicTaskTypeController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/taskType/DynamicTaskInfo.java
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-api/src/main/resources/dynamic-task-type-config.yaml
  dolphinscheduler-api/src/main/resources/static/shell/shell.json
  dolphinscheduler-api/src/main/resources/static/shell/shell.png
  dolphinscheduler-api/src/main/resources/static/shell/shell_hover.png
  dolphinscheduler-standalone-server/src/main/assembly/dolphinscheduler-standalone-server.xml
Labels: feature, backend, 3.1.x

#12886 [3.0.2-prepare] Update version number from 3.0.1 to 3.0.2
  README.md
  README_zh_CN.md
  deploy/README.md
  deploy/docker/.env
  deploy/kubernetes/dolphinscheduler/Chart.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/configs/docs3-0-2.js
  docs/docs/en/contribute/release/release-post.md
  docs/docs/en/history-versions.md
  docs/docs/zh/contribute/release/release-post.md
  docs/docs/zh/history-versions.md
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
  dolphinscheduler-python/pydolphinscheduler/README.md
  dolphinscheduler-python/pydolphinscheduler/setup.py
Labels: improvement, 3.0.x

#12892 [bug][alert-12890]add spring-context to alert api
  dolphinscheduler-alert/dolphinscheduler-alert-api/pom.xml
Labels: bug, backend, 3.1.x

#12862 [Bugfix-12603] Dependency conditions for the last 24 hours of the dependent task did not take effect
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DependentUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/DependentUtilsTest.java
Labels: bug, backend

#12893 [fix] Add token as authentication for python gateway
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/PythonGatewayConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: bug, backend, Python, 3.2.0

#12894 [3.0.2-prepare][cherry-pick] Fix procedure out param
  docs/docs/en/guide/task/stored-procedure.md
  docs/docs/zh/guide/task/stored-procedure.md
  docs/img/procedure-en.png
  docs/img/procedure_edit.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java
Labels: bug, 3.0.x

#12895 [3.0.2-prepare][cherry-pick] Fix send script alert NPE
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptAlertChannel.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/test/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSenderTest.java
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java
Labels: bug, 3.0.x

#12889 Use System#lineSeparator to replace /n
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/generator/SqoopJobGenerator.java
Labels: improvement, backend, 3.2.0

#12883 [Upgrade][SQL]Modify the table t_ds_worker_group to add a description field in the postgresql upgrade script
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/postgresql/dolphinscheduler_ddl.sql
Labels: bug, backend, 3.1.x

#12906 [3.0.2-prepare][Bug] Fix default value for resource center in k8s mode
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: bug

#12857 [Improvement-12856][UT] Refactor duplicated code fragment in UdfFuncMapperTest
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapperTest.java
Labels: improvement, backend, test

#12891 Fix master cluster may loop command unbalanced
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/CommandMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/CommandMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/CommandMapperTest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterSchedulerBootstrap.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/command/CommandService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/command/CommandServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/command/CommandServiceImplTest.java
Labels: improvement, backend, 3.2.0

#12912 [Improvement][Document]Update architecture and process-start-flow picture
  docs/docs/en/architecture/design.md
  docs/img/architecture-lastest.jpg
  docs/img/process-start-flow-1.3.0.png
Labels: improvement, document, 3.0.x, 3.1.x, 3.2.0

#11747 [Feature][Api] Refactor org.apache.dolphinscheduler.api.controller.TaskInstanceController
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskInstanceV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/taskInstance/TaskInstanceListPagingResponse.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/taskInstance/TaskInstanceQueryRequest.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/taskInstance/TaskInstanceSuccessResponse.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TaskInstanceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TaskInstanceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TaskInstanceV2ControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskInstanceServiceTest.java
Labels: feature, first time contributor, backend, refactor, 3.2.0, 4.0.0

#12921 [CI] [Chore] Add label 4.0.0 to mergeable check
  .github/mergeable.yml
Labels: CI&CD, chore, 3.0.x

#12918 [chore][python] Change name from process definition to workflow
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
Labels: backend, chore, 3.2.0

#12693 [Feature-12456][task plugin] Add new task plugin for apache linkis
  docs/configs/docsdev.js
  docs/docs/en/guide/task/linkis.md
  docs/docs/zh/guide/task/linkis.md
  docs/img/tasks/demo/linkis_task01.png
  docs/img/tasks/demo/linkis_task02.png
  docs/img/tasks/icons/linkis.png
  dolphinscheduler-api/src/main/resources/task-type-config.yaml
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/Constants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisJobStatus.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/test/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisTaskTest.java
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/datasync.png
  dolphinscheduler-ui/public/images/task-icons/datasync_hover.png
  dolphinscheduler-ui/public/images/task-icons/linkis.png
  dolphinscheduler-ui/public/images/task-icons/linkis_hover.png
  dolphinscheduler-ui/src/store/project/task-type.ts
  dolphinscheduler-ui/src/store/project/types.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-linkis.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-linkis.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
  script/env/dolphinscheduler_env.sh
Labels: feature, UI, backend, document, miss:docs, 3.2.0

#12867 [Bug] [Alert] Ignore alert not write info to db
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java
Labels: bug, backend, 3.0.x

#12900 [improve]Source skip check
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
Labels: feature, backend, 3.2.0

#12928 [Improvement][Task Plugin] Improvement Kubeflow task plugin
  docs/docs/en/guide/task/kubeflow.md
  docs/docs/zh/guide/task/kubeflow.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-kubeflow/src/main/java/org/apache/dolphinscheduler/plugin/kubeflow/KubeflowHelper.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-kubeflow/src/main/java/org/apache/dolphinscheduler/plugin/kubeflow/KubeflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-kubeflow/src/test/java/org/apache/dolphinscheduler/plugin/kubeflow/KubeflowTaskTest.java
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
Labels: UI, backend, document, 3.2.0

#12909 [Bug-12908][Worker]Fix execute shell task exception no dolphinscheduler_env.sh file execute permission
  dolphinscheduler-worker/src/main/bin/start.sh
Labels: bug, 3.0.x, 3.1.x

#12934 docs: update faq, fix spelling, remove repeated words
  docs/docs/en/faq.md
Labels: document, 3.2.0

#12935 [Document] Fix spelling
  docs/docs/en/architecture/configuration.md
  docs/docs/en/guide/project/workflow-definition.md
  docs/docs/en/guide/task/pytorch.md
  docs/docs/en/guide/upgrade/upgrade.md
Labels: improvement, document, 3.2.0

#12929 [Fix] Fix ldap error
  dolphinscheduler-api/src/main/resources/application.yaml
Labels: bug, 3.0.x

#12922 [Feature][UI]make status and schedule publish status display together (issue-12834)
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: feature, first time contributor, UI, 3.2.0

#12937 Fix grammar and spelling
  docs/docs/en/architecture/design.md
  docs/docs/en/contribute/api-standard.md
  docs/docs/en/contribute/join/become-a-committer.md
  docs/docs/en/faq.md
  docs/docs/en/guide/parameter/priority.md
  docs/docs/en/guide/task/mlflow.md
  docs/docs/zh/architecture/design.md
  dolphinscheduler-master/src/main/resources/logback-spring.xml
  dolphinscheduler-standalone-server/src/main/resources/logback-spring.xml
  dolphinscheduler-worker/src/main/resources/logback-spring.xml
Labels: improvement, document, 3.2.0

#12854 [Improvement-12853][UT] Improve the ut of ResourcePermissionCheckServiceTest
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceTest.java
Labels: improvement, backend, 3.2.0

#12949 [3.0.2-release][Document] Update docs for 3.0.2 release
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: document, 3.0.x

#12940 [Document] Fix grammar and spelling
  docs/docs/en/architecture/configuration.md
  docs/docs/en/contribute/frontend-development.md
  docs/docs/en/contribute/join/unit-test.md
  docs/docs/en/contribute/release/release.md
  docs/docs/en/guide/task/sqoop.md
Labels: document, priority:middle, 3.2.0

#12805 [Improvement-12804][UT] Remove the unused method in DataAnalysisControllerTest
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/DataAnalysisControllerTest.java
Labels: improvement, backend

#12933 [fix-#12932] when subprocess's processInstance is fail,not notify parent processInstance
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java
Labels: bug, backend, priority:high, 3.2.0

#12955 [Bug-12954] [Schedule] Fix that workflow-level configuration information does not take effect when timing triggers execution
  docs/docs/en/guide/task/sqoop.md
  dolphinscheduler-scheduler-plugin/dolphinscheduler-scheduler-quartz/src/main/java/org/apache/dolphinscheduler/scheduler/quartz/ProcessScheduleTask.java
Labels: bug, backend, document, priority:high, 3.0.x, 3.1.x

#12961 [Bug] [Task Plugin] Python task can not pass the parameters to downstream task.
  docs/docs/en/guide/parameter/context.md
  docs/docs/zh/guide/parameter/context.md
  docs/img/new_ui/dev/parameter/python_context_param.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
Labels: backend, document, 3.0.x, 3.1.x

#12977 [ci] Require docs context before merge, and run spotless check
  .asf.yaml
  .github/workflows/docs.yml
Labels: CI&CD, chore, 3.2.0

#12985 [hotfix][ci] Remove dead link check path filter
  .github/workflows/docs.yml
Labels: chore, 3.2.0

#11589 [Feature-10498] Mask the password in the log of sqoop task
  docs/docs/en/architecture/design.md
  docs/docs/zh/architecture/design.md
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/SensitiveDataConverter.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/log/SensitiveDataConverterTest.java
  dolphinscheduler-master/src/main/resources/logback-spring.xml
  dolphinscheduler-standalone-server/src/main/resources/logback-spring.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/SqoopConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/SqoopTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/test/java/org/apache/dolphinscheduler/plugin/task/sqoop/SqoopTaskTest.java
  dolphinscheduler-worker/src/main/resources/logback-spring.xml
Labels: discussion, improvement, backend, document, security, miss:tests, 3.2.0

#12987 [Fix] Fix K8s error
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: document, 3.1.x

#12974 [Improvement-12973][API] The task instance list is sorted by submission time
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
Labels: bug, backend, 3.1.x

#12965 [Bug-12963] [Master] Fix dependent task node null pointer exception
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
Labels: bug, backend, 3.0.x, 3.1.x

#12984 Fix sql task will send alert if we don't choose the send email
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
Labels: bug, backend, 3.1.x

#12980 [Improvement-12907] Change heartbeat log level to debug
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/LowerWeightHostManager.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/task/MasterHeartBeatTask.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/task/WorkerHeartBeatTask.java
Labels: improvement, backend, 3.2.0

#12917 [Fix-12916] Add permission check when query or download log
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoggerController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/LoggerService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/LoggerServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
Labels: improvement, backend, 3.2.0

#13006 [Improvement][UI] Support to drag the column of workflow name to resize its width.
  dolphinscheduler-ui/package.json
  dolphinscheduler-ui/pnpm-lock.yaml
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: UI, improvement, 3.1.x

#13009 [Bug-13008] [UI] When using the complement function, turn on the dependent mode to generate multiple unrelated workflow instances
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: bug, Waiting for review, UI, 3.1.x

#12768 [Improvement-12763][UT] Improve testListAuthorizedProjects() in ProjectMapperTest
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProjectMapperTest.java
Labels: improvement, backend, 3.2.0

#12995 [Bug-12994] [Worker] Fix kill process does not take effect
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
Labels: bug, backend, 3.1.x

#12998 [Bug-12997][API] Fix that the end time is not reset when the workflow instance reruns.
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessInstance.java
Labels: bug, backend, 3.1.x

#13007 Set max loop times when consume StateEvent to avoid dead loop influence the thread.
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: improvement, backend, 3.1.x
