Repository apache/dolphinscheduler, pull requests merged in 2022-07, with the labels that each got.

#9577 [feature][task-flink] Support Flink application mode
  docs/docs/en/guide/task/flink.md
  docs/docs/zh/guide/task/flink.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FileUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkDeployMode.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTaskTest.java
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-flink.ts
Labels: improvement

#10725 [Bug] fix license check
  dolphinscheduler-dist/release-docs/LICENSE
  tools/dependencies/known-dependencies.txt
Labels: bug, backend

#10722 [Bug] [Fix-10673] Workflow recovery bug with failed tasks
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
Labels: bug, backend

#10720 [Fix][UI] Fix bug where project overview page display no data
  dolphinscheduler-ui/src/views/projects/overview/index.tsx
Labels: bug, UI

#10712 Modified quick start.
  docs/docs/en/guide/start/quick-start.md
Labels: document

#10716 Merging general settings to faq
  docs/configs/docsdev.js
Labels: document

#10708 [Fix-10443][server]fix dependent task always running
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
Labels: bug, first time contributor, backend

#10735 [Refactor][UI] Refactor worker group manage using NSpace component.
  dolphinscheduler-ui/src/views/security/worker-group-manage/index.module.scss
  dolphinscheduler-ui/src/views/security/worker-group-manage/index.tsx
Labels: UI, refactor

#10741 [Docs] Replace the dag screenshot of the README.
  images/en_US/master.png
  images/zh_CN/master.png
Labels: document

#10744 [Cherry-pick] pick 8811/9020/9834 from dev to 206
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSender.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/postgresql/dolphinscheduler_dml.sql
  script/dolphinscheduler-daemon.sh
Labels: Chore

#10742 [chore] update by release version
  .github/ISSUE_TEMPLATE/bug-report.yml
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: Chore

#10711 Modified project doc files.
  docs/docs/en/guide/project/project-list.md
  docs/docs/en/guide/project/task-instance.md
  docs/docs/en/guide/project/workflow-definition.md
  docs/docs/en/guide/project/workflow-instance.md
  docs/docs/en/guide/project/workflow-relation.md
  docs/img/new_ui/dev/project/work-relation.png
Labels: document

#10755 [Cherry-pick] fix pick error
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSender.java
Labels: Chore

#10764 Add improvement template
  .github/ISSUE_TEMPLATE/improvement-report.yml
Labels: improvement, Chore

#10688 [Feature-10566][Doc] unified data source switching of the docs during installation
  docs/configs/docsdev.js
  docs/docs/en/guide/datasource/introduction.md
  docs/docs/en/guide/datasource/mysql.md
  docs/docs/en/guide/howto/datasource-setting.md
  docs/docs/en/guide/howto/general-setting.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/en/guide/task/sql.md
  docs/docs/zh/guide/datasource/introduction.md
  docs/docs/zh/guide/datasource/mysql.md
  docs/docs/zh/guide/howto/datasource-setting.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/standalone.md
  docs/docs/zh/guide/task/sql.md
Labels: improvement, document

#10767 206 release
  docker/docker-swarm/docker-compose.yml
  docker/docker-swarm/docker-stack.yml
  docker/kubernetes/dolphinscheduler/Chart.yaml
  docker/kubernetes/dolphinscheduler/values.yaml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
  dolphinscheduler-python/pydolphinscheduler/setup.py
Labels: Chore

#10667 [Fix-10666] Workflow submit failed will still in memory and never retry
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/exception/MasterException.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/ProcessInstanceMetrics.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterSchedulerService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowSubmitStatue.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnableTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
Labels: bug, backend

#10754 [Feature][Master] Failover workflow instance base on priority
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: improvement, backend

#10640 [Feature-10444][Task] Add Dinky task to better support the development and execution of FlinkSQL
  docs/configs/docsdev.js
  docs/docs/en/guide/task/dinky.md
  docs/docs/zh/guide/task/dinky.md
  docs/img/tasks/demo/dinky.png
  docs/img/tasks/demo/dinky_task_id.png
  docs/img/tasks/icons/dinky.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTaskException.java
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/dinky.png
  dolphinscheduler-ui/public/images/task-icons/dinky_hover.png
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dinky.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-dinky.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
  dolphinscheduler-ui/src/views/projects/workflow/definition/tree/index.tsx
Labels: new feature, UI, backend

#10739 [Optimization]Optimize some details of MLFlow task plugin #10740
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/test/java/org/apache/dolphinler/plugin/task/mlflow/MlflowTaskTest.java
Labels: improvement, backend

#10775 [Fix-10773] [UI] Fix language not matched
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-resource-limit.ts
Labels: bug, first time contributor, UI

#10789 [Bug][Script] Remove deprecated arg in remove-zk-node.sh
  script/remove-zk-node.sh
Labels: bug, backend

#10718 [Optimization] Config module resource relation fix.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/EnvironmentServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UdfFuncServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/QueueServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/QueueMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/QueueMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/QueueMapperTest.java
Labels: improvement, backend

#10772 [python] Correct some docs for python api
  dolphinscheduler-python/pydolphinscheduler/DEVELOP.md
  dolphinscheduler-python/pydolphinscheduler/README.md
  dolphinscheduler-python/pydolphinscheduler/docs/source/conf.py
  dolphinscheduler-python/pydolphinscheduler/docs/source/config.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/howto/remote-submit.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/start.rst
  dolphinscheduler-python/pydolphinscheduler/setup.py
Labels: improvement, Python, document

#10480 [Task] Added Apache SeaTunnel 2.x task node
  docs/configs/docsdev.js
  docs/docs/en/guide/task/seatunnel.md
  docs/docs/zh/guide/task/seatunnel.md
  docs/img/tasks/demo/seatunnel_task01.png
  docs/img/tasks/demo/seatunnel_task02.png
  docs/img/tasks/icons/seatunnel.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/Constants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/DeployModeEnum.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/EngineEnum.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/flink/SeatunnelFlinkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/flink/SeatunnelFlinkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/spark/SeatunnelSparkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/spark/SeatunnelSparkTask.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-deploy-mode.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-resources.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sea-tunnel.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sea-tunnel.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  script/env/dolphinscheduler_env.sh
Labels: UI, improvement, backend

#10798 [doc] Replace the dag screenshot of the README.
  images/en_US/home.png
  images/zh_CN/home.png
Labels: document

#10797 [Fix][UI] Fix the environment name display back error.
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-environment-name.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: bug, UI

#10713 [doc] Modify features, hw, intro and homepage docs.
  docs/configs/docsdev.js
  docs/docs/en/about/features.md
  docs/docs/en/about/hardware.md
  docs/docs/en/about/introduction.md
  docs/docs/en/guide/homepage.md
  docs/docs/en/guide/resource/udf-manage.md
  docs/docs/zh/about/features.md
  docs/docs/zh/about/introduction.md
  docs/docs/zh/guide/homepage.md
  docs/img/introduction_ui.png
Labels: document

#10799 [Refactor][UI] Refactor alarm instance manage using NSpace component.
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/index.module.scss
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/index.tsx
Labels: UI, refactor

#10768 [doc] Correct custom jdbc driver for K8s Doc
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: bug, document

#10804 [chore] Add doc issue template
  .github/ISSUE_TEMPLATE/document.yml
Labels: Chore, community

#10793 [Transactional][API][Service] Do not specify rollback for to ensure the correct rollback in case of any exception or error.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AccessTokenServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ClusterServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/EnvironmentServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessTaskRelationServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SessionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UdfFuncServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend

#10805 [API-Test] [Checkstyle] Reformat api-test code and enable checkstyle
  .github/workflows/api-test.yml
  dolphinscheduler-api-test/README.md
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/cases/TenantAPITest.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/entity/TenantListPagingResponseData.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/entity/TenantListPagingResponseTotalList.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/pages/LoginPage.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/pages/security/TenantPage.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/utils/JSONUtils.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/utils/RequestClient.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/docker/basic/docker-compose.yaml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/docker/datasource-clickhouse/docker-compose.yaml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/docker/datasource-hive/docker-compose.yaml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/docker/datasource-postgresql/docker-compose.yaml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/docker/file-manage/common.properties
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/docker/file-manage/docker-compose.yaml
  dolphinscheduler-api-test/dolphinscheduler-api-test-core/src/main/java/org/apache/dolphinscheduler/api/test/core/Constants.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-core/src/main/java/org/apache/dolphinscheduler/api/test/core/DolphinSchedulerExtension.java
  dolphinscheduler-api-test/pom.xml
Labels: test, Chore

#10748 Remove quartz in service
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DqExecuteResultServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DqRuleServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AuditServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DqExecuteResultServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DqRuleServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskInstanceServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-service/pom.xml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/cron/AbstractCycle.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/cron/CronUtils.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/cron/CycleFactory.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/cron/CycleLinks.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/exceptions/CronParseException.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/cron/CronUtilsTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
  dolphinscheduler-worker/pom.xml
Labels: improvement, backend

#10658 [Feature] Enable users to create python env from requirements.txt
  docs/docs/en/guide/task/jupyter.md
  docs/docs/zh/guide/task/jupyter.md
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/utils/DateUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/test/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTaskTest.java
Labels: new feature, backend

#10816 [Refactor][UI] Refactor user manage using NSpace component.
  dolphinscheduler-ui/src/views/security/user-manage/index.tsx
Labels: UI, refactor

#10819 [Improvement] [CI] Add reviewdog token to enable checkstyle
  .github/workflows/api-test.yml
  .github/workflows/e2e.yml
  .github/workflows/py-ci.yml
  .github/workflows/unit-test.yml
Labels: CI&CD, Chore

#10807 [Improvement] Resource authority module database table unique index increased.
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapperTest.java
Labels: improvement, backend

#10650 [Feature-10629][Improvement] Support multi cluster environments - namespace use cluster
  docs/docs/en/guide/security.md
  docs/docs/zh/guide/security.md
  docs/img/new_ui/dev/security/create-namespace.png
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/K8sNamespaceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/k8s/K8sClientService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/k8s/K8sManager.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/K8sNamespaceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ClusterServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/K8SNamespaceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ClusterControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/K8sNamespaceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/k8s/K8sManagerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ClusterServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/K8SNamespaceServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/K8sNamespace.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceMapper.xml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceMapperTest.java
  dolphinscheduler-ui/src/locales/en_US/security.ts
  dolphinscheduler-ui/src/locales/zh_CN/security.ts
  dolphinscheduler-ui/src/service/modules/k8s-namespace/types.ts
  dolphinscheduler-ui/src/views/security/k8s-namespace-manage/components/k8s-namespace-modal.tsx
  dolphinscheduler-ui/src/views/security/k8s-namespace-manage/components/use-modal.ts
  dolphinscheduler-ui/src/views/security/k8s-namespace-manage/use-table.ts
Labels: UI, improvement, backend

#10813 [Build][UI] Updated dependencies.
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/ResourcePage.java
  dolphinscheduler-ui/package.json
  dolphinscheduler-ui/pnpm-lock.yaml
Labels: dependencies, UI

#10838 [Docs] Updated license.
  dolphinscheduler-dist/release-docs/LICENSE
Labels: dependencies, document

#10835 [Feature-10594][ui] Data Quality Result Display Optimize
  dolphinscheduler-ui/src/views/data-quality/task-result/use-table.ts
Labels: bug, UI

#10792 [python] Fix submit and run error
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/exceptions/ApiExceptionHandler.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/exceptions/ServiceException.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/QueueService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TenantService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/QueueControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/QueueServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/QueueMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/QueueMapper.xml
Labels: bug, Python

#10836 [Fix-10829][UI] display real workflow relation.
  dolphinscheduler-ui/src/components/result/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/relation/components/Graph.tsx
  dolphinscheduler-ui/src/views/projects/workflow/relation/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/relation/use-relation.ts
Labels: bug, UI

#10848 [Improvement] [CI] Add label robot to pull request
  .github/actions/labeler/labeler.yml
  .github/workflows/issue-robot.yml
  .github/workflows/pull-request-robot.yml
Labels: CI&CD

#10855 [doc] 206 drop down doc not work
  docs/configs/site.js
Labels: bug, document

#10852 [CI] Try to fix label bot
  .github/actions/labeler/labeler.yml
  .github/workflows/pull-request-robot.yml
Labels: bug, CI&CD

#10859 [CI] Fix label bot again
  .github/actions/labeler/labeler.yml
Labels: CI&CD

#10839 [Fix-10842] Fix master/worker failover will cause status incorrect
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/graph/DAG.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumer.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/context/ExecutionContext.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManager.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryDataListener.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/FailoverExecuteThread.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/CommonTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/FailoverService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/WorkerFailoverService.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutionContextTestUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManagerTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/service/FailoverServiceTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/TaskPriority.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: bug, backend

#10847 [Doc][Upgrade] Fix tiny error in upgrade docs
  docs/docs/en/guide/upgrade.md
  docs/docs/zh/guide/upgrade.md
Labels: document

#10857 [Feature][dependencies] Bump spring-core from 5.3.12 to 5.3.19
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/NOTICE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-spring-beans.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-spring-boot.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-spring-context.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-spring-core.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-spring-jdbc.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-spring-tx.txt
  pom.xml
  tools/dependencies/check-LICENSE.sh
  tools/dependencies/known-dependencies.txt
Labels: first time contributor, backend

#10831 [Fix-10830][Doc] Change the start or install script command sh in the document to bash
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/howto/datasource-setting.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/howto/datasource-setting.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/standalone.md
Labels: first time contributor, document

#10862 Complement numbers will run in a loop under the serial strategy fixed.
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/BlockingTaskTest.java
Labels: backend

#10850 [Bug][Api] Complete Data workflow remove duplicates.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
Labels: bug, backend

#10865 [Fixed-10833] [Bug] [Quartz] timezone display doesn't match the next_fire_time in ds 3.0.0-beta1 version
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/SchedulerControllerTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/DateUtilsTest.java
Labels: bug, backend

#10868 [Bug][Api] Complete Data workflow remove duplicates.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
Labels: backend

#10657 [Feature-10219][EMR] EMR supports use <add-Steps> to add steps to an existing cluster
  docs/docs/en/guide/task/emr.md
  docs/docs/zh/guide/task/emr.md
  docs/img/tasks/demo/emr_add_job_flow_steps.png
  docs/img/tasks/demo/emr_jobFlowId.png
  docs/img/tasks/demo/emr_run_job_flow.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/AbstractEmrTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrAddStepsTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrJobFlowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/ProgramType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/java/org/apache/dolphinscheduler/plugin/task/emr/EmrAddStepsTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/java/org/apache/dolphinscheduler/plugin/task/emr/EmrJobFlowTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/resources/org/apache/dolphinscheduler/plugin/task/emr/EmrAddStepsDefine.json
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/resources/org/apache/dolphinscheduler/plugin/task/emr/EmrErrorAddStepsDefine.json
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-emr.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-emr.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, improvement, backend, document

#10825 [python] Integrate test run strategy change
  .github/workflows/py-ci.yml
Labels: CI&CD

#10864 [Fix-10863] Command execution result data statistics remove userId condition.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/aspect/AccessLogAspectTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/CommandMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/CommandMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/CommandMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapperTest.java
Labels: backend

#10877 [fix] update queue and tenant with same code error
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/QueueServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Queue.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Tenant.java
Labels: improvement, backend

#10879 [Refactor][UI] Refactor tenant manage using NSpace component.
  dolphinscheduler-ui/src/views/security/tenant-manage/index.module.scss
  dolphinscheduler-ui/src/views/security/tenant-manage/index.tsx
Labels: UI, refactor

#10875 [Feature-10871] add workflow executing data query
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/controller/WorkflowExecuteController.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/WorkflowExecutingDataRequestProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/MasterRPCServer.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/ExecutingService.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/CommandType.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/WorkflowExecutingDataRequestCommand.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/WorkflowExecutingDataResponseCommand.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/dto/TaskInstanceExecuteDto.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/dto/WorkflowExecuteDto.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/processor/StateEventCallbackService.java
Labels: new feature, backend

#10880 [Feat][UI] Uniform search button size.
  dolphinscheduler-ui/src/views/security/alarm-group-manage/index.tsx
  dolphinscheduler-ui/src/views/security/cluster-manage/index.tsx
  dolphinscheduler-ui/src/views/security/environment-manage/index.tsx
  dolphinscheduler-ui/src/views/security/k8s-namespace-manage/index.tsx
  dolphinscheduler-ui/src/views/security/token-manage/index.tsx
  dolphinscheduler-ui/src/views/security/worker-group-manage/index.tsx
  dolphinscheduler-ui/src/views/security/yarn-queue-manage/index.tsx
Labels: new feature, UI

#10876 [Fix][UI] Fix hive datasource doesn't show principal bug
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
Labels: bug, UI

#10749 [Feature][Metrics] Add resource download related metrics for workers
  docs/docs/en/guide/metrics/metrics.md
  docs/docs/zh/guide/metrics/metrics.md
  dolphinscheduler-meter/src/main/resources/grafana/DolphinSchedulerWorker.json
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/metrics/WorkerServerMetrics.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
Labels: backend, document, metrics

#10892 [doc] Add missing doc change by snehal
  docs/configs/docsdev.js
  docs/docs/en/about/hardware.md
  docs/docs/en/guide/alert/dingtalk.md
  docs/docs/en/guide/data-quality.md
  docs/docs/en/guide/datasource/oracle.md
  docs/docs/en/guide/datasource/redshift.md
  docs/docs/en/guide/datasource/sqlserver.md
  docs/docs/en/guide/parameter/global.md
  docs/docs/en/guide/parameter/local.md
  docs/docs/en/guide/parameter/priority.md
  docs/docs/en/guide/project/project-list.md
  docs/docs/en/guide/project/task-instance.md
  docs/docs/en/guide/project/workflow-definition.md
  docs/docs/en/guide/project/workflow-instance.md
  docs/docs/en/guide/resource/file-manage.md
  docs/docs/en/guide/resource/task-group.md
  docs/docs/en/guide/resource/udf-manage.md
  docs/docs/en/guide/security.md
  docs/docs/en/guide/start/quick-start.md
  docs/docs/en/guide/task/conditions.md
  docs/docs/en/guide/task/flink.md
  docs/docs/zh/guide/project/project-list.md
  docs/img/new_ui/dev/project/project-create.png
  docs/img/new_ui/dev/project/project-list.png
  docs/img/new_ui/dev/project/workflow-overview.png
  docs/img/video_cover/quick-use.png
Labels: improvement, document

#10823 [Improvement][Python] Python-gate supports creating or editing resources.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/python/PythonGatewayTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/resource.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_process_definition.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_resource_definition.py
Labels: improvement, backend, Python

#10897 [FIX][plugin]fix MLflow project success status
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
Labels: backend

#10873 [fix] delete workflow or task used by other tasks
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkFlowLineageController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkFlowLineageService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkFlowLineageServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskMainInfo.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskRecord.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.xml
Labels: bug, backend

#10915 [Bug] [Api Server] display timing record create time
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/vo/ScheduleVo.java
Labels: bug, backend

#10900 [Fix][UI] Fix bug where task name display in gantt
  dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx
Labels: bug, UI

#10898 [Fix][UI] Add validator to the next node field of the switch task.
  dolphinscheduler-ui/src/components/form/fields/custom-parameters.ts
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-switch.ts
Labels: bug, UI

#10908 Catch exception when check state in StateWheelExecuteThread
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: backend

#10917 [Fix-10916] Solve transaction problems under multi-threading.
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend

#10821 [fix][plugin]: fix spark sql use custom parma.
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/AbstractParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTask.java
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-spark.ts
Labels: bug, UI, backend

#10888 [FIX-10784][Bug] [ALERT-SERVER] FEISHU Plugin might block the whole alert process loop
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertConfig.java
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/resources/application.yaml
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/test/java/org/apache/dolphinscheduler/alert/runner/AlertSenderServiceTest.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: backend

#10884 [fix] Can not query environments for permission issue
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceImpl.java
Labels: bug, backend

#10922 [Fix-10909] Returns executionStatus for each process instance status and access token module support.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AccessTokenServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AccessTokenServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AccessTokenMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AccessTokenMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/AccessTokenMapperTest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: backend

#10926 Fix taskInstance's host is not worker nettyServer address
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/TaskExecuteResponseProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/TaskExecuteRunningProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskEvent.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseServiceTest.java
Labels: backend

#10948 Fix kill yarn job error when failover caused by doesn't set ProcessDefinition
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/WorkerFailoverService.java
Labels: backend

#10932 [Fix][UI] Set the next node to not required.
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-switch.ts
Labels: bug, UI

#10955 [fix-10954]Querying the task group list returns empty data
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java
Labels: backend

#10958 fix: typo task definition
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskDefinition.java
Labels: first time contributor, backend

#10907 [Fix-10890] fix some bugs in the Resource page
  dolphinscheduler-ui/src/views/resource/file/upload/index.tsx
  dolphinscheduler-ui/src/views/resource/udf/function/components/function-modal.tsx
  dolphinscheduler-ui/src/views/resource/udf/resource/components/folder-modal.tsx
  dolphinscheduler-ui/src/views/resource/udf/resource/components/upload-modal.tsx
  dolphinscheduler-ui/src/views/resource/udf/resource/components/use-form.ts
  dolphinscheduler-ui/src/views/resource/udf/resource/components/use-modal.ts
Labels: bug, UI

#10969 [Feat][UI] Add title display to the table in the security center.
  dolphinscheduler-ui/src/views/security/alarm-group-manage/index.tsx
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/index.tsx
  dolphinscheduler-ui/src/views/security/cluster-manage/index.tsx
  dolphinscheduler-ui/src/views/security/environment-manage/index.tsx
  dolphinscheduler-ui/src/views/security/k8s-namespace-manage/index.tsx
  dolphinscheduler-ui/src/views/security/tenant-manage/index.tsx
  dolphinscheduler-ui/src/views/security/token-manage/index.tsx
  dolphinscheduler-ui/src/views/security/user-manage/index.tsx
  dolphinscheduler-ui/src/views/security/worker-group-manage/index.tsx
  dolphinscheduler-ui/src/views/security/yarn-queue-manage/index.tsx
Labels: new feature, UI

#10834 [Fix-10595][api] Fix Dependent Node Only View Projects Created By Self
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProjectMapperTest.java
Labels: bug, backend

#10941 [python] Fix tasks with multiple upstream and workflow query error
  .github/workflows/py-ci.yml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/QueueServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.xml
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py
  dolphinscheduler-python/pydolphinscheduler/tests/integration/test_submit_examples.py
Labels: backend, CI&CD, Python

#10925 [Feature][Task Plugin] Enable users to switch endpoints in zeppelin tasks
  docs/docs/en/guide/resource/configuration.md
  docs/docs/en/guide/task/zeppelin.md
  docs/docs/zh/guide/task/zeppelin.md
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/test/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-zeppelin.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, improvement, backend, document

#10950 [Feature][Datax Task]Datax task plugin support custom parameters
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datax.ts
Labels: UI, backend

#10991 [Refactor][UI] Refactor audio log using NSpace component.
  dolphinscheduler-ui/src/views/monitor/statistics/audit-log/index.module.scss
  dolphinscheduler-ui/src/views/monitor/statistics/audit-log/index.tsx
Labels: UI, refactor

#10987 [fix] [MLflow Task plugin] Sometimes errors are reported using preset algorithms (#10986)
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/test/java/org/apache/dolphinler/plugin/task/mlflow/MlflowTaskTest.java
Labels: bug, backend

#10997 Kill task when we do master failover to avoid task lost
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/service/FailoverServiceTest.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskKillRequestCommand.java
Labels: backend

#10980 Fix typo executor service
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
Labels: improvement, backend

#10979 Fix worker cannot shutdown due to resource close failed or heart beat check failed
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/thread/ThreadUtils.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/config/MasterConfig.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterSchedulerBootstrap.java
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/registry/HeartBeatTask.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/bean/SpringApplicationContext.java
  dolphinscheduler-standalone-server/src/main/java/org/apache/dolphinscheduler/StandaloneServer.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistryClient.java
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: backend

#10994 Don't write taskPlugin to db in master/worker
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/ApiApplicationServer.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/task/TaskPluginManager.java
  dolphinscheduler-worker/pom.xml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
Labels: backend

#11000 Move utils, builder under master
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/builder/TaskExecutionContextBuilder.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskResultEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/BaseTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/DependentTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SwitchTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/WorkerFailoverService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DataQualityResultOperator.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutionContextTestUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManagerTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/processor/TaskResponseProcessorTestConfig.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseServiceTest.java
Labels: backend

#11008 [hotfix][Worker] Remove service dependency from worker module
  dolphinscheduler-worker/pom.xml
Labels: backend

#10982 impv: not mark issue stale with security label
  .github/workflows/stale.yml
Labels: CI&CD

#11022 [Refactor][UI] Refactor datasource using NSpace component.
  dolphinscheduler-ui/src/views/datasource/list/index.module.scss
  dolphinscheduler-ui/src/views/datasource/list/index.tsx
Labels: UI, refactor

#11029 [Feat][UI] Added LDAP function.
  dolphinscheduler-ui/src/layouts/content/use-dataList.ts
  dolphinscheduler-ui/src/service/modules/users/types.ts
Labels: new feature, UI

#11047 Add EricGao888 to help review docs, tools, etc.
  .github/CODEOWNERS
Labels: CI&CD

#11004 [Fix-11003]Task group queue is not updated to final state
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend

#11053 [Bug-11034] fix task params pass
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParams.java
Labels: backend

#11025 Add dolphinscheduler-bom to manage the dependency version
  dolphinscheduler-alert/pom.xml
  dolphinscheduler-api/pom.xml
  dolphinscheduler-bom/README.md
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/pom.xml
  dolphinscheduler-dao/pom.xml
  dolphinscheduler-data-quality/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-clickhouse/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-presto/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/pom.xml
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-log-server/pom.xml
  dolphinscheduler-master/pom.xml
  dolphinscheduler-meter/pom.xml
  dolphinscheduler-microbench/pom.xml
  dolphinscheduler-registry/pom.xml
  dolphinscheduler-remote/pom.xml
  dolphinscheduler-scheduler-plugin/pom.xml
  dolphinscheduler-server/pom.xml
  dolphinscheduler-service/pom.xml
  dolphinscheduler-spi/pom.xml
  dolphinscheduler-standalone-server/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/pom.xml
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-tools/pom.xml
  dolphinscheduler-ui/pom.xml
  dolphinscheduler-worker/pom.xml
  pom.xml
Labels: UI, backend

#11045 [Improvement][Task Plugin]Refactor JupyterParameters.java with lombok
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterParameters.java
Labels: backend

#11027 [Improvement][Task]Improve seatunnel task command log
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
Labels: backend

#11010 [Feature][Task Plugin] Increase zeppelin task stability in production
  docs/docs/en/guide/task/zeppelin.md
  docs/docs/zh/guide/task/zeppelin.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/test/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-zeppelin.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, backend, document

#10734 [fix-10729]The request's url given by the test case looks different f…
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/DataSourceControllerTest.java
Labels: bug, first time contributor, backend

#11041 [Improve] Hide Change Pwd Page When Login With LDAP
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/SecurityConfig.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/AbstractAuthenticator.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/LoginControllerTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
Labels: backend

#11069 [Refactor][UI] Refactor rule manage using NSpace component.
  dolphinscheduler-ui/src/views/data-quality/rule/index.module.scss
  dolphinscheduler-ui/src/views/data-quality/rule/index.tsx
Labels: UI, refactor

#11077 [E2E] [CI] Fix flaky e2e test
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/common/NavBarPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/datasource/DataSourcePage.java
Labels: e2e

#11078 [Refactor][UI] Refactor time display of token manage use datatable render function
  dolphinscheduler-ui/src/views/security/token-manage/components/token-modal.tsx
  dolphinscheduler-ui/src/views/security/token-manage/index.tsx
  dolphinscheduler-ui/src/views/security/token-manage/use-table.ts
Labels: UI, refactor

#10935 [Feature][Task Plugin] Add SageMaker Pipeline task plugin for MLOps scenario (#10826)
  docs/configs/docsdev.js
  docs/docs/en/guide/task/sagemaker.md
  docs/docs/zh/guide/task/sagemaker.md
  docs/img/tasks/demo/sagemaker_pipeline.png
  docs/img/tasks/icons/sagemaker.png
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-aws-java-sdk-sagemaker.txt
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/PipelineUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTaskException.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/test/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/test/resources/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerRequestJson.json
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/sagemaker.png
  dolphinscheduler-ui/public/images/task-icons/sagemaker_hover.png
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sagemaker.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sagemaker.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
  tools/dependencies/known-dependencies.txt
Labels: UI, backend, document

#11073 [Refactor][UI] Refactor file manage using NSpace component.
  dolphinscheduler-ui/src/views/resource/file/index.module.scss
  dolphinscheduler-ui/src/views/resource/file/index.tsx
Labels: UI, refactor

#11097 [E2E] [CI] Try to fix filemanage e2e flaky test
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/FileManagePage.java
Labels: e2e

#11096 [Fix][UI] Widen the segment separator input box.
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sql-type.ts
Labels: bug, UI

#11100 [FIx][UI] Fix view variable display bug
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-toolbar.tsx
Labels: bug, UI

#11090 [Fix][UI] Fix the problem of too large spacing in operation.
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.module.scss
  dolphinscheduler-ui/src/views/projects/workflow/definition/timing/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: bug, UI

#11009 [Improvement][Task Log] Task status log print description instead of code
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskDelayEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskRejectByWorkerEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskResultEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskRunningEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/StateEventResponseService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskEvent.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/processor/TaskAckProcessorTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/processor/TaskKillResponseProcessorTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskResponseServiceTest.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/StateEventResponseCommand.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskExecuteAckCommand.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskExecuteRunningAckMessage.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskExecuteRunningCommand.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskKillResponseCommand.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskRejectAckCommand.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/message/TaskExecuteRunningMessageSender.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteResultAckProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteRunningAckProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskRejectAckProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
Labels: backend

#11106 [Fix][UI] Fix space validate for create folder bug
  dolphinscheduler-ui/src/utils/trim.ts
  dolphinscheduler-ui/src/views/resource/file/folder/index.tsx
  dolphinscheduler-ui/src/views/resource/udf/resource/components/folder-modal.tsx
Labels: bug, UI

#11109 [fix] py sagemaker doc
  docs/configs/docsdev.js
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/sagemaker.rst
Labels: Python, document

#11120 [Fix-10918] Close datasource when expire from guava cache
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/client/CommonDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/HiveDataSourceClient.java
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/datasource/DataSourceClient.java
Labels: bug, backend

#10977 [fix][Data Quality] Data Quality Report Display For Admin Role #10919
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DqExecuteResultServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DqExecuteResultServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/DqExecuteResultMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/DqExecuteResultMapper.xml
Labels: first time contributor, backend

#11121 [Fix][python] add import SageMaker task
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/__init__.py
Labels: Python

#11135 [Fix][UI] fix bug where The Gantt chart does not show the execution status
  dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx
Labels: bug, UI

#11124 [Refactor][UI] Refactor function manage using NSpace component.
  dolphinscheduler-ui/src/views/resource/udf/function/index.module.scss
  dolphinscheduler-ui/src/views/resource/udf/function/index.tsx
Labels: UI, refactor

#11127 [Improvement 11072][common] Added HTTPS request support in kerberos environment
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HttpUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/KerberosHttpClient.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/LocalServerHttpUtilsTest.java
Labels: backend

#11098 [Refactor][UI] Refactor resource manage using NSpace component.
  dolphinscheduler-ui/src/views/resource/udf/resource/index.module.scss
  dolphinscheduler-ui/src/views/resource/udf/resource/index.tsx
Labels: UI, refactor

#10612 [Bug] [API] If the log file is large but has small number of rows, it will causes the View Log page to hang
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoggerController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/LoggerService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ResponseTaskLog.java
  dolphinscheduler-log-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java
  dolphinscheduler-ui/src/views/projects/task/instance/index.tsx
Labels: bug, UI, backend

#11136 [Fix][UI] add duplicate of file suffix
  dolphinscheduler-ui/src/locales/en_US/resource.ts
  dolphinscheduler-ui/src/locales/zh_CN/resource.ts
  dolphinscheduler-ui/src/views/resource/file/create/use-form.ts
Labels: bug, UI

#11128 [Improvement][Metrics] Switch to use tags to indicate task / workflow execution status for metrics
  docs/docs/en/guide/metrics/metrics.md
  docs/docs/zh/guide/metrics/metrics.md
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskRetryStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowStartEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowTimeoutStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/ProcessInstanceMetrics.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/TaskMetrics.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/WorkerFailoverService.java
  dolphinscheduler-meter/src/main/resources/grafana/DolphinSchedulerMaster.json
Labels: improvement, backend, document, metrics

#11146 [Doc]Chinese translation updated
  docs/docs/zh/guide/task/python.md
  docs/docs/zh/guide/task/zeppelin.md
Labels: bug, first time contributor, document

#11137 Add base loop task execotor and http template parser
  .gitignore
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-accessors-smart.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-asm.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-json-path.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-json-smart.txt
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/BaseLoopTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/LoopTaskCancelMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/LoopTaskDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/LoopTaskInstanceInfo.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/LoopTaskInstanceStatus.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/LoopTaskMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/LoopTaskMethodType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/LoopTaskQueryStatusMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/LoopTaskSubmitTaskMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/LoopTaskYamlDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/TaskDefinitionParser.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/TemplateMethodTransformer.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/BaseHttpTemplateLoopTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/HttpLoopTaskDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/HttpLoopTaskInstanceInfo.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/HttpLoopTaskInstanceStatus.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/HttpLoopTaskMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/method/HttpLoopTaskCancelTaskMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/method/HttpLoopTaskQueryStatusMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/method/HttpLoopTaskSubmitTaskMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/CancelTemplateMethodTransformer.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/HttpTaskDefinitionParser.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/QueryStateTemplateMethodTransformer.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/SubmitTemplateMethodTransformer.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/JsonPathUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/OkHttpUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/RetryUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/HttpTaskDefinitionParserTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/JsonPathUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/RetryUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/resources/mock_loop_task.yaml
  tools/dependencies/known-dependencies.txt
Labels: improvement, backend

#10607 [Feature-10604] Task name in the copied and imported workflow without copy suffix
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
Labels: new feature, discussion, backend, incompatible

#10960 [Feature-10837][Task Plugin] Sqoop Task Add --split-by Parameter
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/SqoopConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/generator/CommonGenerator.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/parameter/SqoopParameters.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sqoop.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sqoop.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, backend, miss:docs

#11084 [doc] Fix bugs in doc installation, design and glossary
  docs/docs/en/architecture/design.md
  docs/docs/en/guide/installation/cluster.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/zh/about/glossary.md
  docs/docs/zh/architecture/design.md
  docs/docs/zh/guide/installation/cluster.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/project/workflow-definition.md
Labels: document

#11153 [doc] Add new page incompatible change
  .github/PULL_REQUEST_TEMPLATE.md
  docs/configs/docsdev.js
  docs/docs/en/guide/upgrede/incompatible.md
  docs/docs/en/guide/upgrede/upgrade.md
  docs/docs/zh/guide/upgreade/incompatible.md
  docs/docs/zh/guide/upgreade/upgrade.md
Labels: CI&CD, document

#10677 [Enhancement][API] Copy workflow with scheduler info
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
Labels: bug, backend

#10913 [Feature-10905][API] Add CURD to the project/tenant/user section of the API and add its tests.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
Labels: new feature, backend

#11172 [Cherry-pick] [3.0.0] Fix space validate for create folder bug (#11106)
  dolphinscheduler-ui/src/utils/trim.ts
  dolphinscheduler-ui/src/views/resource/file/folder/index.tsx
  dolphinscheduler-ui/src/views/resource/udf/resource/components/folder-modal.tsx
Labels: bug, UI

#11168 [Bug-11101] fix task failover NPE
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
Labels: backend

#10675 [Fix-10665] [S3] Fix s3 download method
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/S3Utils.java
Labels: bug, first time contributor, backend

#11133 [11130][refactor] refactor alert-api with lombok
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertData.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertInfo.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertResult.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/ShowType.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannelTest.java
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java
Labels: improvement, backend

#11122 [Improvement][ExecutorServiceImpl] remove some unnecessary
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
Labels: improvement, backend

#11169 Add isSuccess in loop task status to judge the task success or failuer
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/BaseLoopTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/LoopTaskInstanceStatus.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/HttpLoopTaskInstanceStatus.java
Labels: backend

#11141 [Fix-11140] Added resource parameters for function verification
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AccessTokenServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertGroupServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertPluginInstanceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DqExecuteResultServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DqRuleServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/EnvironmentServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/MonitorServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/QueueServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskGroupServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TenantServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UdfFuncServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
Labels: backend

#11115 [FIX-11102][Bug] [Task Plugin] Parameter values disappear in UI when editing Zeppelin task
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-zeppelin.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
Labels: bug, UI

#11184 [Bug-11071] fix local params
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/AbstractParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/parameters/AbstractParametersTest.java
Labels: bug, backend

#11173 [feature-11174][doc] add Feishu alert doc and configure email alert doc to the docsdev.js
  docs/configs/docsdev.js
  docs/docs/en/guide/alert/feishu.md
  docs/docs/zh/guide/alert/feishu.md
  docs/img/new_ui/dev/alert/alert_feishu.png
  docs/img/new_ui/dev/alert/alert_feishu_webhook.png
Labels: document

#11167 [python] Refactor structure to avoid cycle import
  dolphinscheduler-python/pydolphinscheduler/DEVELOP.md
  dolphinscheduler-python/pydolphinscheduler/docs/source/api.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/config.rst
  dolphinscheduler-python/pydolphinscheduler/setup.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/cli/commands.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/configuration.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/__init__.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/resource.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/task.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/default_config.yaml
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/task_dependent_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/java_gateway.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/__init__.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/base.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/base_side.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/project.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/queue.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/tenant.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/user.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/worker_group.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/condition.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/dependent.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/switch.py
  dolphinscheduler-python/pydolphinscheduler/tests/cli/test_config.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_configuration.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_process_definition.py
  dolphinscheduler-python/pydolphinscheduler/tests/testing/path.py
Labels: improvement, Python
