Repository apache/dolphinscheduler, pull requests merged in 2022-02, with the labels that each got.

#8294 [python][chore] Add pypi related info badge to readme
  dolphinscheduler-python/pydolphinscheduler/README.md
Labels: Chore, Python

#8282 [E2E] Add the update test for tenant
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/TenantE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/tenement/_source/list.vue
Labels: e2e

#8242 optimize worker taskProcessor logger.
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/DBTaskAckProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/DBTaskResponseProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/HostUpdateProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
Labels: enhancement, core

#8357 [Feature][UI Next] Add e2e to login page.
  dolphinscheduler-ui-next/docs/e2e/login.md
  dolphinscheduler-ui-next/src/views/login/index.tsx
Labels: new feature, UI

#8359 [Fix-8187][UI] Add the function to the module of resource that you can re-upload the file on the page of the file management.
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/subdirectory/_source/list.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/fileReUpload.vue
  dolphinscheduler-ui/src/js/module/components/nav/nav.vue
Labels: bug, UI

#8363 [Fix][UI Next] Fix a few bug with resource manage
  dolphinscheduler-ui-next/src/views/resource/udf/function/index.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/function/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/udf/resource/index.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/resource/use-table.ts
Labels: bug, UI

#8368 [Feature][UI Next]Adding Rights Management
  dolphinscheduler-ui-next/src/layouts/content/index.tsx
  dolphinscheduler-ui-next/src/layouts/content/use-dataList.ts
  dolphinscheduler-ui-next/src/router/index.ts
  dolphinscheduler-ui-next/src/router/modules/data-quality.ts
  dolphinscheduler-ui-next/src/router/modules/datasource.ts
  dolphinscheduler-ui-next/src/router/modules/monitor.ts
  dolphinscheduler-ui-next/src/router/modules/projects.ts
  dolphinscheduler-ui-next/src/router/modules/resources.ts
  dolphinscheduler-ui-next/src/router/modules/security.ts
  dolphinscheduler-ui-next/src/router/routes.ts
Labels: new feature, UI

#8365 [Bug-8067][LogServer] LoggerRequestProcessor incorrect word and improper use of StringBuilder
  dolphinscheduler-log-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java
Labels: first time contributor

#8315 [Bug] [Parameter Context] The preparameter OUT is null
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/task/AbstractParameters.java
Labels: bug, first time contributor, core

#8340 [Feature-8222][python] move examples into the scope of source package
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/condition.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/datax.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/dependent.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/flink.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/map_reduce.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/shell.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/spark.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tasks/switch.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tutorial.rst
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/__init__.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/bulk_create_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/task_condition_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/task_datax_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/task_dependent_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/task_flink_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/task_map_reduce_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/task_spark_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/task_switch_example.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/examples/tutorial.py
  dolphinscheduler-python/pydolphinscheduler/tests/example/test_example.py
  dolphinscheduler-python/pydolphinscheduler/tests/testing/path.py
Labels: enhancement, development, first time contributor, Python

#8375 [Fix-8370][UI] Rectify this issue with missing the re-uploading file button when the file is under the root directory.
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/fileReUpload.vue
Labels: bug, UI

#8252 [Feature][api] Task can run on kubernetes - k8s client and namespace #8247
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/K8sNamespaceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/K8sNameSpaceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/K8sNameSpaceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/K8sNamespaceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/K8sNameSpaceServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/K8s.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/K8sNamespace.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/K8sMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceMapper.xml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.1.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.1.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-automaton.txt
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/NamespacePage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java
  dolphinscheduler-service/pom.xml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/k8s/K8sClientService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/k8s/K8sManager.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/k8s/K8sManagerTest.java
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/namespace/_source/createNamespace.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/namespace/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/namespace/index.vue
  dolphinscheduler-ui/src/js/conf/home/router/module/security.js
  dolphinscheduler-ui/src/js/conf/home/store/security/actions.js
  dolphinscheduler-ui/src/js/module/components/secondaryMenu/_source/menu.js
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: new feature, first time contributor, k8s, core

#8392 [Feature][UI Next] Add e2e to security token manage page.
  dolphinscheduler-ui-next/docs/e2e/security.md
  dolphinscheduler-ui-next/src/views/security/token-manage/components/token-modal.tsx
  dolphinscheduler-ui-next/src/views/security/token-manage/index.tsx
  dolphinscheduler-ui-next/src/views/security/token-manage/use-table.ts
Labels: new feature, UI

#8393 [Feature][UI Next] Add task creation and task editor.
  dolphinscheduler-ui-next/src/components/form/fields/checkbox.ts
  dolphinscheduler-ui-next/src/components/form/fields/radio.ts
  dolphinscheduler-ui-next/src/components/form/fields/select.ts
  dolphinscheduler-ui-next/src/components/form/fields/tree-select.ts
  dolphinscheduler-ui-next/src/components/form/types.ts
  dolphinscheduler-ui-next/src/components/form/use-form.ts
  dolphinscheduler-ui-next/src/components/monaco-editor/index.tsx
  dolphinscheduler-ui-next/src/service/modules/task-definition/index.ts
  dolphinscheduler-ui-next/src/service/modules/task-definition/types.ts
  dolphinscheduler-ui-next/src/views/projects/node/use-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail.tsx
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-delay-time.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-description.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-environment-name.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-failed.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-name.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-pre-tasks.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-process-name.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-run-flag.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-shell.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-task-group.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-task-priority.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-task-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-timeout-alarm.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-worker-group.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-shell.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
  dolphinscheduler-ui-next/src/views/projects/task/definition/index.module.scss
  dolphinscheduler-ui-next/src/views/projects/task/definition/index.tsx
  dolphinscheduler-ui-next/src/views/projects/task/definition/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/definition/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/task/definition/use-task.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
Labels: new feature, UI

#8403 [Fix][UI Next]: Fix the missing delete button in the custom parameter…
  dolphinscheduler-ui-next/src/components/form/fields/custom-parameters.ts
Labels: bug, UI

#8409 [Feature][UI Next] Add Crontab Component
  dolphinscheduler-ui-next/src/components/crontab/common.ts
  dolphinscheduler-ui-next/src/components/crontab/index.module.scss
  dolphinscheduler-ui-next/src/components/crontab/index.tsx
  dolphinscheduler-ui-next/src/components/crontab/modules/day.tsx
  dolphinscheduler-ui-next/src/components/crontab/modules/time.tsx
  dolphinscheduler-ui-next/src/components/crontab/types.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/timing-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
Labels: new feature, UI

#8388 [Fix-8366] [Worker] sudo.enable=false Is invalid
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/util/OSUtils.java
Labels: first time contributor

#8413 [Fix-8412] [UI] fix workflow definition timing edit bug
  dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/timing.vue
Labels: bug, UI

#8420 [Feature][UI Next] Add e2e to security yarn queue manage page.
  dolphinscheduler-ui-next/docs/e2e/security.md
  dolphinscheduler-ui-next/src/views/security/yarn-queue-manage/components/yarn-queue-modal.tsx
  dolphinscheduler-ui-next/src/views/security/yarn-queue-manage/index.module.scss
  dolphinscheduler-ui-next/src/views/security/yarn-queue-manage/index.tsx
  dolphinscheduler-ui-next/src/views/security/yarn-queue-manage/use-table.ts
Labels: new feature, UI, e2e

#8426 [Feature][UI Next]Improve modal component, add link function
  dolphinscheduler-ui-next/src/components/modal/index.tsx
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail.tsx
Labels: new feature, UI

#8434 [Feature][UI Next] Add e2e to security worker group manage page.
  dolphinscheduler-ui-next/docs/e2e/security.md
  dolphinscheduler-ui-next/src/views/security/worker-group-manage/components/worker-group-modal.tsx
  dolphinscheduler-ui-next/src/views/security/worker-group-manage/index.module.scss
  dolphinscheduler-ui-next/src/views/security/worker-group-manage/index.tsx
  dolphinscheduler-ui-next/src/views/security/worker-group-manage/use-table.ts
Labels: new feature, UI, e2e

#8293 fix jdbc connect parameters can not input '@' and '.' character
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java
Labels: bug, first time contributor, plug-in

#8439 [Feature][UI Next]add subprocess task
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-child-node.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sub-process.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
Labels: new feature, UI

#8440 [Feature][UI Next] Add e2e to security tenant manage page.
  dolphinscheduler-ui-next/docs/e2e/security.md
  dolphinscheduler-ui-next/src/views/security/tenant-manage/components/tenant-modal.tsx
  dolphinscheduler-ui-next/src/views/security/tenant-manage/index.module.scss
  dolphinscheduler-ui-next/src/views/security/tenant-manage/index.tsx
  dolphinscheduler-ui-next/src/views/security/tenant-manage/use-table.ts
Labels: new feature, UI, e2e

#8441 [cherry-pick][Fix-8163] Add a tooltip on the task node to rectify this issue. #8280
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/canvas/canvas.vue
Labels: bug, UI

#8443 [Feature][UI Next] Add e2e to security user manage page.
  dolphinscheduler-ui-next/docs/e2e/security.md
  dolphinscheduler-ui-next/src/views/security/user-manage/components/user-modal.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/index.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/use-table.tsx
Labels: new feature, UI, e2e

#8445 [cherry-pick][Fix-8050] When the task is forbidden the node will obviously display.
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/canvas/canvas.vue
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
Labels: bug, UI

#8446 [Feature][UI Next] Add flink task
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/resources/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-flink.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-flink.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
Labels: new feature, UI

#8447 [Feature][UI Next] Add http into task.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-http.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-http.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
Labels: new feature, UI

#8390 [Fix-8389][Common] Fix oshi compatibility issues cause it fail to boot on m1 mac
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/os/OshiTest.java
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-jna-platform.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-jna.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-oshi-core.txt
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: bug, first time contributor, arch-arm64

#8461 [Feature][UI Next]Fix field errors in SubProcess
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-child-node.ts
Labels: new feature, UI

#8467 [Improve]Use hibernate validation framework
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/CheckUtils.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/CheckUtilsTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-dist/release-docs/LICENSE
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: improvement

#8471 [Feature][UI Next] Add the form of sql task to the module of next ui.
  dolphinscheduler-ui-next/docs/e2e/security.md
  dolphinscheduler-ui-next/src/components/form/fields/index.ts
  dolphinscheduler-ui-next/src/components/form/fields/multi-input.ts
  dolphinscheduler-ui-next/src/components/form/types.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/datasource/list/use-form.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-datasource-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-datasource.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sql-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sql.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sql.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
Labels: new feature, UI

#8473 [Feature][UI Next] Add the form of procedure task to the module of next ui.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-procedure.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-procedure.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
Labels: new feature, UI

#8452 [Improvement][Api] add @Override on the Override method
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
Labels: first time contributor

#8481 [Feature][UI Next] Add dag menu
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/utils/common.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-config.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-hooks.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/menu.module.scss
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-canvas-init.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-menu.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: new feature, UI

#8472 [cherry-pick][deploy] Make python api release to ASF dist independent
  dolphinscheduler-dist/pom.xml
  dolphinscheduler-dist/src/main/assembly/dolphinscheduler-python-api.xml
  dolphinscheduler-dist/src/main/assembly/dolphinscheduler-src.xml
  dolphinscheduler-python/pom.xml
  dolphinscheduler-python/pydolphinscheduler/setup.py
Labels: Python, community

#8482 [Fix][UI Next] Fix styling issues under Project.
  dolphinscheduler-ui-next/src/views/projects/task/definition/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag.module.scss
Labels: new feature, UI

#8491 [Fix][UI Next] fix user-page lacks authorization button
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/data-source/index.ts
  dolphinscheduler-ui-next/src/service/modules/projects/index.ts
  dolphinscheduler-ui-next/src/service/modules/resources/index.ts
  dolphinscheduler-ui-next/src/service/modules/users/index.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/user-modal.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/index.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/use-table.tsx
Labels: bug, UI

#8498 [Fix][UI Next] Fix the corresponding incorrect field.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-child-node.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-pigeon.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sub-process.ts
Labels: bug, UI

#8501 [Feature][UI Next] Add workflow instance startup params
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/utils/common.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-startup-param.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/startup.module.scss
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/detail/index.tsx
Labels: new feature, UI

#8505 [Feature][UI Next] Add workflow instance variables params
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/process-instances/index.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag.module.scss
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/variables-view.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/variables.module.scss
Labels: new feature, UI

#8504 [Build][UI Next] Update package.
  dolphinscheduler-ui-next/package.json
  dolphinscheduler-ui-next/pnpm-lock.yaml
Labels: dependencies, UI

#8507 [Feature][UI Next] Add the form of the sea tunnel task to the module of next ui.
  dolphinscheduler-ui-next/pnpm-lock.yaml
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-datasource-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sea-tunnel.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sea-tunnel.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/menu.module.scss
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/startup.module.scss
  dolphinscheduler-ui-next/src/views/security/user-manage/components/user-modal.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/use-table.tsx
Labels: new feature, UI

#8510 [Feature][UI Next] Add workflow instance dag node echo.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/process-instances/index.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-hooks.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-node-status.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/status.module.scss
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-status.ts
Labels: new feature, UI

#8484 Add a property to enable/disable metrics module
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/resources/application.yaml
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterConfiguration.java
  dolphinscheduler-python/src/main/resources/application.yaml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: enhancement, backend

#8502 feat: Unify mysql insert value queto
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
Labels: enhancement

#8514 [Feature][UI Next] Add dag refresh button on workflow instance
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-node-status.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-status.ts
Labels: new feature, UI

#8525 [Feature][UI Next] Support readonly model for dag
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-task-edit.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/detail/index.tsx
Labels: new feature, UI

#8531 [Feature][UI Next] Add style for dag runflag
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-cell-update.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-custom-cell-builder.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: new feature, UI

#8515 upgrade mybatis-plus to 3.4.3
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.java
  dolphinscheduler-dist/release-docs/LICENSE
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: dependencies, development

#8532 [Fix-8394][Server]fix when the data is supplemented business time still date+1
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/task/paramparser/BusinessTimeUtils.java
Labels: first time contributor

#8470 [deploy] Make Python API as independent directory in release's dist
  dolphinscheduler-dist/pom.xml
  dolphinscheduler-dist/src/main/assembly/dolphinscheduler-python-api.xml
  dolphinscheduler-dist/src/main/assembly/dolphinscheduler-src.xml
  dolphinscheduler-python/pom.xml
  dolphinscheduler-python/pydolphinscheduler/setup.py
  pom.xml
Labels: development, Python, priority:high, community

#8536 [Feature][UI Next] Add the form of the switch task to the module of next ui.
  dolphinscheduler-ui-next/src/components/form/fields/index.ts
  dolphinscheduler-ui-next/src/components/form/fields/multi-condition.ts
  dolphinscheduler-ui-next/src/components/form/types.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-switch.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-switch.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/status.module.scss
Labels: new feature, UI

#8540 [Feature][UI Next] Add Dag workflow validation
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/process-definition/index.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/create/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/detail/index.tsx
Labels: new feature, UI

#8542 [Fix][UI Next] Fix build error.
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-custom-cell-builder.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-dag-drag-drop.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-task-edit.ts
  dolphinscheduler-ui-next/src/views/resource/file/create/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/edit/index.tsx
Labels: bug, UI

#8546 [Feature][UI Next] Add dag toolbar tooltip.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag.module.scss
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/detail/index.tsx
Labels: new feature, UI

#8550 [Improve][UI-Next] Work out a little kink about the select component of the environment in the task form.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-environment-name.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
Labels: bug, UI

#8551 [Feature][UI Next] Add relation custom params component into task.
  dolphinscheduler-ui-next/src/components/form/fields/custom-parameters.ts
  dolphinscheduler-ui-next/src/components/form/fields/switch.ts
  dolphinscheduler-ui-next/src/components/form/types.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-custom-params.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-http.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-relation-custom-params.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-task-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/index.module.scss
Labels: new feature, UI

#8553 [Feature][UI Next] Add CONDITIONS.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-child-node.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-relation-custom-params.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-conditions.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
Labels: new feature, UI

#8545 [Docs][UI Next] Add package license.
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@antv-layout
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@antv-x6
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@types-node
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@types-nprogress
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@types-qs
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@typescript-eslint-eslint-plugin
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@typescript-eslint-parser
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@vitejs-plugin-vue
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@vitejs-plugin-vue-jsx
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@vueuse-core
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-axios
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-dart-sass
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-date-fns
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-echarts
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-eslint
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-eslint-config-prettier
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-eslint-plugin-prettier
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-eslint-plugin-vue
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-lodash
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-monaco-editor
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-naive-ui
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-nprogress
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-pinia
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-pinia-plugin-persistedstate
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-prettier
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-qs
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-sass
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-sass-loader
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-typescript
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-typescript-plugin-css-modules
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-vite
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-vite-plugin-compression
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-vue
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-vue-i18n
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-vue-router
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-vue-tsc
  dolphinscheduler-ui-next/.env.development
  dolphinscheduler-ui-next/.env.production
Labels: dependencies, document

#8560 [Docs][UI Next] Update README.
  dolphinscheduler-ui-next/README.md
Labels: UI, document

#8561 [Feature][UI Next] Add dag view log
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-menu.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/log-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/log.module.scss
Labels: new feature, UI

#8566 [Improve][UI Next] Add a few instructions on how to call a procedure in the form of the procedure task.
  dolphinscheduler-ui-next/README.md
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-procedure.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-procedure.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/log.module.scss
Labels: new feature, UI

#8568 [Docs][UI Next] Update README.
  dolphinscheduler-ui-next/README.md
Labels: document

#8578 [Fix-8577][UI Next][V1.0.0-Alpha] Fix workflow instance view log bug.
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-menu.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-status.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/log-modal.tsx
Labels: bug, UI
