Repository apache/dolphinscheduler, pull requests merged in 2022-08, with the labels that each got.

#11213 [Improvement-10760][dolphinscheduler-api] Some variables are redundant and fix checkstyle
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
Labels: backend

#11220 PR: fix install page typo
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/standalone.md
Labels: bug, document

#11221 Write alert result into db
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertChannel.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertData.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertResult.java
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/AlertType.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java
Labels: backend

#11222 [Fix][UI] Fix datax task data instance replay error.
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasource.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datax.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: bug, UI

#11224 fix work oom when task logs's size is very large
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
Labels: first time contributor, backend

#11231 Add alertPluginInstanceId in AlertInfo
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertChannel.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertInfo.java
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java
Labels: backend

#11239 [Fix-11238] Fix recovery from failed task will dead loop
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend

#11212 [Improvement-11074]Add generated annotation to Lombok generated codes to make the code coverage results of Sonar more meaningful
  lombok.config
Labels: good first issue, first time contributor

#11251 [Fix][UI] Fix bug where confirm disable error
  dolphinscheduler-ui/src/views/resource/task-group/option/components/form-modal.tsx
Labels: bug, UI

#11271 [Fix][UI] Fix bug where log modal display object
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/index.tsx
Labels: bug, UI

#11274 [Improvement][UI] Improve monaco-editor component in ts.
  dolphinscheduler-ui/src/components/form/fields/monaco-editor.ts
  dolphinscheduler-ui/src/components/monaco-editor/index.tsx
  dolphinscheduler-ui/src/components/monaco-editor/types.ts
Labels: UI, improvement

#11234 [fix-11233][ui] Remove custom template switch button in chunjun compo…
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-chunjun.ts
Labels: bug, UI

#11276 [doc] Add notice when environment can not select
  docs/docs/en/guide/security.md
  docs/docs/zh/guide/security.md
Labels: document

#11113 [Fix-10571][Doc]update the configuration doc
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
Labels: first time contributor, document, priority:high

#11188 [Feature][Python] Migrate exists method call in PythonGateway to corresponding service
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/python/PythonGatewayTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/resource.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/task.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_resource_definition.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_task.py
Labels: new feature, backend, Python

#11254 Fix TaskGroup cannot work and will cause master dead loop
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskGroupQueue.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskGroupMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/CommonTaskProcessor.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend

#10621 [bug][Api]Appending the copy or import suffix indefinitely causes the name to exceed the lenght limit
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
Labels: bug, backend

#11301 [Fix-11249] No-admin user query alert group fix.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceImpl.java
Labels: backend

#10952 fix dependent task when the dependent on process have forbidden tasks
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/DependentExecute.java
Labels: bug, backend

#11305 [Improvement-11293][dolphinscheduler-api] remove some variables that redundant in subclasses of AbstractAuthenticator
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/AbstractAuthenticator.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/ldap/LdapAuthenticator.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/pwd/PasswordAuthenticator.java
Labels: improvement, backend

#11294 [Fix][UI] Fix the taskPriority options not showing when hover.
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-task-priority.ts
Labels: bug, UI

#11333 [Bug][Doc] Fix typos in docs which causes links to upgrade section to fail
  docs/docs/en/contribute/join/pull-request.md
  docs/docs/en/guide/upgrade/incompatible.md
  docs/docs/en/guide/upgrade/upgrade.md
  docs/docs/zh/contribute/join/pull-request.md
  docs/docs/zh/guide/upgrade/incompatible.md
  docs/docs/zh/guide/upgrade/upgrade.md
  docs/img/contribute/join/pull-request/checkstyle-idea.png
  docs/img/contribute/join/pull-request/code-style-idea.png
Labels: bug, document

#11335 [Improvement][UI] Scrolling will be applied to parent model on editor scrolled to top/bottom
  dolphinscheduler-ui/src/components/monaco-editor/index.tsx
Labels: UI, improvement

#11320 [Fix][UI] Fix bug where icons are displayed in one line.
  dolphinscheduler-ui/src/views/projects/workflow/instance/index.module.scss
  dolphinscheduler-ui/src/views/projects/workflow/instance/use-table.ts
Labels: bug, UI

#11342 [community] Remove stackoverflow ref link in website
  docs/configs/site.js
  docs/docs/en/contribute/have-questions.md
  docs/docs/zh/contribute/have-questions.md
Labels: document

#11341 [Refactor][UI] Refactor task group queue using NSpace component.
  dolphinscheduler-ui/src/views/projects/workflow/instance/use-table.ts
  dolphinscheduler-ui/src/views/resource/task-group/queue/index.module.scss
  dolphinscheduler-ui/src/views/resource/task-group/queue/index.tsx
Labels: UI, refactor

#11330 [Feature][Python] Combine gateway.entry_point call in python api side
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/database.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/engine.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/resource.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/task.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/java_gateway.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/project.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/queue.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/tenant.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/user.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/dependent.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/sub_process.py
Labels: Python

#11345 [Doc] Add tools/libs to the init database steps
  README.md
  README_zh_CN.md
  docs/docs/en/contribute/api-test.md
  docs/docs/en/contribute/e2e-test.md
  docs/docs/en/contribute/join/e2e-guide.md
  docs/docs/en/guide/howto/datasource-setting.md
  docs/docs/zh/contribute/api-test.md
  docs/docs/zh/contribute/e2e-test.md
  docs/docs/zh/contribute/join/e2e-guide.md
  docs/docs/zh/guide/howto/datasource-setting.md
  dolphinscheduler-python/pydolphinscheduler/README.md
  dolphinscheduler-python/pydolphinscheduler/RELEASE.md
Labels: bug, Python, document

#11356 [release] New release version 3.0.0
  .github/ISSUE_TEMPLATE/bug-report.yml
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: CI&CD, document

#11363 [doc] Fixed hadoop link to avoid dead link
  docs/docs/en/guide/task/map-reduce.md
  docs/docs/zh/guide/task/map-reduce.md
Labels: document

#11235 [Feature-9978][UI] add node dependency type feature
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/start-modal.tsx
Labels: new feature, UI

#11369 [Refactor][UI] Refactor project list using NSpace component.
  dolphinscheduler-ui/src/views/projects/list/index.module.scss
  dolphinscheduler-ui/src/views/projects/list/index.tsx
Labels: UI, refactor

#11275 [doc] Improve the document introduction of complement
  docs/docs/en/guide/project/workflow-definition.md
  docs/docs/zh/guide/project/workflow-definition.md
  docs/img/new_ui/dev/project/workflow-concurrency-from.png
  docs/img/new_ui/dev/project/workflow-concurrency.png
  docs/img/new_ui/dev/project/workflow-configuredTiming.png
  docs/img/new_ui/dev/project/workflow-configuredTimingResult.png
  docs/img/new_ui/dev/project/workflow-date.png
  docs/img/new_ui/dev/project/workflow-dependency.png
  docs/img/new_ui/dev/project/workflow-input.png
  docs/img/new_ui/dev/project/workflow-pageSelection.png
  docs/img/new_ui/dev/project/workflow-parallel.png
  docs/img/new_ui/dev/project/workflow-serial.png
  docs/img/new_ui/dev/project/workflow-unconfiguredTimingResult.png
  docs/img/new_ui/dev/project/workflow_date_manual.png
Labels: first time contributor, document

#11361 [doc] Refine the deployment documentation
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/start/docker.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/start/docker.md
Labels: first time contributor, document

#11355 [fix-11295] remove duplicate classes
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/PlaceholderUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/PropertyPlaceholderHelper.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/placeholder/TimePlaceholderUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/ParameterUtilsTest.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/placeholder/TimePlaceholderUtilsTest.java
Labels: bug, backend

#11154 [Feature][Api] Refactor org.apache.dolphinscheduler.api.controller.QueueController
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/QueueController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/QueueService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/QueueServiceTest.java
Labels: backend, refactor

#11367 [Fix-11366][UI] Workflow instance should not support right-click running
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/index.tsx
Labels: UI

#11377 [Fix-11376][task plugin]Seatunnel Task cannot save successfully when …
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/spark/SeatunnelSparkParameters.java
Labels: backend

#11362 [Feature][python] Add local dev mod runing python integate tests
  dolphinscheduler-python/pydolphinscheduler/DEVELOP.md
  dolphinscheduler-python/pydolphinscheduler/tests/integration/conftest.py
  dolphinscheduler-python/pydolphinscheduler/tox.ini
Labels: Python

#11372 [Feature-10117][UI] Hide node execution when start from the workflow definition list page
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/start-modal.tsx
Labels: bug, UI

#11400 [fix-11378] fix API-Server release response message typo
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ReleaseState.java
Labels: improvement, backend

#11285 [Fix-10392][SqlTask]: Fix list param error when use sql task
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parser/ParameterUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/parser/ParameterUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
Labels: backend

#11390 [hotfix-11340] Add pause to task instance status
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/TaskMetrics.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/BlockingTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/ConditionTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/DependentTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SwitchTaskProcessor.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/BlockingTaskTest.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/WorkflowStateEventChangeCommand.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/enums/TaskExecutionStatus.java
Labels: backend

#11099 [Fix-11051][Task]Fix the process exitValue exception when the process times out and th…
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
Labels: backend

#11288 [doc] Recover traffic configuration
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
Labels: document

#11311 [doc] Add how obtain IP address from network card in FAQ
  docs/docs/en/faq.md
  docs/docs/zh/faq.md
Labels: first time contributor, document

#11398 [Refactor][UI] Refactor project workflow definition using NSpace component.
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.tsx
Labels: UI, refactor

#11382 [Improvement-11380][scp-host.sh] Set StrictHostKeyChecking=no option to ssh
  script/scp-hosts.sh
  script/status-all.sh
Labels: improvement, backend

#11391 [python] Add multiple version of document
  .github/workflows/py-ci.yml
  docs/configs/docsdev.js
  dolphinscheduler-python/pydolphinscheduler/DEVELOP.md
  dolphinscheduler-python/pydolphinscheduler/docs/Makefile
  dolphinscheduler-python/pydolphinscheduler/docs/source/_templates/versioning.html
  dolphinscheduler-python/pydolphinscheduler/docs/source/_templates/versions.html
  dolphinscheduler-python/pydolphinscheduler/docs/source/api.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/conf.py
  dolphinscheduler-python/pydolphinscheduler/setup.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/models/__init__.py
  dolphinscheduler-python/pydolphinscheduler/tox.ini
Labels: CI&CD, Python, document

#11416 feat: Modifying Slack Links
  docs/configs/site.js
  docs/docs/en/contribute/have-questions.md
  docs/docs/zh/contribute/have-questions.md
Labels: document

#11371 [Fix-1360]: Fix Description length check
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/BaseService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ClusterServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/EnvironmentServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UdfFuncServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema/postgresql/dolphinscheduler_dml.sql
Labels: first time contributor, backend

#11414 [Fix-11413] Cannot set task status to kill if the task is not in running.
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/CommonTaskProcessor.java
Labels: bug, backend

#11415 [Refactor][UI] Refactor workflow definition timing using NSpace component.
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.module.scss
  dolphinscheduler-ui/src/views/projects/workflow/definition/timing/index.tsx
Labels: UI, refactor

#11420 [Refactor][UI] Refactor workflow definition version using NSpace component.
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/version-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.module.scss
Labels: UI, refactor

#11429 [Fix][UI] Fix bug where warn group name not display
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-startup-param.tsx
Labels: bug, UI

#11170 [python] Add support interpreter version 310 and 311-dev
  .github/workflows/py-ci.yml
  dolphinscheduler-python/pydolphinscheduler/README.md
  dolphinscheduler-python/pydolphinscheduler/setup.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/cli/commands.py
  dolphinscheduler-python/pydolphinscheduler/tests/cli/test_version.py
  dolphinscheduler-python/pydolphinscheduler/tox.ini
Labels: CI&CD, Python

#11435 [Doc][Resources] Instruct users to use local storage if they have remote storage mounted to local
  docs/docs/en/guide/resource/configuration.md
  docs/docs/zh/guide/resource/configuration.md
Labels: improvement, document

#11383 [Improvement] Avoid using search in for and start using testSaveTaskDefine
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: backend

#11422 [hotfix] Clear thread name in BaseTaskProcessor
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/BaseTaskProcessor.java
Labels: backend

#11033 [fix-10961][alert server]Change the content of alert to an array
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/template/DefaultHTMLTemplate.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/template/DefaultHTMLTemplateTest.java
Labels: bug, first time contributor, backend, priority:high

#11443 [Doc][DSIP] Move DSIP docs to the right place
  docs/docs/en/DSIP.md
  docs/docs/zh/DSIP.md
Labels: document

#11447 [Refactor][UI] Refactor task instance batch using NSpace component.
  dolphinscheduler-ui/src/views/projects/task/instance/batch-task.tsx
Labels: UI, refactor

#11424 [hotfix] Fix find last process instance in dependent task is not correct
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
Labels: backend

#11446 [Refactor][UI] Refactor workflow instance using NSpace component.
  dolphinscheduler-ui/src/views/projects/workflow/instance/components/process-instance-condition.tsx
  dolphinscheduler-ui/src/views/projects/workflow/instance/index.module.scss
  dolphinscheduler-ui/src/views/projects/workflow/instance/index.tsx
Labels: UI, refactor

#11419 [Improvement-11386][UI] Concise the logic available for task action buttons
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/index.tsx
Labels: UI, improvement

#11454 [Refactor][UI] Refactor task instance stream using NSpace component.
  dolphinscheduler-ui/src/views/projects/task/instance/batch-task.tsx
  dolphinscheduler-ui/src/views/projects/task/instance/index.module.scss
  dolphinscheduler-ui/src/views/projects/task/instance/stream-task.tsx
Labels: UI, refactor

#11445 [hotfix] Fix workflow instance may failover many times due to doesn't check the restart time
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/service/FailoverServiceTest.java
Labels: backend

#11458 [Feature][Style] Enable spotless to manage imports
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTask.java
  pom.xml
  style/eclipse.importorder
Labels: backend

#11462 [FEATURE-RD][Workflows] optimize sorting priority for workflow define
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
Labels: backend

#11451 Set master's task running status in `runTask` to avoid the task group acquire failed, but the task status is in running
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/BlockingTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/ConditionTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SwitchTaskProcessor.java
Labels: backend

#11461 If the task processor is not found need to throw error rather than exception
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskStateEventHandler.java
Labels: backend

#11466 [Fix-11465] Serial first, the last executing instance will be stopped
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: backend

#10940 2.0.6 fix copy bug
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/canvas/contextMenu.vue
Labels: first time contributor, UI

#11474 [python] Correct PyDolphinScheduler documentation link.
  dolphinscheduler-python/pydolphinscheduler/setup.py
Labels: improvement, Python

#10951 [doc] Use Rainbond deployment DolphinScheduler Cluster
  docs/configs/docsdev.js
  docs/docs/en/guide/integration/rainbond.md
  docs/docs/zh/guide/integration/rainbond.md
  docs/img/rainbond/appstore-dolphinscheduler.png
  docs/img/rainbond/dolpscheduler-worker.png
  docs/img/rainbond/homepage-dolphinscheduler.png
  docs/img/rainbond/install-dolphinscheduler.png
  docs/img/rainbond/monitor-dolphinscheduler.png
  docs/img/rainbond/plugin.png
  docs/img/rainbond/topology-dolphinscheduler.png
Labels: first time contributor, document

#11483 [Doc][Security] Update instructions on worker groups
  docs/docs/en/guide/security.md
  docs/docs/zh/guide/security.md
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: backend, document

#11485 [Refactor][UI] Refactor task definition batch stream using NSpace component.
  dolphinscheduler-ui/src/views/projects/task/definition/batch-task.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/components/start-modal.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/index.module.scss
  dolphinscheduler-ui/src/views/projects/task/definition/stream-task.tsx
Labels: UI, refactor

#11487 [Fix][UI] Fix the table header in the workflow instance.
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/instance/use-table.ts
Labels: bug, UI

#11495 [Refactor][UI] Refactor task definition version using NSpace component.
  dolphinscheduler-ui/src/views/projects/task/definition/components/version-modal.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/components/version.module.scss
Labels: UI, refactor

#11496 [Doc] Update UI readme.
  dolphinscheduler-ui/README.md
Labels: document

#11402 Support reading application properties from kubernetes config map
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-standalone-server/pom.xml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/K8sUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskExecutorTest.java
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: new feature, backend

#11387 [Feature-10182][task-datax] datax access kerberos authenticated bigdata cluster
  docs/docs/en/guide/task/datax.md
  docs/docs/zh/guide/task/datax.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/test/java/org/apache/dolphinscheduler/plugin/task/datax/DataxParametersTest.java
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datax.ts
Labels: UI, backend, document

#11520 [Feature][Style] Make sure there is one and only one empty line at the end of each java file
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertConfig.java
  style/spotless_dolphinscheduler_formatter.xml
Labels: new feature, improvement, backend

#11484 [Improvement-11481][docs] Add log specification document to contribution guidelines.
  docs/configs/docsdev.js
  docs/docs/en/contribute/log-specification.md
  docs/docs/zh/contribute/log-specification.md
Labels: first time contributor, document

#11453 [test-11432][HttpTask] Add unit tests to http task
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/test/java/org/apache/dolphinscheduler/plugin/task/http/HttpTaskTest.java
Labels: first time contributor, backend

#11519 [Improvement] File deletion logic optimization
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
Labels: improvement, backend

#11489 [Improvement-11468] Support re running historical version workflow
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
Labels: improvement, backend

#11498 [Feature][Task Plugin] Add Pytorch task plugin to make running machine learning projects easier #11497
  docs/configs/docsdev.js
  docs/docs/en/guide/task/pytorch.md
  docs/docs/zh/guide/task/pytorch.md
  docs/img/tasks/demo/pytorch_en.png
  docs/img/tasks/demo/pytorch_note_en.png
  docs/img/tasks/icons/pytorch.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/GitProjectManager.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PythonEnvManager.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/test/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTaskTest.java
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/pytorch.png
  dolphinscheduler-ui/public/images/task-icons/pytorch_hover.png
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-pytorch.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-pytorch.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
Labels: UI, backend, document

#11527 [Improvement][UI] Remove unsupported datasource types in the datax task.
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datax.ts
Labels: UI, improvement

#11539 [Bug] [API] The task priority and process instance priority might be null and cause NPE
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: bug, backend

#11384 Enable spotless to fix markdown formatting and refactor faq.md as an example
  docs/docs/en/faq.md
  pom.xml
Labels: document

#11543 [Improvement]Add a stop function when you are ready to do pause operation
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/WorkflowExecutionStatus.java
Labels: improvement, backend

#11325 [Improvement] [LDAP] Config value should return real null instead of 'null' string
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/ldap/LdapService.java
Labels: first time contributor, improvement, backend

#11555 Remove logger header in task log file
  dolphinscheduler-master/src/main/resources/logback-spring.xml
  dolphinscheduler-standalone-server/src/main/resources/logback-spring.xml
  dolphinscheduler-worker/src/main/resources/logback-spring.xml
Labels: backend

#11441 [fix-11404]: make the common.properties to configurable on values.yaml
  deploy/kubernetes/dolphinscheduler/resources/config/common.properties
  deploy/kubernetes/dolphinscheduler/templates/configmap.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: first time contributor, backend

#11493 [feature-11408] add hive option
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxUtils.java
Labels: new feature, backend

#11576 Fix some resource leak
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/FileUtils.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/upgrade/SchemaUtils.java
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/datasource/dao/UpgradeDao.java
Labels: backend

#11580 [Fix][Issue-11579] Cannot check the application status.
  script/dolphinscheduler-daemon.sh
  script/status-all.sh
Labels: first time contributor, backend

#11577 [Improvement-11550] [Doc]Document content update
  docs/docs/en/guide/start/quick-start.md
  docs/docs/zh/guide/start/quick-start.md
  docs/img/new_ui/dev/quick-start/log.png
  docs/img/new_ui/dev/quick-start/workflow-definition.png
Labels: first time contributor, document

#11578 feat: update slack
  docs/configs/site.js
Labels: document

#11586 Fix vulnerability in LDAP login
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/ldap/LdapService.java
  dolphinscheduler-bom/pom.xml
  tools/dependencies/known-dependencies.txt
Labels: bug, backend

#11595 Refresh server startup time when recovery from waiting
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/lifecycle/ServerLifeCycleManager.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/registry/HeartBeatTask.java
Labels: bug, backend

#11596 Fix quartz threadPriority config name error
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-master/src/main/resources/application.yaml
Labels: bug, backend

#11600 [Doc][Bug] Fix resource center docs for standalone mode
  docs/docs/en/guide/resource/configuration.md
  docs/docs/zh/guide/resource/configuration.md
  docs/img/dag1.png
  docs/img/log_en.png
  docs/img/process_definition_en.png
  docs/img/task-log.png
Labels: bug, document

#11541 Add dependent task instance log
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/DependentTaskProcessor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/model/DependentTaskModel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/DependentParameters.java
Labels: improvement, backend

#11469 Fix task kill failed will cause task group cannot release
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/CommonTaskProcessor.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend

#11232 [Fix-9980] [Server] fix heartBeatTaskCount bug
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterHeartBeatTask.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerHeartBeatTask.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistryClient.java
Labels: bug, improvement, backend

#11522 [Improvement][TaskInstance] reduce database queries
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapperTest.java
Labels: improvement, backend

#10957 [Improvement-10942][UI]The workflow or task name is too long and resu…
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
Labels: UI, improvement

#11622 Fix homepage email subscription link
  docs/configs/site.js
Labels: bug, document

#11504 [Improvement][User] Query all users filter un enabled.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/UserMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
Labels: improvement, backend

#11624 [Fix][UI] Fix the port in the datasource edit.
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
Labels: bug, UI

#11535 feat: Locations Formats the layout if it does not exist
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-graph-auto-layout.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/detail/index.tsx
Labels: new feature, UI

#11617 [Fix-11616] Workflow Definition Name Change Validation Optimization.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-ui/src/service/modules/process-definition/index.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-save-modal.tsx
Labels: bug, UI, backend

#11653 [improvement-#11630][doc]fix document about common.properties
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
Labels: improvement, document

#11621 [DOC] should notice that need setting the full path when call the resource file #11620
  docs/docs/en/guide/project/workflow-definition.md
  docs/docs/en/guide/resource/file-manage.md
  docs/docs/zh/guide/project/workflow-definition.md
  docs/docs/zh/guide/resource/file-manage.md
Labels: improvement, document

#11655 [CI] Increase unit test ci timeout
  .github/workflows/unit-test.yml
Labels: CI&CD, Chore

#11540 Refactor worker execute task process
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractYarnTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-chunjun/src/main/java/org/apache/dolphinscheduler/plugin/task/chunjun/ChunJunTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dvc/src/main/java/org/apache/dolphinscheduler/plugin/task/dvc/DvcTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrAddStepsTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrJobFlowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/test/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskTest.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskDispatchProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskSavePointProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/DefaultWorkerDelayTaskExecuteRunnable.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/DefaultWorkerDelayTaskExecuteRunnableFactory.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThread.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerDelayTaskExecuteRunnable.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerDelayTaskExecuteRunnableFactory.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerExecService.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerManagerThread.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnable.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnableFactory.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnableFactoryBuilder.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionCheckerUtils.java
  dolphinscheduler-worker/src/test/java/org/apache/dolphinscheduler/server/worker/processor/TaskDispatchProcessorTest.java
  dolphinscheduler-worker/src/test/java/org/apache/dolphinscheduler/server/worker/runner/DefaultWorkerDelayTaskExecuteRunnableTest.java
  dolphinscheduler-worker/src/test/java/org/apache/dolphinscheduler/server/worker/runner/TaskExecuteThreadTest.java
Labels: backend, refactor

#11641 [Docs] Update README.
  dolphinscheduler-ui/README.md
Labels: UI

#11646 [Fix][UI] Fix the problem that the pagination component is not centered in the environment management.
  dolphinscheduler-ui/src/views/security/environment-manage/index.tsx
Labels: bug, UI

#11659 [Feature][UI] Enable highlight and auto-complete for SQL scripts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sql.ts
Labels: new feature, UI, improvement

#11661 [Fix][UI] Fix bug where crontab special of month and year
  dolphinscheduler-ui/src/components/crontab/common.ts
  dolphinscheduler-ui/src/components/crontab/index.tsx
  dolphinscheduler-ui/src/components/crontab/modules/day.tsx
  dolphinscheduler-ui/src/components/crontab/modules/time.tsx
  dolphinscheduler-ui/src/components/crontab/types.ts
Labels: bug, UI

#11666 [fix][python] Sql pattern add truncate.
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/sql.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_sql.py
Labels: Python

#11606 [bug][python] The default branch will report an error if it is not defined last
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/switch.py
Labels: bug, Python

#11681 [python] Auto location when create process definition
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-python/pydolphinscheduler/UPDATING.md
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/java_gateway.py
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-graph-auto-layout.ts
Labels: UI, backend, Python

#11629 [doc] Correct E2E Doc, fix WorkerGroupPage typo
  docs/docs/en/contribute/e2e-test.md
  docs/docs/zh/contribute/e2e-test.md
Labels: improvement, document

#11676 [Improvement-11662][dao] fix foreach null items in mapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertPluginInstanceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ResourceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ResourceUserMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ScheduleMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
Labels: backend

#11634 [Fix-11633] The data type of the PostgreSQL database column is wrong
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
Labels: first time contributor, backend, sql not sync

#11688 [CI] Fix cluster test abnormal
  .github/workflows/cluster-test/mysql/Dockerfile
  .github/workflows/cluster-test/mysql/deploy.sh
  .github/workflows/cluster-test/mysql/start-job.sh
  .github/workflows/cluster-test/postgresql/Dockerfile
  .github/workflows/cluster-test/postgresql/deploy.sh
  .github/workflows/cluster-test/postgresql/start-job.sh
Labels: CI&CD, Chore

#11703 [DOC] improve zk digest doc
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
Labels: first time contributor, improvement, document

#11701 [Bug] [Worker] Optimize the getAppId method to avoid worker OOM when kill task
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/LoggerUtils.java
  dolphinscheduler-log-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/CommandType.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/log/GetAppIdRequestCommand.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/log/GetAppIdResponseCommand.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/rpc/remote/NettyClient.java
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogClientService.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/LogUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/LogUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/resources/appId.txt
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/rpc/WorkerRpcServer.java
Labels: bug, backend

#11719 [Improvement-11718] optimize the process instance query, change the date time range
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
Labels: improvement, backend
