Repository apache/dolphinscheduler, pull requests merged in 2022-12, with the labels that each got.

#13059 Print GC datestamps in gc log
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/start.sh
  dolphinscheduler-api/src/main/bin/start.sh
  dolphinscheduler-master/src/main/bin/start.sh
  dolphinscheduler-worker/src/main/bin/start.sh
Labels: improvement, 3.1.x

#13065 [Bug] [data-quality & master-server] wrong logic when master-server check data-quality result
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DataQualityResultOperator.java
Labels: bug, backend, 3.0.x, 3.1.x

#13067 [Improvement][Style] Expand all static imports and add CI check to block wildcard static imports
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkflowInstanceV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TaskInstanceV2ControllerTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisTask.java
  pom.xml
Labels: improvement, backend, 3.2.0

#13031 [Feature][API] New restful API for workflow state
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/StatisticsV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/project/StatisticsStateRequest.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataAnalysisService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProjectService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/StatisticsV2ControllerTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DefinitionGroupByUser.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
Labels: feature, backend, 4.0.0

#12951 [improvement-#11879]Keyword Search Improvement
  dolphinscheduler-ui/src/components/input-search/index.tsx
  dolphinscheduler-ui/src/locales/en_US/index.ts
  dolphinscheduler-ui/src/locales/en_US/input-search.ts
  dolphinscheduler-ui/src/locales/zh_CN/index.ts
  dolphinscheduler-ui/src/locales/zh_CN/input-search.ts
  dolphinscheduler-ui/src/views/data-quality/rule/index.tsx
  dolphinscheduler-ui/src/views/data-quality/rule/use-table.ts
  dolphinscheduler-ui/src/views/data-quality/task-result/index.tsx
  dolphinscheduler-ui/src/views/datasource/list/index.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-table.ts
  dolphinscheduler-ui/src/views/projects/list/index.tsx
  dolphinscheduler-ui/src/views/projects/list/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.tsx
  dolphinscheduler-ui/src/views/resource/file/index.tsx
  dolphinscheduler-ui/src/views/resource/task-group/option/index.tsx
  dolphinscheduler-ui/src/views/resource/task-group/queue/index.tsx
  dolphinscheduler-ui/src/views/resource/udf/function/index.tsx
  dolphinscheduler-ui/src/views/resource/udf/resource/index.tsx
  dolphinscheduler-ui/src/views/security/alarm-group-manage/index.tsx
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/index.tsx
  dolphinscheduler-ui/src/views/security/cluster-manage/index.tsx
  dolphinscheduler-ui/src/views/security/environment-manage/index.tsx
  dolphinscheduler-ui/src/views/security/k8s-namespace-manage/index.tsx
  dolphinscheduler-ui/src/views/security/tenant-manage/index.tsx
  dolphinscheduler-ui/src/views/security/token-manage/index.tsx
  dolphinscheduler-ui/src/views/security/user-manage/index.tsx
  dolphinscheduler-ui/src/views/security/worker-group-manage/index.tsx
  dolphinscheduler-ui/src/views/security/yarn-queue-manage/index.tsx
Labels: UI, improvement, priority:middle, 3.2.0

#13042 [fix] Python gateway can not upload to resource center
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/python/PythonGatewayTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
Labels: bug, backend, 3.2.0

#13076 [ci] Update skywalking-eye to fix block CI
  .github/actions/sanity-check/action.yml
  .licenserc.yaml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
Labels: bug, backend, CI&CD, chore, 3.2.0

#13082 Use bigint represent term in mysql registry to avoid time inaccurate
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/MysqlOperator.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/model/MysqlRegistryData.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/model/MysqlRegistryLock.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/resources/mysql_registry_init.sql
Labels: bug, backend, 3.1.x

#13081 Update dolphinscheduler_ddl.sql - for PostgreSQL
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: improvement, backend, 3.1.x

#13091 Fix the invalidate task instance never be deleted.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/TaskInstanceDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskInstanceDaoImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend, 3.0.x, 3.1.x

#13100 [Fix]Correct java cmd in alert start.sh
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/start.sh
Labels: improvement, backend, 3.1.x

#13102 [Bug] Fix task log file might not be clear
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/TaskInstanceDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskInstanceDaoImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogClient.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/LogClientTest.java
Labels: bug, 3.1.x

#13114 [Improvement][Alert] Prevent default alert group from binding alert plugin instances with id 1 and 2 automatically
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
Labels: improvement, backend, 3.2.0

#13106 [Improvement] optimization task definition & fix in the task definition list, if one task have more pre task, the task list can't show all task
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TaskDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskDefinitionServiceImplTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.xml
  dolphinscheduler-ui/src/views/projects/task/definition/batch-task.tsx
Labels: UI, improvement, backend, 3.2.0

#13069 [Fix] Fix Token E2E Bug
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TokenPage.java
Labels: improvement, e2e, 3.2.0

#13121 [3.1.2-prepare][version] Modify the version to 3.1.2
  deploy/docker/.env
  deploy/kubernetes/dolphinscheduler/Chart.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/configs/docsdev.js
  docs/configs/site.js
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/guide/task/mlflow.md
  docs/docs/en/history-versions.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/guide/task/mlflow.md
  docs/docs/zh/history-versions.md
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.2_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.2_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.2_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.2_schema/postgresql/dolphinscheduler_dml.sql
  dolphinscheduler-python/pydolphinscheduler/README.md
  tools/dependencies/known-dependencies.txt
Labels: backend, Python, document

#13126 [Feature][Doc] Added change log.
  docs/configs/docsdev.js
  docs/docs/en/changelog.md
Labels: feature, document, 3.1.x

#13127 [Feature][Doc] Added change log.
  docs/configs/docsdev.js
  docs/docs/en/changelog.md
Labels: feature, document

#13128 [Feature][Doc] Added change log.
  docs/configs/docsdev.js
  docs/docs/en/changelog.md
Labels: feature, document

#13129 [Feature][Doc] Added change log.
  docs/configs/docsdev.js
  docs/docs/en/changelog.md
Labels: feature, document

#13130 [Feature][Doc] Added change log.
  docs/configs/docsdev.js
  docs/docs/en/changelog.md
Labels: feature, document

#13118 [Improvement] Fixed Possible JSON ordering permutations problem in Tests
  dolphinscheduler-spi/src/test/java/org/apache/dolphinscheduler/spi/params/PluginParamsTransferTest.java
Labels: first time contributor, improvement, backend, 3.2.0

#13131 [release] version 3.0.3
  .flake8
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/contribute/release/release-prepare.md
  docs/docs/en/contribute/release/release.md
  docs/docs/en/guide/task/mlflow.md
  docs/docs/en/history-versions.md
  docs/docs/zh/contribute/release/release-prepare.md
  docs/docs/zh/contribute/release/release.md
  docs/docs/zh/guide/task/mlflow.md
  docs/docs/zh/history-versions.md
  docs/img_utils.py
  tools/release/github/pull_request.py
Labels: document, 3.0.x

#13120 [Bug] Throws the correct exception for the updateResource interface
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
Labels: bug, backend, 3.0.x

#13135 [doc] refactor release
  docs/configs/docsdev.js
  docs/docs/en/contribute/release.md
  docs/docs/en/contribute/release/release-post.md
  docs/docs/en/contribute/release/release-prepare.md
  docs/docs/zh/contribute/release.md
  docs/docs/zh/contribute/release/release-post.md
  docs/docs/zh/contribute/release/release-prepare.md
Labels: document, 3.2.0

#13110 [fix-13041] fix example checkFormula
  docs/docs/en/guide/data-quality.md
  docs/docs/zh/guide/data-quality.md
Labels: bug, document, 3.0.x, 3.1.x

#13090 [Improvement-13084][UI] Make download log button disabled when host i…
  dolphinscheduler-ui/src/views/projects/task/instance/use-table.ts
Labels: first time contributor, UI, improvement, 3.0.x, 3.1.x

#13150 [release][3.1.2] Add release 3.1.2 documentation
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: document, 3.1.x

#13115 Fix task group might be rob by multiple task
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskGroupServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskGroup.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskGroupQueue.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskGroupMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupMapper.xml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend, 3.1.x

#12930 [Bug][Worker] Fix duplicated key bug when have out parameters of same name
  docs/docs/en/guide/parameter/context.md
  docs/docs/zh/guide/parameter/context.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/AbstractParameters.java
Labels: bug, backend, document, 3.1.x

#13098 Fix datasource jdbc url param doesn't work
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/provider/JDBCDataSourceProvider.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/main/java/org/apache/dolphinscheduler/plugin/datasource/athena/param/AthenaDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-athena/src/test/java/org/apache/dolphinscheduler/plugin/datasource/athena/param/AthenaDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-clickhouse/src/main/java/org/apache/dolphinscheduler/plugin/datasource/clickhouse/param/ClickHouseDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-db2/src/main/java/org/apache/dolphinscheduler/plugin/datasource/db2/param/Db2DataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-db2/src/test/java/org/apache/dolphinscheduler/plugin/datasource/db2/param/Db2DataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/param/HiveDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/mysql/param/MySQLDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oracle/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oracle/param/OracleDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oracle/src/test/java/org/apache/dolphinscheduler/plugin/datasource/oracle/param/OracleDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-postgresql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/postgresql/param/PostgreSQLDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-postgresql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/postgresql/param/PostgreSQLDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-presto/src/main/java/org/apache/dolphinscheduler/plugin/datasource/presto/param/PrestoDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-presto/src/test/java/org/apache/dolphinscheduler/plugin/datasource/presto/param/PrestoDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-redshift/src/main/java/org/apache/dolphinscheduler/plugin/datasource/redshift/param/RedshiftDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-redshift/src/test/java/org/apache/dolphinscheduler/plugin/datasource/redshift/param/RedshiftDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-spark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/spark/param/SparkDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-spark/src/test/java/org/apache/dolphinscheduler/plugin/datasource/spark/param/SparkDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/src/main/java/org/apache/dolphinscheduler/plugin/datasource/sqlserver/param/SQLServerDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/src/test/java/org/apache/dolphinscheduler/plugin/datasource/sqlserver/param/SQLServerDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-trino/src/main/java/org/apache/dolphinscheduler/plugin/datasource/trino/param/TrinoDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-trino/src/test/java/org/apache/dolphinscheduler/plugin/datasource/trino/param/TrinoDataSourceProcessorTest.java
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/datasource/BaseConnectionParam.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/test/java/org/apache/dolphinscheduler/plugin/task/dq/DataQualityTaskTest.java
Labels: bug, backend, priority:middle, 3.0.x, 3.1.x

#13159 [Feature][Doc] Added change log.
  docs/configs/docsdev.js
  docs/docs/en/changelog.md
Labels: document

#13158 [Feature][Doc] Added change log.
  docs/configs/docsdev.js
  docs/docs/en/changelog.md
Labels: document

#13170 [Fix] Replaced dead links in the docs.
  README.md
  README_zh_CN.md
  deploy/README.md
  docs/docs/en/contribute/architecture-design.md
  docs/docs/en/contribute/development-environment-setup.md
  docs/docs/en/contribute/join/review.md
  docs/docs/en/contribute/release.md
  docs/docs/en/faq.md
  docs/docs/en/guide/demo.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/guide/upgrade/upgrade.md
  docs/docs/zh/contribute/architecture-design.md
  docs/docs/zh/contribute/join/review.md
  docs/docs/zh/contribute/release.md
  docs/docs/zh/faq.md
  docs/docs/zh/guide/demo.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/standalone.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/guide/upgrade/upgrade.md
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/README.md
Labels: backend, document, 3.0.x, 3.1.x

#13173 Format task parameter as pretty json
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/BaseTaskProcessor.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskExecutionContext.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-chunjun/src/main/java/org/apache/dolphinscheduler/plugin/task/chunjun/ChunJunTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/DataQualityTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datasync/src/main/java/org/apache/dolphinscheduler/plugin/task/datasync/DatasyncTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/src/main/java/org/apache/dolphinscheduler/plugin/task/dms/DmsTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dvc/src/main/java/org/apache/dolphinscheduler/plugin/task/dvc/DvcTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/AbstractEmrTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink-stream/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkStreamTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/main/java/org/apache/dolphinscheduler/plugin/task/java/JavaTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-kubeflow/src/main/java/org/apache/dolphinscheduler/plugin/kubeflow/KubeflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mr/src/main/java/org/apache/dolphinscheduler/plugin/task/mr/MapReduceTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/SqoopTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTask.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnable.java
Labels: improvement, backend, 3.2.0

#13171 Remove logic task plugin module
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/task/TaskPluginManager.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-blocking/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-blocking/src/main/java/org/apache/dolphinscheduler/plugin/task/blocking/BlockingTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-blocking/src/main/java/org/apache/dolphinscheduler/plugin/task/blocking/BlockingTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-conditions/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-conditions/src/main/java/org/apache/dolphinscheduler/plugin/task/conditions/ConditionsTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-conditions/src/main/java/org/apache/dolphinscheduler/plugin/task/conditions/ConditionsTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dependent/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-dependent/src/main/java/org/apache/dolphinscheduler/plugin/task/dependent/DependentTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dependent/src/main/java/org/apache/dolphinscheduler/plugin/task/dependent/DependentTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-subprocess/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-subprocess/src/main/java/org/apache/dolphinscheduler/plugin/task/subprocess/SubProcessTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-subprocess/src/main/java/org/apache/dolphinscheduler/plugin/task/subprocess/SubProcessTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-switch/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchCondition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchResult.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchTaskChannelFactory.java
  dolphinscheduler-task-plugin/pom.xml
Labels: improvement, backend, 3.2.0

#12622 [Improvement][ApiServer]Task defination list paging sorted by updateTime not effect
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
Labels: improvement, backend, 3.2.0

#13179 [Fix-13160][UI] Ironed out the issue with failing to save the correct settings of dependent tasks.
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: bug, UI, 3.1.x

#13070 [Feature][API] New restful API for taskInstance
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskInstanceV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TaskInstanceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TaskInstanceV2ControllerTest.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
Labels: feature, backend, 4.0.0

#13094 [Fix] Fix the version inconsistency when updating workflows, tasks and relationships in openapi.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessTaskRelationV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/workflow/WorkflowUpdateRequest.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessTaskRelationService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessTaskRelationServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskDefinitionServiceImplTest.java
Labels: feature, backend, 4.0.0

#13139 [Improvement][Metrics] Filtering data by application in grafana-demo worker dashboard example
  dolphinscheduler-meter/src/main/resources/grafana/DolphinSchedulerWorker.json
Labels: improvement, 3.2.0

#13190 [Fix-13187] refactor OpenmldbParameters
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTask.java
Labels: bug, backend, 3.1.x

#13193 Optimize event loop to fix the event might not be handle since workflow finished
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java
Labels: bug, backend, 3.2.0

#13192 [Improve] Create v2folder
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/AccessTokenV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/ProcessTaskRelationV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/ProjectV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/QueueV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/ScheduleV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/StatisticsV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/TaskDefinitionV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/TaskInstanceV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/WorkflowInstanceV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/WorkflowV2Controller.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/v2/ProjectV2ControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/v2/StatisticsV2ControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/v2/TaskInstanceV2ControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/v2/WorkflowInstanceV2ControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/v2/WorkflowV2ControllerTest.java
Labels: improvement, backend, 3.2.0

#13207 [Fix][Doc]Update pseudo-cluster.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
Labels: document, 3.0.x

#13012 [Improvement][doc] correct error in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: improvement, document, priority:low, 3.0.x

#13208 [refactor] cache compiled regex pattern
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/RegexUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parser/ParameterUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTask.java
Labels: improvement, backend, priority:middle, 3.2.0

#13172 [Improvement][api-sql] Optimize the sql for paging query project
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
Labels: improvement, backend, 3.2.0

#13209 [Feature][task-plugins-12820] azure azure-sql datasource plugins
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/DataSourceConstants.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-all/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/AzureSQLDataSourceChannel.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/AzureSQLDataSourceChannelFactory.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/AzureSQLDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/param/AzureSQLAuthMode.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/param/AzureSQLConnectionParam.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/param/AzureSQLDataSourceParamDTO.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/param/AzureSQLDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/SQLServerDataSourceChannelFactoryTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/SQLServerDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/param/SQLServerDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-azure-core-http-netty.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-azure-core.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-azure-identity.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-content-type.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-jackson-dataformat-xml.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-lang-tag.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-msal4j-persistence-extension.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-msal4j.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-netty-codec-dns.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-netty-codec-socks.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-netty-handler-proxy.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-netty-resolver-dns-native-macos.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-netty-resolver-dns.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-netty-tcnative-boringssl-static.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-netty-transport-native-epoll.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-netty-transport-native-kqueue.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-oauth2-oidc-sdk.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-reactor-core.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-reactor-netty-core.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-reactor-netty-http.txt
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/enums/DbType.java
  tools/dependencies/known-dependencies.txt
Labels: feature, backend, 3.2.0

#13200 feat: add AZURESQL datasource
  dolphinscheduler-ui/src/locales/en_US/datasource.ts
  dolphinscheduler-ui/src/locales/zh_CN/datasource.ts
  dolphinscheduler-ui/src/service/modules/data-source/types.ts
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasource.ts
Labels: feature, UI, 3.2.0

#13221 [fix] [doc] fix dead link
  CONTRIBUTING.md
Labels: document, 3.1.x

#12606 [Fix-12586] [Master] Repeat running the complement process instance will generate redundant complement instances
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
Labels: discussion, backend

#13198 Remove datasource in procedure task
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceProcessorProvider.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java
Labels: improvement, backend, 3.2.0

#13231 [Bug][DAO] Worked out the issue with throwing the sql exception.
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
Labels: bug, backend, 3.1.x

#13234 [Fix-13226][UI] Worked out the issue with failing to enable timeout alarm on the dependent node.
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent-timeout.ts
Labels: bug, UI, 3.1.x

#13233 [Improvement][Master] fix spell error and move comment to correct describe location(issue 13232)
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowStartEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: first time contributor, improvement, backend, 3.2.0

#13237 Fix spelling
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/StateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
Labels: UI, improvement, backend, 3.2.0

#13239 [Bug][Document] Fix a tiny bug in release doc
  docs/docs/en/contribute/release.md
  docs/docs/zh/contribute/release.md
Labels: bug, document, 3.2.0

#13243 [Fix-13144][UI] Worked out the issue with failing to query workflow instances by the incorrect workflow status.
  dolphinscheduler-ui/src/common/common.ts
  dolphinscheduler-ui/src/common/types.ts
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/instance/components/process-instance-condition.tsx
Labels: bug, UI, 3.1.x

#13255 [Improvement][Master] Get varPool from upstream tasks instead of processInstance if dag is incomplete
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, improvement, 3.2.0

#13254 [doc][datasource-12820] add azure sql database doc
  docs/configs/docsdev.js
  docs/docs/en/guide/datasource/azure-sql.md
  docs/docs/zh/guide/datasource/azure-sql.md
  docs/img/new_ui/dev/datasource/azuresql-ad.png
  docs/img/new_ui/dev/datasource/azuresql-ad2.png
  docs/img/new_ui/dev/datasource/azuresql-endpoints.png
  docs/img/new_ui/dev/datasource/azuresql-msi-admin1.png
  docs/img/new_ui/dev/datasource/azuresql-msi-admin2.png
  docs/img/new_ui/dev/datasource/azuresql-msi.png
  docs/img/new_ui/dev/datasource/azuresql-principal.png
  docs/img/new_ui/dev/datasource/azuresql-principal2.png
  docs/img/new_ui/dev/datasource/azuresql-server.png
  docs/img/new_ui/dev/datasource/azuresql-token.png
Labels: document, 3.2.0

#13252 Add Terraform deploy manifests for quick setup in AWS
  .github/workflows/docs.yml
  .licenserc.yaml
  deploy/terraform/.gitignore
  deploy/terraform/README.md
  deploy/terraform/aws/.terraform.lock.hcl
  deploy/terraform/aws/README.md
  deploy/terraform/aws/dolphinscheduler-alert.tf
  deploy/terraform/aws/dolphinscheduler-api.tf
  deploy/terraform/aws/dolphinscheduler-master.tf
  deploy/terraform/aws/dolphinscheduler-output.tf
  deploy/terraform/aws/dolphinscheduler-standalone.tf
  deploy/terraform/aws/dolphinscheduler-variables.tf
  deploy/terraform/aws/dolphinscheduler-worker.tf
  deploy/terraform/aws/key-pair-main.tf
  deploy/terraform/aws/network-main.tf
  deploy/terraform/aws/network-variables.tf
  deploy/terraform/aws/os-versions.tf
  deploy/terraform/aws/packer/ds-ami-local.pkr.hcl
  deploy/terraform/aws/packer/ds-ami-official.pkr.hcl
  deploy/terraform/aws/provider-main.tf
  deploy/terraform/aws/provider-variables.tf
  deploy/terraform/aws/rds-main.tf
  deploy/terraform/aws/rds-output.tf
  deploy/terraform/aws/rds-variables.tf
  deploy/terraform/aws/s3-main.tf
  deploy/terraform/aws/s3-outputs.tf
  deploy/terraform/aws/s3-variables.tf
  deploy/terraform/aws/templates/cloud-init.yaml
  deploy/terraform/aws/templates/zookeeper/cloud-init.yaml
  deploy/terraform/aws/zookeeper-main.tf
  deploy/terraform/aws/zookeeper-output.tf
  deploy/terraform/aws/zookeeper-variables.tf
Labels: feature, CI&CD, 3.1.x, 3.2.0

#13251 [Fix-13248][UI] Ironed out the issue with failing to query task instances by some state of task.
  dolphinscheduler-ui/src/common/common.ts
  dolphinscheduler-ui/src/common/types.ts
  dolphinscheduler-ui/src/service/modules/process-instances/types.ts
  dolphinscheduler-ui/src/store/project/types.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui/src/views/projects/workflow/instance/use-table.ts
Labels: bug, UI, 3.1.x

#13264 [Bug] [Task Plugin] Synchronization status failure in SageMaker task
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/PipelineUtils.java
Labels: bug, backend, 3.1.x

#13265 [Improvement][UI] Support to open a new page to visit the detail page after clicking a link.
  dolphinscheduler-ui/src/views/projects/task/instance/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/instance/use-table.ts
Labels: UI, improvement, 3.2.0

#13267 [Improvement][UI] Support to display extra columns such as 'Worker Group' and 'Environment Name' on the page of cron manage.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/vo/ScheduleVo.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Schedule.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ScheduleMapper.xml
  dolphinscheduler-ui/src/views/projects/workflow/definition/timing/use-table.ts
Labels: UI, improvement, backend, 3.2.0

#13261 [Fix-13260][API] Ironed out the issue with lacking the value of user's name when querying the list of workflow definitions.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessDefinition.java
Labels: bug, backend, 3.2.0

#13222 [Improvement][api]Batch query for optimizing query process-list interface
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/UserWithProcessDefinitionCode.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/UserMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UserMapperTest.java
Labels: improvement, backend, 3.2.0

#13275 Use mybatis in mysql registry module
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/DaoConfiguration.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/pom.xml
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/MysqlOperator.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/MysqlRegistry.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/MysqlRegistryConfiguration.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/mapper/MysqlRegistryDataMapper.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/mapper/MysqlRegistryLockMapper.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/model/MysqlRegistryData.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/model/MysqlRegistryLock.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/src/main/java/org/apache/dolphinscheduler/plugin/registry/mysql/task/EphemeralDateManager.java
Labels: improvement, backend, 3.2.0

#13257 [Improvement][api]Start the downstream workflow when it is online
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.xml
Labels: improvement, backend, 3.1.x

#13276 [Fix][Doc] Replace the links.
  .dlc.json
  README.md
  README_zh_CN.md
  deploy/README.md
  docs/docs/en/contribute/architecture-design.md
  docs/docs/en/contribute/development-environment-setup.md
  docs/docs/en/contribute/join/review.md
  docs/docs/en/contribute/release.md
  docs/docs/en/faq.md
  docs/docs/en/guide/demo.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/guide/upgrade/upgrade.md
  docs/docs/zh/contribute/architecture-design.md
  docs/docs/zh/contribute/join/review.md
  docs/docs/zh/contribute/release.md
  docs/docs/zh/faq.md
  docs/docs/zh/guide/demo.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/standalone.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/guide/upgrade/upgrade.md
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-mysql/README.md
Labels: improvement, backend, document, 3.0.x

#13280 Remove the log path check
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/processor/LoggerRequestProcessor.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/LoggerRequestProcessorTest.java
Labels: improvement, backend, 3.2.0

#13271 [Improvement][docker] Add SPRING_JACKSON_TIME_ZONE to .env file
  deploy/docker/.env
  docs/docs/en/guide/start/docker.md
  docs/docs/zh/guide/start/docker.md
Labels: improvement, document, 3.1.x

#13281 Remove alert when delete workflow instance
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/BaseController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/WorkflowInstanceV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/Result.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/v2/WorkflowInstanceV2ControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertMapper.xml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java
Labels: improvement, backend, 3.2.0

#13075 [fix][dml] Also query workflow without tenant by given name
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
Labels: bug, backend, 3.0.x, 3.1.x

#13273 [Improvement][dao] Optimized countInstanceStateByProjectCodes
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
Labels: improvement, backend, 3.2.0

#13285 Fix when update scheduler will execute workflow
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
  dolphinscheduler-scheduler-plugin/dolphinscheduler-scheduler-quartz/src/main/java/org/apache/dolphinscheduler/scheduler/quartz/QuartzScheduler.java
Labels: improvement, backend, 3.2.0

#13092 [Bug] [Server] Once click online schedule time, task will be automatically scheduled
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/SchedulerServiceTest.java
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-form.ts
Labels: bug, UI, backend, priority:high, 3.0.x

#12902 [Bug-12868][UI] Data target type is only HDFS
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sqoop-target-type.ts
Labels: bug, first time contributor, UI, priority:low, 3.0.x

#13294 [doc] Correct install_env.sh file name
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/upgrade/upgrade.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/upgrade/upgrade.md
Labels: document, 3.0.x, 3.1.x

#13295 Revert "[Bug] [Server] Once click online schedule time, task will be automatically scheduled"
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/SchedulerServiceTest.java
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-form.ts
Labels: bug, UI, backend, 3.2.0

#13274 [Improvement][Worker] Startup parameter should have the highest priority
  docs/docs/en/guide/parameter/context.md
  docs/docs/en/guide/parameter/priority.md
  docs/docs/en/guide/parameter/startup-parameter.md
  docs/docs/zh/guide/parameter/context.md
  docs/docs/zh/guide/parameter/priority.md
  docs/docs/zh/guide/parameter/startup-parameter.md
  docs/img/new_ui/dev/parameter/startup_parameter01.png
  docs/img/new_ui/dev/parameter/startup_parameter02.png
  docs/img/new_ui/dev/parameter/startup_parameter03.png
  docs/img/new_ui/dev/parameter/startup_parameter04.png
  docs/img/new_ui/dev/parameter/startup_parameter05.png
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParams.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParamsServiceTest.java
Labels: bug, improvement, backend, document, 3.2.0

#13291 [Fix-13247] [Master] Kill yarn job failed due to NPE exception
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java
Labels: bug, backend

#13301 [fix][python] schedule unexpect offline each time update from api
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SchedulerService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/SchedulerControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/SchedulerServiceTest.java
Labels: bug, backend, Python, 3.1.x
