Repository apache/dolphinscheduler, pull requests merged in 2022-03, with the labels that each got.

#8590 [Fix][UI Next][V1.0.0-Alpha] Fix build standalone error.
  dolphinscheduler-ui-next/.env.production
  dolphinscheduler-ui-next/src/router/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-procedure.ts
  dolphinscheduler-ui-next/vite.config.ts
Labels: bug, UI

#8503 [Feature-8485][task-plugin] add EMR task plugin to support submit task to AWS EMR
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/TaskType.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/emr/EmrParameters.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/TaskParametersUtils.java
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-aws-java-sdk-core.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-aws-java-sdk-emr.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-ion-java.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-jackson-dataformat-cbor.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-jmespath-java.txt
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/task/TaskConstants.java
  dolphinscheduler-standalone-server/src/main/assembly/dolphinscheduler-standalone-server.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrTaskException.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/java/org/apache/dolphinscheduler/plugin/task/emr/EmrTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/resources/org/apache/dolphinscheduler/plugin/task/emr/EmrJobFlowDefine.json
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-worker/pom.xml
  dolphinscheduler-worker/src/main/assembly/dolphinscheduler-worker-server.xml
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: plug-in, miss document, priority:high

#8587 [Docs] Update README_zh_CN.md
  README_zh_CN.md
Labels: first time contributor

#8596 [Feature][UI Next][V1.0.0-Alpha] Added theme color modification field.
  dolphinscheduler-ui-next/src/themes/modules/dark.ts
  dolphinscheduler-ui-next/src/themes/modules/light.ts
Labels: new feature, UI

#8600 [Feature][UI Next][V1.0.0-Alpha] Delete build:dev in package.json.
  dolphinscheduler-ui-next/package.json
Labels: new feature, UI

#8601 [Docs][UI Next][V1.0.0-Alpha] Update README.md.
  dolphinscheduler-ui-next/README.md
Labels: document

#8606 [Feature][UI Next][V1.0.0-Alpha]Adjust font color in dark mode
  dolphinscheduler-ui-next/src/themes/modules/dark.ts
Labels: new feature, UI

#8603 [Fix-8598][UI Next][V1.0.0-Alpha] Fix menu readonly bug in workflow instance
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-menu.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-status.ts
Labels: bug, UI

#8630 [Fix-8617][UI Next][V1.0.0-Alpha] Fix workflow version info language internationalization bug
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
Labels: bug, UI

#8631 [Fix-8615][UI Next][V1.0.0-Alpha] Fix resource manage file edit page blank bug
  dolphinscheduler-ui-next/src/service/modules/resources/index.ts
  dolphinscheduler-ui-next/src/service/modules/resources/types.ts
  dolphinscheduler-ui-next/src/views/resource/file/create/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/edit/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/edit/use-edit.ts
Labels: bug, UI

#8643 [python] Add server port to python gateway server properties
  dolphinscheduler-python/src/main/resources/python-gateway.properties
Labels: bug

#8644 Revert "[cherry-pick] upgrade mybatis-plus to 3.4.3 (#8539)"
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessDefinition.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessInstance.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskDefinition.java
  dolphinscheduler-dist/release-docs/LICENSE
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: bug

#8638 [python] Fix source and issue tracker link in PyPI
  dolphinscheduler-python/pydolphinscheduler/setup.py
Labels: bug, Python

#8653 [Fix][UI Next][V1.0.0-Alpha] Unify time parsing method with date-fns to avoid compatibility issues
  dolphinscheduler-ui-next/src/service/modules/resources/index.ts
  dolphinscheduler-ui-next/src/views/data-quality/rule/use-table.ts
  dolphinscheduler-ui-next/src/views/data-quality/task-result/use-table.ts
  dolphinscheduler-ui-next/src/views/monitor/statistics/audit-log/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/list/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/option/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/queue/use-table.ts
  dolphinscheduler-ui-next/src/views/security/alarm-group-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/environment-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/k8s-namespace-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/token-manage/use-table.ts
Labels: bug, UI

#8655 [Fix][UI Next][V1.0.0-Alpha]Fixed an issue with time picker clearing
  dolphinscheduler-ui-next/src/views/home/use-process-state.ts
  dolphinscheduler-ui-next/src/views/home/use-task-state.ts
  dolphinscheduler-ui-next/src/views/projects/overview/use-process-state.ts
  dolphinscheduler-ui-next/src/views/projects/overview/use-task-state.ts
Labels: bug, UI

#8664 Add python gateway property file to bin tarball
  dolphinscheduler-dist/src/main/assembly/dolphinscheduler-bin.xml
Labels: bug

#8665 [Feature][UI Next][V1.0.0-Alpha] Delete the space between the create button in Security - Warning Instance Manage.
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/index.tsx
Labels: new feature, UI

#8668 [Fix][UI Next][V1.0.0-Alpha] Fix the task instance button prompts an error.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
Labels: bug, UI

#8669 [Fix][UI Next][V1.0.0-Alpha] Fix the display of the project name is too long, causing UI confusion.
  dolphinscheduler-ui-next/src/views/projects/list/index.module.scss
  dolphinscheduler-ui-next/src/views/projects/list/use-table.ts
Labels: bug, UI

#8660 [python] Increase UT coverage threshold to 0.9
  dolphinscheduler-python/pydolphinscheduler/.coveragerc
Labels: enhancement, Python

#8677 [Fix][UI Next][V1.0.0-Alpha] Fix menu selection status display error
  dolphinscheduler-ui-next/src/layouts/content/components/user/use-dropdown.ts
  dolphinscheduler-ui-next/src/views/login/use-login.ts
Labels: bug, UI

#8681 [Fix-8615][UI Next][V1.0.0-Alpha] Fix workflow startup time invalid bug
  dolphinscheduler-ui-next/src/utils/common.ts
  dolphinscheduler-ui-next/src/views/data-quality/rule/use-table.ts
  dolphinscheduler-ui-next/src/views/data-quality/task-result/use-table.ts
  dolphinscheduler-ui-next/src/views/monitor/statistics/audit-log/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/list/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/option/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/queue/use-table.ts
  dolphinscheduler-ui-next/src/views/security/alarm-group-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/environment-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/k8s-namespace-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/token-manage/use-table.ts
Labels: bug, UI

#8688 [Fix][UI Next][V1.0.0-Alpha] Fix the problem of incomplete Chinese support for all date pickers in the project.
  dolphinscheduler-ui-next/src/App.tsx
Labels: bug, UI

#8694 [Feature][UI Next][V1.0.0-Alpha] Add the tree chart of the work flow definition to the project management.
  dolphinscheduler-ui-next/.eslintrc.js
  dolphinscheduler-ui-next/pnpm-lock.yaml
  dolphinscheduler-ui-next/src/App.tsx
  dolphinscheduler-ui-next/src/components/chart/modules/Tree.tsx
  dolphinscheduler-ui-next/src/components/chart/modules/types.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/router/modules/projects.ts
  dolphinscheduler-ui-next/src/service/modules/process-definition/index.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/table-action.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/tree/index.module.scss
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/tree/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/tree/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/tree/use-tree.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/use-table.ts
Labels: new feature, UI

#8695 [Fix-8623][UI-Next][V1.0.0-Alpha] Rectify the issue to prompt the correct message for the process definition state.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/table-action.tsx
Labels: bug, UI

#8697 [Feature][UI Next][V1.0.0-Alpha] Support gantt
  dolphinscheduler-ui-next/src/router/modules/projects.ts
  dolphinscheduler-ui-next/src/service/modules/process-instances/index.ts
  dolphinscheduler-ui-next/src/utils/common.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/table-action.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/gantt/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/gantt/type.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/gantt/use-gantt.ts
Labels: new feature, UI

#8700 [Fix-8680][UI Next][V1.0.0-Alpha] Startup env name pull-down menu support clear
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/timing-modal.tsx
Labels: bug, UI

#8702 [Fix][UI Next][V1.0.0-Alpha] Change the table button size.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/table-action.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/use-table.ts
Labels: bug, UI

#8705 [Fix-8633][UI Next][V1.0.0-Alpha] Work out this issue to edit the process definition when clicking the edit button.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/table-action.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/use-table.ts
Labels: bug, UI

#8704 [Fix-8624][UI-Next][V1.0.0-Alpha] Rectify the issue to display the timing form when clicking the timing button in the process definition page.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/timing-modal.tsx
Labels: bug, UI

#8712 [Fix][UI Next][V1.0.0-Alpha] Fix the timing management list operation button is too small to be clicked accurately.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/timing/use-table.ts
Labels: bug, UI

#8716 [Fix][UI Next][V1.0.0-Alpha] Fix the is no tooltip for timing management table editing and up and down buttons.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/table-action.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/timing/use-table.ts
Labels: bug, UI

#8718 [Fix][UI Next][V1.0.0-Alpha] Fix the regularly manage multilingual switching issues.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/timing/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/timing/use-table.ts
Labels: bug, UI

#8721 [Fix][UI Next][V1.0.0-Alpha] Fix the Workflow instance table action button is too small to click.
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/table-action.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts
Labels: bug, UI

#8731 [Fix-8722][UI Next][V1.0.0-Alpha] Fix home page error bug
  dolphinscheduler-ui-next/src/locales/index.ts
Labels: bug, UI

#8733 [Fix][UI Next][V1.0.0-Alpha] Fix the issue that user email doesn‘t pass verification
  dolphinscheduler-ui-next/src/utils/regex.ts
Labels: bug, UI

#8734 [Fix-8690][UI Next][V1.0.0-Alpha] Fix startup execType bug
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-form.ts
Labels: bug, UI

#8738 [Refactor][UI Next][V1.0.0-Alpha] Refactor the list of projects under the project module
  dolphinscheduler-ui-next/src/views/projects/list/components/project-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/list/components/table-action.tsx
  dolphinscheduler-ui-next/src/views/projects/list/components/use-form.ts
  dolphinscheduler-ui-next/src/views/projects/list/index.tsx
  dolphinscheduler-ui-next/src/views/projects/list/use-table.ts
Labels: new feature, UI

#8736 [chore] Upgrade versions of issue-report
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Chore

#8739 [Feature-8497][UI Next][V1.0.0-Alpha] Support dependent task re-run automatically
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-form.ts
Labels: new feature, UI

#8742 [Fix-8715][UI Next][V1.0.0-Alpha] Worked out this issue with missing some data in the form of a task when continuously clicking the same task node.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
Labels: bug, UI

#8703 [Docs][UI Next][V1.0.0-Alpha] Add license file.
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-fira-code
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-fira-sans
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-ibm-plex
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-inter
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-lato
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-open-sans
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-roboto
Labels: dependencies, document

#8755 [Fix][UI-Next][V1.0.0-Alpha] Fix ui and backend languages are not consistent bug
  dolphinscheduler-ui-next/package.json
  dolphinscheduler-ui-next/src/layouts/content/components/locales/use-dropdown.ts
  dolphinscheduler-ui-next/src/service/service.ts
Labels: bug, dependencies, UI

#8762 [Docs][UI-Next] Add js-cookie license.
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@types-js-cookie
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-js-cookie
  dolphinscheduler-ui-next/pnpm-lock.yaml
Labels: document

#8763 [Fix] [ui] Fixed the re-upload function of the Resource Management menu #8764
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/list/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/file/pages/subdirectory/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/resource/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/subUdfDirectory/_source/list.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/fileChildReUpdate.vue
  dolphinscheduler-ui/src/js/module/components/fileUpdate/fileReUpload.vue
  dolphinscheduler-ui/src/js/module/components/nav/nav.vue
Labels: bug, UI

#8766 [Feature-8735][UI Next][V1.0.0-Alpha] Added the form of the EMR task.
  dolphinscheduler-ui-next/pnpm-lock.yaml
  dolphinscheduler-ui-next/src/assets/images/task-icons/emr.png
  dolphinscheduler-ui-next/src/assets/images/task-icons/emr_hover.png
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-emr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-emr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag.module.scss
Labels: bug, UI

#8767 [Fix][UI-Next][V1.0.0-Alpha] Fix error when deployed to nginx after compilation
  dolphinscheduler-ui-next/index.html
  dolphinscheduler-ui-next/public/lodash.min.js
Labels: bug, UI

#8773 [Fix][UI-Next][V1.0.0-Alpha] Fix user login error
  dolphinscheduler-ui-next/src/layouts/content/components/user/use-dropdown.ts
  dolphinscheduler-ui-next/src/views/login/use-login.ts
Labels: bug, UI

#8768 [python] Add LICENSE and NOTICE to python dist package
  .github/CODEOWNERS
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/python-api-licenses/LICENSE-click.txt
  dolphinscheduler-dist/release-docs/licenses/python-api-licenses/LICENSE-py4j.txt
  dolphinscheduler-dist/release-docs/licenses/python-api-licenses/LICENSE-ruamel.yaml.txt
  dolphinscheduler-python/pydolphinscheduler/DEVELOP.md
  dolphinscheduler-python/pydolphinscheduler/LICENSE
  dolphinscheduler-python/pydolphinscheduler/NOTICE
Labels: Python

#8782 [Fix][UI Next][V1.0.0-Alpha] Fix workflow duplicate key error bug
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: bug, UI

#8785 [Fix][UI Next][V1.0.0-Alpha] Fix missing pagination in version info table.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/version-modal.tsx
Labels: bug, UI

#8788 [Fix-8786] [ui] Fixed the "RESOURCE_NOT_EXIST" error message when clicking udF resource list file navigation prompt #8786
  dolphinscheduler-ui/src/js/conf/home/pages/resource/pages/udf/pages/subUdfDirectory/index.vue
Labels: bug, UI

#8791 [Fix-8746][UI] Rectify the issue with affecting the original node's data when editing the form of the copied node.
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/canvas/contextMenu.vue
Labels: bug, UI

#8794 [Improvement] [UI Next][V1.0.0-Alpha] Prettier and ESlint
  dolphinscheduler-ui-next/.eslintignore
  dolphinscheduler-ui-next/.prettierignore
  dolphinscheduler-ui-next/public/lodash.min.js
Labels: UI, improvement

#8779 [Feature][UI Next][V1.0.0-Alpha]Unified processing of back-end error messages
  dolphinscheduler-ui-next/src/service/service.ts
  dolphinscheduler-ui-next/src/utils/index.ts
  dolphinscheduler-ui-next/src/utils/log.ts
  dolphinscheduler-ui-next/src/views/datasource/list/use-detail.ts
  dolphinscheduler-ui-next/src/views/datasource/list/use-form.ts
  dolphinscheduler-ui-next/src/views/datasource/list/use-table.ts
  dolphinscheduler-ui-next/src/views/login/index.tsx
  dolphinscheduler-ui-next/src/views/login/use-translate.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-child-node.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-datasource-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-datasource.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-datax.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-environment-name.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-flink.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-mr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-process-name.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-rules.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sea-tunnel.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-shell.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-spark.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sql-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sql.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sqoop-datasource.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-switch.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-task-group.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-worker-group.ts
  dolphinscheduler-ui-next/src/views/projects/task/definition/use-task.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-custom-cell-builder.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/create/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/detail/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/timing/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/log-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/file/create/use-create.ts
  dolphinscheduler-ui-next/src/views/resource/file/edit/use-edit.ts
  dolphinscheduler-ui-next/src/views/resource/file/folder/use-folder.ts
  dolphinscheduler-ui-next/src/views/resource/file/rename/use-rename.ts
  dolphinscheduler-ui-next/src/views/resource/file/upload/use-upload.ts
  dolphinscheduler-ui-next/src/views/resource/udf/function/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/resource/udf/resource/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/resource/udf/resource/use-table.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/use-detail.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/use-form.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/use-table.ts
Labels: new feature, UI

#8797 [Fix][UI Next][V1.0.0-Alpha] Fix tenant not exists error while import…
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
Labels: bug, UI

#8805 [Bug][UI Next][V1.0.0-Alpha]Fixed the abnormal display of project management user values
  dolphinscheduler-ui-next/src/views/projects/list/components/project-modal.tsx
Labels: bug, UI

#8814 [Fix][UI Next][V1.0.0-Alpha] Fix the error message while opening the …
  dolphinscheduler-ui-next/src/views/projects/task/definition/components/version-modal.tsx
Labels: bug, UI

#8815 [Feature][E2E] Restore security center e2e test cases in ui-next
  .github/workflows/e2e.yml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/EnvironmentE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/FileManageE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/FunctionManageE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/QueueE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/TokenE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/UdfManageE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/UserE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkerGroupE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/LoginPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/common/NavBarPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/EnvironmentPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/QueuePage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TokenPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/UserPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/WorkerGroupPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/basic/docker-compose.yaml
  dolphinscheduler-e2e/dolphinscheduler-e2e-core/src/main/java/org/apache/dolphinscheduler/e2e/core/DolphinSchedulerExtension.java
  dolphinscheduler-ui-next/src/layouts/content/components/sidebar/index.tsx
  dolphinscheduler-ui-next/src/layouts/content/index.tsx
  pom.xml
Labels: new feature, UI, e2e

#8821 [Fix][UI Next][V1.0.0-Alpha] Fix the letters overlap with the input field.
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
Labels: bug, UI

#8822 [Fix][UI Next][V1.0.0-Alpha] Fix the DATA_QUALITY icon is null.
  dolphinscheduler-ui-next/src/assets/images/task-icons/data_quality.png
  dolphinscheduler-ui-next/src/assets/images/task-icons/data_quality_hover.png
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-sidebar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag.module.scss
Labels: bug, UI

#8833 [Feature][UI Next][V1.0.0-Alpha] UI support timezone setting
  dolphinscheduler-ui-next/src/layouts/content/components/navbar/index.tsx
  dolphinscheduler-ui-next/src/layouts/content/components/timezone/index.module.scss
  dolphinscheduler-ui-next/src/layouts/content/components/timezone/index.tsx
  dolphinscheduler-ui-next/src/layouts/content/components/timezone/use-dropdown.ts
  dolphinscheduler-ui-next/src/layouts/content/index.tsx
  dolphinscheduler-ui-next/src/layouts/content/use-dataList.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/users/types.ts
  dolphinscheduler-ui-next/src/store/timezone/timezone.ts
  dolphinscheduler-ui-next/src/store/timezone/types.ts
  dolphinscheduler-ui-next/src/views/login/use-login.ts
Labels: new feature, UI

#8839 [Feature][UI Next][V1.0.0-Alpha]: Refactor the user manage page unde…
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/data-source/index.ts
  dolphinscheduler-ui-next/src/service/modules/projects/index.ts
  dolphinscheduler-ui-next/src/service/modules/resources/index.ts
  dolphinscheduler-ui-next/src/service/modules/users/index.ts
  dolphinscheduler-ui-next/src/service/modules/users/types.ts
  dolphinscheduler-ui-next/src/utils/tree-format.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-flink.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-mr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sea-tunnel.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-shell.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-spark.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sql.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/authorize-modal.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-authorize.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-user-detail.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/user-detail-modal.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/components/user-modal.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/index.module.scss
  dolphinscheduler-ui-next/src/views/security/user-manage/index.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/types.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/use-columns.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/use-table.tsx
Labels: new feature, UI

#8830 [python] Change name to_string to __str__ and add __repr__
  dolphinscheduler-python/pydolphinscheduler/DEVELOP.md
  dolphinscheduler-python/pydolphinscheduler/UPDATING.md
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/configuration.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/utils/yaml_parser.py
  dolphinscheduler-python/pydolphinscheduler/tests/utils/test_yaml_parser.py
Labels: enhancement, Python

#8604 [Fix-8602][k8s] Re-patch values.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: first time contributor

#8795 [Improvement-8758] [worker] Delete unused object preTaskCache
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java
Labels: first time contributor

#8849 [Fix][UI Next][V1.0.0-Alpha] Fix the performance warning of ButtonLink co…
  dolphinscheduler-ui-next/src/components/button-link/index.tsx
Labels: bug, UI

#8868 [Fix][UI Next][V1.0.0-Alpha] Fix the Workflow Relation page cannot be zoomed in or out using a scroll wheel.
  dolphinscheduler-ui-next/src/views/projects/workflow/relation/components/Graph.tsx
Labels: bug, UI

#8872 [Feature][UI Next][V1.0.0-Alpha] Timezone to support search
  dolphinscheduler-ui-next/src/layouts/content/components/timezone/index.module.scss
  dolphinscheduler-ui-next/src/layouts/content/components/timezone/index.tsx
  dolphinscheduler-ui-next/src/layouts/content/components/timezone/use-dropdown.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: new feature, UI

#8870 [Feature][UI Next][V1.0.0-Alpha] Add the corresponding state for the …
  dolphinscheduler-ui-next/src/views/datasource/list/use-detail.ts
  dolphinscheduler-ui-next/src/views/password/use-form.ts
  dolphinscheduler-ui-next/src/views/profile/index.tsx
  dolphinscheduler-ui-next/src/views/profile/use-form.ts
  dolphinscheduler-ui-next/src/views/profile/use-update.ts
  dolphinscheduler-ui-next/src/views/projects/list/components/project-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/list/components/use-form.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/task/definition/components/move-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/task/definition/components/use-move.ts
  dolphinscheduler-ui-next/src/views/projects/task/definition/index.tsx
  dolphinscheduler-ui-next/src/views/projects/task/definition/use-task.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/import-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/timing-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-form.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/resource/file/folder/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/folder/use-folder.ts
  dolphinscheduler-ui-next/src/views/resource/file/folder/use-form.ts
  dolphinscheduler-ui-next/src/views/resource/file/rename/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/rename/use-form.ts
  dolphinscheduler-ui-next/src/views/resource/file/rename/use-rename.ts
  dolphinscheduler-ui-next/src/views/resource/file/upload/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/upload/use-form.ts
  dolphinscheduler-ui-next/src/views/resource/file/upload/use-upload.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/option/components/form-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/task-group/option/use-form.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/queue/components/form-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/task-group/queue/use-form.ts
  dolphinscheduler-ui-next/src/views/resource/udf/function/components/function-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/function/components/use-form.ts
  dolphinscheduler-ui-next/src/views/resource/udf/function/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/resource/udf/resource/components/folder-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/resource/components/upload-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/resource/components/use-form.ts
  dolphinscheduler-ui-next/src/views/resource/udf/resource/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/security/alarm-group-manage/components/alarm-group-modal.tsx
  dolphinscheduler-ui-next/src/views/security/alarm-group-manage/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/use-detail.ts
  dolphinscheduler-ui-next/src/views/security/environment-manage/components/environment-modal.tsx
  dolphinscheduler-ui-next/src/views/security/environment-manage/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/security/k8s-namespace-manage/components/k8s-namespace-modal.tsx
  dolphinscheduler-ui-next/src/views/security/k8s-namespace-manage/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/security/tenant-manage/components/tenant-modal.tsx
  dolphinscheduler-ui-next/src/views/security/tenant-manage/components/use-modalData.ts
  dolphinscheduler-ui-next/src/views/security/token-manage/components/token-modal.tsx
  dolphinscheduler-ui-next/src/views/security/token-manage/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-user-detail.ts
  dolphinscheduler-ui-next/src/views/security/worker-group-manage/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/security/worker-group-manage/components/worker-group-modal.tsx
  dolphinscheduler-ui-next/src/views/security/yarn-queue-manage/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/security/yarn-queue-manage/components/yarn-queue-modal.tsx
Labels: bug, UI

#8843 [Feature-8591][Python] Add pre-commit to run basic test before commit
  dolphinscheduler-python/pydolphinscheduler/.flake8
  dolphinscheduler-python/pydolphinscheduler/.pre-commit-config.yaml
  dolphinscheduler-python/pydolphinscheduler/DEVELOP.md
Labels: enhancement, CI&CD, Python

#8885 [Feature][UI Next][V1.0.0-Alpha] Scheduler datetime display optimization
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/timing/use-table.ts
Labels: new feature, UI

#8886 [ci] Add timeout to each job avoiding zombie process
  .github/workflows/backend.yml
  .github/workflows/e2e.yml
  .github/workflows/frontend.yml
  .github/workflows/py-ci.yml
  .github/workflows/unit-test.yml
Labels: CI&CD, Chore

#8876 [Fix] [UI Next][V1.0.0-Alpha] Fix the pre task options missing in dag page.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail.tsx
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-pre-tasks.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-process-name.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-conditions.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-data-quality.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-datax.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-dependent.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-emr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-flink.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-http.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-mr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-pigeon.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-procedure.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-python.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sea-tunnel.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-shell.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-spark.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sql.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sqoop.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sub-process.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-switch.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
Labels: bug, UI

#8880 [Fix-8836][UI Next][V1.0.0-Alpha] Rectify this issue about creating a file or directory with a wrong path.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-ui-next/src/layouts/content/components/timezone/index.module.scss
  dolphinscheduler-ui-next/src/service/modules/resources/index.ts
  dolphinscheduler-ui-next/src/service/modules/resources/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/resource/file/folder/use-folder.ts
  dolphinscheduler-ui-next/src/views/resource/file/index.tsx
Labels: bug, UI

#8888 Revert "[Fix-8836][UI Next][V1.0.0-Alpha] Rectify this issue about creating a file or directory with a wrong path."
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-ui-next/src/layouts/content/components/timezone/index.module.scss
  dolphinscheduler-ui-next/src/service/modules/resources/index.ts
  dolphinscheduler-ui-next/src/service/modules/resources/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/resource/file/folder/use-folder.ts
  dolphinscheduler-ui-next/src/views/resource/file/index.tsx
Labels: bug, UI

#8898 [Fix][UI Next][V1.0.0-Alpha] Fix some types missing when direct was e…
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sqoop-source-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sqoop-target-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sqoop.ts
Labels: bug, UI

#8902 [Bug] [UI Next][V1.0.0-Alpha] Fix crontab component styles
  dolphinscheduler-ui-next/src/components/crontab/index.module.scss
  dolphinscheduler-ui-next/src/components/crontab/modules/day.tsx
  dolphinscheduler-ui-next/src/components/crontab/modules/time.tsx
Labels: bug, UI

#8905 [Bug] [UI Next][V1.0.0-Alpha] Fix workflow import form was not cleaned up bug
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
Labels: bug, UI

#8899 [Feature-8530][API] add system default timezone if no user timezone when get userInfo
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
Labels: new feature, backend

#8907 [Docs][UI-Next] Add date-fns-tz license.
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-date-fns-tz
Labels: document

#8901 [python] Make the logs look better
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/task.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_task.py
  dolphinscheduler-python/pydolphinscheduler/tests/testing/task.py
Labels: enhancement, Python

#8912 [Fix][UI Next][V1.0.0-Alpha] Fix the task instance logs are not automatically updated.
  dolphinscheduler-ui-next/src/components/modal/index.tsx
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/instance/components/log-modal.tsx
Labels: bug, UI

#8909 [Feature-8850][E2E] Restore project center e2e test cases in ui-next
  .github/workflows/e2e.yml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/LoginPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/common/CodeEditor.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/ProjectDetailPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/ProjectPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowDefinitionTab.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowInstanceTab.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowRunDialog.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowSaveDialog.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/ShellTaskForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/SubWorkflowTaskForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/TaskNodeForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/FunctionManagePage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/basic/docker-compose.yaml
  dolphinscheduler-ui-next/src/components/form/fields/custom-parameters.ts
  dolphinscheduler-ui-next/src/components/modal/index.tsx
  dolphinscheduler-ui-next/src/views/projects/list/components/project-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/list/index.tsx
  dolphinscheduler-ui-next/src/views/projects/list/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-child-node.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-custom-params.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-name.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-pre-tasks.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-canvas.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-sidebar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/table-action.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/table-action.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts
Labels: UI, backend, e2e

#8897 [python] Add autoflake to auto rm unused import
  dolphinscheduler-python/pydolphinscheduler/.pre-commit-config.yaml
  dolphinscheduler-python/pydolphinscheduler/DEVELOP.md
  dolphinscheduler-python/pydolphinscheduler/setup.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/exceptions.py
  dolphinscheduler-python/pydolphinscheduler/tox.ini
Labels: enhancement, CI&CD, Python

#8920 AlertPluginInstanceController verifyGroupName method code optimizatio…
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AlertPluginInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/Result.java
Labels: first time contributor

#8924 [Fix][UI Next][V1.0.0-Alpha] Fix the instructions links error in task…
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/task/constants/task-type.ts
Labels: bug, UI

#8926 [Bug][UI Next][V1.0.0-Alpha] Fix workflow instance save is not responding bug
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/process-instances/index.ts
  dolphinscheduler-ui-next/src/service/modules/process-instances/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/detail/index.tsx
Labels: bug, UI

#8928 [Fix][UI Next][V1.0.0-Alpha] Fix pre task error when creating task i…
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-cell-update.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: bug, UI

#8930 [Fix][UI Next][V1.0.0-Alpha] Support workflow batch operation
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/process-definition/index.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/copy-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-form.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/index.module.scss
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/use-table.ts
Labels: bug, UI

#8932 [Fix][UI Next][V1.0.0-Alpha] Fix refresh resource manage auto logout bug
  dolphinscheduler-ui-next/src/service/service.ts
  dolphinscheduler-ui-next/src/views/login/use-login.ts
Labels: bug, UI

#8921 [Bug][DataSource] fix oracle datasource validation query
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oracle/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oracle/OracleDataSourceClient.java
Labels: first time contributor

#8947 [Fix][UI Next][V1.0.0-Alpha] Fix the edge missing after editing the …
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-cell-update.ts
Labels: bug, UI

#8949 [Fix][UI Next][V1.0.0-Alpha]Fix the serial wait text language not con…
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI

#8950 [Fix][UI Next][V1.0.0-Alpha] Fix the English display problem of timeout alert minute
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
Labels: bug, UI

#8952 [Fix][UI Next][V1.0.0-Alpha] Fix the workflow instance not clickable …
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
Labels: bug, UI

#8954 [Fix][UI Next][V1.0.0-Alpha]Fix the pagination of task instance table…
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
Labels: bug, UI

#8957 [Fix] [UI Next][V1.0.0-Alpha] Enviroment name display error in cron manage
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/timing-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-form.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
Labels: bug, UI

#8960 [Fix][UI Next][V1.0.0-Alpha] Fix the stop button tips error and its u…
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/table-action.tsx
Labels: bug, UI

#8963 [Fix-8834][UI Next][V1.0.0-Alpha] Rectify this issue about missing the path in the page of file management.
  dolphinscheduler-ui-next/src/components/card/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/index.module.scss
  dolphinscheduler-ui-next/src/views/resource/file/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/types.ts
Labels: bug, UI

#8968 [Fix][UI Next][V1.0.0-Alpha] Fix the problem of table multilingual switching in alarm instance management.
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/index.tsx
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/use-columns.ts
Labels: bug, UI

#8977 [Fix][UI Next][V1.0.0-Alpha] Add the hover tips for the datasource ta…
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/datasource/list/use-columns.ts
Labels: bug, UI

#8978 [Fix][UI Next][V1.0.0-Alpha] Add the hover tips for the alarm instanc…
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/use-columns.ts
Labels: bug, UI

#8984 [Fix][UI Next][V1.0.0-Alpha] Fix the new button in the English state of the alarm instance page lacks a space.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/detail.tsx
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/index.tsx
Labels: bug, UI

#8981 [Fix][UI Next][V1.0.0-Alpha] The problem of multi-language support in FeiShu alert instance.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI

#8966 [python] Add integrated test to python gateway server
  .github/workflows/py-ci.yml
  dolphinscheduler-python/pydolphinscheduler/DEVELOP.md
  dolphinscheduler-python/pydolphinscheduler/pytest.ini
  dolphinscheduler-python/pydolphinscheduler/setup.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/configuration.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_configuration.py
  dolphinscheduler-python/pydolphinscheduler/tests/integration/__init__.py
  dolphinscheduler-python/pydolphinscheduler/tests/integration/test_submit_examples.py
  dolphinscheduler-python/pydolphinscheduler/tests/testing/constants.py
  dolphinscheduler-python/pydolphinscheduler/tests/testing/docker_wrapper.py
  dolphinscheduler-python/pydolphinscheduler/tox.ini
  dolphinscheduler-standalone-server/src/main/docker/Dockerfile
Labels: enhancement, CI&CD, Python

#8989 [Feature][Dag] Jump back to the list page after the workflow is saved.
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
Labels: new feature, UI

#8992 [Fix][UI Next][V1.0.0-Alpha] Fix the task definition page table scale imbalance problem.
  dolphinscheduler-ui-next/src/components/card/index.tsx
  dolphinscheduler-ui-next/src/views/projects/task/definition/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/file/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/types.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/index.tsx
Labels: bug, UI

#8991 [Feature][UI Next][V1.0.0-Alpha] The label of the form in the unified project is arranged up and down.
  dolphinscheduler-ui-next/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-auto-layout-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/copy-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/import-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/timing-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/file/create/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/folder/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/rename/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/upload/index.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/function/components/function-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/resource/components/folder-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/resource/components/upload-modal.tsx
  dolphinscheduler-ui-next/src/views/security/tenant-manage/components/tenant-modal.tsx
Labels: new feature, UI

#9004 [Feature-8985][UI-Next] Add a new option of 'thisMonthBegin into the options of the month select for the dependent task.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-dependent.ts
Labels: new feature, UI

#9005 [Fix][UI Next][V1.0.0-Alpha] Fix the alarm instance management edit button floating prompt error.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI

#9006 [Fix][UI Next][V1.0.0-Alpha] Fix the scale of the table on the task instance page is out of balance.
  dolphinscheduler-ui-next/src/views/projects/task/instance/index.tsx
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-auto-layout-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/copy-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/import-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/file/folder/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/rename/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/upload/index.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/function/components/function-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/resource/components/folder-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/udf/resource/components/upload-modal.tsx
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/detail.tsx
Labels: bug, UI

#9011 [Fix][UI Next][V1.0.0-Alpha] Fix there is a warning message in the task group configuration.
  dolphinscheduler-ui-next/src/service/modules/task-group/types.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/option/components/form-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/task-group/option/use-form.ts
Labels: bug, UI

#9008 [Bug][UI Next]Fix styling problems in the project
  dolphinscheduler-ui-next/src/views/projects/task/instance/index.tsx
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
Labels: bug, UI

#9012 [Fix][UI Next][V1.0.0-Alpha] Fix the information entered after the task group configuration is clicked on the Edit button is incorrect.
  dolphinscheduler-ui-next/src/views/resource/task-group/option/index.tsx
Labels: bug, UI

#9014 [Fix][UI Next][V1.0.0-Alpha] Fix the new task group configuration item name is displayed as 0.
  dolphinscheduler-ui-next/src/service/modules/task-group/types.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/option/components/form-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/task-group/option/use-form.ts
Labels: bug, UI

#9017 [Fix-9015][UI Next][V1.0.0-Alpha] Worked out this issue about failing to assign another project to an existing task group.
  dolphinscheduler-ui-next/src/views/resource/task-group/option/components/form-modal.tsx
Labels: bug, UI

#8999 [python] Separate py from main dist and auto add gpg sign
  dolphinscheduler-dist/pom.xml
  dolphinscheduler-python/pom.xml
  pom.xml
Labels: Python, miss document

#9023 [Feature-9021][E2E] Recover sub_process e2e test in ui-next
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowDefinitionTab.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/SubWorkflowTaskForm.java
Labels: UI, backend, e2e

#9027 [Fix][UI Next][V1.0.0-Alpha] Fix there is a problem with the language support of the PagerDuty alarm instance.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI

#9033 [Fix][UI Next][V1.0.0-Alpha] Fix the WebexTeams alarm instance language support has problems.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI

#9037 [Fix][UI Next][V1.0.0-Alpha] When creating a new project, the last created project information is not cleared
  dolphinscheduler-ui-next/src/views/projects/list/components/project-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/list/components/use-form.ts
Labels: bug, UI

#9038 [Fix][UI Next][V1.0.0-Alpha] Fix the Dry Run Flag column of task inst…
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
Labels: bug, UI

#9036 [Fix][UI Next][V1.0.0-Alpha] Menu error
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/ResourcePage.java
  dolphinscheduler-ui-next/src/layouts/content/components/navbar/index.tsx
  dolphinscheduler-ui-next/src/layouts/content/components/sidebar/index.tsx
  dolphinscheduler-ui-next/src/layouts/content/index.tsx
  dolphinscheduler-ui-next/src/layouts/content/use-dataList.ts
  dolphinscheduler-ui-next/src/router/index.ts
  dolphinscheduler-ui-next/src/router/modules/data-quality.ts
  dolphinscheduler-ui-next/src/router/modules/datasource.ts
  dolphinscheduler-ui-next/src/router/modules/monitor.ts
  dolphinscheduler-ui-next/src/router/modules/projects.ts
  dolphinscheduler-ui-next/src/router/modules/resources.ts
  dolphinscheduler-ui-next/src/router/modules/security.ts
  dolphinscheduler-ui-next/src/router/routes.ts
  dolphinscheduler-ui-next/src/store/menu/menu.ts
  dolphinscheduler-ui-next/src/store/route/route.ts
  dolphinscheduler-ui-next/src/store/route/types.ts
  dolphinscheduler-ui-next/src/views/login/use-login.ts
  dolphinscheduler-ui-next/src/views/projects/list/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/file/index.tsx
Labels: bug, UI

#9049 [Fix][UI Next][V1.0.0-Alpha] Fix the branch flow options not showing …
  dolphinscheduler-ui-next/src/store/project/task-node.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-conditions.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-canvas-init.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-cell-update.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: bug, UI

#9054 [Fix][UI Next][V1.0.0-Alpha]Fix the data_quality.rule.all not configu…
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI

#9057 [Fix][UI Next][V1.0.0-Alpha] Fix workflow delete handle
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/table-action.tsx
Labels: bug, UI

#9060 [Fix][UI Next][V1.0.0-Alpha] User Manage Queue display error
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-user-detail.ts
Labels: bug, UI

#9063 [Fix-9025] [UI Next] Rectify this issue about failing to save a process when the user is ordinary user.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-task-group.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
Labels: bug, UI

#9067 [Bug][UI Next]Fix style errors
  dolphinscheduler-ui-next/src/views/security/tenant-manage/use-table.ts
Labels: bug, UI

#9064 [Fix][UI Next][V1.0.0-Alpha] fix queue display bug in tenant modal
  dolphinscheduler-ui-next/src/views/security/tenant-manage/components/tenant-modal.tsx
  dolphinscheduler-ui-next/src/views/security/tenant-manage/components/use-modalData.ts
Labels: bug, UI

#9077 [Feature][e2e] Suggest e2e test adapt M1 chip
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowRunDialog.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-core/src/main/java/org/apache/dolphinscheduler/e2e/core/DolphinSchedulerExtension.java
Labels: enhancement, e2e

#9075 [Fix][UI Next][V1.0.0-Alpha]Fix default display of node name in sub p…
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-child-node.ts
Labels: bug, UI

#9083 [Fix][UI Next][V1.0.0-Alpha] Workflow upload button internationalization
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/import-modal.tsx
Labels: bug, UI

#9086 [Fix][UI Next][V1.0.0-Alpha] Fix the worker page name.
  dolphinscheduler-ui-next/src/views/monitor/servers/worker/index.tsx
Labels: bug, UI

#9079 [Fix-9078][UI Next][V1.0.0-Alpha] The interface for adding DingTalk a…
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI

#9092 [Fix][UI Next][V1.0.0-Alpha] Resource authorization failed
  dolphinscheduler-ui-next/src/utils/tree-format.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-authorize.ts
Labels: bug, UI

#9110 [Fix][UI Next][V1.0.0-Alpha]Fix udf function upload internationalization bug
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/resource/udf/function/components/function-modal.tsx
Labels: bug, UI

#9111 [Fix][UI Next][V1.0.0-Alpha] Fix udf function auth bug
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-authorize.ts
Labels: bug, UI

#9104 [Fix][UI Next][V1.0.0-Alpha] Fix the task icons not shown in dag page
  dolphinscheduler-ui-next/public/images/task-icons/conditions.png
  dolphinscheduler-ui-next/public/images/task-icons/conditions_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/data_quality.png
  dolphinscheduler-ui-next/public/images/task-icons/data_quality_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/datax.png
  dolphinscheduler-ui-next/public/images/task-icons/datax_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/dependent.png
  dolphinscheduler-ui-next/public/images/task-icons/dependent_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/emr.png
  dolphinscheduler-ui-next/public/images/task-icons/emr_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/flink.png
  dolphinscheduler-ui-next/public/images/task-icons/flink_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/http.png
  dolphinscheduler-ui-next/public/images/task-icons/http_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/mr.png
  dolphinscheduler-ui-next/public/images/task-icons/mr_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/pigeon.png
  dolphinscheduler-ui-next/public/images/task-icons/pigeon_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/procedure.png
  dolphinscheduler-ui-next/public/images/task-icons/procedure_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/python.png
  dolphinscheduler-ui-next/public/images/task-icons/python_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/seatunnel.png
  dolphinscheduler-ui-next/public/images/task-icons/seatunnel_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/shell.png
  dolphinscheduler-ui-next/public/images/task-icons/shell_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/spark.png
  dolphinscheduler-ui-next/public/images/task-icons/spark_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/sql.png
  dolphinscheduler-ui-next/public/images/task-icons/sql_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/sqoop.png
  dolphinscheduler-ui-next/public/images/task-icons/sqoop_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/sub_process.png
  dolphinscheduler-ui-next/public/images/task-icons/sub_process_hover.png
  dolphinscheduler-ui-next/public/images/task-icons/switch.png
  dolphinscheduler-ui-next/public/images/task-icons/switch_hover.png
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag.module.scss
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-cell-active.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-custom-cell-builder.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/tree/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/relation/components/Graph.tsx
Labels: bug, UI

#9112 [Fix] [UI Next] [V1.0.0-Alpha] Fix the send email and the log not shown in SQL.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/utils/column-width-config.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-datasource.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sql-type.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/index.module.scss
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sql.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/definition/use-table.ts
Labels: bug, UI

#9117 [Improve-9108][UI Next][V1.0.0-Alpha] Rectify the issue about having a few misspelled words in the resource management.
  dolphinscheduler-ui-next/src/views/resource/file/index.tsx
Labels: new feature, UI

#9116 [Fix][UI Next][V1.0.0-Alpha] Fix there are multiple hover prompts.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/use-table.ts
Labels: bug, UI

#9120 [Fix][UI Next][V1.0.0-Alpha]Fix the SQL Parameter and UDF function no…
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/resources/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-sql.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-udfs.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sql.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
Labels: bug, UI

#9119 [Improve-9118][UI Next][V1.0.0-Alpha] Extend the column of the resource name on the page of the UDF resource management.
  dolphinscheduler-ui-next/src/views/resource/udf/resource/use-table.ts
Labels: bug, UI

#9128 [Fix][UI Next][V1.0.0-Alpha] Fix the resources options incorrect in S…
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-spark.ts
Labels: bug, UI

#9131 [Fix][UI Next][V1.0.0-Alpha] Fix the deploy mode with an extra client option in FLINK.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-deploy-mode.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-flink.ts
Labels: bug, UI

#9107 [Fix-8544][API] The folder's size can't be updated when creating, updating or deleting a resource file int the folder.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/datasource/DolphinSchedulerManager.java
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/datasource/dao/ResourceDao.java
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/datasource/dao/UpgradeDao.java
Labels: bug, backend

#9123 [Fix][UI Next][V1.0.0-Alpha] Fix the user token edit bug.
  dolphinscheduler-ui-next/src/views/security/token-manage/components/token-modal.tsx
Labels: bug, UI

#9141 [Fix][UI Next][V1.0.0-Alpha] Alarm Instance console error
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI
