Repository apache/dolphinscheduler, pull requests merged in 2022-05, with the labels that each got.

#9858 [Fix][UI Next][V1.0.0-Beta] Fix the problem that there is no prompt for selecting users.
  dolphinscheduler-ui-next/package.json
  dolphinscheduler-ui-next/pnpm-lock.yaml
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/security/token-manage/components/token-modal.tsx
  dolphinscheduler-ui-next/src/views/security/token-manage/components/use-modal.ts
Labels: bug, UI

#9850 [Fix-9849] [worker] Fix CommandType TASK_EXECUTE_RUNNING_ACK don't consume…
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskCallbackService.java
Labels: first time contributor, backend

#9869 [Fix-9868] A task flow definition isolates the runs of different execution strategies by version numbers.
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: bug, backend

#9861 [Fix-9856]Failed to upload the file but get misleading error message
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
Labels: first time contributor, backend

#9864 [Fix][UI Next][V1.0.0-Beta] Fix bug where logo disappeared when format dag
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
Labels: bug, UI

#9851 [Improvement-9772][docs/docs-zh] add spark sql docs for Docs
  docs/docs/en/guide/task/spark.md
  docs/docs/zh/guide/task/spark.md
  docs/img/tasks/demo/spark_sql.png
Labels: document

#9862 [doc] Separate and correct getting start by docker
  docs/docs/en/faq.md
  docs/docs/en/guide/datasource/hive.md
  docs/docs/en/guide/datasource/introduction.md
  docs/docs/en/guide/datasource/mysql.md
  docs/docs/en/guide/datasource/postgresql.md
  docs/docs/en/guide/datasource/spark.md
  docs/docs/en/guide/start/docker.md
  docs/docs/zh/faq.md
  docs/docs/zh/guide/datasource/hive.md
  docs/docs/zh/guide/datasource/introduction.md
  docs/docs/zh/guide/datasource/mysql.md
  docs/docs/zh/guide/datasource/postgresql.md
  docs/docs/zh/guide/datasource/spark.md
  docs/docs/zh/guide/start/docker.md
Labels: bug, document

#9879 [Fix][UI Next][V1.0.0-Beta] Fix the page input error on the token manage page.
  dolphinscheduler-ui-next/src/views/security/token-manage/use-table.ts
Labels: bug, UI

#9877 [Fix][UI Next][V1.0.0-Beta] Fix some errors on the datasource page.
  dolphinscheduler-ui-next/src/views/datasource/list/index.tsx
  dolphinscheduler-ui-next/src/views/datasource/list/use-columns.ts
Labels: bug, UI

#9875 [Fix][UI Next][V1.0.0-Beta] Fix edge deletion unhandled and remove the useless nextNodes.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-switch.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: bug, UI

#9883 [Docs][UI Next][V1.0.0-Beta] Add @types-lodash license.
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-@types-lodash
Labels: document

#9888 [Feature][UI Next][V1.0.0-Beta] Add hints to the password repeat.
  dolphinscheduler-ui-next/src/views/password/index.tsx
  dolphinscheduler-ui-next/src/views/password/use-form.ts
Labels: new feature, UI

#9895 [Docs][UI][Beta] Update README.
  dolphinscheduler-ui-next/README.md
Labels: document

#9893 [Fix][UI-NEXT]Disable file name
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/import-modal.tsx
Labels: bug, UI

#9887 [bug] [doc] fix the data quality link error about the navigation of dolphinscheduler 3.0.0-alpha zh docs
  docs/configs/docsdev.js
Labels: first time contributor, document

#9866 [Feature][Doc] Add docs for zeppelin task plugin (#9838)
  docs/configs/docsdev.js
  docs/docs/en/guide/task/zeppelin.md
  docs/docs/zh/guide/task/zeppelin.md
  docs/img/tasks/demo/zeppelin.png
  docs/img/tasks/demo/zeppelin_id.png
  docs/img/tasks/icons/zeppelin.png
Labels: document

#9915 [Fix]Added request header validation
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-http.ts
Labels: bug, UI

#9932 [Fix][UI Next][V1.0.0-Beta] Fix console bug after deleting a node fr…
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: bug, UI

#9933 [Fix]fix miss fixvalue input
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-rules.ts
Labels: bug, UI

#9935 [Feature][UI] Disabled statistics.
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/monitor/statistics/statistics/index.tsx
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-http.ts
Labels: bug, UI

#9939 [docs] Correct custom docker image in faq
  docs/docs/en/faq.md
  docs/docs/zh/faq.md
Labels: bug, document

#9658 [Feature][Document] Refactor the Resource Center Document
  docs/configs/docsdev.js
  docs/docs/en/guide/resource.md
  docs/docs/en/guide/resource/configuration.md
  docs/docs/en/guide/resource/file-manage.md
  docs/docs/en/guide/resource/task-group.md
  docs/docs/en/guide/resource/udf-manage.md
  docs/docs/en/guide/task/flink.md
  docs/docs/en/guide/task/map-reduce.md
  docs/docs/en/guide/task/spark.md
  docs/docs/zh/guide/resource.md
  docs/docs/zh/guide/resource/configuration.md
  docs/docs/zh/guide/resource/file-manage.md
  docs/docs/zh/guide/resource/task-group.md
  docs/docs/zh/guide/resource/udf-manage.md
  docs/docs/zh/guide/task/flink.md
  docs/docs/zh/guide/task/map-reduce.md
  docs/docs/zh/guide/task/spark.md
  docs/img/file_detail.png
  docs/img/file_detail_en.png
  docs/img/new_ui/dev/resource/demo/file-demo01.png
  docs/img/new_ui/dev/resource/demo/file-demo02.png
  docs/img/new_ui/dev/resource/demo/file-demo03.png
  docs/img/new_ui/dev/resource/demo/udf-demo01.png
  docs/img/new_ui/dev/resource/demo/udf-demo02.png
  docs/img/new_ui/dev/resource/demo/udf-demo03.png
  docs/img/tasks/demo/file_detail.png
Labels: enhancement, document

#9840 [Feature- 9837][plugin/ui] support FlinkSQL Task
  docs/docs/en/guide/task/flink.md
  docs/docs/zh/guide/task/flink.md
  docs/img/tasks/demo/flink_sql_test.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/ProgramType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTaskTest.java
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-flink.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-main-jar.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-flink.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: first time contributor, UI, backend

#9959 [chore] Combine version 206 and 210 sql upgrade to 300
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/postgresql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/postgresql/dolphinscheduler_dml.sql
Labels: Chore

#9962 [Fix][UI][V1.0.0-Beta] Fix the problem of packing failure.
  dolphinscheduler-ui/src/components/form/fields/radio.ts
  dolphinscheduler-ui/src/components/form/types.ts
Labels: bug, UI

#9966 [Cherry-Pick][Fix][UI][V1.0.0-Beta] Fix the problem of packing failure.
  dolphinscheduler-ui/src/components/form/types.ts
Labels: bug, UI

#9967 [Docs] Upgrade license.
  dolphinscheduler-dist/release-docs/LICENSE
Labels: document

#9968 [Docs] Upgrade license.
  dolphinscheduler-dist/release-docs/LICENSE
Labels: document

#9970 [Docs] Update README.
  README.md
  README_zh_CN.md
  images/en_US/dag.png
  images/en_US/data-source.png
  images/en_US/home.png
  images/en_US/master.png
  images/en_US/workflow-tree.png
  images/zh_CN/dag.png
  images/zh_CN/data-source.png
  images/zh_CN/home.png
  images/zh_CN/master.png
  images/zh_CN/workflow-tree.png
Labels: document

#9945 [Feature][Document] Add example and notice about task type Conditions
  docs/docs/en/guide/task/conditions.md
  docs/docs/zh/guide/task/conditions.md
  docs/img/condition_dag_en.png
  docs/img/condition_task_en.png
  docs/img/condition_task_zh.png
  docs/img/tasks/demo/condition_task01.png
  docs/img/tasks/demo/condition_task02.png
  docs/img/tasks/demo/condition_task03.png
Labels: document

#9881 [Feature-8252][doc] K8s and namespace manager docs and web page update
  docs/docs/en/guide/security.md
  docs/docs/zh/guide/security.md
  docs/img/new_ui/dev/security/create-namespace.png
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceMapperTest.java
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/security/k8s-namespace-manage/components/k8s-namespace-modal.tsx
  dolphinscheduler-ui/src/views/security/k8s-namespace-manage/components/use-modal.ts
  dolphinscheduler-ui/src/views/security/k8s-namespace-manage/use-table.ts
Labels: UI, backend, document

#9998 [Docs] Fix docker link.
  README.md
  README_zh_CN.md
Labels: document

#10004 [ci] Dead link check all markdown file
  .github/workflows/docs.yml
  deploy/README.md
Labels: CI&CD, Chore

#10008 [Fix][UI] Fix the task name validator error.
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: bug, UI

#10007 [Fix][UI] Support only one file upload on the file manage page.
  dolphinscheduler-ui/src/views/resource/file/upload/index.tsx
  dolphinscheduler-ui/src/views/resource/file/upload/use-form.ts
Labels: bug, UI

#9872 [Feature][Task Plugin] Add jupyter task plugin
  docs/configs/docsdev.js
  docs/docs/en/guide/task/jupyter.md
  docs/docs/zh/guide/task/jupyter.md
  docs/img/tasks/demo/jupyter.png
  docs/img/tasks/icons/jupyter.png
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/test/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTaskTest.java
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/jupyter.png
  dolphinscheduler-ui/public/images/task-icons/jupyter_hover.png
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-jupyter.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-jupyter.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
Labels: new feature, miss:docs, miss:ui

#10030 Monitoring: Added disk available capacity monitoring
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/HeartBeat.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/os/OSUtilsTest.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/HeartBeatTest.java
  dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/master.vue
  dolphinscheduler-ui/src/js/conf/home/pages/monitor/pages/servers/worker.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: first time contributor, UI, backend

#10014 [fix-9991][worker]fix statement is closed before resultSet.getMetaData()
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
Labels: first time contributor, backend

#9974 [Fix] [DataQuality] Fix task commnd null bug
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/DataQualityTask.java
Labels: don't merge

#9995 [Fix-9990] fix development-environment-setup.md's outdate description
  docs/docs/en/development/development-environment-setup.md
  docs/docs/zh/development/development-environment-setup.md
Labels: first time contributor, document

#10013 [feat] Add batch rerun and stop for process instance
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/resources/i18n/messages.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_en_US.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_zh_CN.properties
Labels: enhancement, backend

#10042 [Fix-10039] Flink run command when perfecting Python jobs
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkTask.java
Labels: bug, backend

#10026 [Bug] fix run on docker and k8s
  deploy/docker/docker-compose.yml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/job-dolphinscheduler-schema-initializer.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  docs/docs/en/guide/start/docker.md
  docs/docs/zh/guide/start/docker.md
  dolphinscheduler-tools/src/main/bin/upgrade-schema.sh
  dolphinscheduler-tools/src/main/docker/Dockerfile
Labels: bug, backend

#10032 [python] Fix pre submit check error when local params already in task lists
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/switch.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_process_definition.py
Labels: backend, Python

#10054 [Fix][UI]Modify error message
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/projects/workflow/instance/components/table-action.tsx
Labels: new feature, UI

#10056 [Fix][UI] Fix in the Chinese state, there is a problem with the multi
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-jupyter.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-rules.ts
  dolphinscheduler-ui/src/views/security/tenant-manage/components/use-modalData.ts
Labels: bug, UI

#10060 Revert "[Fix][UI] Fix in the Chinese state, there is a problem with the multi"
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-jupyter.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-rules.ts
  dolphinscheduler-ui/src/views/security/tenant-manage/components/use-modalData.ts
Labels: bug, UI

#10068 [Feature] [E2e] Fix flakey filemanage e2e test
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/FileManagePage.java
Labels: CI&CD

#10066 [Fix][UI] Fix in the Chinese state, there is a problem with the multi-language support of the form.
  dolphinscheduler-ui/src/views/security/tenant-manage/components/use-modalData.ts
Labels: bug, UI

#10072 [Cherry Pick][Fix][UI] Fix in the Chinese state, there is a problem with the multi…
  dolphinscheduler-ui/src/views/security/tenant-manage/components/use-modalData.ts
Labels: bug, UI

#10070 [Fix][UI] Fix bug where username is empty in file manage
  dolphinscheduler-ui/src/service/modules/resources/types.ts
  dolphinscheduler-ui/src/views/resource/file/use-file.ts
Labels: bug, UI

#10077 [Fix-10049] Conditions Task branch flow failed
  docs/docs/en/guide/task/conditions.md
  docs/docs/zh/guide/task/conditions.md
  docs/img/tasks/demo/condition_task04.png
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/ConditionTaskProcessor.java
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-conditions.ts
Labels: bug, UI, backend, document

#10086 [Feat][UI] Add resource username for function and resource manage
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/resource/udf/function/use-table.ts
  dolphinscheduler-ui/src/views/resource/udf/resource/use-table.ts
Labels: new feature, UI

#10062 [Bug][Document] Fix task group management document link error
  docs/configs/docsdev.js
Labels: bug, document

#9425 [Feature][plugin] Add k8s task in task plugin
  docs/configs/docsdev.js
  docs/docs/en/guide/task/kubernetes.md
  docs/docs/zh/guide/task/kubernetes.md
  docs/img/tasks/demo/kubernetes-task-en.png
  docs/img/tasks/icons/kubernetes.png
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/builder/TaskExecutionContextBuilder.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/BaseTaskProcessor.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/K8sTaskExecutionContext.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskExecutionContext.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskMainParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/K8sUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskExecutorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sParametersTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskTest.java
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/k8s.png
  dolphinscheduler-ui/public/images/task-icons/k8s_hover.png
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/service/modules/k8s-namespace/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-k8s.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-namespace.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-k8s.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
Labels: first time contributor

#10098 [Fix-10095][UI] fulfill missing fields in DataQuality
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: bug, UI

#10094 [fix] Enhance name pre checker in resource center
  docs/docs/en/guide/resource/file-manage.md
  docs/docs/zh/guide/resource/file-manage.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/FileUtilsTest.java
Labels: bug, backend

#10105 [Build][UI] Solve vite config throws terser warning.
  dolphinscheduler-ui/vite.config.ts
Labels: improvement

#10036 [Feature][Task Plugin] Add mlflow task plugin for MLops scenario.
  docs/configs/docsdev.js
  docs/docs/en/guide/task/mlflow.md
  docs/docs/zh/guide/task/mlflow.md
  docs/img/tasks/demo/mlflow-automl.png
  docs/img/tasks/demo/mlflow-basic-algorithm.png
  docs/img/tasks/demo/mlflow-conda-env.png
  docs/img/tasks/demo/mlflow-server.png
  docs/img/tasks/demo/mlflow-set-conda-env.png
  docs/img/tasks/icons/mlflow.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/resources/run_mlflow_automl_project.sh
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/resources/run_mlflow_basic_algorithm_project.sh
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/test/java/org/apache/dolphinler/plugin/task/mlflow/MlflowTaskTest.java
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/mlflow.png
  dolphinscheduler-ui/public/images/task-icons/mlflow_hover.png
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-mlflow.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-mlflow.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
Labels: new feature, UI, backend

#10100 [Bug] [Document] Fix the open-api documentation request error
  docs/docs/en/guide/open-api.md
  docs/docs/zh/guide/open-api.md
  docs/img/api/create_project1.png
  docs/img/api/create_project2.png
  docs/img/api/create_project3.png
  docs/img/api/create_source1.png
  docs/img/api/create_source2.png
  docs/img/new_ui/dev/open-api/api_doc.png
  docs/img/new_ui/dev/open-api/api_source01.png
  docs/img/new_ui/dev/open-api/api_source02.png
  docs/img/new_ui/dev/open-api/api_test.png
  docs/img/new_ui/dev/open-api/create_project01.png
  docs/img/new_ui/dev/open-api/create_project02.png
  docs/img/new_ui/dev/open-api/create_project03.png
  docs/img/new_ui/dev/open-api/token_expiration.png
Labels: bug, document

#10124 [doc] change document structure
  docs/configs/docsdev.js
  docs/configs/site.js
Labels: Chore, document

#10122 [doc] Remove flink call docs
  docs/configs/docsdev.js
  docs/docs/en/guide/flink-call.md
  docs/docs/zh/guide/flink-call.md
  docs/img/api-documentation-en.png
  docs/img/api-documentation.png
  docs/img/api/create_queue.png
  docs/img/api/create_tenant.png
  docs/img/api/create_user.png
  docs/img/api/create_workflow1.png
  docs/img/api/create_workflow2.png
  docs/img/api/create_workflow3.png
  docs/img/api/create_workflow4.png
  docs/img/api/execution_result.png
  docs/img/api/log.png
  docs/img/api/upload_resource.png
  docs/img/api/user_authorization.png
  docs/img/api/user_login.png
  docs/img/create-token-en1.png
  docs/img/create-token.png
  docs/img/test-api.png
  docs/img/token-management-en.png
  docs/img/token-management.png
Labels: Chore, document

#10125 [Feature] [CI] Add alert server cluster test
  .github/workflows/cluster-test/mysql/running_test.sh
  .github/workflows/cluster-test/postgresql/running_test.sh
Labels: CI&CD

#10134 [python] Change distribute name avoid confusion with main pkg
  dolphinscheduler-python/pom.xml
Labels: Python

#10129 [Fix][UI] Add the task status of pending.
  dolphinscheduler-ui/src/common/common.ts
  dolphinscheduler-ui/src/common/types.ts
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
Labels: bug, UI

#10155 [Cherry-Pick][Build][UI] Solve vite config throws terser warning.
  dolphinscheduler-ui/vite.config.ts
Labels: improvement

#10158 [Fix][UI] Limit task group resource capacity to only positive integers.
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/resource/task-group/option/components/form-modal.tsx
  dolphinscheduler-ui/src/views/resource/task-group/option/use-form.ts
Labels: bug, UI

#10162 [Cherry-Pick][Fix][UI] Limit task group resource capacity to only positive integers.
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/resource/task-group/option/components/form-modal.tsx
  dolphinscheduler-ui/src/views/resource/task-group/option/use-form.ts
Labels: bug, UI

#10130 [doc]update editorial workflow content and images
  docs/docs/en/guide/project/workflow-instance.md
  docs/docs/zh/guide/project/workflow-instance.md
  docs/img/editDag-en.png
  docs/img/editDag.png
  docs/img/new_ui/dev/project/project-overview.png
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
Labels: document

#10161 [improvement][doc]update website docs link
  docs/configs/site.js
Labels: bug, discussion, UI

#10169 [Fix][UI] Fix the problem that the failure strategy field in the time management form is multilingual.
  dolphinscheduler-ui/src/views/projects/workflow/definition/timing/use-table.ts
Labels: bug, UI

#10173 [Cherry-Pick][Fix][UI] Fix the problem that the failure strategy field in the time management form is multilingual.
  dolphinscheduler-ui/src/views/projects/workflow/definition/timing/use-table.ts
Labels: bug, UI

#10150 [Feature][MLops] Support MLflow Models to deploy model service (MLflow models serve and Docker)
  docs/docs/en/guide/task/mlflow.md
  docs/docs/zh/guide/task/mlflow.md
  docs/img/tasks/demo/mlflow-automl.png
  docs/img/tasks/demo/mlflow-basic-algorithm.png
  docs/img/tasks/demo/mlflow-models-docker.png
  docs/img/tasks/demo/mlflow-models-mlflow.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/test/java/org/apache/dolphinler/plugin/task/mlflow/MlflowTaskTest.java
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-mlflow-models.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-mlflow-projects.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-mlflow.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-mlflow.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, backend, document

#10099 [refactor][perf] cache pattern
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ParameterUtils.java
Labels: first time contributor, improvement, backend

#10063 [Fix-10057][api] api parameter name misspelling
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
Labels: first time contributor, backend

#10176 [Cherry-Pick][Fix][UI]Change the HTTP or HTTPS regular expression (#10166)
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-http.ts
Labels: bug, UI

#10178 [Fix][UI] Add seatunnel icon
  dolphinscheduler-ui/public/images/task-icons/seatunnel.png
  dolphinscheduler-ui/public/images/task-icons/seatunnel_hover.png
Labels: bug, UI

#10183 [Fix][UI] Fix spcial week init bug for timing
  dolphinscheduler-ui/src/components/crontab/modules/day.tsx
Labels: bug, UI

#10177 [Fix-10076] queryUserByToken use server timezone
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/interceptor/LoginHandlerInterceptor.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/interceptor/LoginHandlerInterceptorTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/UserMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UserMapperTest.java
Labels: bug, first time contributor, backend

#10045 [Docment][Feature] Refactor global parameter docment
  docs/docs/en/guide/parameter/global.md
  docs/docs/zh/guide/parameter/global.md
  docs/img/local_parameter.png
  docs/img/local_parameter_en.png
  docs/img/new_ui/dev/parameter/global_parameter01.png
  docs/img/new_ui/dev/parameter/global_parameter02.png
  docs/img/new_ui/dev/parameter/global_parameter03.png
  docs/img/supplement_global_parameter.png
  docs/img/supplement_global_parameter_en.png
Labels: document

#10107 [Bug][Doc]Update project directory structure in docs
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
Labels: document

#10187 [Fix][UI] Add seatunnel icon
  dolphinscheduler-ui/public/images/task-icons/seatunnel.png
  dolphinscheduler-ui/public/images/task-icons/seatunnel_hover.png
Labels: bug, UI

#10188 [Doc] Add complie supporting system
  docs/docs/en/development/development-environment-setup.md
  docs/docs/zh/development/development-environment-setup.md
Labels: document

#10202 [Fix][UI] Fix data-quality component multi-language support.
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-rules.ts
Labels: bug, UI

#10203 [doc] Update delete workflow description
  docs/docs/en/guide/project/workflow-definition.md
  docs/docs/zh/guide/project/workflow-definition.md
Labels: document

#10201 [Fix-10199] [Workflow/Workflow Definition] After deleting messages in batches, the error message is repeated
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
Labels: bug, backend

#10175 [Feature][MLops] Add MLflow Projects (custom project) component
  docs/docs/en/guide/task/mlflow.md
  docs/docs/zh/guide/task/mlflow.md
  docs/img/tasks/demo/mlflow-custom-project-template.png
  docs/img/tasks/demo/mlflow-custom-project.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/test/java/org/apache/dolphinler/plugin/task/mlflow/MlflowTaskTest.java
  dolphinscheduler-ui/src/locales/modules/en_US.ts
  dolphinscheduler-ui/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-mlflow-projects.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-mlflow.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: new feature, UI, backend, document

#10209 [Bug][Deploy]Fix worker-server path in script scp-hosts.sh
  script/scp-hosts.sh
Labels: bug, backend

#10215 [fix-10214] Delete online workflows in batches, prompt information is accurate
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
Labels: bug, backend

#10151 [python] Fix process definition attr release state not work
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-python/pydolphinscheduler/docs/source/config.rst
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/constants.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/configuration.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/default_config.yaml
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_process_definition.py
  dolphinscheduler-python/pydolphinscheduler/tests/utils/test_yaml_parser.py
Labels: bug, Python

#10165 [Fix-10159][UI] add assignment of totalPage
  dolphinscheduler-ui/src/views/data-quality/rule/use-table.ts
  dolphinscheduler-ui/src/views/data-quality/task-result/use-table.ts
  dolphinscheduler-ui/src/views/monitor/statistics/audit-log/use-table.ts
Labels: bug, UI

#10218 [doc] Update task DataX document
  docs/docs/en/guide/task/datax.md
  docs/docs/zh/guide/task/datax.md
  docs/img/datax_edit.png
Labels: document

#10128 [Fix-10103][k8s]Fix k8s Change DataSource Error
  dolphinscheduler-tools/src/main/bin/upgrade-schema.sh
  dolphinscheduler-tools/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: bug, k8s

#10119 [Docment][Feature] Refactor local parameter docment
  docs/docs/en/guide/parameter/local.md
  docs/docs/zh/guide/parameter/local.md
  docs/img/global_parameter_en.png
  docs/img/new_ui/dev/parameter/local_parameter01.png
  docs/img/new_ui/dev/parameter/local_parameter02.png
  docs/img/supplement_local_parameter.png
  docs/img/supplement_local_parameter_en.png
Labels: document

#10224 [fix-10207] When the registered alarm plugin is empty, the error message is not clear
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
Labels: improvement, backend

#10229 [Fix][UI] Fix issue with treemap depth in workflow relationships.
  dolphinscheduler-ui/src/components/chart/modules/Tree.tsx
Labels: bug, UI

#10228 [Fix-10226] Change Docker Doc && Delete config SPRING_DATASOURCE_DRIVER_CLASS_NAME
  .github/workflows/cluster-test/mysql/dolphinscheduler_env.sh
  .github/workflows/cluster-test/postgresql/dolphinscheduler_env.sh
  docs/docs/en/architecture/configuration.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/guide/upgrade.md
  docs/docs/zh/architecture/configuration.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/guide/upgrade.md
  script/env/dolphinscheduler_env.sh
Labels: backend, document

#10220 [Improvement]Change Mysql Driver
  docs/docs/en/development/development-environment-setup.md
  docs/docs/zh/development/development-environment-setup.md
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/resources/application.yaml
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-data-quality/src/test/java/org/apache/dolphinscheduler/data/quality/configuration/ConfigurationParserTest.java
  dolphinscheduler-data-quality/src/test/java/org/apache/dolphinscheduler/data/quality/flow/reader/ReaderFactoryTest.java
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-tools/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: improvement, backend

#10237 [fix] Task group queue query all list error
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskGroupController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TaskGroupQueueService.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.xml
Labels: bug, backend

#9924 [Fix#9923] The alarm instance management interface is always in the loading state
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/use-form.ts
Labels: bug, UI

#10243 [Fix][UI] Set task group name empty of default value
  dolphinscheduler-ui/src/views/resource/task-group/queue/index.tsx
  dolphinscheduler-ui/src/views/resource/task-group/queue/use-table.ts
Labels: bug, UI

#10241 [fix] File overwrite when specific value set to installPath
  script/install.sh
  script/scp-hosts.sh
Labels: Chore

#10249 [fix] Deploy scp-hosts use fullpath avoid dangling
  script/scp-hosts.sh
Labels: bug, Chore, priority:high

#10244 [Bug] init docker compose DATABASE env
  deploy/docker/.env
  dolphinscheduler-tools/src/main/bin/upgrade-schema.sh
Labels: docker

#10074 [doc] Correct all setup documents
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/en/guide/start/quick-start.md
  docs/docs/en/guide/upgrade.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/standalone.md
  docs/docs/zh/guide/start/quick-start.md
  docs/docs/zh/guide/upgrade.md
Labels: document

#10185 [Fix-10181] Fix the logic of judging that the tenant does not exist
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/os/OSUtilsTest.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: bug, discussion, first time contributor, backend, priority:high

#10268 [Fix][UI] Fix status statistics card height is inconsistent.
  dolphinscheduler-ui/src/views/home/components/state-card.tsx
Labels: bug, UI

#10260 [Fix] Fix the timeout alarm button is invalid #10259
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-conditions.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-datax.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-emr.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-flink.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-http.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-jupyter.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-k8s.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-mlflow.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-mr.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-pigeon.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-procedure.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-python.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sea-tunnel.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-spark.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sql.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sqoop.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sub-process.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-switch.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-zeppelin.ts
Labels: bug, first time contributor, UI

#10261 [Feature][Permission] Project management module authority control refactoring, authority abstract interface setting.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/BaseService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/DataAnalysisControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/AuthorizationType.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProjectMapperTest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/ProjectE2ETest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/permission/ResourcePermissionCheckService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/permission/ResourcePermissionCheckServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/permission/ResourcePermissionCheckServiceTest.java
Labels: bug, backend

#10278 [Fix] Fix the line.separator problem for alert-plugin' test case #10277
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/template/DefaultHTMLTemplateTest.java
Labels: backend, test

#10258 [fix] Fix the SERIAL_DISCARD execution_type not working
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: bug, first time contributor, backend

#10227 [Docment][Feature] Refactor context parameter docment
  docs/docs/en/guide/parameter/context.md
  docs/docs/zh/guide/parameter/context.md
  docs/img/globalParam/image-20210723101242216.png
  docs/img/globalParam/image-20210723102522383.png
  docs/img/globalParam/image-20210723104957031.png
  docs/img/globalParam/image-20210723105026924.png
  docs/img/globalParam/image-20210723105131381.png
  docs/img/globalParam/image-20210723105255850.png
  docs/img/global_parameter.png
  docs/img/new_ui/dev/parameter/context_log01.png
  docs/img/new_ui/dev/parameter/context_log02.png
  docs/img/new_ui/dev/parameter/context_log03.png
  docs/img/new_ui/dev/parameter/context_parameter01.png
  docs/img/new_ui/dev/parameter/context_parameter02.png
  docs/img/new_ui/dev/parameter/context_parameter03.png
  docs/img/new_ui/dev/parameter/context_parameter04.png
Labels: document

#10264 [Feature-9385][docs] Added Local File Resource Configuration Guide to the document
  docs/docs/en/guide/resource/configuration.md
  docs/docs/zh/guide/resource/configuration.md
Labels: first time contributor, improvement, document

#10286 [Fix][UI] Add mapping_columns filed for the data_quality ruleInputPar…
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-rules.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: bug, UI

#10246 [improve][doc] Update the development environment to build the software version
  docs/docs/en/development/development-environment-setup.md
  docs/docs/zh/development/development-environment-setup.md
Labels: document

#10292 [Doc] Fix api standard error
  docs/docs/en/development/api-standard.md
  docs/docs/zh/development/api-standard.md
Labels: document

#10298 [Fix][UI] Display the result page when the DB page has no data.
  dolphinscheduler-ui/src/locales/en_US/monitor.ts
  dolphinscheduler-ui/src/locales/zh_CN/monitor.ts
  dolphinscheduler-ui/src/views/monitor/servers/db/index.tsx
Labels: bug, UI

#10299 [chore] update by release version
  .github/ISSUE_TEMPLATE/bug-report.yml
  docs/configs/site.js
Labels: Chore

#10198 [Feature][Task-Plugin]Add OpenMLDB task plugin
  docs/configs/docsdev.js
  docs/docs/en/guide/task/openmldb.md
  docs/docs/zh/guide/task/openmldb.md
  docs/img/tasks/demo/openmldb-feature-extraction.png
  docs/img/tasks/demo/openmldb-load-data.png
  docs/img/tasks/icons/openmldb.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/test/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/openmldb.png
  dolphinscheduler-ui/public/images/task-icons/openmldb_hover.png
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-openmldb.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-openmldb.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
  pom.xml
Labels: new feature, UI, backend

#10269 [Feature][Task Plugin] Add support for dynamic form in zeppelin task
  docs/docs/en/guide/task/zeppelin.md
  docs/docs/zh/guide/task/zeppelin.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/test/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-zeppelin.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
Labels: UI, improvement, backend

#10296 [hotfix] Fix database initialize late in standalone.
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.java
Labels: improvement, backend

#10301 [Feature-10290] [API] Refactor org.apache.dolphinscheduler.api.controller.AccessTokenController#createToken api
  .gitignore
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/AppConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/SwaggerConfig.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AccessTokenController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AccessTokenV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/CreateTokenRequest.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/CreateTokenResponse.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/AccessTokenService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AccessTokenServiceImpl.java
  dolphinscheduler-api/src/main/resources/swagger.properties
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/AccessTokenControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/AccessTokenV2ControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AccessTokenServiceTest.java
Labels: improvement, backend

#10314 [Style][UI] Format code.
  dolphinscheduler-ui/src/locales/en_US/crontab.ts
  dolphinscheduler-ui/src/locales/en_US/data-quality.ts
  dolphinscheduler-ui/src/locales/en_US/datasource.ts
  dolphinscheduler-ui/src/locales/en_US/home.ts
  dolphinscheduler-ui/src/locales/en_US/login.ts
  dolphinscheduler-ui/src/locales/en_US/menu.ts
  dolphinscheduler-ui/src/locales/en_US/modal.ts
  dolphinscheduler-ui/src/locales/en_US/monitor.ts
  dolphinscheduler-ui/src/locales/en_US/password.ts
  dolphinscheduler-ui/src/locales/en_US/profile.ts
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/en_US/resource.ts
  dolphinscheduler-ui/src/locales/en_US/security.ts
  dolphinscheduler-ui/src/locales/en_US/theme.ts
  dolphinscheduler-ui/src/locales/en_US/user-dropdown.ts
  dolphinscheduler-ui/src/locales/zh_CN/crontab.ts
  dolphinscheduler-ui/src/locales/zh_CN/data-quality.ts
  dolphinscheduler-ui/src/locales/zh_CN/datasource.ts
  dolphinscheduler-ui/src/locales/zh_CN/home.ts
  dolphinscheduler-ui/src/locales/zh_CN/login.ts
  dolphinscheduler-ui/src/locales/zh_CN/menu.ts
  dolphinscheduler-ui/src/locales/zh_CN/modal.ts
  dolphinscheduler-ui/src/locales/zh_CN/monitor.ts
  dolphinscheduler-ui/src/locales/zh_CN/password.ts
  dolphinscheduler-ui/src/locales/zh_CN/profile.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/resource.ts
  dolphinscheduler-ui/src/locales/zh_CN/security.ts
  dolphinscheduler-ui/src/locales/zh_CN/theme.ts
  dolphinscheduler-ui/src/locales/zh_CN/user-dropdown.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-http.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-jupyter.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-openmldb.ts
  dolphinscheduler-ui/src/views/resource/task-group/option/components/form-modal.tsx
Labels: UI
