Repository apache/dolphinscheduler, pull requests merged in 2022-04, with the labels that each got.

#9176 [dolphinscheduler-api][task-group-controller] Corrected notes for create, update and queryTaskGroupByStatus
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskGroupController.java
Labels: first time contributor

#9309 [Docs][UI Next][V1.0.0-Alpha] Delete E2E docs.
  dolphinscheduler-ui-next/README.md
  dolphinscheduler-ui-next/docs/e2e/data-source.md
  dolphinscheduler-ui-next/docs/e2e/login.md
  dolphinscheduler-ui-next/docs/e2e/navbar.md
  dolphinscheduler-ui-next/docs/e2e/project.md
  dolphinscheduler-ui-next/docs/e2e/resource.md
  dolphinscheduler-ui-next/docs/e2e/security.md
Labels: document

#9314 [Fix][UI-Next][V1.0.0-Alpha] Fix the notification strategy options display error in the set parameters before timing modal.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/timing-modal.tsx
Labels: UI

#9333 [Fix][UI Next][V1.0.0-Alpha] Fix the two hover prompts appear.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/timing/use-table.ts
Labels: bug, UI

#9334 [Fix][UI Next][V1.0.0-Alpha] Fix the time columns cannot be broken in the cron manage table.
  dolphinscheduler-ui-next/src/utils/column-width-config.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/timing/use-table.ts
Labels: bug, UI

#9335 [Fix-9088] [Doc] There are some version errors in the 2.0.1-release
  docs/docs/en/faq.md
  docs/docs/zh/faq.md
Labels: bug, document

#9341 [Feature]Modifying site Configurations
  docs/configs/site.js
Labels: UI, document

#9336 [Improvement-9338][API] show more create datasource exception message
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
Labels: first time contributor

#9325 [Improve][CI] improve ci checking
  .github/workflows/backend.yml
  .github/workflows/docs.yml
  .github/workflows/e2e.yml
  .github/workflows/unit-test.yml
Labels: CI&CD

#9351 [Fix] [UI-Next][V1.0.0-Alpha] Rename node to task in the task creation modal
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
Labels: bug, UI

#9350 [Fix] [UI-Next] Rename process to workflow
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-process-name.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/queue/index.tsx
  dolphinscheduler-ui-next/src/views/resource/task-group/queue/use-table.ts
Labels: bug, UI

#9363 [Fix][UI Next][V1.0.0-Alpha]Add zh for dag execution policy
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
Labels: bug, UI

#9375 [task-spark][docs] Corrected notice section
  docs/docs/en/guide/task/spark.md
Labels: document

#9372 [python] Migrate pythonGatewayServer into api server
  deploy/docker/docker-compose.yml
  deploy/docker/docker-stack.yml
  deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl
  docs/docs/en/faq.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/en/guide/upgrade.md
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/main/docker/Dockerfile
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/PythonGatewayConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-dist/src/main/assembly/dolphinscheduler-bin.xml
  dolphinscheduler-python/pom.xml
  dolphinscheduler-python/pydolphinscheduler/UPDATING.md
  dolphinscheduler-python/pydolphinscheduler/docs/source/start.rst
  dolphinscheduler-python/pydolphinscheduler/docs/source/tutorial.rst
  dolphinscheduler-python/pydolphinscheduler/tests/integration/__init__.py
  dolphinscheduler-python/pydolphinscheduler/tests/integration/test_submit_examples.py
  dolphinscheduler-python/src/main/assembly/dolphinscheduler-python-gateway-server.xml
  dolphinscheduler-python/src/main/bin/start.sh
  dolphinscheduler-python/src/main/docker/Dockerfile
  dolphinscheduler-python/src/main/resources/application.yaml
  dolphinscheduler-python/src/main/resources/logback-spring.xml
  dolphinscheduler-standalone-server/src/main/assembly/dolphinscheduler-standalone-server.xml
  dolphinscheduler-standalone-server/src/main/dist-bin/start.sh
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  script/dolphinscheduler-daemon.sh
  script/env/install_env.sh
  script/scp-hosts.sh
  script/start-all.sh
  script/status-all.sh
  script/stop-all.sh
Labels: development, Chore, Python

#9381 [Fix][UI Next][V1.0.0-Alpha] Add light color theme to echarts.
  dolphinscheduler-ui-next/src/components/chart/index.ts
Labels: bug, UI, priority:low

#9392 [Fix][UI Next][V1.0.0-Alpha] Fix the task instance forced success button multi-language support error.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI

#9395 [cherry-pick][Fix][UI Next][V1.0.0-Alpha] Fix the task instance forced success button multi-language support error.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
Labels: bug, UI

#9388 Add new code owner of docs module
  .github/CODEOWNERS
Labels: Chore, document

#9397 [cherry-pick][Fix][UI Next][V1.0.0-Alpha]Add zh for dag execution policy
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
Labels: bug, UI

#9393 [Feature][CI]Enable CI to remove unexpected files in /docs/img dir(#9321)
  docs/img_utils.py
Labels: CI&CD, document

#9403 [Bug][UI Next]Modify the display state logic of save buttons under workflow definition
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
Labels: bug, UI

#9402 [doc] Remove observability
  docs/configs/docsdev.js
  docs/docs/en/guide/installation/skywalking-agent.md
  docs/docs/zh/guide/installation/skywalking-agent.md
  docs/img/skywalking/import-dashboard-1.jpg
Labels: bug, Chore, document

#9411 [cherry-pick][UI Next] Modify the display state logic of save buttons under wo…
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
Labels: UI, Chore

#9431 [UI] Migrate NPM to PNPM in CI builds
  .github/workflows/frontend.yml
  dolphinscheduler-ui-next/pom.xml
  pom.xml
Labels: UI

#9427 [doc] Add some dev missing doc
  docs/configs/docsdev.js
  docs/docs/en/guide/howto/general-setting.md
  docs/docs/en/guide/monitor.md
  docs/docs/en/guide/project/task-definition.md
  docs/docs/zh/guide/howto/general-setting.md
  docs/docs/zh/guide/monitor.md
  docs/docs/zh/guide/project/task-definition.md
  docs/img/new_ui/dev/monitor/audit-log.jpg
  docs/img/new_ui/dev/project/task-definition.jpg
Labels: document

#9444 [python] Recover python release properties
  dolphinscheduler-dist/pom.xml
  dolphinscheduler-python/pom.xml
  dolphinscheduler-standalone-server/pom.xml
Labels: development, Chore

#9421 [Fix-9420][doc] fix url wrong in zh doc
  docs/docs/zh/guide/start/docker.md
Labels: first time contributor, document

#9436 [CI] Improve CI
  .github/workflows/backend.yml
  .github/workflows/e2e.yml
  .github/workflows/unit-test.yml
Labels: CI&CD

#9455 [Fix][UI][2.0.5] Add LIST type to the custom parameter types of task node.
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/commcon.js
Labels: bug, UI

#9457 [doc] Migrate develop docs from website
  docs/docs/en/development/api-standard.md
  docs/docs/en/development/architecture-design.md
  docs/docs/en/development/backend/mechanism/global-parameter.md
  docs/docs/en/development/backend/mechanism/overview.md
  docs/docs/en/development/backend/mechanism/task/switch.md
  docs/docs/en/development/backend/spi/alert.md
  docs/docs/en/development/backend/spi/datasource.md
  docs/docs/en/development/backend/spi/registry.md
  docs/docs/en/development/backend/spi/task.md
  docs/docs/en/development/development-environment-setup.md
  docs/docs/en/development/e2e-test.md
  docs/docs/en/development/frontend-development.md
  docs/docs/en/development/have-questions.md
  docs/docs/zh/development/api-standard.md
  docs/docs/zh/development/architecture-design.md
  docs/docs/zh/development/backend/mechanism/global-parameter.md
  docs/docs/zh/development/backend/mechanism/overview.md
  docs/docs/zh/development/backend/mechanism/task/switch.md
  docs/docs/zh/development/backend/spi/alert.md
  docs/docs/zh/development/backend/spi/datasource.md
  docs/docs/zh/development/backend/spi/registry.md
  docs/docs/zh/development/backend/spi/task.md
  docs/docs/zh/development/development-environment-setup.md
  docs/docs/zh/development/e2e-test.md
  docs/docs/zh/development/frontend-development.md
  docs/docs/zh/development/have-questions.md
  docs/img/architecture-design/dag_examples.png
  docs/img/architecture-design/distributed_lock.png
  docs/img/architecture-design/distributed_lock_procss.png
  docs/img/architecture-design/fault-tolerant.png
  docs/img/architecture-design/fault-tolerant_master.png
  docs/img/architecture-design/fault-tolerant_worker.png
  docs/img/architecture-design/grpc.png
  docs/img/architecture-design/lack_thread.png
  docs/img/architecture-design/process_priority.png
  docs/img/architecture-design/task_priority.png
  docs/img/architecture.jpg
  docs/img/e2e-test/Dlocal.png
  docs/img/e2e-test/E2E_Cases.png
  docs/img/e2e-test/MP4.png
  docs/img/e2e-test/SecurityPage.png
  docs/img/e2e-test/timeout.png
  docs/img_utils.py
Labels: Chore, document

#9454 [Bug][UI Next]Fix global variable validation condition for save button in workflow definition.
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
Labels: bug, UI

#9468 [Fix][Next-UI] Add LIST type to the custom parameter types of task node.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-custom-params.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-emr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-procedure.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
Labels: bug, UI

#9434 [Feature][Doc]Switch shell task instruction screenshots to latest (#9432)
  docs/img/tasks/demo/shell.jpg
  docs/img/tasks/demo/shell_custom_param.jpg
Labels: document

#9481 [Fix][Next UI] Fix the branch flow options of the switch task is not available.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-switch.ts
Labels: bug, UI

#9371 [Fix-9174] [Alert] Fix deduplication of alarm information
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Alert.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertMapper.xml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/AlertDaoTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/AlertMapperTest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java
Labels: first time contributor

#9494 [Fix][Next-UI] Fix the jumping problem of close button on dag page.
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
Labels: bug, UI

#9511 [Feature][UI Next][V1.0.0-Beta] Change the css style usage of the blue number flopper in the alarm center to css variables.
  dolphinscheduler-ui-next/src/views/monitor/servers/db/index.module.scss
  dolphinscheduler-ui-next/src/views/monitor/servers/master/index.module.scss
  dolphinscheduler-ui-next/src/views/monitor/servers/worker/index.module.scss
  dolphinscheduler-ui-next/src/views/monitor/statistics/statistics/index.module.scss
Labels: new feature, UI

#9513 [Improvement][Master] Fix typo for MasterTaskExecThreadTest
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecThreadTest.java
Labels: first time contributor

#9517 [python] Support read config in env variable
  dolphinscheduler-python/pydolphinscheduler/UPDATING.md
  dolphinscheduler-python/pydolphinscheduler/docs/source/config.rst
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/cli/commands.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/configuration.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/utils/yaml_parser.py
  dolphinscheduler-python/pydolphinscheduler/tests/cli/test_config.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_configuration.py
  dolphinscheduler-python/pydolphinscheduler/tests/testing/constants.py
  dolphinscheduler-python/pydolphinscheduler/tests/utils/test_yaml_parser.py
Labels: new feature, Python

#9515 [Fix-9516] [Statistics] Statistics Manager shows data should belongs to current user
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/CommandMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapperTest.java
Labels: first time contributor

#9518 [Fix][UI Next][V1.0.0-Beta] Added access to the child node function
  dolphinscheduler-ui-next/src/components/modal/index.tsx
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/process-instances/index.ts
  dolphinscheduler-ui-next/src/service/modules/process-instances/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
Labels: bug, UI

#9521 [Feature][UI Next][V1.0.0-Beta] Monaco Editor supports theme switching function.
  dolphinscheduler-ui-next/src/components/monaco-editor/index.tsx
Labels: new feature, UI

#9526 [Fix][UI Next][V1.0.0-Beta] Fix the resource Center dark mode display exception when viewing the file details.
  dolphinscheduler-ui-next/src/components/modal/index.tsx
  dolphinscheduler-ui-next/src/components/monaco-editor/index.tsx
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui-next/src/views/resource/file/edit/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/index.module.scss
Labels: bug, UI

#9527 [Fix-9525] [Worker] Environment did not work as expected
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/test/java/org/apache/dolphinscheduler/plugin/task/python/PythonTaskTest.java
Labels: bug, backend

#9327 [Feature][Task-Plugin]Add zeppelin task-plugin to support Apache Zeppelin (#9201)
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-commons-text.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-httpasyncclient.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-httpcore-nio.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-jetty-client.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-unirest-java.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-websocket-api.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-websocket-client.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-websocket-common.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-zeppelin-client.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-zeppelin-common.txt
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskException.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/test/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskTest.java
  dolphinscheduler-task-plugin/pom.xml
  tools/dependencies/known-dependencies.txt
Labels: miss document, miss UI

#9548 [Fix][UI] Fix condition task connection failure.
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-canvas-init.ts
Labels: bug, UI

#9549 [Fix][UI] Fix the problem of displaying task execution icons.
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-config.ts
Labels: bug, UI

#9546 [Fix][UI Next][V1.0.0-Beta] Fix the color matching problem of the relationship diagram.
  dolphinscheduler-ui-next/src/views/projects/workflow/relation/components/Graph.tsx
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/detail.tsx
Labels: bug, UI

#9552 Correct the version of 3.0.0-alpha document
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/history-versions.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/history-versions.md
Labels: bug, document

#9555 [doc] Correct 3.0.0 content link version
  docs/configs/docsdev.js
Labels: bug, document

#9519 [doc] Add new release for 3.0.0-alpha
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/history-versions.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/history-versions.md
Labels: document

#9561 [Perf][UI Next][V1.0.0-Beta] Optimize judgment logic.
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
Labels: UI, improvement

#9554 [Fix][UI Next][V1.0.0-Beta] Fix workflow instance can not be save bug
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
Labels: bug, UI

#9562 [doc] Fix dead link after 3.0.0 release
  docs/docs/en/development/architecture-design.md
  docs/docs/zh/development/architecture-design.md
Labels: bug, document

#9531 [fix-9428] [DataSource] delete the password and test again, it is successful without password bug (#9428)
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/mysql/MySQLDataSourceProcessorTest.java
Labels: first time contributor

#9574 [Refactor][UI Next]Reconstructing the Log Component
  dolphinscheduler-ui-next/package.json
  dolphinscheduler-ui-next/pnpm-lock.yaml
  dolphinscheduler-ui-next/src/components/log-modal/index.tsx
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/instance/components/log-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/task/instance/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/projects/task/instance/index.tsx
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-menu.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/log-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/log.module.scss
Labels: enhancement, UI

#9581 [Docs] Add license file for screenfull.
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/ui-next-licenses/LICENSE-screenfull
Labels: document

#9590 [Fix][UI Next][V1.0.0-Beta] The version information creation time in the workflow definition is changed to the operateTime field.
  dolphinscheduler-ui-next/src/components/log-modal/index.tsx
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/task/instance/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-table.ts
Labels: bug, UI

#9492 Add ingress annotations
  deploy/kubernetes/dolphinscheduler/templates/ingress.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: first time contributor

#9605 [Feature][UI Next]Added the method of downloading files
  dolphinscheduler-ui-next/src/service/modules/resources/index.ts
  dolphinscheduler-ui-next/src/service/modules/task-instances/index.ts
  dolphinscheduler-ui-next/src/service/service.ts
  dolphinscheduler-ui-next/src/utils/downloadFile.ts
  dolphinscheduler-ui-next/src/utils/index.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
Labels: new feature, UI

#9534 [Docs] enhance alert doc
  docs/docs/en/development/backend/spi/alert.md
  docs/docs/en/guide/alert/alert_plugin_user_guide.md
  docs/docs/zh/development/backend/spi/alert.md
  docs/docs/zh/guide/alert/alert_plugin_user_guide.md
  docs/img/alert/alert_scenarios_en.png
  docs/img/alert/alert_scenarios_zh.png
  docs/img/alert/alert_step_2.png
  docs/img/alert/alert_step_3.png
  docs/img/alert/alert_step_4.png
Labels: enhancement, document

#9591 [Feature][API] Refactor get dependent node information api
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/resources/i18n/messages.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_en_US.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_zh_CN.properties
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentProcessDefinition.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentSimplifyDefinition.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
Labels: backend

#9620 [Fix][UI][V1.0.0-Beta] Change node name to task name in the task modal on the task definition page.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-name.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-conditions.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-data-quality.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-datax.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-dependent.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-emr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-flink.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-http.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-mr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-pigeon.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-procedure.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-python.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sea-tunnel.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-shell.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-spark.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sql.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sqoop.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sub-process.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-switch.ts
Labels: bug, UI

#9623 [Fix][UI][V1.0.0-Beta] Fix the task name cleared after switching the task type.
  dolphinscheduler-ui-next/src/store/project/task-node.ts
  dolphinscheduler-ui-next/src/store/project/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/task/components/node/detail.tsx
  dolphinscheduler-ui-next/src/views/projects/task/components/node/use-task.ts
Labels: bug, UI

#9630 [Fix][UI][V1.0.0-Beta] Fix tooltip not display bug in task instance
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
Labels: bug, UI

#9303 [Feature][Task] K8s namespace auth manager
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/K8sNamespaceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/K8sNamespaceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/UsersService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/K8SNamespaceServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/K8sNamespaceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/K8SNamespaceServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/K8sNamespace.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/K8sNamespaceUser.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceUserMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/K8sNamespaceUserMapper.xml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.1.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.1.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/modules/k8s-namespace/index.ts
  dolphinscheduler-ui-next/src/service/modules/users/index.ts
  dolphinscheduler-ui-next/src/service/modules/users/types.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/authorize-modal.tsx
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-authorize.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/types.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/use-columns.ts
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/namespace/_source/createNamespace.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/namespace/_source/list.vue
  dolphinscheduler-ui/src/js/conf/home/pages/security/pages/users/_source/list.vue
  dolphinscheduler-ui/src/js/module/components/transfer/transfer.vue
  dolphinscheduler-ui/src/js/module/i18n/locale/en_US.js
  dolphinscheduler-ui/src/js/module/i18n/locale/zh_CN.js
Labels: miss document

#9637 [Bug][DAO] Update db init script and soft_version (#9628)
  dolphinscheduler-dao/src/main/resources/sql/soft_version
  dolphinscheduler-tools/src/main/bin/create-schema.sh
Labels: miss document

#9622 [Bug-9608] Serialize the task definition failed
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskDefinition.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapperTest.java
Labels: first time contributor

#9247 [Improvement][style]add comment and clear warn
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertChannel.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertData.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertInfo.java
  dolphinscheduler-alert/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/AlertResult.java
Labels: enhancement, backend

#9512 [Docs][DataQuality]: Add DataQuality Docs
  docs/docs/en/guide/task/data-quality.md
  docs/docs/zh/guide/task/data-quality.md
  docs/img/tasks/demo/custom_sql_check.png
  docs/img/tasks/demo/enumeration_check.png
  docs/img/tasks/demo/field_length_check.png
  docs/img/tasks/demo/multi_table_accuracy_check.png
  docs/img/tasks/demo/multi_table_comparison_check.png
  docs/img/tasks/demo/null_check.png
  docs/img/tasks/demo/regexp_check.png
  docs/img/tasks/demo/result.png
  docs/img/tasks/demo/rule_detail.png
  docs/img/tasks/demo/rule_list.png
  docs/img/tasks/demo/table_count_check.png
  docs/img/tasks/demo/timeliness_check.png
  docs/img/tasks/demo/uniqueness_check.png
Labels: document

#9642 [Fix][UI][V1.0.0-Beta]Fix data not update bug for workflow version switch
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/version-modal.tsx
Labels: bug, UI

#9645 [Fix][UI][V1.0.0-Beta] Replace the back-end interface for dependent task.
  dolphinscheduler-ui-next/src/service/modules/process-definition/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-dependent.ts
Labels: new feature, UI

#9644 [Feature][UI][V1.0.0-Beta] Modify timeout from 10s to 15s of axios
  dolphinscheduler-ui-next/src/service/service.ts
Labels: enhancement, UI

#9649 [Feature][UI][V1.0.0-Beta] Adjust the UI presentation of the dependent task.
  dolphinscheduler-ui-next/src/components/form/fields/custom-parameters.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/service/service.ts
  dolphinscheduler-ui-next/src/utils/downloadFile.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-dependent.ts
Labels: new feature, UI

#9586 [Improvement-9576][server] varPool support "#{setValue(key=value)}"
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
Labels: first time contributor, backend

#9553 [Improvement-9502][Api] Support to upload file without file type suffix
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
Labels: first time contributor, backend

#9662 [doc] Add data quality to sidebar and correct docker resource path
  docs/configs/docsdev.js
  docs/docs/en/guide/data-quality.md
  docs/docs/en/guide/start/docker.md
  docs/docs/zh/guide/data-quality.md
  docs/docs/zh/guide/start/docker.md
Labels: bug, document

#9657 [Bug][UI][V1.0.0-Beta] Fix display resource not exist error message bug
  dolphinscheduler-ui-next/src/views/resource/file/index.tsx
Labels: bug, UI

#9663 [Feature][UI][V1.0.0-Beta] Add dependent task status in dependent task.
  dolphinscheduler-ui-next/src/store/project/task-node.ts
  dolphinscheduler-ui-next/src/store/project/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-status.ts
Labels: new feature, UI

#9659 [Bug][Doc]Update database init instruction docs (#9598)
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/upgrade.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/upgrade.md
  dolphinscheduler-tools/src/main/bin/upgrade-schema.sh
Labels: document

#9602 the doc of DagHelperTest generateDag2 is not correct.
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/utils/DagHelperTest.java
Labels: test

#9677 [hotfix][docker] Removed extra equals in mail user in docker.md
  docs/docs/en/guide/start/docker.md
Labels: document

#9634 [Fix-9633][TenantManage/CreateTenant] Create a tenant is prompting an…
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/RegexUtils.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/RegexUtilsTest.java
Labels: first time contributor, backend

#9678 [Bug][Master] global taskRetryCheckList clear conflict in killAllTasks in WorkflowExecuteThread
  dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
Labels: bug

#9684 [Fix][UI Next][V1.0.0-Beta] Fix bug where name copy is invalid
  dolphinscheduler-ui-next/src/utils/clipboard.ts
Labels: bug, UI

#9683 [Fix][UI Next][V1.0.0-Beta] Change update user to edit user.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/user-detail-modal.tsx
Labels: bug, UI

#9692 [Fix][UI Next][V1.0.0-Beta] Fix the startup parameter display error.
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
Labels: bug, UI

#9698 [Feature]Unified exposure method class
  dolphinscheduler-ui-next/src/utils/clipboard.ts
  dolphinscheduler-ui-next/src/utils/index.ts
  dolphinscheduler-ui-next/src/utils/tree-format.ts
  dolphinscheduler-ui-next/src/utils/truncate-text.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-main-jar.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-resources.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-text-copy.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-authorize.ts
Labels: new feature

#9694 [Fix][UI Next][V1.0.0-Beta] Fix success logo is not display bug
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-status.ts
Labels: bug, UI

#9697 [Fix][UI Next][V1.0.0-Beta] Fix bug where route is error in file manage root
  dolphinscheduler-ui-next/src/views/resource/file/index.tsx
Labels: bug, UI

#9706 [Feature]The utils configuration files are centrally managed under common
  dolphinscheduler-ui-next/src/common/column-width-config.ts
  dolphinscheduler-ui-next/src/common/common.ts
  dolphinscheduler-ui-next/src/common/timezone.ts
  dolphinscheduler-ui-next/src/common/types.ts
  dolphinscheduler-ui-next/src/layouts/content/use-dataList.ts
  dolphinscheduler-ui-next/src/service/modules/process-instances/types.ts
  dolphinscheduler-ui-next/src/store/timezone/types.ts
  dolphinscheduler-ui-next/src/views/data-quality/rule/use-table.ts
  dolphinscheduler-ui-next/src/views/data-quality/task-result/use-table.ts
  dolphinscheduler-ui-next/src/views/datasource/list/use-columns.ts
  dolphinscheduler-ui-next/src/views/monitor/statistics/audit-log/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/list/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/definition/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/task/instance/index.tsx
  dolphinscheduler-ui-next/src/views/projects/task/instance/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-startup-param.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/types.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-status.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/timing-modal.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/timing/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/tree/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/process-instance-condition.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/gantt/type.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/file/create/index.tsx
  dolphinscheduler-ui-next/src/views/resource/file/table/table-action.tsx
  dolphinscheduler-ui-next/src/views/resource/file/table/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/option/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/task-group/queue/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/udf/function/use-table.ts
  dolphinscheduler-ui-next/src/views/resource/udf/resource/use-table.ts
  dolphinscheduler-ui-next/src/views/security/alarm-group-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/alarm-instance-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/environment-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/k8s-namespace-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/tenant-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/token-manage/use-table.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/use-columns.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/use-table.ts
Labels: new feature, UI

#9710 [Fix][UI Next][V1.0.0-Beta] Set the timeout label to not show.
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx
Labels: bug, UI

#9708 [Bug] [UI][V1.0.0-Beta] Fix task group name can't clear bug
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-task-group.ts
Labels: bug, UI

#9700 [Bug] [UI][V1.0.0-Beta] Fix action buttons not displayed on one line bug
  dolphinscheduler-ui-next/src/views/datasource/list/index.tsx
  dolphinscheduler-ui-next/src/views/datasource/list/use-columns.ts
Labels: bug, UI

#9673 [Improvement-9665][python] add create table regex
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/tasks/sql.py
  dolphinscheduler-python/pydolphinscheduler/tests/tasks/test_sql.py
Labels: bug, first time contributor, Python

#9728 [Bug]Fixed the problem of no request from right click viewing log
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
Labels: bug, UI

#9741 [Fix][UI Next][V1.0.0-Beta] Fix citation errors.
  dolphinscheduler-ui-next/src/views/datasource/list/index.tsx
Labels: bug, UI

#9742 [Fix][UI][V1.0.0-Beta] Set the default value of host to '-' and Disab…
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
Labels: bug, UI

#9739 [Fix][UI Next][V1.0.0-Beta] Fix the bug that the tenant is 0 when editing a user.
  dolphinscheduler-ui-next/src/service/modules/users/types.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/components/use-user-detail.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/types.ts
  dolphinscheduler-ui-next/src/views/security/user-manage/use-table.ts
Labels: bug, UI

#9726 [common] Make dolphinscheduler_env.sh work when start server
  docs/docs/en/architecture/configuration.md
  docs/docs/en/faq.md
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/installation/cluster.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/task/datax.md
  docs/docs/en/guide/task/flink.md
  docs/docs/en/guide/task/map-reduce.md
  docs/docs/en/guide/task/spark.md
  docs/docs/zh/architecture/configuration.md
  docs/docs/zh/faq.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/installation/cluster.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/task/datax.md
  docs/docs/zh/guide/task/flink.md
  docs/docs/zh/guide/task/map-reduce.md
  docs/docs/zh/guide/task/spark.md
  docs/docs/zh/guide/upgrade.md
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/assembly/dolphinscheduler-alert-server.xml
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/start.sh
  dolphinscheduler-api/src/main/assembly/dolphinscheduler-api-server.xml
  dolphinscheduler-api/src/main/bin/start.sh
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CommonUtils.java
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/CommonUtilsTest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/file-manage/common.properties
  dolphinscheduler-master/src/main/assembly/dolphinscheduler-master-server.xml
  dolphinscheduler-master/src/main/bin/start.sh
  dolphinscheduler-standalone-server/src/main/assembly/dolphinscheduler-standalone-server.xml
  dolphinscheduler-standalone-server/src/main/bin/start.sh
  dolphinscheduler-standalone-server/src/main/dist-bin/start.sh
  dolphinscheduler-tools/src/main/assembly/dolphinscheduler-tools.xml
  dolphinscheduler-tools/src/main/bin/upgrade-schema.sh
  dolphinscheduler-worker/src/main/assembly/dolphinscheduler-worker-server.xml
  dolphinscheduler-worker/src/main/bin/start.sh
  script/dolphinscheduler-daemon.sh
  script/env/dolphinscheduler_env.sh
  script/scp-hosts.sh
Labels: bug, backend

#9732 [Fix] task flow date time exception handle
  dolphinscheduler-ui-next/src/common/common.ts
  dolphinscheduler-ui-next/src/views/projects/task/instance/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts
Labels: UI

#9761 [Fix][UI Next][V1.0.0-Beta] Change the label from recovery failed to …
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/table-action.tsx
Labels: bug, UI

#9760 [Fix][UI Next][V1.0.0-Beta] Remove the default values for node name a…
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-child-node.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-sub-process.ts
Labels: bug, UI

#9762 [Fix][UI Next][V1.0.0-Beta] Fix cannot select the workload scheduling time bug
  dolphinscheduler-ui-next/src/components/crontab/index.module.scss
  dolphinscheduler-ui-next/src/components/crontab/modules/day.tsx
  dolphinscheduler-ui-next/src/components/crontab/modules/time.tsx
Labels: bug, UI

#9736 [Feature][doc] Add how to change standalone database type (#9376)
  docs/docs/en/development/development-environment-setup.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/zh/development/development-environment-setup.md
  docs/docs/zh/guide/installation/standalone.md
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: document

#9769 [Fix][UI Next][V1.0.0-Beta] Add the 'startNodeList' field to the 'sta…
  dolphinscheduler-ui-next/src/store/project/task-node.ts
  dolphinscheduler-ui-next/src/utils/truncate-text.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-menu.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/start-modal.tsx
Labels: bug, UI

#9775 [Bug]Fix groupId initialization value problem
  dolphinscheduler-ui-next/src/views/resource/task-group/queue/index.tsx
Labels: bug, UI

#9784 [Fix-9783] Task group queue supports fuzzy search.
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.xml
Labels: backend

#9791 [Bug]Fix log request errors
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
Labels: bug, UI

#9795 [Bug][Api] Failed to rerun the workflow instance
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
Labels: first time contributor, backend, priority:high

#9778 [Feature-9566][Docs] Missing shell script application_id listening logic
  docs/docs/en/guide/task/shell.md
  docs/docs/zh/guide/task/shell.md
Labels: document

#8261 [Feature] Update README
  README.md
Labels: document

#9788 [fix-9785][UI Next][dev] dynamic change height in viewlog when full s…
  dolphinscheduler-ui-next/src/components/log-modal/index.tsx
Labels: first time contributor, UI

#9536 bugfix:relation_project_user duplicate
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/postgresql/dolphinscheduler_ddl.sql
Labels: first time contributor, backend

#9631 [Bug-9538]upgrade httpclient version to 4.5.13
  dolphinscheduler-dist/release-docs/LICENSE
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: dependencies

#9733 [Feature][Deploy] Add missing default values in dolphinscheduler_env.sh
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/upgrade.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/upgrade.md
  dolphinscheduler-tools/src/main/assembly/dolphinscheduler-tools.xml
  dolphinscheduler-tools/src/main/bin/create-schema.sh
  dolphinscheduler-tools/src/main/bin/upgrade-schema.sh
Labels: document

#9792 [Bug] [Website-9764]add http alert doc and change body param to unnecessary
  docs/configs/docsdev.js
  docs/docs/en/guide/alert/http.md
  docs/docs/zh/guide/alert/http.md
  docs/img/alert/http-get-example.png
  docs/img/alert/http-post-example.png
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelFactory.java
Labels: document

#9790 [Feature-9772][plugin/ui] support SparkSQL Task
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ProgramType.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/SparkVersion.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractYarnTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/ProgramType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkArgsUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkVersion.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/test/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTaskTest.java
  dolphinscheduler-ui-next/src/service/modules/resources/types.ts
  dolphinscheduler-ui-next/src/store/project/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-deploy-mode.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-flink.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-main-jar.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-mr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-spark.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-spark.ts
Labels: new feature, first time contributor, UI, improvement

#9815 [Fix][UI] Fix timing modal start time and end time bug
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/instance/components/process-instance-condition.tsx
Labels: bug, UI

#9773 [Improvement-9759][Python] Specify warning group when deploy process-definition via python-gate
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-python/pydolphinscheduler/docs/source/config.rst
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/configuration.py
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/default_config.yaml
  dolphinscheduler-python/pydolphinscheduler/src/pydolphinscheduler/core/process_definition.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_configuration.py
  dolphinscheduler-python/pydolphinscheduler/tests/core/test_process_definition.py
  dolphinscheduler-python/pydolphinscheduler/tests/utils/test_yaml_parser.py
Labels: new feature, Python

#9826 [doc] Fix syntax error cause website not work correctly
  docs/configs/docsdev.js
Labels: bug, document

#9825 [Fix][UI] Hide the version control button in workflow instance
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/use-table.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/definition/components/version-modal.tsx
Labels: bug, UI

#9810 [Feature][UI Next] Add front-end for Apache Zeppelin task plugin (#9597)
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-ui-next/public/images/task-icons/zeppelin.png
  dolphinscheduler-ui-next/public/images/task-icons/zeppelin_hover.png
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-zeppelin.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-zeppelin.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui-next/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag.module.scss
Labels: UI, improvement

#9832 [Fix-9831]Task queue status update miss fix.
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java
Labels: bug, UI

#9833 [Fix][UI][V1.0.0-Beta] Fix the problem of wrong workflow name.
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
Labels: bug, UI

#9828 [Fix] json object serialization error
  dolphinscheduler-ui-next/src/views/datasource/list/use-form.ts
Labels: bug, UI

#9834 [BUG][ALERT-SERVER]validate script before alert script
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-script/src/main/java/org/apache/dolphinscheduler/plugin/alert/script/ScriptSender.java
Labels: document

#9839 [Feature][UI Next][V1.0.0-Beta] Rename SeaTunnel.
  dolphinscheduler-ui-next/src/views/projects/task/constants/task-type.ts
Labels: new feature, UI

#9835 [Fix]fix the search bar echoes abnormally
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-toolbar.tsx
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-search.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: bug, UI

#9435 [Improvement][Common] code clean in the common module
  docs/docs/en/faq.md
  docs/docs/zh/faq.md
  dolphinscheduler-common/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-all/pom.xml
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-dist/src/main/assembly/dolphinscheduler-bin.xml
  dolphinscheduler-standalone-server/src/main/assembly/dolphinscheduler-standalone-server.xml
  pom.xml
Labels: backend

#9844 [Fix][UI Next][V1.0.0-Beta] Add validation rules to dependency of the…
  dolphinscheduler-ui-next/src/components/form/fields/custom-parameters.ts
  dolphinscheduler-ui-next/src/components/form/types.ts
  dolphinscheduler-ui-next/src/locales/modules/en_US.ts
  dolphinscheduler-ui-next/src/locales/modules/zh_CN.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-deploy-mode.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-main-jar.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-mr.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/fields/use-spark.ts
  dolphinscheduler-ui-next/src/views/projects/task/components/node/tasks/use-zeppelin.ts
  dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/use-node-search.ts
Labels: bug, UI

#9855 [Fix-9854][api] Query access token for specified user failed
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AccessTokenMapper.xml
Labels: first time contributor, backend
