Repository apache/dolphinscheduler, pull requests merged in 2023-11, with the labels that each got.

#15098 Fix kubectl installation step in e2e-k8s
  .github/workflows/e2e-k8s.yml
Labels: bug, CI&CD, ready-to-merge, 3.2.1

#15097 [Fix-15072][Resource Center] Non-admin user can not query resource recursively
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15093 [fix-#11726] fix error when set connection proerty both in the URL an…
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-presto/src/main/java/org/apache/dolphinscheduler/plugin/datasource/presto/param/PrestoDataSourceProcessor.java
Labels: bug, first time contributor, backend, 3.1.x, ready-to-merge, 3.2.1

#15126 [Improvement] Fix confusing constant string for unit convertor
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/builder/TaskExecutionContextBuilder.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
Labels: improvement, ready-to-merge, 3.3.0

#15123 fix: execute sql error: datasource plugin 'doris' is not found。
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/main/java/org/apache/dolphinscheduler/plugin/doris/DorisDataSourceChannelFactory.java
Labels: bug, backend, 3.1.x, ready-to-merge, 3.2.1

#15092 [fix-#13045] fix endless loop
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowStartEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowSubmitFailStateEventHandler.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15140 [bug]Fix: missing 'KYUUBI' in droplist UI of datasource
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasource.ts
Labels: bug, first time contributor, UI, ready-to-merge, 3.2.1

#15016 [Fix-14805] Task definition log may be written twice
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend, 3.1.x

#14992 [Fix][Data Quality] Change t_ds_dq_rule_input_entry field name fix PostgreSQL not support value issue
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DqRuleServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DqRuleServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DqRuleInputEntry.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DqRuleUtils.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/DqRuleInputEntryMapper.xml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.3.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.3.0_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/TaskExecutionContextFactory.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/enums/dp/DataType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/enums/dp/DataTypeTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/rule/entity/DqRuleInputEntry.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/utils/RuleParserUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/test/java/org/apache/dolphinscheduler/plugin/task/dq/DataQualityTaskTest.java
Labels: bug, backend, ready-to-merge

#15160 Fix incorrect button display text
  dolphinscheduler-ui/src/views/projects/workflow/instance/index.tsx
Labels: bug, UI, ready-to-merge, 3.2.1

#15145 [Doc] when \n in in variable, then setValue will not work well,
  docs/docs/en/guide/parameter/context.md
  docs/docs/zh/guide/parameter/context.md
Labels: first time contributor, improvement, document, ready-to-merge, 3.2.1

#15164 [Fix] Fix spotless
  docs/docs/en/guide/parameter/context.md
  docs/docs/zh/guide/parameter/context.md
Labels: document, ready-to-merge

#15169 Exclude DataSourceAutoConfiguration in worker server
  dolphinscheduler-master/src/main/resources/logback-spring.xml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
  dolphinscheduler-worker/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/resources/logback-spring.xml
Labels: improvement, backend, ready-to-merge

#15153 [Bug] Fix TriggerRelationMapper cannot work due to miss DatabaseIdProvider
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/DaoConfiguration.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TriggerRelationMapper.xml
Labels: bug, first time contributor, backend, ready-to-merge, 3.2.1

#15174 [Improvement][Alert] Add timeout params for HTTP plugin
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertConstants.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelFactoryTest.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelTest.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/test/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSenderTest.java
  dolphinscheduler-ui/src/locales/en_US/security.ts
  dolphinscheduler-ui/src/locales/zh_CN/security.ts
Labels: UI, improvement, backend, ready-to-merge

#15175 [Improvement][Resource Center] Display brief file name in file-details page
  dolphinscheduler-ui/src/views/resource/components/resource/edit/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/table/table-action.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/types.ts
Labels: UI, improvement, ready-to-merge, 3.2.1

#15179 [Improvement][Helm] support task type filter
  deploy/kubernetes/dolphinscheduler/templates/configmap.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: kubernetes, document, ready-to-merge

#15189 [Improvement][Doc] Add deploy on Terraform on README
  README.md
  deploy/README.md
Labels: improvement, ready-to-merge

#15191 [Bug] Workflow instance can't stop due to doesn't refresh status in master
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowStateEventHandler.java
Labels: bug, first time contributor, backend, ready-to-merge, 3.2.1

#15192 [Chore] Fix Information Leakage Vulnerability
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/AbstractAuthenticator.java
Labels: improvement, backend, chore, ready-to-merge, 3.2.1

#15198 [Improvement] Clean up Scheduler logic
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/SchedulerService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessTaskRelationServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/SchedulerControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecuteFunctionServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessTaskRelationServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/SchedulerServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskDefinitionServiceImplTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapperTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: improvement, backend, ready-to-merge, 3.3.0

#15184 [Improvement] Remove spring cache for dao
  docs/docs/en/architecture/cache.md
  docs/docs/zh/architecture/cache.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/aspect/CacheEvictAspect.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ScheduleMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionLogMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TenantMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/UserMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/WorkerGroupMapper.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/IMasterCacheService.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/CacheExpireRequest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/MasterCacheServiceImpl.java
Labels: improvement, backend, document, ready-to-merge, 3.3.0

#15220 Remove unused cache-evict.png
  docs/img/cache-evict.png
Labels: document, ready-to-merge

#15167 Fix docs style is incorrect by CI pass
  .github/workflows/docs.yml
Labels: bug, CI&CD, ready-to-merge

#15228 [Bug] fix switch condition
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/switchtask/SwitchLogicTask.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtilsTest.java
Labels: bug, backend, 3.1.x, ready-to-merge

#15234 [Fix] Change HTTP plugin timeout param to number type
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpAlertChannelFactory.java
Labels: bug, backend, ready-to-merge

#15240 Use chown to set the file owner
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionCheckerUtils.java
Labels: improvement, backend, ready-to-merge

#15010 [Improvement-15009][Parameter] Change project parameter value to text
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.1_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.1_schema/postgresql/dolphinscheduler_ddl.sql
Labels: improvement, backend, ready-to-merge, 3.2.1
