Repository apache/dolphinscheduler, pull requests merged in 2023-05, with the labels that each got.

#13930 [Bug-13929][K8S Task] Set command contains single quote is invalid
  docs/docs/en/guide/task/kubernetes.md
  docs/docs/zh/guide/task/kubernetes.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskMainParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/K8sTaskParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskExecutorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sParametersTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-k8s.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: bug, UI, backend, document, 3.1.6

#14043 Fix registry table field
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/JdbcOperator.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/mapper/JdbcRegistryDataMapper.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/model/JdbcRegistryData.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/model/JdbcRegistryLock.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/task/SubscribeDataManager.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/resources/mysql_registry_init.sql
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/resources/postgresql_registry_init.sql
Labels: bug, backend, 3.2.0

#11778 [Feature] Support run all level dependent when complement
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ExecuteFunctionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecuteFunctionServiceTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-form.ts
Labels: feature, UI, backend, 3.2.0

#14058 [Improvement-14057][api] alarm instance add sort
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertPluginInstanceMapper.xml
Labels: improvement, backend, 3.2.0

#14059 FIX: allLevelDependent default value
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-form.ts
Labels: bug, UI, 3.2.0

#14061 [Doc-14060][Task Plugin] Change DinkyTask chinese picture into english picture
  docs/img/tasks/demo/dinky_task_id.png
Labels: document, 3.1.x

#14021 [Fix-13989] Add path validation
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperator.java
Labels: bug, 3.2.0

#14053 [Improvement-14052][Log] Remove the useless filter in getAppIdsFromLogFile
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/LogUtils.java
Labels: improvement, backend, 3.2.0

#14051 [Fix-14049][dao] fix init sql and use on conflict do update in pg
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TriggerRelationMapper.xml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
Labels: bug, backend, 3.1.6

#14029 [Fix-13928][UI] Fix repeat CustomParams input box
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datax.ts
Labels: bug, first time contributor, UI, 3.1.6

#14055 [Improvement-14054][Worker] Kill multiple yarn apps at the same time
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/am/YarnApplicationManager.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/WorkerTaskKillProcessor.java
Labels: improvement, backend, 3.2.0

#13729 [Feature][plugin] Add snowflake datasource in datasource plugin
  docs/configs/docsdev.js
  docs/docs/en/guide/datasource/snowflake.md
  docs/docs/zh/guide/datasource/snowflake.md
  docs/img/new_ui/dev/datasource/snowflake.png
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/DataSourceConstants.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-all/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/main/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/SnowflakeDataSourceChannel.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/main/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/SnowflakeDataSourceChannelFactory.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/main/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/SnowflakeDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/main/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/param/SnowflakeConnectionParam.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/main/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/param/SnowflakeDatasourceParamDTO.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/main/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/param/SnowflakeDatasourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/test/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/SnowflakeDataSourceChannelFactoryTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/test/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/SnowflakeDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/test/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/SnowflakeDataSourceClientTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/test/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/param/SnowflakeDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/test/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/provider/SnowflakeJDBCDataSourceProviderTest.java
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-dist/release-docs/licenses/LICENSE-snowflake-jdbc.txt
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/enums/DbType.java
  dolphinscheduler-ui/src/locales/en_US/datasource.ts
  dolphinscheduler-ui/src/locales/zh_CN/datasource.ts
  dolphinscheduler-ui/src/service/modules/data-source/types.ts
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
  tools/dependencies/known-dependencies.txt
Labels: feature, UI, backend, document, 3.2.0

#13958 [Bug-13951 ][dolphinscheduler-service] StartParams is not applied when task is failover(RECOVER_TOLERANCE_FAULT_PROCESS CommandType)
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: bug, first time contributor, backend, 3.1.x

#14072 [Doc] Fix upgrade-schema.sh cannot load driver class
  docs/docs/en/guide/howto/datasource-setting.md
  docs/docs/zh/guide/howto/datasource-setting.md
Labels: first time contributor, improvement, document, 3.1.x

#14094 [CI] Try fix api test error
  .github/workflows/api-test.yml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/pom.xml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/cases/WorkerGroupAPITest.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/utils/JSONUtils.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api.test/utils/RequestClient.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-core/src/main/java/org/apache/dolphinscheduler/api/test/core/DolphinSchedulerExtension.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-core/src/main/resources/logback.xml
  dolphinscheduler-api-test/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/test/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteExecutorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/test/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteShellTaskTest.java
Labels: bug, backend, test, CI&CD, 3.2.0

#14100 [release][3.1.6] Added 3.1.6 release document
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: document, 3.1.6

#14097 [Improvement-14095][Resource Center] Implement getResourceFileName in StorageOperator
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/TaskCacheUtils.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-api/src/main/java/org/apache/dolphinscheduler/plugin/storage/api/StorageOperate.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-gcs/src/main/java/org/apache/dolphinscheduler/plugin/storage/gcs/GcsStorageOperator.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-gcs/src/test/java/org/apache/dolphinscheduler/plugin/storage/gcs/GcsStorageOperatorTest.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperator.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-oss/src/main/java/org/apache/dolphinscheduler/plugin/storage/oss/OssStorageOperator.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-oss/src/test/java/org/apache/dolphinscheduler/plugin/storage/oss/OssStorageOperatorTest.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-s3/src/main/java/org/apache/dolphinscheduler/plugin/storage/s3/S3StorageOperator.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-s3/src/test/java/org/apache/dolphinscheduler/plugin/storage/s3/S3StorageOperatorTest.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionCheckerUtils.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskFilesTransferUtils.java
Labels: improvement, backend, 3.2.0

#14103 chore: roadmap should not label stale
  .github/workflows/stale.yml
Labels: improvement, CI&CD, 3.2.0

#14116 [Improvement-14111][UI] Add a tooltip for the copy button of workflow definition.
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: UI, improvement, 3.2.0

#14106 [Bug-14105][Task] Replace default tenant when downloading resource
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperator.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionCheckerUtils.java
Labels: bug, backend, 3.2.0

#14122 Add supported operations of workflow definition
  docs/docs/en/guide/project/workflow-definition.md
  docs/docs/zh/guide/project/workflow-definition.md
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.tsx
Labels: UI, improvement, document, 3.2.0

#14087 [fix-#14086]The subprocess type node is always in the ready stop state
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SubTaskProcessor.java
Labels: bug, backend, 3.0.x

#14016 [fix-#13940] add status of ``` stop``` in class of TaskExecutionStatus
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/enums/TaskExecutionStatus.java
Labels: bug, backend, 3.1.x

#14144 [Bug][ui] fix error TS2339: Property $route does not exist on type CreateComponentPublicInstance
  dolphinscheduler-ui/src/layouts/content/index.tsx
Labels: bug, UI, 3.2.0

#14141 [Fix-14140] [API] Fix dependent task nodes in workflow instances cannot display data
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/dependent/DependentAsyncTaskExecuteFunction.java
Labels: bug, backend, 3.2.0

#14142 Revert [fix-#13956] [Master]taskId is null cause NPE #13980
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, 3.2.0

#14134 [Improvement-14112][UI] Add a quick link to visit workflow instances of the current workflow.
  dolphinscheduler-ui/src/common/column-width-config.ts
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/instance/components/process-instance-condition.tsx
  dolphinscheduler-ui/src/views/projects/workflow/instance/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/instance/types.ts
  dolphinscheduler-ui/src/views/projects/workflow/instance/use-table.ts
Labels: UI, improvement, 3.2.0

#14129 fix: Save task seatunnel error
  docs/docs/en/guide/task/seatunnel.md
  docs/docs/zh/guide/task/seatunnel.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/Constants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/DeployModeEnum.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/EngineEnum.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/flink/SeatunnelFlinkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/self/SeatunnelEngineParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/spark/SeatunnelSparkParameters.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sea-tunnel.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-sea-tunnel.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, backend, document, 3.1.x

#14150 [Feature-#14148][Task] Added status check interval and dependent failure policy parameters for dependent task nodes
  docs/docs/en/guide/task/dependent.md
  docs/docs/zh/guide/task/dependent.md
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/dependent/DependentAsyncTaskExecuteFunction.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/DependentParameters.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-dependent.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: feature, UI, backend, document, 3.2.0

#14170 [fix-#14169]The subprocess type node is always in the ```ready pause``` or ``` ready stop ``` state
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SubTaskProcessor.java
Labels: bug, backend, 3.1.x

#13378 [Fix-13381][plugin] fix error while parsing hive load sql
  docs/docs/en/guide/upgrade/incompatible.md
  docs/docs/zh/guide/upgrade/incompatible.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTaskTest.java
Labels: bug, first time contributor, backend, document, priority:middle, incompatible, 3.2.0

#11979 [fix-11321][ui] fix create workflow contains chunjun node failed
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-chunjun.ts
Labels: bug, UI, priority:low, 3.1.x

#14172 [release][3.1.7] Added 3.1.7 release document
  deploy/docker/.env
  deploy/kubernetes/dolphinscheduler/Chart.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/configs/docsdev.js
  docs/configs/site.js
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/history-versions.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/history-versions.md
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.7_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.7_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.7_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.7_schema/postgresql/dolphinscheduler_dml.sql
Labels: backend, document

#14145 [Bug][Worker] generate kill command with unknown user: default
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
Labels: bug, backend, 3.2.0

#14163 fix: PULL_REQUEST_TEMPLATE.md dead link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: improvement, CI&CD, 3.2.0, ready-to-merge

#14081 [Improvement-14080][script] cleanup dist directory at the beginning of check-LICENSE.sh
  tools/dependencies/check-LICENSE.sh
Labels: chore, 3.2.0, ready-to-merge

#14177 [Feature-14138][Metrics] Add metrics for api server
  docs/docs/en/guide/metrics/metrics.md
  docs/docs/zh/guide/metrics/metrics.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/aspect/AccessLogAspect.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/interceptor/LoginHandlerInterceptor.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/metrics/ApiServerMetrics.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-meter/src/main/resources/grafana/DolphinSchedulerApi.json
Labels: feature, backend, document, 3.2.0

#14188 [fix-14119] The checkBucketNameExists method should not use s3Client. listBuckets()
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/S3RemoteLogHandler.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-s3/src/main/java/org/apache/dolphinscheduler/plugin/storage/s3/S3StorageOperator.java
Labels: bug, backend, 3.2.0

#14162 Fix master memory leak due to MasterTaskExecuteRunnableDoesn't be removed
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/MasterTaskDispatchProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/MasterTaskKillProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/MasterTaskPauseProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterDelayTaskExecuteRunnableDelayQueueLooper.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/MasterTaskExecuteRunnableThreadPool.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskCallbackFunctionImpl.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/MasterTaskExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/MasterTaskExecuteRunnableHolder.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/MasterTaskExecuteRunnableThreadPool.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/SyncMasterDelayTaskExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/operator/TaskTimeoutOperator.java
Labels: bug, backend, 3.2.0

#14197 fix: disordered comments in values.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: improvement, backend, 3.2.0

#14099 [Feature] Add project name/workflow definition name/instance id/task name to the built-in variables
  docs/docs/en/guide/parameter/built-in.md
  docs/docs/zh/guide/parameter/built-in.md
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParams.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParamsServiceTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
Labels: feature, first time contributor, backend, document, miss:docs, 3.2.0

#14202 [Improvement-14201][UI] Improve the select component to support users to filter options.
  dolphinscheduler-ui/src/views/projects/workflow/instance/components/process-instance-condition.tsx
  dolphinscheduler-ui/src/views/projects/workflow/relation/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/timing/components/timing-condition.tsx
Labels: UI, improvement, 3.2.0

#14200 Fix taskGroupQueue doesn't removed from inQueue where wakeup failed
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/operator/TaskTimeoutOperator.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend, 3.2.0

#14206 [release][3.1.7] Added 3.1.7 release document
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: feature, improvement, document, 3.1.x

#14014 [Fix-13913][Master] syncMasterNodes does not make current slot correctly after zookeeper reconnect
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterConnectionStateListener.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java
Labels: bug, backend, 3.0.x

#14196 [Improvement-14195][Parameter] remove misleading comment of combining local and global parameter
  dolphinscheduler-task-plugin/dolphinscheduler-task-dms/src/main/java/org/apache/dolphinscheduler/plugin/task/dms/DmsTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/main/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteShellTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/task/sagemaker/SagemakerTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/SqoopTask.java
Labels: improvement, backend, 3.2.0

#14147 [Improvement-14146][K8S Task] print complete error logs in task log file
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTask.java
Labels: bug, backend, 3.2.0

#14207 [Bug][API] Fix TreeView "Task Status" not show bug and compatibility with older versions use WorkflowExecutionStatus.name()
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
Labels: bug, first time contributor, backend, 3.1.x

#14234 chore: Release version 3.0.6
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: chore, document, 3.0.x
