Repository apache/dolphinscheduler, pull requests merged in 2023-02, with the labels that each got.

#12830 [Fix-12828][api] Add permission check when query specific datasource
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataSourceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
Labels: bug, backend, 3.2.0

#13466 Fix task wake up failed will block the event processing
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/StateEventType.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskWaitTaskGroupStateHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/TaskEventProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend, 3.1.x

#13479 Use convert to set the exist column collate to utf8_bin
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_ddl.sql
Labels: improvement, backend, 3.2.0

#13456 Use single thread to refresh kerberos
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/thread/ThreadUtils.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/HiveDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/security/UserGroupInformationFactory.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/utils/CommonUtil.java
Labels: improvement, backend, 3.2.0

#13485 FIX: 3.1.1_schema mysql ddl sql error
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/mysql/dolphinscheduler_ddl.sql
Labels: bug, backend, 3.1.x

#13486 Fix serial wait will go into block when there is no task need to submit
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend, 3.1.x

#13494 FIX: qrtz table use uppercase
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/postgresql/dolphinscheduler_dml.sql
Labels: bug, backend, 3.1.x

#13148 [bug][UI]Fixed a bug where the environment name of a task could not be changed when a workflow was created(issue-12457)
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-environment-name.ts
Labels: bug, UI, 3.2.0

#13502 Fix task log might delay until task finished due to batch flush
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
Labels: improvement, backend, 3.1.x

#13487 [fix-13483] Fix complement data date order will change due to use set
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
Labels: improvement, backend, 3.2.0

#13507 [Doc] Update LDAP Doc
  docs/configs/docsdev.js
  docs/docs/en/architecture/configuration.md
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/security/authentication-type.md
  docs/docs/en/guide/security/security.md
  docs/docs/en/guide/task/kubeflow.md
  docs/docs/zh/architecture/configuration.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/security/authentication-type.md
  docs/docs/zh/guide/security/security.md
  docs/docs/zh/guide/task/kubeflow.md
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/security/impl/ldap/LdapServiceTest.java
Labels: improvement, backend, document, 3.2.0

#13495 Flinksql support standalone deploy mode
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkDeployMode.java
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-flink.ts
Labels: feature, first time contributor, UI, backend, miss:docs, 3.2.0

#13475 [Improvement-13472][Api] Removes the overhead of idle Quartz Threadpool of Api
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-scheduler-plugin/dolphinscheduler-scheduler-quartz/src/main/java/org/apache/dolphinscheduler/scheduler/quartz/QuartzZeroSizeThreadPool.java
Labels: improvement, backend, document, 3.2.0

#13508 [Improvement][task node] task node resources improvement
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-resources.ts
Labels: first time contributor, UI, improvement, 3.1.x

#13435 [Fix-13434][Resource Center] fix the NPE when use OSS as the resource center
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-oss/src/main/java/org/apache/dolphinscheduler/plugin/storage/oss/OssStorageOperator.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-oss/src/test/java/org/apache/dolphinscheduler/plugin/storage/oss/OssStorageOperatorTest.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-s3/src/main/java/org/apache/dolphinscheduler/plugin/storage/s3/S3StorageOperator.java
  dolphinscheduler-ui/src/locales/zh_CN/resource.ts
Labels: feature, UI, backend, 3.2.0

#13526 Fix the parameter table is messed up
  docs/docs/en/guide/task/flink.md
Labels: improvement, document, 3.2.0

#13512 [Feature][Resource Center] One-time migration script for unmanaged resources
  docs/docs/en/guide/upgrade/upgrade.md
  docs/docs/zh/guide/upgrade/upgrade.md
  dolphinscheduler-tools/pom.xml
  dolphinscheduler-tools/src/main/bin/migrate-resource.sh
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/resource/MigrateResource.java
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/resource/MigrateResourceService.java
Labels: feature, backend, document, 3.2.0

#13529 [Improvement][Task Plugin] Support Task Plugin output response as a parameter
  docs/docs/en/guide/task/http.md
  docs/docs/zh/guide/task/http.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/AbstractParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/test/java/org/apache/dolphinscheduler/plugin/task/http/HttpTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/test/java/org/apache/dolphinscheduler/plugin/task/sqoop/EntityTestUtils.java
Labels: bug, backend, document, 3.2.0

#13535 Alter title in t_ds_alert to 512
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: improvement, backend, 3.2.0

#13538 Fix typos in tools for demo
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/demo/DemoConstants.java
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/demo/ProcessDefinitionDemo.java
Labels: first time contributor, improvement, backend, 3.2.0

#11203 [Feature-11195][UI] Add re-upload feature for resource files
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/FileManagePage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/UdfManagePage.java
  dolphinscheduler-ui/src/locales/en_US/resource.ts
  dolphinscheduler-ui/src/locales/zh_CN/resource.ts
  dolphinscheduler-ui/src/service/modules/resources/types.ts
  dolphinscheduler-ui/src/views/resource/components/resource/create/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/create/use-create.ts
  dolphinscheduler-ui/src/views/resource/components/resource/create/use-form.ts
  dolphinscheduler-ui/src/views/resource/components/resource/edit/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/edit/use-edit.ts
  dolphinscheduler-ui/src/views/resource/components/resource/edit/use-form.ts
  dolphinscheduler-ui/src/views/resource/components/resource/folder/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/folder/use-folder.ts
  dolphinscheduler-ui/src/views/resource/components/resource/folder/use-form.ts
  dolphinscheduler-ui/src/views/resource/components/resource/index.module.scss
  dolphinscheduler-ui/src/views/resource/components/resource/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/rename/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/rename/use-form.ts
  dolphinscheduler-ui/src/views/resource/components/resource/rename/use-rename.ts
  dolphinscheduler-ui/src/views/resource/components/resource/table/table-action.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/table/use-table.ts
  dolphinscheduler-ui/src/views/resource/components/resource/types.ts
  dolphinscheduler-ui/src/views/resource/components/resource/upload/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/upload/use-form.ts
  dolphinscheduler-ui/src/views/resource/components/resource/upload/use-upload.ts
  dolphinscheduler-ui/src/views/resource/components/resource/use-file.ts
  dolphinscheduler-ui/src/views/resource/file/create/index.tsx
  dolphinscheduler-ui/src/views/resource/file/edit/index.tsx
  dolphinscheduler-ui/src/views/resource/file/folder/index.tsx
  dolphinscheduler-ui/src/views/resource/file/index.tsx
  dolphinscheduler-ui/src/views/resource/file/table/use-table.ts
  dolphinscheduler-ui/src/views/resource/udf/function/components/function-modal.tsx
  dolphinscheduler-ui/src/views/resource/udf/function/components/use-modal.ts
  dolphinscheduler-ui/src/views/resource/udf/resource/components/upload-modal.tsx
  dolphinscheduler-ui/src/views/resource/udf/resource/components/use-form.ts
  dolphinscheduler-ui/src/views/resource/udf/resource/components/use-modal.ts
  dolphinscheduler-ui/src/views/resource/udf/resource/index.module.scss
  dolphinscheduler-ui/src/views/resource/udf/resource/index.tsx
  dolphinscheduler-ui/src/views/resource/udf/resource/types.ts
  dolphinscheduler-ui/src/views/resource/udf/resource/use-table.ts
Labels: feature, UI, e2e, 3.2.0

#13518 [Improvement] add cost time for api call
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/aspect/AccessLogAnnotation.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/aspect/AccessLogAspect.java
Labels: improvement, backend, 3.2.0

#13546 Publish Helm Chart snapshot to ghcr.io for convenient test
  .github/workflows/owasp-dependency-check.yaml
  .github/workflows/publish-helm-chart.yaml
  dolphinscheduler-common/src/main/resources/common.properties
Labels: feature, backend, kubernetes, CI&CD, 3.2.0

#13540 [BUG][Resource Center] NPE caused by uninitialized hdfsProperties
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperator.java
Labels: bug, backend, 3.2.0

#13547 Set init job as a helm hook so that DS can be upgraded using `helm upgrade`, also remove legacy `registryPluginDir`
  deploy/kubernetes/dolphinscheduler/templates/job-dolphinscheduler-schema-initializer.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: feature, 3.2.0

#13332 [Feature-13331][Remote Logging] Add support for writing task logs to OSS
  docs/configs/docsdev.js
  docs/docs/en/guide/remote-logging.md
  docs/docs/zh/guide/remote-logging.md
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/OssRemoteLogHandler.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/RemoteLogHandleThreadPool.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/RemoteLogHandler.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/RemoteLogHandlerFactory.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/RemoteLogService.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/RemoteLogUtils.java
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/log/remote/OssRemoteLogHandlerTest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/processor/LoggerRequestProcessor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskExecutionContext.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/LogUtils.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnable.java
Labels: feature, improvement, backend, document, 3.2.0

#13560 [Feature-13354][deploy] Add configurable busybox image in values.yaml…
  deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: feature, first time contributor, backend, 3.2.0

#13572 [fix-13504] Display the current project name on the left corner of the page
  dolphinscheduler-ui/src/layouts/content/components/sidebar/use-menuClick.ts
  dolphinscheduler-ui/src/layouts/content/index.tsx
  dolphinscheduler-ui/src/layouts/content/use-dataList.ts
  dolphinscheduler-ui/src/views/projects/list/use-table.ts
Labels: first time contributor, UI, improvement, 3.2.0

#13571 Fix task instance will generate multiple times when retry interval is 0/s
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskStateEventHandler.java
Labels: bug, backend, 3.1.x

#13051 [improve-#13045] after a submit failure, stop the processInstance to avoid an endless loop
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/StateEventType.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowStartEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowStateEventHandler.java
Labels: improvement, backend, 3.2.0

#13586 [Improvement] Support modal close for datasources
  dolphinscheduler-ui/src/components/modal/index.tsx
  dolphinscheduler-ui/src/views/datasource/list/index.tsx
  dolphinscheduler-ui/src/views/datasource/list/source-modal.tsx
Labels: UI, improvement, 3.2.0

#13589 [3.1.4-prepare][release] Updated documentation and code to version 3.1.4
  deploy/docker/.env
  deploy/kubernetes/dolphinscheduler/Chart.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/configs/docsdev.js
  docs/configs/site.js
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/history-versions.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/history-versions.md
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.4_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.4_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.4_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.4_schema/postgresql/dolphinscheduler_dml.sql
Labels: backend, document, 3.1.x

#13587 [improvement][UI][2.0.9] Speed up the refresh of task status in process instance
  dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/dag.vue
Labels: first time contributor

#13599 [improve-#13597] fix the method name
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapMapper.xml
Labels: bug, backend, 3.2.0

#13206 [improve-#13201] update pid during running
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/TaskEventType.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskUpdatePidEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/TaskUpdatePidProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskEvent.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/MasterRPCServer.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/CommandType.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskUpdatePidAckMessage.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/TaskUpdatePidCommand.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractYarnTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskCallBack.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-chunjun/src/main/java/org/apache/dolphinscheduler/plugin/task/chunjun/ChunJunTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/test/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dvc/src/main/java/org/apache/dolphinscheduler/plugin/task/dvc/DvcTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/java/org/apache/dolphinscheduler/plugin/task/emr/EmrAddStepsTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/test/java/org/apache/dolphinscheduler/plugin/task/emr/EmrJobFlowTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-hivecli/src/main/java/org/apache/dolphinscheduler/plugin/task/hivecli/HiveCliTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/main/java/org/apache/dolphinscheduler/plugin/task/java/JavaTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/test/java/org/apache/dolphinscheduler/plugin/task/java/JavaTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-jupyter/src/main/java/org/apache/dolphinscheduler/plugin/task/jupyter/JupyterTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-linkis/src/main/java/org/apache/dolphinscheduler/plugin/task/linkis/LinkisTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-mlflow/src/main/java/org/apache/dolphinscheduler/plugin/task/mlflow/MlflowTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/test/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinTaskTest.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/message/TaskUpdatePidMessageSender.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskUpdatePidAckProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/rpc/WorkerRpcClient.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/rpc/WorkerRpcServer.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskCallbackImpl.java
Labels: improvement, backend, 3.2.0

#13604 [fix-13603][DATAX]SQLServer not support special field
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxUtils.java
Labels: bug, backend, 3.2.0

#13530 [Improvement-13437][UT] Add UT for S3StorageOperator
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-s3/src/main/java/org/apache/dolphinscheduler/plugin/storage/s3/S3StorageOperator.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-s3/src/main/java/org/apache/dolphinscheduler/plugin/storage/s3/S3StorageOperatorFactory.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-s3/src/test/java/org/apache/dolphinscheduler/plugin/storage/s3/S3StorageOperatorTest.java
Labels: improvement, 3.2.0

#13605 [doc] spark on native k8s
  docs/docs/en/guide/task/spark.md
  docs/docs/zh/guide/task/spark.md
Labels: document, 3.2.0

#13608 docs: update rainbond docs
  docs/docs/en/guide/integration/rainbond.md
  docs/docs/zh/guide/integration/rainbond.md
  docs/img/rainbond/appstore-dolphinscheduler.png
  docs/img/rainbond/dolpscheduler-worker.png
  docs/img/rainbond/homepage-dolphinscheduler.png
  docs/img/rainbond/install-dolphinscheduler.png
  docs/img/rainbond/monitor-dolphinscheduler.png
  docs/img/rainbond/plugin.png
  docs/img/rainbond/topology-dolphinscheduler.png
Labels: document, 3.2.0

#13621 [Release][3.1.4] add 3.1.4 release doc
  README.md
  README_zh_CN.md
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: document, 3.2.0

#13631 Publish Docker images to docker hub when released
  .github/workflows/publish-docker.yaml
  .github/workflows/publish-helm-chart.yaml
  docs/docs/en/contribute/release.md
  docs/docs/zh/contribute/release.md
Labels: CI&CD, document, 3.2.0

#13632 Fix typo
  .github/workflows/publish-helm-chart.yaml
Labels: CI&CD, chore, 3.2.0

#13607 doc: new quick start doc with more detail and gif
  docs/docs/en/guide/start/quick-start.md
  docs/docs/zh/guide/start/quick-start.md
  docs/img/new_ui/dev/quick-start/create-alarmGroup.png
  docs/img/new_ui/dev/quick-start/create-alarmInstance.png
  docs/img/new_ui/dev/quick-start/create-environment.png
  docs/img/new_ui/dev/quick-start/create-queue.png
  docs/img/new_ui/dev/quick-start/create-tenant.png
  docs/img/new_ui/dev/quick-start/create-token.png
  docs/img/new_ui/dev/quick-start/create-user.png
  docs/img/new_ui/dev/quick-start/create-workerGroup.png
  docs/img/new_ui/dev/quick-start/log.png
  docs/img/new_ui/dev/quick-start/project.png
  docs/img/new_ui/dev/quick-start/workflow-definition.png
  docs/img/start/assign-tenant.gif
  docs/img/start/create-project.gif
  docs/img/start/create-task.gif
  docs/img/start/create-tenant.gif
  docs/img/start/create-workflow.gif
  docs/img/start/login.gif
  docs/img/start/run-workflow.gif
  docs/img/start/set-dep.gif
  docs/img/start/view-log.gif
  docs/img_utils.py
Labels: document, 3.1.x

#13627 [fix-13625] Modify systemd-run from MemoryMax to MemoryLimit for more generality.
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
Labels: bug, backend, 3.2.0

#13643 [Fix][Data Quality]Dataquality Spark Get Datasource Password Error When Password Has $
  dolphinscheduler-data-quality/src/main/java/org/apache/dolphinscheduler/data/quality/flow/batch/reader/JdbcReader.java
  dolphinscheduler-data-quality/src/main/java/org/apache/dolphinscheduler/data/quality/flow/batch/writer/JdbcWriter.java
  dolphinscheduler-data-quality/src/main/java/org/apache/dolphinscheduler/data/quality/utils/ParserUtils.java
  dolphinscheduler-data-quality/src/test/java/org/apache/dolphinscheduler/data/quality/utils/ParserUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/utils/RuleParserUtils.java
Labels: bug, backend, 3.1.x
