Repository apache/dolphinscheduler, pull requests merged in 2023-09, with the labels that each got.

#14837 [Improvement-14835][UI] Support to immediately adjust the fill color of the task node after changing the run flag of the task.
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-cell-update.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: UI, improvement, ready-to-merge

#14800 [Improvement] [Task] Change Seatunnel task run-mode to deploy-mode
  docs/docs/en/guide/task/seatunnel.md
  docs/docs/zh/guide/task/seatunnel.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/flink/SeatunnelFlinkParameters.java
Labels: first time contributor, improvement, backend, document, ready-to-merge

#14328 fix invalid registry path ends with 'master' or 'worker'
  dolphinscheduler-registry/dolphinscheduler-registry-api/src/main/java/org/apache/dolphinscheduler/registry/api/RegistryClient.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14844 feat: Add others scopes for release tool
  tools/release/github/changelog.py
Labels: chore, ready-to-merge

#14814 [Feature-14802][api] Use Casdoor SSO to log in, add admin user configuration
  docs/docs/en/architecture/configuration.md
  docs/docs/en/guide/security/authentication-type.md
  docs/docs/zh/architecture/configuration.md
  docs/docs/zh/guide/security/authentication-type.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/security/impl/sso/CasdoorAuthenticator.java
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/security/impl/sso/CasdoorAuthenticatorTest.java
  dolphinscheduler-api/src/test/resources/application.yaml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: first time contributor, improvement, backend, document, ready-to-merge

#14852 [fix-#14851] [standalone]fix yaml in standalone
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: backend

#14838 Revert "fix: Local resource error in some entrypoint"
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
Labels: bug, backend, ready-to-merge

#14853 chore: add revert label check
  .github/mergeable.yml
Labels: CI&CD, chore, ready-to-merge

#14856 [Bug] [Mater] The process always runs when the process contains subprocess and params deliver
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskStateEventHandler.java
Labels: backend, 3.1.x, release cherry-pick 3.1.x

#14860 [improvement][API] fix class in loggerFactory
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
Labels: backend

#14850 [Improve] Fix placeholders should match arguments in log statement
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UdfFuncServiceImpl.java
Labels: improvement, backend, ready-to-merge

#14862 [Bug] [UI] New tasks with the flag normal show a grey color
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: bug, UI, ready-to-merge, 3.2.1

#14859 Fix session/thread leak at ssh datasource
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/DataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/SshClientWrapper.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/param/SSHDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/test/java/org/apache/dolphinscheduler/plugin/datasource/ssh/SSHDataSourceProcessorTest.java
Labels: bug, backend, ready-to-merge, 3.2.1

#14661 [Fix-14660] [Resource Center] Remove NONE storage type and set LOCAL type as default
  docs/docs/en/guide/resource/configuration.md
  docs/docs/zh/guide/resource/configuration.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UdfFuncServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TenantControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UdfFuncServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ResUploadType.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/PropertyUtilsTest.java
  dolphinscheduler-common/src/test/resources/common.properties
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperator.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperatorFactory.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionCheckerUtils.java
Labels: bug, backend, document, ready-to-merge

#14812 [Fix-14811][api] Fix when using Casdoor SSO, ldap, OAuth2 to login, the tenant problem of not specifying the currently logged in user
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
Labels: bug, backend, ready-to-merge

#14871 [Improvement-14870][UI] Optimize task disable node style in dark theme
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-custom-cell-builder.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-task-edit.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/x6-style.scss
Labels: UI, improvement, ready-to-merge, 3.2.1

#14793 fix(dolphinscheduler-alert): fix create http request error
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSender.java
Labels: bug, first time contributor, backend, 3.2.0, ready-to-merge

#14824 [Improvement][Master] Split the task dependency mode of the dependent node into workflow dependent and task dependent
  docs/docs/en/guide/task/dependent.md
  docs/docs/zh/guide/task/dependent.md
  docs/img/tasks/demo/dependent_task01.png
  docs/img/tasks/demo/dependent_task02.png
  docs/img/tasks/demo/dependent_task03.png
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/TaskDefinitionDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/TaskInstanceDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskDefinitionDaoImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskInstanceDaoImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/dependent/DependentAsyncTaskExecuteFunction.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, backend, document, OSPP, ready-to-merge

#14883 Add doap.rdf for DS to be listed in https://projects.apache.org
  doap.rdf
Labels: chore, 3.2.0, ready-to-merge

#14888 [Cherry pick] Construct processInstance may NPE when master handling command
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend, release cherry-pick 3.1.x

#14792 [Fix-14790][dolphinscheduler-ui] Fix the data quality task, keyword filtering not supported
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-rules.ts
Labels: bug, UI, 3.1.x, ready-to-merge, 3.2.1

#14791 [Fix-14788][dolphinscheduler-ui] Fix the task name of dependent node, keyword filtering not supported
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
Labels: bug, UI, 3.1.x, ready-to-merge, 3.2.1

#13050 Fix java.sql.Date serialize error by convert it to java.util.Date
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java
Labels: bug, first time contributor, backend, ready-to-merge

#14893 [Improvement][API] Support to check if the worker group has been used by any tasks or schedulers when users delete or rename it.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/WorkerGroupServiceTest.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#14909 [Fix-14907]Fix click to view the history in the task node of the workflow instance
  docs/docs/en/guide/project/workflow-instance.md
  docs/docs/zh/guide/project/workflow-instance.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/TaskInstanceV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/taskInstance/TaskInstanceQueryRequest.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TaskInstanceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TaskInstanceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/v2/TaskInstanceV2ControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskInstanceServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapperTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui/src/views/projects/task/instance/batch-task.tsx
  dolphinscheduler-ui/src/views/projects/task/instance/use-table.ts
Labels: UI, backend, document, ready-to-merge

#14926 [Bug][Worker]Global and local parameters are mismatch in SQL task
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTaskTest.java
Labels: bug, backend, ready-to-merge

#14919 [Improvement-14916][dolphinscheduler-alert] alert message contains the taskPriority
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessAlertContent.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskAlertContent.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#14921 [fix-#14918] add missing ddl
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: bug, backend, ready-to-merge

#14924 [Bug] Dependent components cannot be justified and viewed
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-node-status.ts
Labels: bug, UI, ready-to-merge, 3.2.1

#14936 Fix the ephemeralId will not be deleted before jdbc-registry closed.
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/task/EphemeralDateManager.java
Labels: bug, backend, ready-to-merge

#14617 [Fix-14546] seatunnel unable submit spark job to spark
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/spark/SeatunnelSparkTask.java
Labels: bug, first time contributor, backend, 3.1.x, ready-to-merge

#14912 [Fix-14895][API] Keep printing null if task log file not exist
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
Labels: bug, backend, ready-to-merge, 3.2.1

#14940 [Improvement][Api]Change default zookeeper timeout setting
  dolphinscheduler-api/src/main/resources/application.yaml
Labels: improvement, backend, chore, ready-to-merge, 3.2.1

#14945 [fix-14944][SQL] add missing postgrepsql's ddl in 3.1.x
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.6_schema/postgresql/dolphinscheduler_ddl.sql
Labels: backend

#14902 [Fix-14729] fix problem with the command generated by the flink task
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java
Labels: bug, first time contributor, backend, 3.1.x, ready-to-merge

#14957 Exclude DataSourceAutoConfiguration in WorkerServer
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#14910 [Improvement-14894][dolphinscheduler-alert] alert message contains the operator
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessAlertContent.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManagerTest.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#14955 Set charset in upgrading tools to solve read upgrade sql mojibake
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/sql/ClasspathSqlScriptParser.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/sql/SqlScriptParser.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/sql/SqlScriptRunner.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ScriptRunner.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/sql/ClasspathSqlScriptParserTest.java
  dolphinscheduler-common/src/test/resources/sql/mysql_ddl.sql
  dolphinscheduler-common/src/test/resources/sql/mysql_dml.sql
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/datasource/dao/UpgradeDao.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#14964 [Fix-14963] Fix the error of using shell task to obtain Home variable in Ubuntu system
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/shell/BaseLinuxShellInterceptorBuilder.java
Labels: bug, backend, 3.1.x, ready-to-merge, 3.2.1

#14966 [Bug] [Api] Logback file STDOUT duplicate
  dolphinscheduler-api/src/main/resources/logback-spring.xml
Labels: improvement, backend, ready-to-merge, 3.2.1

#14973 [Improvement] Fix typo for redshift datasource
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
Labels: UI, improvement, ready-to-merge, 3.2.1

#14930 [feature-#14449] add secret in k8s Task
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskMainParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/K8sTaskParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskExecutorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-k8s.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, improvement, backend, kubernetes, ready-to-merge

#14968 [Improvement][Common] Obtain resource information in the k8s environm…
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/KubernetesUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
Labels: first time contributor, improvement, backend, ready-to-merge
