Repository apache/dolphinscheduler, pull requests merged in 2023-07, with the labels that each got.

#14435 [Doc] Support Sqoop in Website
  docs/configs/docsdev.js
Labels: improvement, document, 3.1.x

#14398 [Fix-14397][dao] the task node in the imported workflow definition was not displayed on the task definition page
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskDefinitionLog.java
Labels: bug, first time contributor, backend, 3.1.x

#14423 [Improvement-14371][Hivecli] Add support for hivevar setting in hivecli task
  dolphinscheduler-task-plugin/dolphinscheduler-task-hivecli/src/main/java/org/apache/dolphinscheduler/plugin/task/hivecli/HiveCliTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-hivecli/src/test/java/org/apache/dolphinscheduler/plugin/task/hivecli/HiveCliTaskTest.java
Labels: improvement, backend, 3.2.0

#14443 [Improvement-14442][UI] Uniformly set the label name of parameter
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/menu.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/router/modules/projects.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-hive-cli.ts
Labels: UI, improvement, 3.2.0

#14444 [Fix-14441] [Bug] [Alarm Instance Manage] Search result list error
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/AlertPluginInstanceServiceImpl.java
Labels: bug, backend, 3.1.x

#14426 [Feature-14421][K8S Task] Configurable image pull policy
  docs/docs/en/guide/task/kubernetes.md
  docs/docs/zh/guide/task/kubernetes.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskMainParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/K8sTaskParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskExecutorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sParametersTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-k8s.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: feature, UI, backend, document, 3.2.0

#14450 [Feature-14321][API] Support to complement data in descending or ascending order of date
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ExecuteFunctionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecuteFunctionServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ExecutionOrder.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-form.ts
Labels: feature, UI, backend, 3.2.0

#14433 [Fix] Fix running task instance throught api gots failed
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StreamTaskExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/TaskExecutionContextFactory.java
Labels: bug, backend, 3.1.x

#14459 [Improvement-14457][UT] Improve the expected and actual value of Assertions
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/enums/StatusTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/AuditLogMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/DataSourceUserMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/EnvironmentWorkerGroupRelationMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionLogMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationLogMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProjectMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProjectUserMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/QueueMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ResourceUserMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ScheduleMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/SessionMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionLogMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TenantMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UDFUserMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UdfFuncMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/UserMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapperTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-snowflake/src/test/java/org/apache/dolphinscheduler/plugin/datasource/snowflake/param/SnowflakeDataSourceProcessorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-kubeflow/src/test/java/org/apache/dolphinscheduler/plugin/kubeflow/KubeflowTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/test/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTaskTest.java
Labels: improvement, backend, 3.2.0

#14300 [Improvement][API Test] Add API test cases for process definition controller
  .github/workflows/api-test.yml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/cases/ProcessDefinitionAPITest.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/cases/ProjectAPITest.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/pages/workflow/ProcessDefinitionPage.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/utils/RequestClient.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/workflow-json/test.json
  dolphinscheduler-api-test/dolphinscheduler-api-test-core/src/main/java/org/apache/dolphinscheduler/api/test/core/Constants.java
Labels: improvement, test, CI&CD, 3.2.0

#14461 Remove code owner
  .github/CODEOWNERS
Labels: CI&CD, document, 3.2.0

#14465 [Improvement-14464][Task] Remove the useless taskResultString
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
Labels: improvement, 3.2.0

#13662 Support to use OceanBase like MySQL as metadata database
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
Labels: improvement, backend, sql not sync, 3.2.0

#14448 [fix-#14447]The judgment in k8sUtils#getPodLog is not accurate
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/K8sUtils.java
Labels: bug, backend, 3.1.x

#14480 [Improvement][API Test] Add api test cases for scheduler page
  .github/workflows/api-test.yml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/cases/SchedulerAPITest.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/pages/workflow/SchedulerPage.java
Labels: improvement, test, CI&CD, 3.2.0

#14481 [Improvement][API] Fix some nits in apis
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/cases/ProcessDefinitionAPITest.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/cases/SchedulerAPITest.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/pages/workflow/ProcessDefinitionPage.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/pages/workflow/SchedulerPage.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
Labels: improvement, backend, test, 3.2.0

#14471 [document]Modify the inconsistencies of grammar and wording in README_zh_CN.md
  README_zh_CN.md
Labels: first time contributor, improvement, document, 3.2.0, ready-to-merge

#14460 [Improvement-14456][UI] When making the process online the system should remind user to take care of its offline timing.
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/LoginPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowDefinitionTab.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/table-action.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/timing/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: UI, improvement, e2e, 3.2.0

#14452 [Feature-14339][Parameter] Add parameter combining of project-level parameters
  docs/configs/docsdev.js
  docs/docs/en/guide/parameter/priority.md
  docs/docs/en/guide/parameter/project-parameter.md
  docs/docs/zh/guide/parameter/priority.md
  docs/docs/zh/guide/parameter/project-parameter.md
  docs/img/new_ui/dev/parameter/project_parameter01.png
  docs/img/new_ui/dev/parameter/project_parameter02.png
  docs/img/new_ui/dev/parameter/project_parameter03.png
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectParameterServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProjectParameterControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectParameterServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProjectParameterMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectParameterMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProjectParameterMapperTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceTest.java
Labels: feature, backend, document, 3.2.0

#14492 [Fix-14488][UI] When creating a tenant add the strong validation of its tenant code.
  dolphinscheduler-ui/src/locales/en_US/security.ts
  dolphinscheduler-ui/src/locales/zh_CN/security.ts
  dolphinscheduler-ui/src/views/security/tenant-manage/components/use-modalData.ts
Labels: bug, UI, 3.2.0

#14463 [improvement] DataQuality module improve
  dolphinscheduler-data-quality/src/main/java/org/apache/dolphinscheduler/data/quality/DataQualityApplication.java
  dolphinscheduler-data-quality/src/main/java/org/apache/dolphinscheduler/data/quality/execution/SparkRuntimeEnvironment.java
  dolphinscheduler-data-quality/src/test/java/org/apache/dolphinscheduler/data/quality/SparkApplicationTestBase.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dataquality/src/main/java/org/apache/dolphinscheduler/plugin/task/dq/utils/SparkArgsUtils.java
Labels: improvement, backend, 3.2.0

#14494 [Improvement][Document] Fix worker failover service comment
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/WorkerFailoverService.java
Labels: improvement, backend, 3.2.0

#14501 Polish config, expose rpc config in application.yml
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/AuditPublishService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/ApiConfig.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/AppConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/AuditConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/PythonGatewayConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/TrafficConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/interceptor/RateLimitInterceptor.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/configuration/ApiConfigTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/configuration/AuditConfigurationTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/interceptor/RateLimitInterceptorTest.java
  dolphinscheduler-api/src/test/resources/application.yaml
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/config/MasterConfig.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/MasterRPCServer.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/MasterRpcClient.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/rpc/WorkerRpcClient.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/rpc/WorkerRpcServer.java
Labels: improvement, backend, document, 3.2.0

#12702 [Improvement-12700][Project]Improve the sql of listAuthorizedProjects
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
Labels: improvement, backend, 3.2.0

#13998 [Fix-13987][bom] set 3.17.2 version protobuf-java
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  tools/dependencies/known-dependencies.txt
Labels: bug, backend, 3.2.0

#14267 [Bug] [Seatunnel-Task] Run Mode defaults to run, and you cannot select a null value
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/flink/SeatunnelFlinkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/flink/SeatunnelFlinkTask.java
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sea-tunnel.ts
Labels: bug, first time contributor, UI, backend, 3.1.x

#14500 [Improvement][API-Test] Add api tests for executor controller
  .github/workflows/api-test.yml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/cases/ExecutorAPITest.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/pages/workflow/ExecutorPage.java
Labels: improvement, test, CI&CD, 3.2.0

#14520 [Improvement] Remove the unused newDaemonSingleThreadExecutor
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
Labels: improvement, backend, 3.2.0

#14530 ci: Require up to date before merging
  .asf.yaml
Labels: improvement, CI&CD, 3.2.0

#14534 [Improvement][Worker] No need to kill remote app when appid is empty
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java
Labels: improvement, backend, 3.2.0

#14430 [FIX-14299][api]: check schedule exists
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
Labels: bug, first time contributor, backend, 3.2.0

#14528 [Bug][Core] Fix query process instances by trigger code bug
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
Labels: bug, backend, 3.2.0

#14362 fix terrafrom config bug
  deploy/terraform/aws/.terraform.lock.hcl
  deploy/terraform/aws/README.md
  deploy/terraform/aws/dolphinscheduler-worker.tf
  deploy/terraform/aws/s3-main.tf
  deploy/terraform/aws/zookeeper-main.tf
Labels: bug, 3.2.0, ready-to-merge

#14514 [Improvement][API Test] Add api tests for process instance
  .github/workflows/api-test.yml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/cases/ProcessInstanceAPITest.java
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/pages/workflow/ProcessInstancePage.java
Labels: improvement, test, CI&CD, 3.2.0

#14529 [Bug] [Mater] Not got latest task intance by task code
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnableTest.java
Labels: bug, backend, 3.2.0

#14548 [Typo] standardized license header.
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/rpc/common/ResponseEventType.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/rpc/serializer/ProtoStuffSerializer.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/rpc/serializer/RpcSerializer.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTaskChannelFactory.java
Labels: improvement, backend, 3.2.0

#14539 [Feature-14542][K8S] add prometheus serviceMonitor
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/templates/svc-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/svc-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/svc-dolphinscheduler-master-headless.yaml
  deploy/kubernetes/dolphinscheduler/templates/svc-dolphinscheduler-worker-headless.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: feature, kubernetes, 3.2.0

#14568 [CI] Try to fix flaky CI
  .github/workflows/cluster-test/mysql/dolphinscheduler_env.sh
  .github/workflows/cluster-test/postgresql/dolphinscheduler_env.sh
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowE2ETest.java
Labels: CI&CD, chore, e2e, 3.2.0

#14504 [Fix-14503][Worker] Fix the problem of subprocess cannot be killed
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/WorkerTaskKillProcessor.java
Labels: bug, discussion, backend, 3.2.0

#14571 [Improvement][Task] Mask configYaml in task log
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/log/SensitiveDataConverterTest.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnable.java
Labels: improvement, backend, 3.2.0

#14574 [fix-14517][api] An error occurred while trying to access the Postgres data…
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
Labels: bug, first time contributor, backend, 3.2.0

#14578 [Improvement] Add log for get local NetworkInterface
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/config/AlertConfig.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/config/MasterConfig.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
Labels: improvement, backend, 3.2.0

#14575 [Dependency] Bump h2, snowflake-jdbc, snappy-java version
  dolphinscheduler-bom/pom.xml
  tools/dependencies/known-dependencies.txt
Labels: dependencies, improvement, 3.2.0

#14527 [Improvement-14136][task] Support submitting spark-sql task with the sql file in resource center
  dolphinscheduler-task-plugin/dolphinscheduler-task-hivecli/src/main/java/org/apache/dolphinscheduler/plugin/task/hivecli/HiveCliConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-spark/src/main/java/org/apache/dolphinscheduler/plugin/task/spark/SparkTask.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-hive-cli.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-spark.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-spark.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, improvement, backend, 3.2.0

#14343 [Fix-14303][Master] Workflow with sub_process task can't be stopped w…
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/SubTaskProcessor.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/SubProcessTaskTest.java
Labels: bug, backend, 3.1.x

#14577 [Bug][dolphinscheduler-api]validated for duplicate username when creating or registering a user
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
Labels: bug, backend, 3.2.0

#14573 [Feature-14505][UI] Support to set project-level preferences
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectPreferenceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProjectPreferenceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectPreferenceServiceImpl.java
  dolphinscheduler-api/src/main/resources/i18n/messages.properties
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProjectPreferenceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectPreferenceServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProjectPreference.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProjectPreferenceMapper.java
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProjectPreferenceMapperTest.java
  dolphinscheduler-ui/src/components/form/use-form.ts
  dolphinscheduler-ui/src/layouts/content/use-dataList.ts
  dolphinscheduler-ui/src/locales/en_US/menu.ts
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/menu.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/router/modules/projects.ts
  dolphinscheduler-ui/src/service/modules/projects-preference/index.ts
  dolphinscheduler-ui/src/service/modules/projects-preference/types.ts
  dolphinscheduler-ui/src/views/projects/preference/components/use-alert-group.ts
  dolphinscheduler-ui/src/views/projects/preference/components/use-tenant.ts
  dolphinscheduler-ui/src/views/projects/preference/components/use-warning-type.ts
  dolphinscheduler-ui/src/views/projects/preference/detail.tsx
  dolphinscheduler-ui/src/views/projects/preference/index.tsx
  dolphinscheduler-ui/src/views/projects/preference/use-form.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/timing-modal.tsx
Labels: feature, UI, backend, miss:docs, 3.2.0

#14584 Support parse ipv6
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/LoggerServiceTest.java
  dolphinscheduler-registry/dolphinscheduler-registry-api/src/main/java/org/apache/dolphinscheduler/registry/api/RegistryClient.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/utils/Host.java
  dolphinscheduler-remote/src/test/java/org/apache/dolphinscheduler/remote/utils/HostTest.java
Labels: bug, backend, 3.2.0

#14588 [Improvement-14587][UI] Improve the environment component
  dolphinscheduler-ui/src/views/projects/preference/components/use-alert-group.ts
  dolphinscheduler-ui/src/views/projects/preference/components/use-tenant.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-environment-name.ts
Labels: UI, improvement, 3.2.0

#14590 Expose swagger.properties to release
  dolphinscheduler-api/src/main/assembly/dolphinscheduler-api-server.xml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/SwaggerConfiguration.java
  dolphinscheduler-api/src/main/resources/swagger.properties
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DsVersion.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/DsVersionMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/DsVersionDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/DsVersionDaoImpl.java
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: improvement, backend, 3.2.0, ready-to-merge

#14523 impv: Correct datax execute and python execute script name
  .github/workflows/cluster-test/mysql/dolphinscheduler_env.sh
  .github/workflows/cluster-test/postgresql/dolphinscheduler_env.sh
  README.md
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/docs/en/architecture/configuration.md
  docs/docs/en/faq.md
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/integration/rainbond.md
  docs/docs/en/guide/task/datax.md
  docs/docs/en/guide/task/openmldb.md
  docs/docs/en/guide/task/pytorch.md
  docs/docs/en/guide/upgrade/incompatible.md
  docs/docs/zh/architecture/configuration.md
  docs/docs/zh/faq.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/integration/rainbond.md
  docs/docs/zh/guide/task/datax.md
  docs/docs/zh/guide/task/openmldb.md
  docs/docs/zh/guide/task/pytorch.md
  docs/docs/zh/guide/upgrade/incompatible.md
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/EnvironmentServiceTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ClusterMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/EnvironmentMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/utils/TaskCacheUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/test/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/test/java/org/apache/dolphinscheduler/plugin/task/python/PythonTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PythonEnvManager.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/test/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-pytorch.ts
  dolphinscheduler-ui/src/views/security/environment-manage/components/environment-modal.tsx
Labels: UI, improvement, backend, CI&CD, document, 3.2.0, ready-to-merge

#14594 [Fix][SeaTunnel] Fix wrong judgment condition when building parameters of seatunnel task node.
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/flink/SeatunnelFlinkTask.java
Labels: bug, backend, 3.1.x, ready-to-merge

#14595 [release][3.1.8] Added docs for release 3.1.8
  deploy/docker/.env
  deploy/kubernetes/dolphinscheduler/Chart.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/configs/docsdev.js
  docs/configs/site.js
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/history-versions.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/history-versions.md
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.8_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.8_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.8_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.8_schema/postgresql/dolphinscheduler_dml.sql
Labels: backend, document, 3.1.x

#14596 Disable dependabot pull requests
  .asf.yaml
  .github/CODEOWNERS
Labels: chore, 3.2.0

#14599 [CI] [E2E] Increase container healthcheck timeout
  dolphinscheduler-e2e/dolphinscheduler-e2e-core/src/main/java/org/apache/dolphinscheduler/e2e/core/DolphinSchedulerExtension.java
Labels: chore, e2e, 3.2.0

#14391 [Feature] doris add datasource
  docs/configs/docsdev.js
  docs/docs/en/guide/datasource/doris.md
  docs/docs/zh/guide/datasource/doris.md
  docs/img/new_ui/dev/datasource/doris.png
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/DataSourceConstants.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-all/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/main/java/org/apache/dolphinscheduler/plugin/doris/DorisDataSourceChannel.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/main/java/org/apache/dolphinscheduler/plugin/doris/DorisDataSourceChannelFactory.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/main/java/org/apache/dolphinscheduler/plugin/doris/DorisDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/main/java/org/apache/dolphinscheduler/plugin/doris/param/DorisConnectionParam.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/main/java/org/apache/dolphinscheduler/plugin/doris/param/DorisDataSourceParamDTO.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/main/java/org/apache/dolphinscheduler/plugin/doris/param/DorisDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/test/java/org/apache/dolphinscheduler/plugin/doris/DorisDataSourceChannelFactoryTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/test/java/org/apache/dolphinscheduler/plugin/doris/DorisDataSourceChannelTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/test/java/org/apache/dolphinscheduler/plugin/doris/param/DorisDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/test/java/org/apache/dolphinscheduler/plugin/doris/provider/JDBCDataSourceProviderTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/test/java/org/apache/dolphinscheduler/plugin/doris/utils/DataSourceUtilsTest.java
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/enums/DbType.java
  dolphinscheduler-ui/src/service/modules/data-source/types.ts
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasource.ts
Labels: feature, first time contributor, UI, backend, document, 3.2.0, ready-to-merge

#14379 [Feature-13763][K8S Task] collect real-time log
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/am/KubernetesApplicationManager.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/am/KubernetesApplicationManagerContext.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskExecutorTest.java
Labels: feature, backend, kubernetes, 3.2.0, ready-to-merge

#14608 [CI] [Chore] Increase browser container timeout
  dolphinscheduler-e2e/dolphinscheduler-e2e-core/src/main/java/org/apache/dolphinscheduler/e2e/core/DolphinSchedulerExtension.java
Labels: chore, e2e, 3.2.0, ready-to-merge

#14592 [Improvement] Dataquality code style enhance
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataSourceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataSourceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
Labels: improvement, backend, 3.2.0, ready-to-merge

#14604 [Fix-14603] phone Number validate
  dolphinscheduler-ui/src/views/security/user-manage/components/use-user-detail.ts
Labels: bug, UI, 3.2.0, ready-to-merge

#14591 Add host/port in heartbeat
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/registry/AlertHeartbeatTask.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/AlertServerHeartBeat.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/HeartBeat.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/MasterHeartBeat.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/WorkerHeartBeat.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/task/MasterHeartBeatTask.java
  dolphinscheduler-registry/dolphinscheduler-registry-api/src/main/java/org/apache/dolphinscheduler/registry/api/RegistryClient.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/task/WorkerHeartBeatTask.java
Labels: improvement, backend, document, 3.2.0, ready-to-merge

#14605 [Fix-14601][UI] Ironed out the issue with choosing an environment on the task form of both types of DMS and DATASYNC.
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-datasync.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-dms.ts
Labels: bug, UI, 3.2.0, ready-to-merge

#14597 [Improvement][K8S] Disable delete namespaces in the K8S cluster
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/k8s/K8sClientService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/K8SNamespaceServiceImpl.java
Labels: improvement, backend, 3.2.0, ready-to-merge

#14611 [Fix-13976][dao] task complete contain force success state
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14613 [Improvement][Document] Fix process utils comment typo
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java
Labels: improvement, backend, 4.0.0, ready-to-merge

#14600 [DISCUSS]ci: Mergeable must have ready-to-merge and not require version
  .github/mergeable.yml
Labels: discussion, CI&CD, chore, 3.2.0, ready-to-merge

#14193 datasource test and sql task Remove connection pool issues is #14179
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/client/CommonDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/AzureSQLDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/HiveDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-kyuubi/src/main/java/org/apache/dolphinscheduler/plugin/datasource/kyuubi/KyuubiDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-kyuubi/src/test/java/org/apache/dolphinscheduler/plugin/datasource/kyuubi/KyuubiDataSourceClientTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-redshift/src/main/java/org/apache/dolphinscheduler/plugin/datasource/redshift/RedshiftDataSourceClient.java
Labels: bug, first time contributor, backend, priority:high, ready-to-merge

#14561 [Fix-14512][BOM] kubernetes-client version conflict
  dolphinscheduler-alert/dolphinscheduler-alert-server/pom.xml
  dolphinscheduler-api/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-bucket4j-core.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-client-java.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-jose4j.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-spring-cloud-kubernetes-client-autoconfig.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-spring-cloud-kubernetes-client-config.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-spring-cloud-starter-kubernetes-client-config.txt
  dolphinscheduler-master/pom.xml
  dolphinscheduler-standalone-server/pom.xml
  dolphinscheduler-worker/pom.xml
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: bug, backend, priority:high, 3.2.0, ready-to-merge

#14392 [Improvement-14269][API] Bind task group with project
  docs/docs/en/guide/resource/task-group.md
  docs/docs/zh/guide/resource/task-group.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TaskGroupControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskGroupServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskGroupMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TaskGroupMapperTest.java
  dolphinscheduler-ui/src/views/resource/task-group/option/components/form-modal.tsx
  dolphinscheduler-ui/src/views/resource/task-group/option/use-table.ts
Labels: discussion, UI, improvement, backend, document, 3.2.0, ready-to-merge

#14614 [Improvement][HELM] add driver-class-name
  deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: improvement, 3.2.0, ready-to-merge

#14628 [CI] [E2E] Increase e2e containers timeout
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/datasource-clickhouse/docker-compose.yaml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/datasource-hive/docker-compose.yaml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/datasource-mysql/docker-compose.yaml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/datasource-postgresql/docker-compose.yaml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/datasource-sqlserver/docker-compose.yaml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/file-manage/docker-compose.yaml
  dolphinscheduler-e2e/dolphinscheduler-e2e-core/src/main/java/org/apache/dolphinscheduler/e2e/core/DolphinSchedulerExtension.java
Labels: CI&CD, chore, e2e, 3.2.0, ready-to-merge

#14626 Revert "datasource test and sql task Remove connection pool issues is #14179"
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/client/CommonDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-azure-sql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/azuresql/AzureSQLDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/HiveDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-kyuubi/src/main/java/org/apache/dolphinscheduler/plugin/datasource/kyuubi/KyuubiDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-kyuubi/src/test/java/org/apache/dolphinscheduler/plugin/datasource/kyuubi/KyuubiDataSourceClientTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-redshift/src/main/java/org/apache/dolphinscheduler/plugin/datasource/redshift/RedshiftDataSourceClient.java
Labels: bug, backend, 3.1.x, ready-to-merge

#14633 [Chore] [E2E] Add e2e optional for ci
  .github/workflows/e2e.yml
Labels: CI&CD, chore, e2e, 3.2.0, ready-to-merge

#14606 [Fix-14566][master] Fix serial_wait command_params does not replace global_params
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14634 [CI][E2E] Upgrade e2e dependency version
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/ClickhouseDataSourceE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/ClusterE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/EnvironmentE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/FileManageE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/FunctionManageE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/HiveDataSourceE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/MysqlDataSourceE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/PostgresDataSourceE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/ProjectE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/QueueE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/SqlServerDataSourceE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/TenantE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/TokenE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/UdfManageE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/UserE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkerGroupE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowSwitchE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/LoginPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/common/CodeEditor.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/common/NavBarPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/datasource/DataSourcePage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowDefinitionTab.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowRunDialog.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/SubWorkflowTaskForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/SwitchTaskForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/TaskNodeForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/FileManagePage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/ResourcePage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/UdfManagePage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/EnvironmentPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TokenPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/UserPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-core/src/main/java/org/apache/dolphinscheduler/e2e/core/DolphinSchedulerExtension.java
  dolphinscheduler-e2e/pom.xml
Labels: CI&CD, chore, e2e, 3.2.0, ready-to-merge

#10776 [Fix-10795][plugin] sqoop task query columns bug
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/SqoopColumnType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/generator/sources/MySQLSourceGenerator.java
Labels: bug, backend, 3.2.0, ready-to-merge

#13046 [Improvement-4375][api] cannot delete yarn queue
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/QueueController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/QueueService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/QueueControllerTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TenantMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TenantMapper.xml
  dolphinscheduler-ui/src/locales/en_US/security.ts
  dolphinscheduler-ui/src/locales/zh_CN/security.ts
  dolphinscheduler-ui/src/service/modules/queues/index.ts
  dolphinscheduler-ui/src/views/security/yarn-queue-manage/use-table.ts
Labels: UI, improvement, backend, priority:middle, 3.2.0, ready-to-merge

#14555 [Improvement][CI] deploy to k8s
  .github/workflows/e2e-k8s.yml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: improvement, CI&CD, priority:high, 3.2.0, ready-to-merge

#14638 [Feature] Support filter restrict network interface
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/PropertyUtilsTest.java
Labels: improvement, backend, document, 3.1.x, 3.2.0, ready-to-merge

#14581 [Improvement][Parameter] Improve the order of project parameter
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectParameterMapper.xml
Labels: improvement, backend, 3.2.0, ready-to-merge

#14645 [Improvement] Support get property from env/jvm/common.properties
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TenantServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UdfFuncServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TenantControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UdfFuncServiceTest.java
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/pom.xml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/config/IPropertyDelegate.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/config/ImmutablePriorityPropertyDelegate.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/config/ImmutablePropertyDelegate.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/PropertyUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/config/ImmutablePriorityPropertyDelegateTest.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/config/ImmutablePropertyDelegateTest.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/FileUtilsTest.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/PropertyUtilsTest.java
  dolphinscheduler-common/src/test/resources/common.properties
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtilsTest.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperator.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/shell/BaseLinuxShellInterceptorBuilder.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionCheckerUtils.java
Labels: improvement, backend, 3.2.0, ready-to-merge

#14034 [Fix-14008][registry] cache keep alive lease
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/main/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdKeepAliveLeaseManager.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/main/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdRegistry.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/test/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdKeepAliveLeaseManagerTest.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14650 [Improvement][UI] Image pull policy in the K8S task provides default values
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-k8s.ts
Labels: UI, improvement, 3.2.0, ready-to-merge

#14666 [3.1.8-prepare][Fix-14008][registry] cache keep alive lease #14034
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/main/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdKeepAliveLeaseManager.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/main/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdRegistry.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/test/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdKeepAliveLeaseManagerTest.java
Labels: backend

#14670 [3.1.8-prepare] Use adhoc connection in sql/procedure task
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataSourceServiceTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
Labels: backend
