Repository apache/dolphinscheduler, pull requests merged in 2023-10, with the labels that each got.

#14986 [Bug][Master] fix duplicate event, avoid event stacking
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java
Labels: bug, backend, 3.1.x

#14989 Fix task log appender will not be closed immediate after throwing exception
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/MasterTaskExecuteRunnable.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#14988 [Improvement][Task] Mask password in task log
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/DataSourceConstants.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/log/SensitiveDataConverterTest.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#14934 [Improvement][K8S] K8S task support passing context parameters to downstream task
  docs/docs/en/guide/parameter/context.md
  docs/docs/zh/guide/parameter/context.md
  docs/img/new_ui/dev/parameter/k8s_context_param.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/VarPoolUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskExecutorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/VarPoolUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskTest.java
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-k8s.ts
Labels: UI, improvement, backend, document, ready-to-merge, 3.2.1

#15006 Revert "[Bug][Master] fix duplicate event, avoid event stacking"
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java
Labels: backend

#14972 [Improvement][Alert] HTTP Related Alert plugin add retry logic
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-api/src/main/java/org/apache/dolphinscheduler/alert/api/HttpServiceRetryStrategy.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-dingtalk/src/main/java/org/apache/dolphinscheduler/plugin/alert/dingtalk/DingTalkSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/HttpRequestUtil.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-pagerduty/src/main/java/org/apache/dolphinscheduler/plugin/alert/pagerduty/PagerDutySender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-slack/src/main/java/org/apache/dolphinscheduler/plugin/alert/slack/SlackSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-telegram/src/main/java/org/apache/dolphinscheduler/plugin/alert/telegram/TelegramSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-webexteams/src/main/java/org/apache/dolphinscheduler/plugin/alert/webexteams/WebexTeamsSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-wechat/src/main/java/org/apache/dolphinscheduler/plugin/alert/wechat/WeChatSender.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#15005 [Doc]fix typo
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: document, ready-to-merge

#15012 [Improvement][Master] Calculate the remainTime then we set the delay execution.
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/LogicITaskInstanceDispatchOperationFunction.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/GlobalTaskInstanceDispatchQueueLooper.java
Labels: first time contributor, improvement, backend, ready-to-merge

#15004 Reduce the size of tarball to continue ASF release
  dolphinscheduler-alert/dolphinscheduler-alert-server/pom.xml
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/pom.xml
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-dist/src/main/assembly/dolphinscheduler-bin.xml
  dolphinscheduler-master/pom.xml
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/TaskMetrics.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-oss/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-all-prune/pom.xml
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-tools/src/main/assembly/dolphinscheduler-tools.xml
  dolphinscheduler-tools/src/main/dist-bin/create-demo-processes.sh
  dolphinscheduler-tools/src/main/dist-bin/migrate-resource.sh
  dolphinscheduler-tools/src/main/dist-bin/upgrade-schema.sh
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: backend, test

#15008 [Bug] fix duplicate event
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java
Labels: bug, backend, 3.1.x

#15003 [Bug] [Resource] fix resource delete bug
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TaskDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskDefinitionServiceImplTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskDefinition.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.xml
Labels: improvement, backend, ready-to-merge, 3.2.1

#15018 [Improvement][workFlow] online,offline and delete Button, edge Popconfirm message does not take effect
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/table-action.tsx
  dolphinscheduler-ui/src/views/projects/workflow/instance/components/table-action.tsx
  dolphinscheduler-ui/src/views/projects/workflow/instance/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/table/table-action.tsx
Labels: UI, improvement, ready-to-merge, 3.2.1

#14954 [improvement][Resources] Improve details page return to the previous list page (#14951)
  dolphinscheduler-ui/src/views/resource/components/resource/edit/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/edit/use-edit.ts
  dolphinscheduler-ui/src/views/resource/components/resource/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/table/use-table.ts
Labels: bug, UI, 3.1.x, ready-to-merge, 3.2.1

#15022 Delete File generated by UT
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/FileUtilsTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/utils/TaskCacheUtilsTest.java
Labels: improvement, backend, ready-to-merge

#15027 Recover md config content
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: bug, document, ready-to-merge, 3.2.1

#15028 [Doc] remove skywalking, update note
  docs/docs/en/contribute/development-environment-setup.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/contribute/development-environment-setup.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: document, ready-to-merge, 3.2.1

#15019 Add dolphinscheduler-dao-plugin module
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/resources/application.yaml
  dolphinscheduler-api/pom.xml
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/MonitorServiceImpl.java
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/MonitorServiceTest.java
  dolphinscheduler-api/src/test/resources/application.yaml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/sql/ClasspathSqlScriptParser.java
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-api/pom.xml
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-api/src/main/java/org/apache/dolphinscheduler/dao/plugin/api/DaoPluginConfiguration.java
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-api/src/main/java/org/apache/dolphinscheduler/dao/plugin/api/monitor/DatabaseMetrics.java
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-api/src/main/java/org/apache/dolphinscheduler/dao/plugin/api/monitor/DatabaseMonitor.java
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-h2/pom.xml
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-h2/src/main/java/org/apache/dolphinscheduler/dao/plugin/h2/H2DaoPluginConfiguration.java
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-h2/src/main/java/org/apache/dolphinscheduler/dao/plugin/h2/monitor/H2Monitor.java
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-mysql/pom.xml
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-mysql/src/main/java/org/apache/dolphinscheduler/dao/plugin/mysql/MysqlDaoPluginConfiguration.java
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-mysql/src/main/java/org/apache/dolphinscheduler/dao/plugin/mysql/monitor/MysqlMonitor.java
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-plugin-all/pom.xml
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-postgresql/pom.xml
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-postgresql/src/main/java/org/apache/dolphinscheduler/dao/plugin/postgresql/PostgresqlDaoPluginConfiguration.java
  dolphinscheduler-dao-plugin/dolphinscheduler-dao-postgresql/src/main/java/org/apache/dolphinscheduler/dao/plugin/postgresql/monitor/PostgresqlMonitor.java
  dolphinscheduler-dao-plugin/pom.xml
  dolphinscheduler-dao/pom.xml
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/MonitorDBDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/H2Performance.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/MySQLPerformance.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/PostgreSQLPerformance.java
  dolphinscheduler-dao/src/test/resources/application.yaml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-standalone-server/pom.xml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: improvement, backend, core, ready-to-merge, 3.2.1

#15024 [Improvement][Alert] Alert plugin enhance fail message
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/MailSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-http/src/main/java/org/apache/dolphinscheduler/plugin/alert/http/HttpSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-pagerduty/src/main/java/org/apache/dolphinscheduler/plugin/alert/pagerduty/PagerDutySender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-webexteams/src/main/java/org/apache/dolphinscheduler/plugin/alert/webexteams/WebexMessage.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-webexteams/src/main/java/org/apache/dolphinscheduler/plugin/alert/webexteams/WebexTeamsSender.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#15039 chore: release version 3.2.0
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: document, ready-to-merge

#15032 [Docs] fix typo
  docs/docs/zh/guide/resource/file-manage.md
Labels: first time contributor, improvement, document, 3.1.x, ready-to-merge

#14967 Fix When the task instance status is 'STOP'
  dolphinscheduler-ui/src/common/common.ts
  dolphinscheduler-ui/src/common/types.ts
Labels: bug, UI, ready-to-merge, 3.2.1

#14889 [Fix-14885][pom] fix spotless format file path
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-all/pom.xml
  pom.xml
Labels: improvement, backend, ready-to-merge, 3.3.0

#15053 Set kubectl version to v1.28.3
  .github/workflows/e2e-k8s.yml
Labels: bug, CI&CD, ready-to-merge

#15051 Fix missing Kyuubi type in UI
  dolphinscheduler-ui/src/service/modules/data-source/types.ts
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
Labels: bug, UI, ready-to-merge

#15057 [Bug] remove sub workflow finish notify
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java
Labels: bug, backend, 3.0.x, 3.1.x, ready-to-merge, 3.2.1

#15063 Add IT for initialize application and upgrade application under mysql5/postgre16 environment
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/jupiter/DatabaseContainerProvider.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/jupiter/DolphinSchedulerDatabaseContainer.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/jupiter/DolphinSchedulerDatabaseContainerExtension.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/mysql/BaseDolphinSchedulerDatabaseWithMysqlIT.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/mysql/DolphinSchedulerMysqlProfile.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/mysql/MysqlDatabaseContainerProvider.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/mysql/v5/InitializeWithMysqlIT.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/mysql/v5/UpgradeWithMysqlIT.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/mysql/v8/InitializeWithMysqlIT.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/mysql/v8/UpgradeWithMysqlIT.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/BaseDolphinSchedulerManagerWithPostgresqlIT.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/DolphinSchedulerPostgresqlProfile.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/PostgresqlDatabaseContainerProvider.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/v11/InitializeWithPostgresqlIT.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/v11/UpgradeWithPostgresqlIT.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/v16/InitializeWithPostgresql16IT.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/v16/UpgradeWithPostgresql16IT.java
Labels: improvement, backend, ready-to-merge

#14702 [Feature-14678][Master][UI]Dependent task parameter passing
  docs/docs/en/guide/task/dependent.md
  docs/docs/zh/guide/task/dependent.md
  docs/img/tasks/demo/dependent_task01.png
  docs/img/tasks/demo/dependent_task02.png
  docs/img/tasks/demo/dependent_task03.png
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/dependent/DependentAsyncTaskExecuteFunction.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/model/DependentItem.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/DependentUtils.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dependent.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, backend, document, ready-to-merge

#14801 [Fix-15036] [API] Fix task definition edit doesn't work
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskDefinitionServiceImplTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
Labels: bug, first time contributor, backend, 3.1.x, ready-to-merge, 3.2.1

#15062 Fix SqlTask cannot split the given sql when browser in windows
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/utils/SqlSplitUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/utils/SqlSplitUtilsTest.java
Labels: bug, backend, ready-to-merge
