Repository apache/dolphinscheduler, pull requests merged in 2023-03, with the labels that each got.

#12784 [Improvement-12782][UT] Add UT for the 13 implementations of ResourceAcquisitionAndPermissionCheck
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/permission/ResourcePermissionCheckServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/AccessTokenResourcePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/AlertGroupResourcePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/AlertPluginInstanceResourcePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/DataSourceResourcePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/EnvironmentResourcePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/FilePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/K8sNamespaceResourcePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/ProjectsResourcePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/QueueResourcePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/TaskGroupPermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/TenantResourcePermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/UdfFuncPermissionCheckTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/permission/WorkerGroupResourcePermissionCheckTest.java
Labels: improvement, backend, test, 3.2.0

#12698 [Improvement-12697][UT] Improve the ProjectServiceTest
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectServiceTest.java
Labels: improvement, backend, 3.2.0

#13628 [BUG][UI] Flink task display right version and deploy mode
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-flink.ts
Labels: bug, UI, 3.1.x

#13660 Fix task instance log order might be wrong due to async print
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/LogUtils.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/log/TaskInstanceLogHeader.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskDispatchProcessor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/TaskCallbackImpl.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecuteRunnable.java
Labels: improvement, backend, 3.2.0

#13641 docs(file-manage): The file in File manage is a relative path, not an absolute path
  docs/docs/en/guide/resource/file-manage.md
  docs/docs/zh/guide/resource/file-manage.md
Labels: bug, first time contributor, document, 3.1.x

#13663 Add missing placeholder
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/am/KubernetesApplicationManager.java
Labels: improvement, backend, 3.2.0

#13671 [Improvement][master-sql] Optimize the sql for queryTheHighestPriorityTasks
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.xml
Labels: improvement, backend, 3.2.0

#13676 [Improvement][api] Remove unless code in ResourcesServiceImpl
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
Labels: improvement, backend, 3.2.0

#13675 [Feature][DataSource] add oceanbase datasource
  .dlc.json
  docs/configs/docsdev.js
  docs/docs/en/guide/datasource/oceanbase.md
  docs/docs/zh/guide/datasource/oceanbase.md
  docs/img/new_ui/dev/datasource/oceanbase.png
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/DataSourceConstants.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-all/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oceanbase/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oceanbase/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oceanbase/OceanBaseDataSourceChannel.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oceanbase/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oceanbase/OceanBaseDataSourceChannelFactory.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oceanbase/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oceanbase/OceanBaseDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oceanbase/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oceanbase/param/OceanBaseConnectionParam.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oceanbase/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oceanbase/param/OceanBaseDataSourceParamDTO.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oceanbase/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oceanbase/param/OceanBaseDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/enums/DbType.java
  dolphinscheduler-ui/src/locales/en_US/datasource.ts
  dolphinscheduler-ui/src/locales/zh_CN/datasource.ts
  dolphinscheduler-ui/src/service/modules/data-source/types.ts
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
Labels: feature, UI, backend, document, 3.2.0

#13680 [improve-#13665] improve datax parser if sql contain *
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
Labels: improvement, backend, 3.2.0

#13616 feat: Python return datasource object and allow filter by type
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
Labels: feature, backend, 3.1.x

#13551 feat: Python add online_schedule for workflow control schedule state
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java
Labels: feature, backend, 3.1.x

#13709 Fix-13708 [Bug] [Resouces] Resource file search paging error
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
Labels: bug, backend, 3.2.0

#13640 [Feature][Metrics] Tag workflow related metrics with process definition code (workflow id)
  docs/docs/en/guide/metrics/metrics.md
  docs/docs/zh/guide/metrics/metrics.md
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/MetricsCleanUpService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/MetricsCleanUpServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowStartEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/WorkflowTimeoutStateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/ProcessInstanceMetrics.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/WorkflowMetricsCleanUpProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/MasterRPCServer.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/MasterFailoverService.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/service/FailoverServiceTest.java
  dolphinscheduler-meter/src/main/resources/grafana/DolphinSchedulerMaster.json
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/CommandType.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/WorkflowMetricsCleanUpCommand.java
Labels: feature, backend, document, 3.2.0

#13700 [Doc] Add OceanBase to supported list
  README.md
  README_zh_CN.md
Labels: feature, document, 3.2.0

#13689 Clearer task runnable.
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/IParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/main/java/org/apache/dolphinscheduler/plugin/task/java/JavaTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-openmldb/src/main/java/org/apache/dolphinscheduler/plugin/task/openmldb/OpenmldbTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-python/src/main/java/org/apache/dolphinscheduler/plugin/task/python/PythonTask.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java
Labels: improvement, backend, 3.2.0

#13718 [Bug-13666] remove WORKER_GROUP in values.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: bug, backend, 3.1.x

#13719 Ignore unknown VM options in start.sh
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/start.sh
  dolphinscheduler-api/src/main/bin/start.sh
  dolphinscheduler-master/src/main/bin/start.sh
  dolphinscheduler-worker/src/main/bin/start.sh
Labels: improvement, backend, 3.2.0

#13716 [doc] update kubernetes doc
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: bug, document, 3.2.0

#13649 [Feature-13419][Remote Logging] Add support for writing task logs to S3
  docs/docs/en/guide/remote-logging.md
  docs/docs/zh/guide/remote-logging.md
  dolphinscheduler-common/pom.xml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/OssRemoteLogHandler.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/RemoteLogHandlerFactory.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/RemoteLogService.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/RemoteLogUtils.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/S3RemoteLogHandler.java
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/log/remote/RemoteLogHandlerTest.java
Labels: feature, backend, document, 3.2.0

#13562 [Feature-13428][Resource Center] Add support for Google Cloud Storage in the resource center
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/docs/en/architecture/configuration.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/resource/configuration.md
  docs/docs/zh/architecture/configuration.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/resource/configuration.md
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/docker/file-manage/common.properties
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ResUploadType.java
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-api-common.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-auto-value-annotations.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-auto-value.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-conscrypt-openjdk-uber.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-gapic-google-cloud-storage-v2.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-gax-grpc.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-gax-httpjson.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-gax.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-api-client.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-api-services-storage.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-auth-library-credentials.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-auth-library-oauth2-http.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-cloud-core-grpc.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-cloud-core-http.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-cloud-core.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-cloud-storage.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-http-client-apache-v2.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-http-client-appengine.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-http-client-gson.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-http-client-jackson2.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-http-client.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-google-oauth-client.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-grpc-alts.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-grpc-auth.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-grpc-google-cloud-storage-v2.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-grpc-googleapis.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-grpc-netty-shaded.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-grpc-services.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-grpc-xds.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-opencensus-api.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-opencensus-contrib-http-util.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-opencensus-proto.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-proto-google-cloud-storage-v2.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-proto-google-iam-v1.txt
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/file-manage/common.properties
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-all/pom.xml
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-api/src/main/java/org/apache/dolphinscheduler/plugin/storage/api/StorageType.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-gcs/pom.xml
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-gcs/src/main/java/org/apache/dolphinscheduler/plugin/storage/gcs/GcsStorageOperator.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-gcs/src/main/java/org/apache/dolphinscheduler/plugin/storage/gcs/GcsStorageOperatorFactory.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-gcs/src/test/java/org/apache/dolphinscheduler/plugin/storage/gcs/GcsStorageOperatorTest.java
  dolphinscheduler-storage-plugin/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/resources/common.properties
  tools/dependencies/known-dependencies.txt
Labels: feature, backend, test, e2e, document, 3.2.0

#13738 [Improvement]update spelling mistake for Constants
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
Labels: backend, document, 3.2.0

#13748 [improve-#13678] add filter in method of ``` setMainJarName ```
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink-stream/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkStreamTask.java
Labels: improvement, backend, 3.2.0

#13767 [Improvement] Test DataSource connection return msg may not internati…
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
Labels: improvement, backend, 3.2.0

#13761 [Fix][Alert] Fix when auth is false and user || pwd null can't send email excection
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/MailSender.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/MailUtilsTest.java
Labels: bug, backend, 3.0.x, 3.1.x

#13773 remove duplicate dependencies
  pom.xml
Labels: first time contributor, improvement, backend, 3.2.0

#13721 [Improvement-13651] Remove useless resources task record
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ResourcesTask.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ResourceTaskMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ResourceTaskMapper.xml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: improvement, backend, 3.2.0

#13787 [Bug-13782] match ')' in setValue regular expression
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/AbstractTaskTest.java
Labels: bug, backend, 3.2.0

#13788 Modify name len to 255
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: improvement, backend, 3.2.0

#13791 Fix retry task instance will loss varpool
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: improvement, backend, 3.2.0

#13735 [fix-13734] [api] Fixed the problem that the corresponding task definition could not be queried after workflow import correctly(#13734)
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskDefinitionLog.java
Labels: bug, backend, 3.2.0

#13805 [Improvement-13803][UI] The select on the page of the workflow relation can filter options by inputing workflow name.
  dolphinscheduler-ui/src/views/projects/workflow/relation/index.tsx
Labels: UI, improvement, 3.2.0

#13812 Add jdbc registry module
  dolphinscheduler-registry/dolphinscheduler-registry-all/pom.xml
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/README.md
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/pom.xml
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/JdbcOperator.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/JdbcRegistry.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/JdbcRegistryConfiguration.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/JdbcRegistryConstant.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/JdbcRegistryProperties.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/mapper/JdbcRegistryDataMapper.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/mapper/JdbcRegistryLockMapper.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/model/DataType.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/model/JdbcRegistryData.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/model/JdbcRegistryLock.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/task/EphemeralDateManager.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/task/RegistryLockManager.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/task/SubscribeDataManager.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/resources/mysql_registry_init.sql
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/resources/postgresql_registry_init.sql
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/pom.xml
Labels: feature, backend, 3.2.0

#13818 [Improvement][Dependent] support self-dependent
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/ProcessInstanceDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/ProcessInstanceDaoImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/DependentTaskProcessor.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/DependentTaskTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: improvement, backend, 3.2.0

#13668 [Fix-13657][Master]NPE caused by the execution of workflow with startNode and forbidden task
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, 3.0.x

#13654 [Improvement-13653][Remote Logging] Support api-server to get task log from remote target
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/LogUtils.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/processor/BaseLogProcessor.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/processor/GetLogBytesProcessor.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/processor/RollViewLogRequest.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/processor/ViewWholeLogProcessor.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogClient.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/log/LoggerRequestProcessorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/LogUtils.java
Labels: improvement, backend, 3.2.0

#13155 [Bug][Master] fix task failure continue
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, first time contributor, backend, 3.0.x, 3.1.x

#13032 [Bug] [Athena Datasource]Fix datasource other params illegal
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java
Labels: bug, first time contributor, backend, 3.1.x

#13827 fix: Alarm instance port verification
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-dingtalk/src/main/java/org/apache/dolphinscheduler/plugin/alert/dingtalk/DingTalkAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-telegram/src/main/java/org/apache/dolphinscheduler/plugin/alert/telegram/TelegramAlertChannelFactory.java
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/params/base/FormType.java
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/params/input/number/InputNumberParam.java
Labels: bug, backend, 3.2.0

#13764 [fix] DB2 username can not be save
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-db2/src/main/java/org/apache/dolphinscheduler/plugin/datasource/db2/param/Db2DataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-db2/src/test/java/org/apache/dolphinscheduler/plugin/datasource/db2/param/Db2DataSourceProcessorTest.java
Labels: bug, first time contributor, backend, 3.1.x

#13801 [FEATURE][Task Plugin]Add remote-shell task plugin
  docs/configs/docsdev.js
  docs/docs/en/guide/datasource/ssh.md
  docs/docs/en/guide/task/remoteshell.md
  docs/docs/zh/guide/datasource/ssh.md
  docs/docs/zh/guide/task/remoteshell.md
  docs/img/new_ui/dev/datasource/ssh.png
  docs/img/tasks/demo/remote-shell.png
  docs/img/tasks/icons/remoteshell.png
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-api/src/main/resources/task-type-config.yaml
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-all/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/DataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/SSHDataSourceChannel.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/SSHDataSourceChannelFactory.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/SSHDataSourceClient.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/SSHUtils.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/param/SSHConnectionParam.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/param/SSHDataSourceParamDTO.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/param/SSHDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/test/java/org/apache/dolphinscheduler/plugin/datasource/ssh/SSHDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-sshd-scp.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-sshd-sftp.txt
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/datasource/ConnectionParam.java
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/enums/DbType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/main/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/main/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteShellParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/main/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteShellTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/main/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteShellTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/main/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteShellTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/test/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteExecutorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/test/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteShellTaskTest.java
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/remoteshell.png
  dolphinscheduler-ui/public/images/task-icons/remoteshell_hover.png
  dolphinscheduler-ui/src/service/modules/data-source/types.ts
  dolphinscheduler-ui/src/store/project/task-type.ts
  dolphinscheduler-ui/src/store/project/types.ts
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasource.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-remote-shell.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-remote-shell.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
  tools/dependencies/known-dependencies.txt
Labels: feature, UI, backend, document, 3.2.0

#13829 [Fix-13828][api] Fix the problem of work groups have two defult records
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
Labels: bug, first time contributor, backend, 3.1.x

#13839 [release-3.1.5] add release 3.1.5 version
  deploy/docker/.env
  deploy/kubernetes/dolphinscheduler/Chart.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/configs/docsdev.js
  docs/configs/site.js
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/history-versions.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/start/docker.md
  docs/docs/zh/history-versions.md
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
Labels: backend, document, 3.1.x
