Repository apache/dolphinscheduler, pull requests merged in 2023-08, with the labels that each got.

#14667 [Doc] fix built-in typo
  docs/docs/en/guide/parameter/built-in.md
  docs/docs/zh/guide/parameter/built-in.md
Labels: document, 4.0.0, ready-to-merge

#14563 [fix-#14537] the branch that needs to be executed overlaps with another branch, it may not be able to complete the normal execution
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/DagHelperTest.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14676 [Fix-14675][Alert]batchInsert execption
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/AlertSendStatusMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertSendStatusMapper.xml
Labels: bug, backend, 3.2.0, ready-to-merge

#14677 [Workflow] Print WorkflowInstance detail/ TaskInstance detail when finished
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/WorkflowInstanceUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/utils/WorkflowInstanceUtilsTest.java
Labels: first time contributor, improvement, backend, 3.2.0, ready-to-merge

#14669 [Fix-14668][dolphinscheduler-tools] Modify the imported jar package. Use org.apache.commons.lang3.StringUtils.
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/resource/MigrateResourceService.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14682 [Fix-14685] [Task] Remove override method k8sConfigYaml in ShShellInterceptorBuilder
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/shell/sh/ShShellInterceptorBuilder.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14689 [3.1.8] [fix-#14537] the branch that needs to be executed overlaps with another branch, it may not be able to complete the normal execution #14563
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/DagHelperTest.java
Labels: backend

#14687 [Fix-14686][Alert]batchInsert execption
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AlertSendStatusMapper.xml
Labels: bug, backend, 3.2.0, ready-to-merge

#14697 [Fix-14696] [Startup scripts] /bin/java command Argument list too long
  dolphinscheduler-standalone-server/src/main/bin/start.sh
Labels: bug, backend, 3.2.0, ready-to-merge

#14691 [Doc]fix typo
  README.md
Labels: bug, document, 3.2.0, ready-to-merge

#14684 [Fix-14683][pom] upgrade mysql driver version
  docs/docs/en/guide/upgrade/incompatible.md
  docs/docs/zh/guide/upgrade/incompatible.md
  dolphinscheduler-bom/pom.xml
Labels: bug, document, 3.2.0, ready-to-merge

#14707 [3.1.8] Add 3.1.8 release document
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: document, ready-to-merge

#14657 [Improvement][helm] configmap changes automatically trigger restart
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: discussion, improvement, 3.2.0, ready-to-merge

#14718 [Fix-14714][master] package task instance before put into cache
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14725 Fix message in MessageRetryRunner might disorder
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/message/MessageRetryRunner.java
Labels: improvement, backend, 3.2.0, ready-to-merge

#14726 Upgrade JDK17 for Sonar
  .github/workflows/unit-test.yml
Labels: improvement, CI&CD, ready-to-merge

#14716 [Fix-14715] [Resource Center] Modify default fs of local storage plugin
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/LocalStorageOperatorFactory.java
Labels: bug, backend, 3.2.0, ready-to-merge

#13832 Set tenant as the the resource file owner
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionCheckerUtils.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14735 fix fault tolerant enviroment missing
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, ready-to-merge

#14722 [Fix-14721] [K8S Task] Handle job delete event when user manually delete the job in k8s cluster
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14612 [Fix-13972][dao] set default value for command
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Command.java
Labels: improvement, backend, 3.2.0, ready-to-merge

#14680 [Improvement][security] get-user-info API endpoint should not return the user's password in MD5 format
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/UserMapper.xml
Labels: discussion, improvement, backend, ready-to-merge

#14756 [Improvement][UI] Support to disable or enable the project preferences.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectPreferenceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProjectPreferenceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectPreferenceServiceImpl.java
  dolphinscheduler-api/src/main/resources/i18n/messages.properties
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProjectPreferenceControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectPreferenceServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProjectPreference.java
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/service/modules/projects-preference/index.ts
  dolphinscheduler-ui/src/service/modules/projects-preference/types.ts
  dolphinscheduler-ui/src/views/projects/preference/detail.tsx
  dolphinscheduler-ui/src/views/projects/preference/use-form.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/timing-modal.tsx
Labels: UI, improvement, backend, 3.2.0, ready-to-merge

#14762 fix: kubectl version update
  .github/workflows/e2e-k8s.yml
Labels: bug, CI&CD, 3.2.0, ready-to-merge

#14652 [Fix-14646][Worker] Fix match wrong pid on linux server
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java
Labels: bug, backend, 3.1.x, 3.2.0, ready-to-merge

#14761 [Improvement] add dispatch fail times when compare
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/GlobalTaskDispatchWaitingQueueLooper.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/PriorityTaskExecuteRunnable.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/execute/PriorityTaskExecuteRunnableTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskExecutionContext.java
Labels: improvement, backend, 3.2.0, ready-to-merge

#14752 fix: null app-info-path cause NPE
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/command/log/GetAppIdRequest.java
  dolphinscheduler-remote/src/main/java/org/apache/dolphinscheduler/remote/processor/GetAppIdProcessor.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/log/LogClient.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/ProcessUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/LogUtils.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14770 [Fix-14627][dolphinscheduler-ui] Fix there are too many child node in sub_process, it cannot to filter by keywords
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-child-node.ts
Labels: bug, UI, 3.1.x, ready-to-merge

#14743 [Feature][Authentication] support oauth2 login
  docs/docs/en/guide/security/authentication-type.md
  docs/docs/zh/guide/security/authentication-type.md
  docs/img/security/authentication/create-client-credentials-1.png
  docs/img/security/authentication/create-client-credentials-2.png
  docs/img/security/authentication/login-with-oauth2.png
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/AppConfiguration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/configuration/OAuth2Configuration.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/LoginControllerTest.java
  dolphinscheduler-api/src/test/resources/application.yaml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OkHttpUtils.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-ui/src/locales/en_US/login.ts
  dolphinscheduler-ui/src/locales/zh_CN/login.ts
  dolphinscheduler-ui/src/service/modules/login/index.ts
  dolphinscheduler-ui/src/service/modules/login/types.ts
  dolphinscheduler-ui/src/views/login/index.module.scss
  dolphinscheduler-ui/src/views/login/index.tsx
  dolphinscheduler-ui/src/views/login/use-login.ts
Labels: UI, backend, document, miss:docs, ready-to-merge

#14803 Remove `@AccessLogAnnotation` annotation, replace with built-in access log
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/aspect/AccessLogAnnotation.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/aspect/AccessLogAspect.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AccessTokenController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AlertGroupController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AlertPluginInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AuditLogController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/CloudController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ClusterController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataAnalysisController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataSourceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DynamicTaskTypeController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/EnvironmentController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/K8sNamespaceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoggerController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/MonitorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessTaskRelationController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectParameterController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectPreferenceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/QueueController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskGroupController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskInstanceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TenantController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UiPluginController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkFlowLineageController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkerGroupController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/AccessTokenV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/ProcessTaskRelationV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/ProjectV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/QueueV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/ScheduleV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/StatisticsV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/TaskDefinitionV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/TaskInstanceV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/WorkflowInstanceV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/WorkflowV2Controller.java
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/aspect/AccessLogAspectTest.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
Labels: improvement, backend, ready-to-merge

#14808 Fix cache is overriden randomly after build and before tests
  .github/workflows/api-test.yml
  .github/workflows/backend.yml
  .github/workflows/e2e.yml
  .github/workflows/publish-docker.yaml
  .github/workflows/unit-test.yml
Labels: bug, improvement, CI&CD, chore, ready-to-merge

#14821 [Fix-14819][Master] Fix the full log path of logical task is not be set when task is dispatched.
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/LogicITaskInstanceDispatchOperationFunction.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14822 [Fix-14820][Master] Fix the status of logical task is not be correctly changed when task is finished.
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/message/LogicTaskInstanceExecutionFinishEventSender.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14659 [Improvement-14658][etcd] Distinguish between add and update by using pre kv
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/main/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdRegistry.java
Labels: improvement, backend, 3.2.0, ready-to-merge

#14827 Add workflowInstanceHost and taskInstanceHost in ITaskInstanceExecutionEvent
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/ITaskInstanceExecutionEvent.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/TaskInstanceExecutionFinishEvent.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/TaskInstanceExecutionInfoEvent.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/TaskInstanceExecutionRunningEvent.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskEvent.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/message/LogicTaskInstanceExecuteRunningEventSender.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/message/LogicTaskInstanceExecutionFinishEventSender.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/message/MessageRetryRunner.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/message/TaskInstanceExecutionFinishEventSender.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/message/TaskInstanceExecutionInfoUpdateEventSender.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/message/TaskInstanceExecutionRunningEventSender.java
Labels: bug, backend, 3.2.0, ready-to-merge

#14836 ci: Fix wrong condition of beckend
  .github/workflows/backend.yml
Labels: CI&CD, chore, 3.2.0, ready-to-merge

#14831 [Improvement-14830][dolphinscheduler-storage-s3] Allow customization of s3 region
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-s3/src/main/java/org/apache/dolphinscheduler/plugin/storage/s3/S3StorageOperator.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#14829 [Fix-14828][master] check task id not null to avoid NPE
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, ready-to-merge, 3.2.1

#14161 [Fix-14149][master] fix workflow always ready pause
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnableTest.java
Labels: bug, backend, 3.2.0, ready-to-merge
