Repository apache/dolphinscheduler, pull requests merged in 2024-05, with the labels that each got.

#15944 [TEST] increase coverage of project workergroup relation service
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectWorkerGroupRelationServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectWorkerGroupRelationServiceTest.java
Labels: improvement, backend, ready-to-merge, 3.3.0

#15958 [HotFix] [CI] Temporary skipping mergeable check
  .asf.yaml
  .github/mergeable.yml
  .github/workflows/mergeable.yml
Labels: CI&CD, ready-to-merge, 3.2.2, chore

#15884 [FIX] Completed tasks cannot be re-executed in a workflow instance
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, priority:high, ready-to-merge, 3.2.2

#15956 [Fix-15937] Add tenantCode propagation to DynamicCommandUtils.createCommand
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/dynamic/DynamicCommandUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/task/dynamic/DynamicCommandUtilsTest.java
Labels: bug, first time contributor, backend, ready-to-merge, 3.2.2

#15911 [fix-15907] Fix get remote shell exit code is incorrect
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/main/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteExecutor.java
Labels: bug, backend, priority:middle, ready-to-merge, 3.2.2

#15950 [Improvement] Fix the git url command injection in pytorch task(#15873)
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/main/java/org/apache/dolphinscheduler/plugin/task/pytorch/GitProjectManager.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pytorch/src/test/java/org/apache/dolphinscheduler/plugin/task/pytorch/PytorchTaskTest.java
Labels: first time contributor, improvement, backend, ready-to-merge, 3.2.2

#15597 Add link to ETCD/JDBC Registry Guideline
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
Labels: improvement, document, ready-to-merge, 3.3.0

#15970 [Fix-15969] [Helm] No DB Nodes Exist
  deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl
Labels: bug, backend, 3.2.2

#15975 EMR task support replace params placeholder
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrAddStepsTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-emr/src/main/java/org/apache/dolphinscheduler/plugin/task/emr/EmrJobFlowTask.java
Labels: bug, backend, priority:middle, ready-to-merge

#15988 [Doc] Repair resource configuration exist typo
  docs/docs/zh/guide/resource/configuration.md
Labels: first time contributor, improvement, document, ready-to-merge, 3.2.2

#15758 [Improvement] Use safe constructor with snake yaml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/ClassFilterConstructor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/AbstractK8sTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/HttpTaskDefinitionParser.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskExecutorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/HttpTaskDefinitionParserTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/resources/mock_loop_task.yaml
Labels: improvement, backend, priority:high, 3.2.2

#15996 docs: fix spelling
  docs/docs/en/guide/resource/configuration.md
  docs/docs/en/guide/start/docker.md
  docs/docs/en/guide/task/datafactory.md
  docs/docs/en/guide/task/kubernetes.md
  docs/docs/en/guide/task/mlflow.md
  docs/docs/zh/guide/task/datafactory.md
  docs/docs/zh/guide/task/mlflow.md
Labels: bug, minor, document, 3.2.2

#15995 Fix database schema change check failed with pg in ci
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.0.0_schema/postgresql/dolphinscheduler_ddl.sql
Labels: bug, backend, priority:high, 3.2.2

#15993 [Fix-15992] maintain slot index by iterate MasterPriorityQueue orderly
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/MasterPriorityQueue.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/queue/MasterPriorityQueueTest.java
Labels: bug, first time contributor, backend, priority:high, 3.2.2

#15998 [Improvement][Monitor] Add UT for montor
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/DataAnalysisControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/CommandMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ErrorCommandMapperTest.java
Labels: improvement, backend, ready-to-merge, 3.2.2

#16001 Fix workflow instance restart failed due to duplicate key in varpool
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/ApiApplicationServer.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceProcessorProvider.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnableTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/model/Property.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/AbstractParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/SqlParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/VarPoolUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/VarPoolUtilsTest.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecutor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskFilesTransferUtils.java
Labels: bug, backend, priority:high, 3.2.2

#15922 [Feature][Helm] make api/master/worker/alert application.yaml configurable
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
Labels: priority:middle

#16014 Use random port in registry IT
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/test/java/org/apache/dolphinscheduler/plugin/registry/jdbc/MysqlJdbcRegistryTestCase.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/test/java/org/apache/dolphinscheduler/plugin/registry/jdbc/PostgresqlJdbcRegistryTestCase.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-zookeeper/src/test/java/org/apache/dolphinscheduler/plugin/registry/zookeeper/ZookeeperRegistryTestCase.java
Labels: bug, backend, 3.2.2

#16012 Deprecated 2.0.9/3.0.6 upgrade test
  .github/workflows/backend.yml
  dolphinscheduler-tools/src/test/resources/3.0.0_schema/postgresql_3.0.0.sql
Labels: improvement, backend, CI&CD, ready-to-merge, 3.2.2

#16022 docs: fix type in contribute.md
  docs/docs/zh/contribute/join/contribute.md
Labels: first time contributor, improvement, minor, document, ready-to-merge, 3.2.2

#16021 Fix rpc channel leak due to concurrent operation
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/main/java/org/apache/dolphinscheduler/extract/base/client/NettyRemotingClient.java
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/test/java/org/apache/dolphinscheduler/extract/base/utils/HostTest.java
Labels: bug, backend, priority:high, ready-to-merge, 3.2.2

#16027 Fix WorkerTaskExecutorThreadPool#isOverload is incorrect
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecutorHolder.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecutorThreadPool.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/operator/TaskInstanceKillOperationFunction.java
  dolphinscheduler-worker/src/test/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecutorThreadPoolTest.java
Labels: bug, backend, priority:middle, 3.2.2

#16041 [Hotfix] Increase block-until-connected in ZookeeperRegistryTestCase
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-zookeeper/src/main/java/org/apache/dolphinscheduler/plugin/registry/zookeeper/ZookeeperRegistry.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-zookeeper/src/test/resources/application.yaml
Labels: improvement, CI&CD

#16031 [Fix][CI] fix the ci error of E2E-K8S-Execute
  deploy/kubernetes/dolphinscheduler/README.md
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: bug, 3.2.2

#16033 [Improvement][Docs]Correction of Typos in the Chinese Document in appendix.md
  docs/docs/zh/guide/task/appendix.md
Labels: first time contributor, improvement, document, 3.2.2

#15967 [DSIP-39][parameter] Improvement startup parameters/global parameters/project parameters data type
  docs/docs/en/guide/parameter/global.md
  docs/docs/en/guide/parameter/project-parameter.md
  docs/docs/en/guide/parameter/startup-parameter.md
  docs/docs/zh/guide/parameter/global.md
  docs/docs/zh/guide/parameter/project-parameter.md
  docs/docs/zh/guide/parameter/startup-parameter.md
  docs/img/new_ui/dev/parameter/context-subprocess02.png
  docs/img/new_ui/dev/parameter/context_parameter04.png
  docs/img/new_ui/dev/parameter/global_parameter02.png
  docs/img/new_ui/dev/parameter/project_parameter01.png
  docs/img/new_ui/dev/parameter/startup_parameter02.png
  docs/img/new_ui/dev/parameter/startup_parameter04.png
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectParameterController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ExecutorService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProjectParameterService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectParameterServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ExecuteFunctionControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProjectParameterControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProjectParameterServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProjectParameter.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProjectParameterMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectParameterMapper.xml
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.2_schema/mysql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.2_schema/postgresql/dolphinscheduler_ddl.sql
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProjectParameterMapperTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/PropertyUtils.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/service/modules/projects-parameter/types.ts
  dolphinscheduler-ui/src/views/projects/parameter/components/parameter-modal.tsx
  dolphinscheduler-ui/src/views/projects/parameter/components/use-modal.ts
  dolphinscheduler-ui/src/views/projects/parameter/data_type.ts
  dolphinscheduler-ui/src/views/projects/parameter/index.tsx
  dolphinscheduler-ui/src/views/projects/parameter/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-save-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/types.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-modal.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/create/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/detail/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/instance/detail/index.tsx
Labels: feature, UI, backend, DSIP, document, 3.2.2

#16038 [Hotfix] Fix NettyRemotingClient might throw IllegalMonitorStateException
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/main/java/org/apache/dolphinscheduler/extract/base/client/NettyRemotingClient.java
Labels: bug, backend, 3.2.2

#16052 Removed unused StateEventHandleFailure
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/StateEventHandleFailure.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/StateEventHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: improvement, backend, minor

#16054 Remove OmitStackTraceInFastThrow in start.sh
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/jvm_args_env.sh
  dolphinscheduler-api/src/main/bin/jvm_args_env.sh
  dolphinscheduler-master/src/main/bin/jvm_args_env.sh
  dolphinscheduler-standalone-server/src/main/bin/jvm_args_env.sh
  dolphinscheduler-worker/src/main/bin/jvm_args_env.sh
Labels: improvement, backend, ready-to-merge, 3.3.0

#16062 [Fix-16061] modify log msg in `WorkflowExecuteRunnable#isTaskDepsComplete()`
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, ready-to-merge, 3.3.0

#16040 Rename variable QUEUE_MAX_SIZE to QUEUE_INITIAL_SIZE
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/StandByTaskInstancePriorityQueue.java
Labels: improvement, backend, 3.3.0

#16071 Fix sudo enable is false will still check tenant exist
  deploy/kubernetes/dolphinscheduler/README.md
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/TenantConstants.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/config/TenantConfig.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecutor.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/operator/TaskInstanceDispatchOperationFunction.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TenantUtils.java
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: bug, backend, document, priority:low

#16077 [Fix] Fix audit log parma typo
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/OperatorUtils.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/BaseAuditOperator.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/AlertGroupAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/AlertInstanceAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/ClusterAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/DatasourceAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/EnvironmentAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/K8SNamespaceAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/ProcessAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/ProcessInstanceAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/ProjectAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/ResourceAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/ScheduleAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/TaskAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/TaskGroupAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/TaskInstancesAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/TenantAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/TokenAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/UdfFunctionAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/UserAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/WorkerGroupAuditOperatorImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/audit/operator/impl/YarnQueueAuditOperatorImpl.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sqoop/src/main/java/org/apache/dolphinscheduler/plugin/task/sqoop/generator/sources/HdfsSourceGenerator.java
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-linkis.ts
Labels: UI, improvement, backend, minor, ready-to-merge

#16079 docs: fix typos in installation md
  docs/docs/en/guide/installation/cluster.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
Labels: first time contributor, improvement, document, ready-to-merge, 3.3.0

#16085 [Doc] Update ZooKeeper download link
  docs/docs/en/contribute/development-environment-setup.md
  docs/docs/zh/contribute/development-environment-setup.md
Labels: first time contributor, improvement, document, 3.3.0

#16004 [Improvement][Flink] Change Flink command into FLINK_HOME
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink-stream/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java
Labels: improvement, backend, minor, ready-to-merge, 3.3.0

#16089 [Fix][UI] ensure number type field has number type value when edting alarm instance
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/use-form.ts
Labels: bug, UI, 3.3.0

#16088 [Fix][UI] Fix the message toast issue
  dolphinscheduler-ui/src/views/datasource/list/use-detail.ts
  dolphinscheduler-ui/src/views/security/alarm-instance-manage/use-detail.ts
Labels: bug, UI, 3.3.0

#16092 [Bug] Fix Complement data Tenant abnormality
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, first time contributor, backend, priority:high, 3.3.0

#16095 Rename dolphinscheduler-aop to dolphinscheduler-yarn-aop
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-tools/pom.xml
  dolphinscheduler-worker/pom.xml
  dolphinscheduler-yarn-aop/pom.xml
  dolphinscheduler-yarn-aop/src/main/java/org/apache/dolphinscheduler/aop/YarnClientAspect.java
  dolphinscheduler-yarn-aop/src/main/resources/META-INF/aop.xml
  dolphinscheduler-yarn-aop/src/main/resources/log4j.properties
  dolphinscheduler-yarn-aop/src/test/java/org/apache/dolphinscheduler/YarnClientAspectMocTest.java
  dolphinscheduler-yarn-aop/src/test/java/org/apache/dolphinscheduler/poc/YarnClientAspectMoc.java
  dolphinscheduler-yarn-aop/src/test/java/org/apache/dolphinscheduler/poc/YarnClientMoc.java
  dolphinscheduler-yarn-aop/src/test/resources/log4j.properties
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: backend

#16102 Revert "[Improvement] Abnormal characters check"
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/CheckUtils.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/CheckUtilsTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
Labels: backend, priority:high

#16103 Revert "[Improvement] Abnormal characters check (#15824)" (#16102)
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/utils/CheckUtils.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/utils/CheckUtilsTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
Labels: backend
