Repository apache/dolphinscheduler, pull requests merged in 2024-08, with the labels that each got.

#16397 [DSIP-59] remove single task definition code and ui
  docs/docs/en/guide/project/task-definition.md
  docs/docs/zh/guide/project/task-definition.md
  docs/img/new_ui/dev/project/batch-task-definition.png
  docs/img/new_ui/dev/project/stream-task-definition.png
  docs/img/new_ui/dev/project/stream-task-execute.png
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/TaskDefinitionV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/TaskDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/TaskDefinitionServiceImplTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.xml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/ProjectDetailPage.java
  dolphinscheduler-ui/src/layouts/content/use-dataList.ts
  dolphinscheduler-ui/src/locales/en_US/menu.ts
  dolphinscheduler-ui/src/locales/zh_CN/menu.ts
  dolphinscheduler-ui/src/router/modules/projects.ts
  dolphinscheduler-ui/src/service/modules/task-definition/index.ts
  dolphinscheduler-ui/src/service/modules/task-definition/types.ts
  dolphinscheduler-ui/src/views/projects/task/definition/batch-task.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/components/start-modal.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/components/use-start.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/components/use-version.ts
  dolphinscheduler-ui/src/views/projects/task/definition/components/version-modal.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/index.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/stream-task.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/types.ts
  dolphinscheduler-ui/src/views/projects/task/definition/use-stream-table.ts
  dolphinscheduler-ui/src/views/projects/task/definition/use-table.ts
  dolphinscheduler-ui/src/views/projects/task/definition/use-task.ts
Labels: UI, backend, test, DSIP, e2e, document

#16402 [Doc-16403] simplify k8s deploy steps
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: improvement, document

#16126 [Feature-16127] Support emr serverless spark
  docs/docs/en/guide/task/aliyun-serverless-spark.md
  docs/docs/zh/guide/task/aliyun-serverless-spark.md
  docs/img/tasks/demo/aliyun_serverless_spark_1.png
  docs/img/tasks/demo/aliyun_serverless_spark_2.png
  docs/img/tasks/demo/aliyun_serverless_spark_3.png
  docs/img/tasks/demo/aliyun_serverless_spark_4.png
  dolphinscheduler-api/src/main/resources/task-type-config.yaml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/AliyunServerlessSparkClientWrapper.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/AliyunServerlessSparkConstants.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/AliyunServerlessSparkDataSourceChannel.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/AliyunServerlessSparkDataSourceChannelFactory.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/AliyunServerlessSparkUtils.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/param/AliyunServerlessSparkConnectionParam.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/param/AliyunServerlessSparkDataSourceParamDTO.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/param/AliyunServerlessSparkDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/test/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/AliyunServerlessSparkDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-all/pom.xml
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/enums/DbType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-aliyunserverlessspark/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/task/aliyunserverlessspark/AliyunServerlessSparkParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/task/aliyunserverlessspark/AliyunServerlessSparkTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/task/aliyunserverlessspark/AliyunServerlessSparkTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/task/aliyunserverlessspark/AliyunServerlessSparkTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/task/aliyunserverlessspark/AliyunServerlessSparkTaskException.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/task/aliyunserverlessspark/RunState.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-aliyunserverlessspark/src/test/java/org/apache/dolphinscheduler/plugin/task/aliyunserverlessspark/AliyunServerlessSparkTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/aliyun_serverless_spark.png
  dolphinscheduler-ui/public/images/task-icons/aliyun_serverless_spark_hover.png
  dolphinscheduler-ui/src/locales/en_US/datasource.ts
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/datasource.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/service/modules/data-source/types.ts
  dolphinscheduler-ui/src/store/project/task-type.ts
  dolphinscheduler-ui/src/store/project/types.ts
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-aliyun-serverless-spark.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasource.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-aliyun-serverless-spark.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
  tools/dependencies/known-dependencies.txt
Labels: UI, backend, test, document, 3.3.0

#16416 [Chore][Hotfix] Change docker-compose to docker compose in ci
  .github/workflows/cluster-test/mysql_with_mysql_registry/start-job.sh
  .github/workflows/cluster-test/mysql_with_zookeeper_registry/start-job.sh
  .github/workflows/cluster-test/postgresql_with_postgresql_registry/start-job.sh
  .github/workflows/cluster-test/postgresql_with_zookeeper_registry/start-job.sh
Labels: CI&CD, chore

#16412 [Fix-16410] wrong env in values.yaml
  deploy/kubernetes/dolphinscheduler/README.md
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: first time contributor, kubernetes, document, ready-to-merge

#16422 [Improvement-16421]remove duplicate code of AliyunServerlessSparkDataSourceProcessor
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-aliyunserverlessspark/src/main/java/org/apache/dolphinscheduler/plugin/datasource/aliyunserverlessspark/param/AliyunServerlessSparkDataSourceProcessor.java
Labels: improvement, backend

#16413 [DSIP-60][Http task plugin] Refactor http task plugin
  docs/docs/en/guide/task/http.md
  docs/docs/zh/guide/task/http.md
  docs/img/tasks/demo/http_post.png
  docs/img/tasks/demo/http_task01.png
  docs/img/tasks/icons/http.png
  docs/img/tasks/icons/http_get.png
  dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/java/org/apache/dolphinscheduler/api/test/utils/RequestClient.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/LoginControllerTest.java
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/HttpCheckCondition.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/HttpMethod.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/OkHttpRequestHeaderContentType.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/OkHttpRequestHeaders.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/model/OkHttpResponse.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OkHttpUtils.java
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-okhttp.txt
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/TemplateMethodTransformer.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/BaseHttpTemplateLoopTaskExecutor.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/HttpLoopTaskDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/HttpLoopTaskInstanceInfo.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/HttpLoopTaskMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/method/HttpLoopTaskCancelTaskMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/method/HttpLoopTaskQueryStatusMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/method/HttpLoopTaskSubmitTaskMethodDefinition.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/CancelTemplateMethodTransformer.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/HttpTaskDefinitionParser.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/QueryStateTemplateMethodTransformer.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/SubmitTemplateMethodTransformer.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/loop/template/http/parser/HttpTaskDefinitionParserTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpMethod.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpParametersType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpProperty.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpRequestMethod.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpTaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/test/java/org/apache/dolphinscheduler/plugin/task/http/HttpParametersTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/test/java/org/apache/dolphinscheduler/plugin/task/http/HttpTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-http.ts
  tools/dependencies/known-dependencies.txt
Labels: UI, backend, test, DSIP, e2e, document

#16425 [Improvement-16426] Delete the TaskGroupQueue in release method
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/taskgroup/TaskGroupCoordinator.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/taskgroup/TaskGroupCoordinatorTest.java
Labels: improvement, backend, test

#16429 [Fix-16428] only admin user can grant datasource
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
Labels: bug, backend, test

#16432 [Fix-16424] K8sUtils#jobExist may cause huge memory usage
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/K8sUtils.java
Labels: bug, first time contributor, backend

#16379 [Fix-16374][dolphinscheduler-alert] Fix DingTalk replace the atUserIds parameter with atDingtalkIds
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-dingtalk/src/main/java/org/apache/dolphinscheduler/plugin/alert/dingtalk/DingTalkAlertChannelFactory.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-dingtalk/src/main/java/org/apache/dolphinscheduler/plugin/alert/dingtalk/DingTalkParamsConstants.java
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-dingtalk/src/main/java/org/apache/dolphinscheduler/plugin/alert/dingtalk/DingTalkSender.java
  dolphinscheduler-ui/src/locales/en_US/security.ts
  dolphinscheduler-ui/src/locales/zh_CN/security.ts
Labels: bug, UI, backend

#16439 [Chore] Add E2E-K8S-Result to mergeable check
  .asf.yaml
  .github/workflows/e2e-k8s.yml
Labels: CI&CD, e2e, chore

#16463 [Fix-16464] [pom] fix parent pom plugin config error
  pom.xml
Labels: bug, first time contributor, backend, test

#16461 [Fix-16382] Fix the bug of async master task casthread pool invocations ramp-up
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java
Labels: bug, backend, ready-to-merge

#16476 [Fix-16475][UI] Can't SET Timing successful in Workflow Definition grid
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: bug, first time contributor, UI, ready-to-merge

#16498 [Fix-16492][alert] FeiShuSender Exception.getMessage is null
  dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-feishu/src/main/java/org/apache/dolphinscheduler/plugin/alert/feishu/FeiShuSender.java
Labels: bug, first time contributor, backend

#16493 [Doc-16490] Changed some notes about python gateway service
  docs/docs/en/guide/installation/standalone.md
  docs/docs/zh/guide/installation/standalone.md
Labels: bug, first time contributor, document

#16488 [Improvement-16487][Master] Improve the dependent result for workflow dependency tasks
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
Labels: first time contributor, improvement, backend

#16504 [Improvement-16501][dolphinscheduler-api]typo in Status.java（#16501）
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
Labels: first time contributor, improvement, backend, 3.3.0

#16495 [Fix-15961] [UI] Rename pythonCommand to pythonLauncher in pytorch task.
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-pytorch.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-pytorch.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: bug, first time contributor, UI

#16538 [Improvement-16537][API] Fix typo on api workflow parallel backfill
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/BackfillWorkflowExecutorDelegate.java
Labels: improvement, backend, ready-to-merge, 3.3.0

#16536 [Doc-16535] remove doc of extra ssh task node type
  docs/configs/docsdev.js
Labels: bug, document

#16547 [Chore] Remove staleness code owner
  .github/CODEOWNERS
Labels: CI&CD, chore

#16545 [Improvement-16546][Master] Add repeatTriggerWorkflowInstance/triggerFromFailureTasks/triggerFromSuspendTasks in IWorkflowControlClient
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/RecoverFailureTaskInstanceExecutorDelegate.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/RecoverSuspendedWorkflowInstanceExecutorDelegate.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/RepeatRunningWorkflowInstanceExecutorDelegate.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/IWorkflowControlClient.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/workflow/WorkflowInstanceRecoverFailureTasksRequest.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/workflow/WorkflowInstanceRecoverFailureTasksResponse.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/workflow/WorkflowInstanceRecoverSuspendTasksRequest.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/workflow/WorkflowInstanceRecoverSuspendTasksResponse.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/workflow/WorkflowInstanceRepeatRunningRequest.java
  dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/workflow/WorkflowInstanceRepeatRunningResponse.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/trigger/AbstractWorkflowInstanceTrigger.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/trigger/WorkflowInstanceRecoverFailureTaskTrigger.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/trigger/WorkflowInstanceRecoverSuspendTaskTrigger.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/trigger/WorkflowInstanceRepeatTrigger.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/rpc/WorkflowControlClient.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/it/WorkflowOperator.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/it/cases/WorkflowInstanceRecoverFailureTaskIT.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/it/cases/WorkflowInstanceRepeatRunningIT.java
  dolphinscheduler-master/src/test/resources/it/recover_failure_tasks/failure_workflow_with_two_serial_fake_task.yaml
  dolphinscheduler-master/src/test/resources/it/repeat_running/failed_workflow_with_one_fake_task_failed.yaml
  dolphinscheduler-master/src/test/resources/it/repeat_running/success_workflow_with_one_fake_task_success.yaml
  dolphinscheduler-master/src/test/resources/it/repeat_running/success_workflow_with_task_only.yaml
Labels: improvement, backend, test

#16549 [Chore] Remove unsupported feature in README.md
  README.md
  README_zh_CN.md
Labels: document, 3.3.0, chore

#16553 [Chore] Improve release doc
  .gitignore
  docs/docs/en/contribute/release.md
  docs/docs/zh/contribute/release.md
  tools/release/README.md
  tools/release/github/changelog.py
  tools/release/release.py
Labels: improvement, document, chore
