Repository apache/dolphinscheduler, pull requests merged in 2024-03, with the labels that each got.

#15652 [Bug] Fix can modify file which is not under resource path
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ResourcesService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ResourcesControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
  dolphinscheduler-ui/src/service/modules/resources/index.ts
  dolphinscheduler-ui/src/views/projects/list/components/use-worker-group.ts
  dolphinscheduler-ui/src/views/projects/list/use-table.ts
Labels: bug, UI, backend, ready-to-merge, 3.2.2

#15664 [Doc] Fix ci docs check timeout issue
  .github/workflows/docs.yml
Labels: CI&CD, ready-to-merge, 3.2.2, chore

#15654 chore: modify some CODEOWNERS
  .github/CODEOWNERS
Labels: CI&CD, minor, ready-to-merge, 3.2.2, chore

#15659 [TEST] fix log server related test
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/LoggerServiceTest.java
Labels: improvement, backend, ready-to-merge, 3.3.0

#15660 [Doc][remote shell] missing remote shell doc for version 3.2.1
  docs/configs/docsdev.js
Labels: improvement, document, ready-to-merge, 3.2.2

#15670 [Bug] [Worker] fix: create linux user with home dir
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
Labels: bug, first time contributor, backend, ready-to-merge, 3.2.2

#15428 [Improvement][UT] Improve Worker runner coverage
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerTaskExecutorFactoryBuilder.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/listener/TaskInstanceExecutionEventAckListenFunctionManager.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/listener/TaskInstanceExecutionFinishEventAckListenFunction.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/listener/TaskInstanceExecutionInfoEventAckListenFunction.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/listener/TaskInstanceExecutionRunningEventAckListenFunction.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/operator/TaskInstanceDispatchOperationFunction.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/operator/TaskInstanceKillOperationFunction.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/operator/TaskInstanceOperationFunctionManager.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/operator/UpdateWorkflowHostOperationFunction.java
  dolphinscheduler-worker/src/test/java/org/apache/dolphinscheduler/server/worker/runner/listener/TaskInstanceExecutionEventAckListenFunctionTest.java
  dolphinscheduler-worker/src/test/java/org/apache/dolphinscheduler/server/worker/runner/operator/TaskInstanceOperationFunctionTest.java
Labels: improvement, backend, ready-to-merge, 3.3.0

#15624 [bug] [dolphinscheduler-ui] UI timed scheduler Improvement
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: bug, UI, ready-to-merge, 3.2.2

#15684 [Bug] fix UT test
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ResourcesServiceTest.java
Labels: bug, backend, ready-to-merge, 3.2.2

#15678 [Fix-15639] [Master] parameterPassing is null case NPE
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/model/DependentItem.java
Labels: bug, backend, ready-to-merge

#15681 [Improvement-15603][API] When removing or modifying a workflow the system can check if there any tasks depend on it.
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectWorkerGroupController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkFlowLineageController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkFlowLineageService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkFlowLineageServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/WorkFlowLineageControllerTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskMainInfo.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.xml
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/service/modules/lineages/index.ts
  dolphinscheduler-ui/src/service/modules/lineages/types.ts
  dolphinscheduler-ui/src/views/projects/components/dependencies/dependencies-modal.tsx
  dolphinscheduler-ui/src/views/projects/components/dependencies/use-dependencies.ts
  dolphinscheduler-ui/src/views/projects/task/definition/batch-task.tsx
  dolphinscheduler-ui/src/views/projects/task/definition/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-context-menu.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-toolbar.tsx
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/table-action.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/timing/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/timing/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
  dolphinscheduler-ui/src/views/projects/workflow/timing/index.tsx
Labels: UI, improvement, backend, ready-to-merge, 3.2.2

#15686 [Fix-15679][UI] fix switch status button not show correctly
  dolphinscheduler-ui/src/views/resource/task-group/option/use-table.ts
Labels: bug, UI, ready-to-merge, 3.2.2

#15693 [Improvement-15692][task-datasync] rewrite the mockito test file for DatasyncTaskTest.
  dolphinscheduler-task-plugin/dolphinscheduler-task-datasync/src/test/java/org/apache/dolphinscheduler/plugin/task/datasync/DatasyncTaskTest.java
Labels: improvement, backend, ready-to-merge, 3.2.2

#15695 [Improvement-15694][UI] After saving the task form the task node uses the wrong background color.
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/use-task-edit.ts
Labels: UI, improvement, ready-to-merge

#15689 [Fix][Master] Fix Potential danger in the event of a worker failover
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClientTest.java
Labels: bug, backend, ready-to-merge, 3.2.2

#15712 [Improvement-15707][Master] Work out the issue that the workflow with a task dependency couldn't work well.
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/ProcessInstanceDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/ProcessInstanceDaoImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapperTest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
Labels: improvement, backend, ready-to-merge, 3.2.2

#15716 [bug][Plugins]fix word spell error in readme.md
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/README.md
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/README.md
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-zookeeper/README.md
Labels: bug, minor, document, ready-to-merge, 3.2.2

#15677 Fix the NullPointerException when "start param to overwrite global param"
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/process/ProcessServiceTest.java
Labels: bug, first time contributor, backend, ready-to-merge, 3.2.2

#15724 [Improvement-15723][UI] Work out the issue that project preferences doesn't replace all places that they need to affect.
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/start-modal.tsx
Labels: UI, improvement, ready-to-merge

#15727 [Improvement-15725][UI] The default option of project preferences can be clearable.
  dolphinscheduler-ui/src/views/projects/preference/use-form.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/detail-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/start-modal.tsx
Labels: UI, improvement, ready-to-merge, 3.2.2

#15710 [TEST] fill up access token test
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AccessTokenServiceTest.java
Labels: improvement, backend, ready-to-merge, 3.3.0

#15720 [Improvement-15719] Remove the useless methods in ProcessUtils
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/ProcessUtils.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/ProcessUtilsTest.java
Labels: improvement, backend, ready-to-merge, 3.3.0

#15680 [Fix] add black key for switch task
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtilsTest.java
Labels: bug, backend, ready-to-merge

#15735 [CI] Frontend ci require passed before merge
  .asf.yaml
  .github/workflows/frontend.yml
Labels: improvement, CI&CD, ready-to-merge, 3.2.2, chore

#15736 [Fix-15698][UI] close the definition when opened in the new tab
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-toolbar.tsx
Labels: bug, UI, ready-to-merge, 3.2.2

#15749 [CI] Fix frontend ci not trigger
  .github/workflows/frontend.yml
Labels: bug, CI&CD, ready-to-merge, 3.2.2, chore

#15743 [Improvement] Remove unused method
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapperTest.java
Labels: improvement, backend, ready-to-merge

#15730 [Bug] Disable delete a specific workflow version when exist workflow instance under this version which is not finish
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/ProcessDefinitionControllerTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/WorkflowExecutionStatus.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/ProcessInstanceDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/ProcessInstanceDaoImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/repository/impl/ProcessInstanceDaoImplTest.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15747 [Improvement] change js engine
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/pom.xml
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-delight-nashorn-sandbox.TXT
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtilsTest.java
  tools/dependencies/known-dependencies.txt
Labels: improvement, backend, ready-to-merge, 3.2.2

#15751 [Bug] Fix delay execution task will never be dispatched
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/GlobalTaskDispatchWaitingQueueLooper.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/operator/BaseTaskExecuteRunnableDispatchOperator.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15755 [Bug] Fix Switch logic task doesn't check the branch exist
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/switchtask/SwitchLogicTask.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15764 [Bug][Worker] Replace jre with jdk
  docs/docs/en/guide/task/java.md
  docs/docs/zh/guide/task/java.md
  dolphinscheduler-worker/src/main/docker/Dockerfile
Labels: improvement, backend, document, ready-to-merge, 3.2.2

#15776 [bug][ui] add missing datasource and update datasource id
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasource.ts
Labels: bug, UI, ready-to-merge, 3.2.2

#15777 [TEST] fill up alert group service test
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/AlertGroupServiceTest.java
Labels: improvement, backend, ready-to-merge, 3.3.0

#15773 [Bug] Fix TaskGroupCoordinator might cause OOM when there is a lot of waiting TaskGroupQueue
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/TaskGroupQueueDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskGroupQueueDaoImpl.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/repository/impl/TaskGroupQueueDaoImplTest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/taskgroup/TaskGroupCoordinator.java
Labels: bug, backend, ready-to-merge

#15780 [Improvement][RemoteLogging] Move init into loghandler
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/GcsRemoteLogHandler.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/OssRemoteLogHandler.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/log/remote/S3RemoteLogHandler.java
Labels: improvement, backend, minor, ready-to-merge
