Repository apache/dolphinscheduler, pull requests merged in 2024-10, with the labels that each got.

#16648 [Improvement-16647][UI][Workflow Instance] Remove deprecated workflow execution states
  dolphinscheduler-ui/src/common/common.ts
  dolphinscheduler-ui/src/common/types.ts
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
Labels: UI, improvement

#16681 [Fix-16680][ApiServer] Query project list paging error
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
Labels: bug, backend, ready-to-merge

#16616 [Improvement-16612][Master] For logical tasks on the Master, there should be support for dry run
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/MasterTaskExecutor.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/WorkflowOperator.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java
Labels: improvement, backend, test, priority:high, ready-to-merge

#16693 [Fix-16692][Doc] Incorrect docs of howto
  docs/configs/docsdev.js
Labels: bug, document

#16609 [Feature-16608][Doc] Add Security Model
  docs/configs/docsdev.js
  docs/docs/en/contribute/join/security-model.md
  docs/docs/en/contribute/join/security.md
  docs/docs/zh/contribute/join/security-model.md
  docs/docs/zh/contribute/join/security.md
Labels: feature, document

#16708 [CI] [Hotfix] Fix docs dead link error
  docs/docs/en/contribute/join/document.md
  docs/docs/en/guide/datasource/athena.md
  docs/docs/en/guide/datasource/dameng.md
  docs/docs/en/guide/datasource/doris.md
  docs/docs/en/guide/datasource/hana.md
  docs/docs/en/guide/datasource/mysql.md
  docs/docs/en/guide/datasource/oceanbase.md
  docs/docs/en/guide/datasource/starrocks.md
  docs/docs/en/guide/demo.md
  docs/docs/en/guide/task/spark.md
  docs/docs/en/guide/task/sql.md
  docs/docs/zh/contribute/join/document.md
  docs/docs/zh/guide/datasource/athena.md
  docs/docs/zh/guide/datasource/dameng.md
  docs/docs/zh/guide/datasource/doris.md
  docs/docs/zh/guide/datasource/hana.md
  docs/docs/zh/guide/datasource/mysql.md
  docs/docs/zh/guide/datasource/oceanbase.md
  docs/docs/zh/guide/datasource/starrocks.md
  docs/docs/zh/guide/demo.md
  docs/docs/zh/guide/task/spark.md
  docs/docs/zh/guide/task/sql.md
Labels: document, chore

#16701 [Fix-16700] [doc] The Vertica datasource is under "Introduction to Function"
  docs/configs/docsdev.js
Labels: bug, first time contributor, document

#16593 [Improvement-16507] Remove spring-boot-starter-cache
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/WorkflowDefinitionLogMapper.java
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-log4j-api-2.11.2.txt
  dolphinscheduler-dist/release-docs/licenses/LICENSE-log4j-core-2.11.2.txt
  dolphinscheduler-master/pom.xml
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/pom.xml
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-it/pom.xml
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/pom.xml
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-zookeeper/pom.xml
  pom.xml
  tools/dependencies/known-dependencies.txt
Labels: first time contributor, improvement, backend

#16733 [Doc-16732][Development] development-environment-setup improvement
  docs/docs/en/contribute/development-environment-setup.md
  docs/docs/zh/contribute/development-environment-setup.md
Labels: improvement, document

#16715 [Fix-16705] [Built-in Parameter] Fix project name and definition name variable parameter not resolved
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/AbstractCommandHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/RecoverFailureTaskCommandHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/RunWorkflowCommandHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/WorkflowFailoverCommandHandler.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/runnable/TaskExecutionContextCreateRequest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/runnable/TaskExecutionRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/runnable/TaskExecutionRunnableBuilder.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionContextFactory.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteContext.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/GlobalTaskDispatchWaitingQueueLooperTest.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/GlobalTaskDispatchWaitingQueueTest.java
  dolphinscheduler-master/src/test/resources/it/start/workflow_with_built_in_param.yaml
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsService.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceTest.java
Labels: bug, backend, test

#16741 [Fix-16740][SeaTunnel-Task] fix can't submit resource center config file issue
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/test/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTaskTest.java
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
Labels: bug, UI, backend, test
