Repository apache/dolphinscheduler, pull requests merged in 2024-01, with the labels that each got.

#15367 [Improvement] Use Druid to split multiple sql
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/DataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-clickhouse/src/main/java/org/apache/dolphinscheduler/plugin/datasource/clickhouse/param/ClickHouseDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-dameng/src/main/java/org/apache/dolphinscheduler/plugin/datasource/dameng/param/DamengDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-db2/src/main/java/org/apache/dolphinscheduler/plugin/datasource/db2/param/Db2DataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/test/java/org/apache/dolphinscheduler/plugin/doris/param/DorisDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/src/main/java/org/apache/dolphinscheduler/plugin/datasource/hive/param/HiveDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-k8s/src/main/java/org/apache/dolphinscheduler/plugin/datasource/k8s/param/K8sDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/mysql/param/MySQLDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/mysql/param/MySQLDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oceanbase/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oceanbase/param/OceanBaseDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oracle/src/main/java/org/apache/dolphinscheduler/plugin/datasource/oracle/param/OracleDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-oracle/src/test/java/org/apache/dolphinscheduler/plugin/datasource/oracle/param/OracleDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-postgresql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/postgresql/param/PostgreSQLDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sagemaker/src/main/java/org/apache/dolphinscheduler/plugin/datasource/sagemaker/param/SagemakerDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/src/main/java/org/apache/dolphinscheduler/plugin/datasource/sqlserver/param/SQLServerDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-ssh/src/main/java/org/apache/dolphinscheduler/plugin/datasource/ssh/param/SSHDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-trino/src/main/java/org/apache/dolphinscheduler/plugin/datasource/trino/param/TrinoDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/datasource/zeppelin/param/ZeppelinDataSourceProcessor.java
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-druid.txt
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/utils/SqlSplitUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/utils/SqlSplitUtilsTest.java
  tools/dependencies/known-dependencies.txt
Labels: improvement, backend, ready-to-merge

#15384 [improvement-#15382][workFlow] adjust the sequence of alarm group and add validate
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/start-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/timing-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-form.ts
Labels: UI, improvement, 3.1.x, 4.0.0, ready-to-merge, 3.2.1, 3.3.0

#15223 [Bug][Registry] Optimizing waiting strategy
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterWaitingStrategy.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerWaitingStrategy.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/operator/TaskInstanceDispatchOperationFunction.java
Labels: bug, backend, ready-to-merge

#15385 [Doc]remove temporary markdown comments
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: document, ready-to-merge

#15395 [BUG] [DOC] doc write wrong,should be MinIO it's not MinION
  docs/docs/en/guide/resource/intro.md
  docs/docs/zh/guide/resource/intro.md
Labels: bug, first time contributor, document, ready-to-merge, 3.2.1

#15418 [Bug] [docs] doc MinIO write wrong #15394
  docs/docs/en/guide/resource/intro.md
  docs/docs/zh/guide/resource/intro.md
Labels: document

#15416 [Bug] [docs] doc MinIO write wrong #15394
  docs/docs/en/guide/resource/intro.md
  docs/docs/zh/guide/resource/intro.md
Labels: document

#15415 [Bug] [docs] doc MinIO write wrong #15394
  docs/docs/en/guide/resource/intro.md
  docs/docs/zh/guide/resource/intro.md
Labels: document

#15410 [Bug] [docs] doc MinIO write wrong #15394
  docs/docs/en/guide/resource/intro.md
  docs/docs/zh/guide/resource/intro.md
Labels: document

#15414 [Bug] [docs] doc MinIO write wrong #15394
  docs/docs/en/guide/resource/intro.md
  docs/docs/zh/guide/resource/intro.md
Labels: document

#15413 [Bug] [docs] doc MinIO write wrong #15394
  docs/docs/en/guide/resource/intro.md
  docs/docs/zh/guide/resource/intro.md
Labels: document

#15420 [Improvement][E2E]e2e improve add workflow httpTask e2e case
  .github/workflows/e2e.yml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowHttpTaskE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/common/HttpInput.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/HttpTaskForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/workflow-http/docker-compose.yaml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/workflow-http/mockserver-config.json
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-http.ts
Labels: UI, improvement, CI&CD, e2e, ready-to-merge, 3.3.0

#15427 [Bug] [Audit log] Fix Audit log UI query error
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/AuditLogMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/AuditLogMapperTest.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15391 Add config for defaultTenantEnabled
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/config/TenantConfig.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/config/WorkerConfig.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: improvement, backend, document, ready-to-merge

#15433 [Enhancement][API]Enhance mysql connection properties
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/main/java/org/apache/dolphinscheduler/plugin/datasource/mysql/param/MySQLDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/mysql/param/MySQLDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/mysql/utils/DataSourceUtilsTest.java
Labels: improvement, backend, priority:high, ready-to-merge, 3.2.1

#15450 [Feature] timed scheduler Improvement (#15449)
  docs/docs/en/guide/project/workflow-definition.md
  docs/docs/zh/guide/project/workflow-definition.md
  docs/img/new_ui/dev/project/workflow-list.png
  docs/img/new_ui/dev/project/workflow-time03.png
  docs/img/new_ui/dev/project/workflow-time04.png
  docs/img/scheduler_online.png
  docs/img/timeManagement.png
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProcessDefinition.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/table-action.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/components/timing-modal.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/index.tsx
  dolphinscheduler-ui/src/views/projects/workflow/definition/types.ts
  dolphinscheduler-ui/src/views/projects/workflow/definition/use-table.ts
Labels: feature, UI, backend, document, ready-to-merge, 3.3.0

#15470 [BUG][Task] fix java task classpath
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/main/java/org/apache/dolphinscheduler/plugin/task/java/JavaTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/test/java/org/apache/dolphinscheduler/plugin/task/java/JavaTaskTest.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15469 [Improvement][E2E] add e2e javatask case
  .github/workflows/e2e.yml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowJavaTaskE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/JavaTaskForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/task/TaskNodeForm.java
  dolphinscheduler-standalone-server/src/main/docker/Dockerfile
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-environment-name.ts
Labels: UI, improvement, backend, CI&CD, e2e, ready-to-merge, 3.3.0

#15270 [Bug][Master]serial_wait strategy workflow unable to wake up
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/ProcessInstanceDao.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/ProcessInstanceDaoImpl.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: bug, backend, ready-to-merge, 3.2.1

#14040 [bug] Exception when using host in ipv6 format
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-mysql/src/test/java/org/apache/dolphinscheduler/plugin/datasource/mysql/utils/DataSourceUtilsTest.java
Labels: bug, backend, 3.1.x, ready-to-merge, 3.2.1

#15377 [HotFix] Fix createTaskInstanceWorkingDirectory failed if the old path exist
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java
  dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/FileUtilsTest.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/ProcessUtils.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java
  dolphinscheduler-worker/src/test/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtilsTest.java
Labels: bug, backend, ready-to-merge

#15479 [Feature-15475][DinkyTask] DinkyTask supports Dinky-1.0.0 and common sql
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTaskConstants.java
  dolphinscheduler-ui/public/images/task-icons/dinky.png
  dolphinscheduler-ui/public/images/task-icons/dinky_hover.png
Labels: feature, UI, backend, ready-to-merge

#15499 [Bug] Fix notify failover WorkflowInstance will cause NPE
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, ready-to-merge

#15501 [Doc-15500][Task] Update cli opts of spark and flink
  docs/docs/en/guide/task/flink.md
  docs/docs/en/guide/task/spark.md
  docs/docs/zh/guide/task/flink.md
  docs/docs/zh/guide/task/spark.md
Labels: improvement, document, ready-to-merge, 3.2.1

#15390 [Improvement][K8S]Optimize MDC for K8S tasks
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/impl/K8sTaskExecutor.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#15488 [Bug][Api] fix NullPointException when deleting a workflow instance (…
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15486 TaskGroupPriority only compare When TaskGroup is same
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/StandByTaskInstancePriorityQueue.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/queue/StandByTaskInstancePriorityQueueTest.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15504 [Improvement-15489][api]the vo object suffix,converted to uppercase
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataAnalysisController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/DataAnalysisService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/vo/ScheduleVO.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/vo/TaskDefinitionVO.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/vo/TaskInstanceCountVO.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/vo/WorkflowDefinitionCountVO.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/vo/WorkflowInstanceCountVO.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/DataAnalysisControllerTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/DataAnalysisServiceTest.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#15510 Set TaskGroupQueue updateTime when force start
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java
Labels: bug, backend, ready-to-merge

#15434 [HotFix] Fix PostgresqlDatabaseContainerProvider get Image is incorrect
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/PostgresqlDatabaseContainerProvider.java
Labels: bug, backend, ready-to-merge

#15447 [Improvement] Add guideline link into DolphinScheduler mail list
  README.md
  README_zh_CN.md
Labels: improvement, ready-to-merge, 3.2.1

#15511 [Improvement] Directly Throw exception when taskInstancy log path is empty which log need to be queried
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#15514 [Improvement] Throw IllegalArgumentException if parse time placeholder error
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parser/TimePlaceholderUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ParameterUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/parser/TimePlaceholderUtilsTest.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#15438 [improvement][api] Fix typo for controllers
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AlertGroupController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/BaseController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/CloudController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ClusterController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DataSourceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DynamicTaskTypeController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/K8sNamespaceController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/LoginController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/MonitorController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ProjectController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/SchedulerController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TaskGroupController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/TenantController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkFlowLineageController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkerGroupController.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/ProcessTaskRelationV2Controller.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/v2/ProjectV2Controller.java
  dolphinscheduler-api/src/main/resources/i18n/messages.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_en_US.properties
  dolphinscheduler-api/src/main/resources/i18n/messages_zh_CN.properties
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/controller/TenantControllerTest.java
Labels: improvement, backend, ready-to-merge, 3.2.1

#15516 [Doc][K8S] Add DS K8S Operator into k8s deployment character
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: document, ready-to-merge, 3.2.1

#14810 Fix the issue of disordered pagination queries caused by the same update time during workflow import
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
Labels: first time contributor, improvement, backend, ready-to-merge, 3.2.1

#15459 【Master】【Bug】Fix a bug, When the worker service offline, workerNodeInfo cache in master cannot delete the offline worker
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManagerTest.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15526 Change download url to archive in backend.yml
  .github/workflows/backend.yml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/AuditLogMapperTest.java
Labels: bug, backend, CI&CD, ready-to-merge

#12819 front: When you edit a task in the task definition list, the front task list is displayed
  dolphinscheduler-ui/src/views/projects/task/definition/use-task.ts
Labels: bug, first time contributor, UI, ready-to-merge, 3.2.1

#15536 Fix exception occur in RpcServer side, it will not be sent to RpcClient
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/main/java/org/apache/dolphinscheduler/extract/base/StandardRpcRequest.java
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/main/java/org/apache/dolphinscheduler/extract/base/config/NettyServerConfig.java
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/main/java/org/apache/dolphinscheduler/extract/base/server/ServerMethodInvokerImpl.java
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/test/java/org/apache/dolphinscheduler/extract/base/client/SingletonJdkDynamicRpcClientProxyFactoryTest.java
Labels: bug, backend, ready-to-merge, 3.2.1

#15531 [Improvement][HTTP] support customization of the JSON format in http body
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/main/java/org/apache/dolphinscheduler/plugin/task/http/HttpTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-http/src/test/java/org/apache/dolphinscheduler/plugin/task/http/HttpTaskTest.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-http.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-http.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/types.ts
Labels: UI, improvement, backend, ready-to-merge, 3.3.0

#15538 Exit JVM when OOM
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/jvm_args_env.sh
  dolphinscheduler-api/src/main/bin/jvm_args_env.sh
  dolphinscheduler-master/src/main/bin/jvm_args_env.sh
  dolphinscheduler-standalone-server/src/main/bin/jvm_args_env.sh
  dolphinscheduler-worker/src/main/bin/jvm_args_env.sh
Labels: improvement, backend, ready-to-merge, 3.2.1

#15539 chore: Docs change for 3.2.1 release
  .github/workflows/backend.yml
  deploy/docker/.env
  deploy/kubernetes/dolphinscheduler/Chart.yaml
  deploy/kubernetes/dolphinscheduler/README.md
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/configs/docsdev.js
  docs/docs/en/guide/expansion-reduction.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/en/guide/start/docker.md
  docs/docs/zh/guide/expansion-reduction.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/standalone.md
  docs/docs/zh/guide/start/docker.md
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql
  dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql
  dolphinscheduler-dao/src/main/resources/sql/soft_version
Labels: backend, CI&CD, chore, document
