Repository apache/dolphinscheduler, pull requests merged in 2024-06, with the labels that each got.

#16104 [Fix] chore: fix a typo
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/exceptions/ApiExceptionHandler.java
Labels: improvement, backend, 3.3.0

#16107 Fix task instance which status is dispatch will not be failover
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, priority:high, 3.2.2

#16110 Fix task instance which status is dispatch will not be failover
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
Labels: bug, backend, release cherry-pick

#16108 Fix task nodes under switch task will not be skipped
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/switchtask/SwitchLogicTask.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/log/TaskInstanceLogHeader.java
Labels: bug, backend, priority:high, 3.2.2

#16109 Fix task nodes under switch task will not be skipped
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/switchtask/SwitchLogicTask.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtils.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/utils/SwitchTaskUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/log/TaskInstanceLogHeader.java
Labels: bug, backend, release cherry-pick

#16118 Fix SqlServer split merge sql will miss ;
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/src/main/java/org/apache/dolphinscheduler/plugin/datasource/sqlserver/param/SQLServerDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/src/test/java/org/apache/dolphinscheduler/plugin/datasource/sqlserver/param/SQLServerDataSourceProcessorTest.java
Labels: bug, backend, priority:high

#16120 Fix SqlServer split merge sql will miss ; (#16118)
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/src/main/java/org/apache/dolphinscheduler/plugin/datasource/sqlserver/param/SQLServerDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-sqlserver/src/test/java/org/apache/dolphinscheduler/plugin/datasource/sqlserver/param/SQLServerDataSourceProcessorTest.java
Labels: backend

#16130 [CI][E2E] Improve e2e m1 chip local mode
  dolphinscheduler-e2e/README.md
  dolphinscheduler-e2e/dolphinscheduler-e2e-core/src/main/java/org/apache/dolphinscheduler/e2e/core/DolphinSchedulerExtension.java
  dolphinscheduler-e2e/pom.xml
Labels: improvement, e2e, 3.3.0

#16134 [Imporvement] Improve the MasterCofnig module comments of dolphinscheduler
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/config/MasterConfig.java
Labels: improvement, backend, 3.3.0

#16144 [Improvement][Worker] Rename workerZKPath to workerRegistryPath
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistryClient.java
Labels: improvement, backend, 3.3.0

#16151 [CI][UT] Fix flaky unit test
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/test/java/org/apache/dolphinscheduler/plugin/registry/jdbc/MysqlJdbcRegistryTestCase.java
Labels: improvement, backend, test, CI&CD, 3.3.0

#16149 [Imporve][Master] Refine the doselect annotation of the distributionpolicy
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobin.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/RandomSelector.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/RoundRobinSelector.java
Labels: improvement, backend, 3.3.0

#16160 [Fix] Fix typo: tpc -> tcp
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/main/java/org/apache/dolphinscheduler/extract/base/config/NettyServerConfig.java
Labels: improvement, backend, 3.3.0

#16161 [Chore] Improve ci check
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/auto-assign/auto-assign.yml
  .github/boring-cyborg.yml
  .github/workflows/pull-request-target-robot.yml
  docs/docs/en/contribute/join/pull-request.md
  docs/docs/zh/contribute/join/pull-request.md
Labels: improvement, CI&CD, document, 3.3.0

#16163 [Chore] update code owner
  .github/CODEOWNERS
Labels: CI&CD

#16171 [CI] Fix ci auto assign error
  .github/CODEOWNERS
  .github/actions/labeler/labeler.yml
  .github/boring-cyborg.yml
  .github/workflows/pull-request-target-robot.yml
Labels: bug, CI&CD, 3.3.0

#16158 [Chore] Add issue link tempate for IDEA
  .gitignore
  .idea/vcs.xml
  .licenserc.yaml
Labels: discussion, improvement, 3.3.0

#16152 [Bug] Fix condition task will cause workflow instance failed
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/condition/ConditionLogicTask.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/condition/ConditionLogicTaskPluginFactory.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ListenerEventAlertManager.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/alert/ListenerEventAlertManagerTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/DagHelperTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/ConditionsParameters.java
Labels: bug, backend, test, priority:high, 3.2.2

#16177 Fix condition task will cause workflow instance failed (#16152)
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/condition/ConditionLogicTask.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/task/condition/ConditionLogicTaskPluginFactory.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ListenerEventAlertManager.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/alert/ListenerEventAlertManagerTest.java
  dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/DagHelperTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/ConditionsParameters.java
Labels: backend

#16176 Fix DelayEntryTest might failed
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/queue/DelayEntryTest.java
Labels: bug, backend, test, priority:high

#16178 Fix HdfsStorageOperatorTest NPE
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/test/java/org/apache/dolphinscheduler/plugin/storage/hdfs/LocalStorageOperatorTest.java
Labels: bug, backend, test, priority:high

#16175 [CI] Fix CommandDaoImplTest might failed
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/repository/impl/CommandDaoImplTest.java
Labels: bug, backend, test, priority:high, 3.3.0

#16064 [Fix-16063] Fix admin login tenant unspecified issue after upgrade to v3.2.1
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/postgresql/dolphinscheduler_dml.sql
Labels: bug, first time contributor, backend, 3.2.2

#16172 [Chore] Disable discover composite indicator
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: improvement, backend, priority:low

#16185 [Cherry-Pick-3.2.2] cherry-pick #16064
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_dml.sql
  dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/postgresql/dolphinscheduler_dml.sql
Labels: backend, release cherry-pick

#16180 [Improvement-16182] Increase zk connect timeout
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/resources/application.yaml
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/repository/impl/CommandDaoImplTest.java
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/runner/queue/DelayEntryTest.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-zookeeper/src/main/java/org/apache/dolphinscheduler/plugin/registry/zookeeper/ZookeeperRegistryProperties.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: improvement, backend, test, 3.3.0

#16058 [Improvement][Helm] Make configmap of api/master/worker/alert configuration
  deploy/kubernetes/dolphinscheduler/README.md
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: improvement, kubernetes, document, ready-to-merge, 3.3.0

#16195 [Chore] Use testcontainer origin exposed port rather than generate random port
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/repository/impl/CommandDaoImplTest.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/test/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdRegistryTestCase.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/test/java/org/apache/dolphinscheduler/plugin/registry/jdbc/MysqlJdbcRegistryTestCase.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/test/java/org/apache/dolphinscheduler/plugin/registry/jdbc/PostgresqlJdbcRegistryTestCase.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-zookeeper/src/test/java/org/apache/dolphinscheduler/plugin/registry/zookeeper/ZookeeperRegistryTestCase.java
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/test/java/org/apache/dolphinscheduler/plugin/storage/hdfs/LocalStorageOperatorTest.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/jupiter/DolphinSchedulerDatabaseContainerExtension.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/mysql/DolphinSchedulerMysqlProfile.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/mysql/MysqlDatabaseContainerProvider.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/DolphinSchedulerPostgresqlProfile.java
  dolphinscheduler-tools/src/test/java/org/apache/dolphinscheduler/tools/datasource/postgresql/PostgresqlDatabaseContainerProvider.java
Labels: backend, test, priority:high

#16187 [CI] Bump up owasp version
  pom.xml
Labels: improvement, CI&CD, 3.3.0

#16199 [Fix-16191] Fix task cannot use workflow's environment
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/task/TaskCreateRequest.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkerGroupService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectWorkerGroupRelationServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecuteFunctionServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/WorkerGroupServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/EnvironmentUtils.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/WorkerGroupUtils.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/CommandMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/repository/impl/CommandDaoImplTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/utils/EnvironmentUtilsTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/utils/WorkerGroupUtilsTest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowJavaTaskE2ETest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/context/ExecutionContext.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StreamTaskExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/utils/WorkflowInstanceUtilsTest.java
  dolphinscheduler-scheduler-plugin/dolphinscheduler-scheduler-quartz/src/main/java/org/apache/dolphinscheduler/scheduler/quartz/ProcessScheduleTask.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend, test, e2e, priority:high

#16192 [Improvement-16125][dolphinscheduler-dist] Reduce binary distribution tarball file size
  dolphinscheduler-dist/pom.xml
  dolphinscheduler-dist/src/main/assembly/create-symlinks.sh
Labels: improvement, backend, priority:high, 3.2.2

#16205 [Chore] Disable composite indicator (#16172)
  dolphinscheduler-api/src/main/resources/application.yaml
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: backend

#16206 Fix task cannot use workflow's environment (#16199)
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/dto/task/TaskCreateRequest.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkerGroupService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectWorkerGroupRelationServiceImpl.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecuteFunctionServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/WorkerGroupServiceTest.java
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/EnvironmentUtils.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/WorkerGroupUtils.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/CommandMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/repository/impl/CommandDaoImplTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/utils/EnvironmentUtilsTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/utils/WorkerGroupUtilsTest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/WorkflowJavaTaskE2ETest.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/context/ExecutionContext.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StreamTaskExecuteRunnable.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/utils/WorkflowInstanceUtilsTest.java
  dolphinscheduler-scheduler-plugin/dolphinscheduler-scheduler-quartz/src/main/java/org/apache/dolphinscheduler/scheduler/quartz/ProcessScheduleTask.java
  dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java
Labels: backend, e2e, release cherry-pick

#16200 [Chore] Remove unused SQLIntegrityConstraintViolationException in JdbcOperator
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/JdbcOperator.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/test/java/org/apache/dolphinscheduler/plugin/registry/jdbc/JdbcRegistryTestCase.java
Labels: backend, test, 3.3.0, chore

#16208 [Fix-16174] Incorrect cluster installation guide.
  docs/docs/en/guide/installation/cluster.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/cluster.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  script/env/install_env.sh
  script/install.sh
Labels: bug, backend, document, 3.3.0

#16214 [Chore] Revert some incompatible change for 3.2.2
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-all/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-k8s/pom.xml
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-k8s/src/main/java/org/apache/dolphinscheduler/plugin/datasource/k8s/K8sClientWrapper.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-k8s/src/main/java/org/apache/dolphinscheduler/plugin/datasource/k8s/K8sDataSourceChannel.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-k8s/src/main/java/org/apache/dolphinscheduler/plugin/datasource/k8s/K8sDataSourceChannelFactory.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-k8s/src/main/java/org/apache/dolphinscheduler/plugin/datasource/k8s/param/K8sConnectionParam.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-k8s/src/main/java/org/apache/dolphinscheduler/plugin/datasource/k8s/param/K8sDataSourceParamDTO.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-k8s/src/main/java/org/apache/dolphinscheduler/plugin/datasource/k8s/param/K8sDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-k8s/src/test/java/org/apache/dolphinscheduler/plugin/datasource/k8s/K8sDataSourceProcessorTest.java
  dolphinscheduler-datasource-plugin/pom.xml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/datasource/DataSourcePage.java
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/enums/DbType.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/K8sTaskExecutionContext.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskMainParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/AbstractParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/K8sTaskParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/k8s/K8sTaskExecutorTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/main/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sParametersTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskTest.java
  dolphinscheduler-ui/src/service/modules/data-source/types.ts
  dolphinscheduler-ui/src/views/datasource/list/detail.tsx
  dolphinscheduler-ui/src/views/datasource/list/use-form.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-k8s.ts
Labels: UI, backend, e2e, priority:high, 3.2.2, chore

#16215 [Chore] [Cherry-Pick] cherry pick some pr to 3.2.2
  deploy/kubernetes/dolphinscheduler/README.md
  deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/configmap-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-alert.yaml
  deploy/kubernetes/dolphinscheduler/templates/deployment-dolphinscheduler-api.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
  docs/docs/en/guide/installation/cluster.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/cluster.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-k8s/src/test/java/org/apache/dolphinscheduler/plugin/task/k8s/K8sTaskTest.java
  script/env/install_env.sh
  script/install.sh
Labels: backend, document, release cherry-pick, 3.2.2

#16223 [Fix-16222] Fix worker overload will casue task failed
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/BaseTaskDispatcher.java
Labels: backend, priority:high, release cherry-pick

#16221 [Fix-16222] Fix worker overload will casue task failed
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/BaseTaskDispatcher.java
Labels: bug, priority:high, 3.2.2

#16219 [DSIP-51][Task] Remove unused pigeon task plugin
  docs/configs/docsdev.js
  docs/docs/en/guide/task/pigeon.md
  docs/docs/en/guide/upgrade/incompatible.md
  docs/docs/zh/guide/task/pigeon.md
  docs/docs/zh/guide/upgrade/incompatible.md
  docs/img/pigeon.png
  dolphinscheduler-api/src/main/resources/dynamic-task-type-config.yaml
  dolphinscheduler-api/src/main/resources/task-type-config.yaml
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/src/main/resources/common.properties
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-dist/release-docs/licenses/LICENSE-Java-WebSocket.txt
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/workflow/BaseWorkflowE2ETest.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/common/NavBarPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/ProjectDetailPage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowForm.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowRunDialog.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowSaveDialog.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/FileManagePage.java
  dolphinscheduler-e2e/dolphinscheduler-e2e-core/src/main/java/org/apache/dolphinscheduler/e2e/core/DolphinSchedulerExtension.java
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-api/src/main/java/org/apache/dolphinscheduler/plugin/storage/api/AbstractStorageOperator.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-all/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/pom.xml
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/readme.md
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonConfig.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonParameters.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonParamsConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonTaskChannel.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonTaskChannelFactory.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/main/resources/org/apache/dolphinscheduler/plugin/task/pigeon/config.properties
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/test/java/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonTaskTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-pigeon/src/test/resources/org/apache/dolphinscheduler/plugin/task/pigeon/PigeonTaskTest.json
  dolphinscheduler-task-plugin/pom.xml
  dolphinscheduler-ui/public/images/task-icons/pigeon.png
  dolphinscheduler-ui/public/images/task-icons/pigeon_hover.png
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/store/project/task-type.ts
  dolphinscheduler-ui/src/store/project/types.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/format-data.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/index.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/tasks/use-pigeon.ts
  dolphinscheduler-ui/src/views/projects/task/constants/task-type.ts
  dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag.module.scss
  dolphinscheduler-ui/src/views/projects/workflow/definition/tree/index.tsx
  tools/dependencies/known-dependencies.txt
Labels: UI, improvement, backend, test, e2e, document

#16238 [Fix-16211] Remove ExecutePath in buildJarCommand to fix Java Task in Jar Mode
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/main/java/org/apache/dolphinscheduler/plugin/task/java/JavaTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/test/java/org/apache/dolphinscheduler/plugin/task/java/JavaTaskTest.java
Labels: bug, backend, test, priority:high

#16241 [Fix-16211] Remove ExecutePath in buildJarCommand to fix Java Task in Jar Mode (#16238)
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/main/java/org/apache/dolphinscheduler/plugin/task/java/JavaTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-java/src/test/java/org/apache/dolphinscheduler/plugin/task/java/JavaTaskTest.java
Labels: bug, priority:high, release cherry-pick

#16236 [Chore] Remove unused dependentResult in TaskInstance
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/ProcessInstanceService.java
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstance.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/TaskInstanceUtils.java
Labels: backend, test, chore
