Repository apache/dolphinscheduler, pull requests merged in 2024-07, with the labels that each got.

#16216 [Chore] Force check ci on prapare/release branch
  .github/workflows/api-test.yml
  .github/workflows/codeql.yaml
  .github/workflows/e2e-k8s.yml
  .github/workflows/e2e.yml
  .github/workflows/frontend.yml
  .github/workflows/owasp-dependency-check.yaml
  .github/workflows/unit-test.yml
Labels: UI, improvement, CI&CD, e2e, 3.3.0

#16252 [Fix-16253] Fix JDBCRegistry refresh lock error
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/mapper/JdbcRegistryLockMapper.java
Labels: bug, backend, ready-to-merge

#16246 [Chore] Fix flaky e2e test
  .github/workflows/e2e.yml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/datasource/DataSourcePage.java
Labels: test, CI&CD, e2e, ready-to-merge

#16259 [Chore] add codeowner to help review k8s,meter,registry,helm, etc.
  .github/CODEOWNERS
Labels: CI&CD, chore

#16261 [Fix-16257][Doc] The incorrect document screenshot of the task parmas passing
  docs/img/new_ui/dev/parameter/priority_parameter01.png
  docs/img/new_ui/dev/parameter/priority_parameter02.png
Labels: improvement, document, chore

#16267 [Improvement-16266][Metrics] add heartbeat metrics
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/metrics/AlertServerMetrics.java
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/registry/AlertHeartbeatTask.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/MasterServerMetrics.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/task/MasterHeartBeatTask.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/metrics/WorkerServerMetrics.java
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/task/WorkerHeartBeatTask.java
Labels: improvement, backend, metrics, 3.3.0

#16239 [Chore] remove unuse resource query
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapper.xml
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapperTest.java
  dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/TaskDefinitionMapperTest.java
Labels: backend, test, chore

#15947 [Feature-16269][dinky-task]Supports dinky tasks to accept Prepare Params passed within a task or from a previous task
  docs/docs/en/guide/task/dinky.md
  docs/docs/zh/guide/task/dinky.md
  docs/img/tasks/demo/dinky_task_id.png
  dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java
Labels: feature, first time contributor, improvement, backend, document, priority:high, 3.3.0

#16275 [Fix-16272][Alert Server] Alarm server failed to send alarm
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/service/AbstractEventSender.java
Labels: bug, backend, priority:high, 3.2.2

#16284 [Chore] Alarm server failed to send alarm (#16275)
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/service/AbstractEventSender.java
Labels: backend, release cherry-pick, 3.2.2

#16289 [Fix-16290] Filter the NaN of system_cpu_usage/process_cpu_usage
  dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java
Labels: bug, backend, priority:high, 3.3.0

#16296 [Fix-16295][Task] Remote Shell Task plugin run error
  dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/main/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteExecutor.java
Labels: bug, backend

#16305 [Chore] Improve owasp dependency check
  .github/workflows/backend.yml
  .github/workflows/owasp-dependency-check.yaml
  .github/workflows/unit-test.yml
  pom.xml
Labels: backend, CI&CD, priority:high, chore

#16307 [Chore] Fix sonar cannot work
  .github/workflows/unit-test.yml
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/TaskTypeUtilsTest.java
  dolphinscheduler-tools/src/main/java/org/apache/dolphinscheduler/tools/lineage/MigrateLineageService.java
  pom.xml
Labels: backend, test, CI&CD, chore

#16312 [Improvement-16311] Polish installation docs
  .github/workflows/cluster-test/mysql_with_mysql_registry/Dockerfile
  .github/workflows/cluster-test/mysql_with_mysql_registry/deploy.sh
  .github/workflows/cluster-test/mysql_with_mysql_registry/dolphinscheduler_env.sh
  .github/workflows/cluster-test/mysql_with_mysql_registry/running_test.sh
  .github/workflows/cluster-test/mysql_with_mysql_registry/start-job.sh
  .github/workflows/cluster-test/mysql_with_zookeeper_registry/Dockerfile
  .github/workflows/cluster-test/mysql_with_zookeeper_registry/deploy.sh
  .github/workflows/cluster-test/mysql_with_zookeeper_registry/install_env.sh
  .github/workflows/cluster-test/mysql_with_zookeeper_registry/running_test.sh
  .github/workflows/cluster-test/mysql_with_zookeeper_registry/start-job.sh
  .github/workflows/cluster-test/postgresql_with_postgresql_registry/Dockerfile
  .github/workflows/cluster-test/postgresql_with_postgresql_registry/deploy.sh
  .github/workflows/cluster-test/postgresql_with_postgresql_registry/running_test.sh
  .github/workflows/cluster-test/postgresql_with_postgresql_registry/start-job.sh
  .github/workflows/cluster-test/postgresql_with_zookeeper_registry/Dockerfile
  .github/workflows/cluster-test/postgresql_with_zookeeper_registry/deploy.sh
  .github/workflows/cluster-test/postgresql_with_zookeeper_registry/running_test.sh
  .github/workflows/cluster-test/postgresql_with_zookeeper_registry/start-job.sh
  docs/docs/en/architecture/configuration.md
  docs/docs/en/faq.md
  docs/docs/en/guide/installation/cluster.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/zh/architecture/configuration.md
  docs/docs/zh/faq.md
  docs/docs/zh/guide/installation/cluster.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/standalone.md
  dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/start.sh
  dolphinscheduler-api/src/main/bin/start.sh
  dolphinscheduler-dist/src/main/assembly/dolphinscheduler-bin.xml
  dolphinscheduler-master/src/main/bin/start.sh
  dolphinscheduler-standalone-server/src/main/assembly/dolphinscheduler-standalone-server.xml
  dolphinscheduler-standalone-server/src/main/bin/start.sh
  dolphinscheduler-standalone-server/src/main/dist-bin/start.sh
  dolphinscheduler-worker/src/main/bin/start.sh
  script/dolphinscheduler-daemon.sh
  script/remove-zk-node.sh
  script/scp-hosts.sh
  script/start-all.sh
  script/status-all.sh
  script/stop-all.sh
Labels: improvement, backend, CI&CD, document

#16316 [Fix-16314][NOTICE] Correct year in NOTICE file
  NOTICE
  dolphinscheduler-dist/release-docs/NOTICE
Labels: improvement, backend

#16304 [Fix-16279] Support Java 8 date/time type `java.time.OffsetDateTime`
  dolphinscheduler-bom/pom.xml
  dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
  dolphinscheduler-dist/release-docs/LICENSE
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/model/JSONUtilsTest.java
  tools/dependencies/known-dependencies.txt
Labels: bug, backend, test, ready-to-merge

#16281 [Feature-16132][Task Plugin] support for oceanbase datax task
  dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/datasource/BaseConnectionParam.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxUtils.java
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datax.ts
Labels: feature, first time contributor, UI, backend, ready-to-merge

#16323 [Fix-16322] Set default registry-disconnect-strategy:strategy to stop
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/MasterServer.java
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-master/src/test/resources/application.yaml
  dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: bug, backend, test

#16123 [Improvement-16122][Authentication] Improvement k8s resource center statement
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/kubernetes.md
Labels: improvement, document, ready-to-merge, 3.3.0

#15647 [Fix-15644][ui] fix ui Failed to query list after editing file
  dolphinscheduler-ui/src/views/resource/components/resource/edit/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/edit/use-edit.ts
Labels: bug, first time contributor, UI, ready-to-merge

#16330 [Fix-16329] Fix offline workflow error
  dolphinscheduler-ui/src/layouts/content/use-dataList.ts
  dolphinscheduler-ui/src/locales/en_US/about.ts
  dolphinscheduler-ui/src/locales/en_US/index.ts
  dolphinscheduler-ui/src/locales/zh_CN/index.ts
  dolphinscheduler-ui/src/views/about/index.tsx
  dolphinscheduler-ui/src/views/projects/components/dependencies/use-dependencies.ts
Labels: bug, UI

#16325 [Fix-15519] Polish datax task docs
  docs/docs/en/guide/task/datax.md
  docs/docs/zh/guide/task/datax.md
Labels: bug, document, ready-to-merge

#16324 [Fix-16308] Fix query resources list paging error and docs.
  docs/docs/en/guide/installation/cluster.md
  docs/docs/en/guide/installation/kubernetes.md
  docs/docs/en/guide/installation/pseudo-cluster.md
  docs/docs/en/guide/installation/standalone.md
  docs/docs/zh/guide/installation/cluster.md
  docs/docs/zh/guide/installation/kubernetes.md
  docs/docs/zh/guide/installation/pseudo-cluster.md
  docs/docs/zh/guide/installation/standalone.md
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperator.java
Labels: bug, backend, document, ready-to-merge

#16334 [Improvement-16333][Helm] Support for updateStrategy
  deploy/kubernetes/dolphinscheduler/README.md
  deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-master.yaml
  deploy/kubernetes/dolphinscheduler/templates/statefulset-dolphinscheduler-worker.yaml
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: improvement, kubernetes, document, 3.3.0

#16335 [Chore] Improve frontend ci check
  .github/workflows/frontend.yml
  dolphinscheduler-ui/src/views/resource/components/resource/edit/index.tsx
  dolphinscheduler-ui/src/views/resource/components/resource/edit/use-edit.ts
Labels: UI, CI&CD, chore

#16342 [Fix-15927] Polish dependent task docs.
  docs/docs/en/guide/task/dependent.md
  docs/docs/zh/guide/task/dependent.md
Labels: improvement, document

#16341 [Improvement-15448] Remove redundant query in project list
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
  dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/UsersServiceTest.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/Project.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/ProjectProcessDefinitionCount.java
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.java
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper.xml
  dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProjectMapper.xml
  dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/resource/FileManagePage.java
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/list/use-table.ts
Labels: UI, improvement, backend, test, e2e

#16326 [Chore] 3.2.2-release doc
  docs/configs/index.md.jsx
  docs/configs/site.js
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: document, ready-to-merge, chore

#16348 [Fix-16347] Fix JdbcRegistry will get duplicate children
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-it/src/test/java/org/apache/dolphinscheduler/plugin/registry/RegistryTestCase.java
  dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/JdbcRegistry.java
Labels: bug, backend, test

#16349 [Chore] 3.2.2-doc Modify transfer characters
  docs/docs/en/history-versions.md
  docs/docs/zh/history-versions.md
Labels: document, ready-to-merge, 3.2.2, chore

#15878 [Fix-15828] fix expandListParameter
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/TaskConstants.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ParameterUtils.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ParameterUtilsTest.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java
  dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTaskTest.java
Labels: bug, backend, test, priority:middle

#16354 [Fix-16353][dao] Fix incorrect parameter name 'processLineages' in batchInsert method
  dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/ProcessTaskLineageMapper.java
Labels: bug, first time contributor, backend

#16356 [Fix-16346] Fix a bug that prevents re-uploading resource files
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/validator/resource/UpdateFileDtoValidator.java
Labels: bug, backend

#16361 [Improvement-16360] [Doc] Add project worker group auth doc
  docs/docs/en/guide/project/project-list.md
  docs/docs/zh/guide/project/project-list.md
  docs/img/new_ui/dev/project/project-worker-group-auth.png
Labels: improvement, document

#16371 [Chore] modify release doc
  docs/docs/en/contribute/release.md
  docs/docs/zh/contribute/release.md
Labels: improvement, document, chore

#16372 [Doc-16375] change front build command
  docs/docs/en/contribute/frontend-development.md
  docs/docs/zh/contribute/frontend-development.md
Labels: first time contributor, improvement, document

#16365 [Improvement-15448][api] Use Map to avoid traversing List repeatedly
  dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java
Labels: first time contributor, improvement, backend

#16389 [Fix-16388][Helm] fail to change updateStrategy from RollingUpdate to onDelete
  deploy/kubernetes/dolphinscheduler/README.md
  deploy/kubernetes/dolphinscheduler/values.yaml
Labels: bug, kubernetes, document, 3.3.0

#16398 [Chore] Stale issue improvement
  .github/workflows/stale.yml
Labels: CI&CD, chore
