Repository apache/dolphinscheduler, pull requests merged in 2025-03, with the labels that each got.

#17041 [Chore] Fix ci error
  .github/workflows/cluster-test/mysql_with_mysql_registry/dolphinscheduler_env.sh
  .github/workflows/cluster-test/mysql_with_zookeeper_registry/dolphinscheduler_env.sh
  .github/workflows/cluster-test/postgresql_with_postgresql_registry/dolphinscheduler_env.sh
  .github/workflows/cluster-test/postgresql_with_zookeeper_registry/dolphinscheduler_env.sh
  docs/docs/en/architecture/configuration.md
  docs/docs/zh/architecture/configuration.md
  dolphinscheduler-master/src/main/resources/application.yaml
  dolphinscheduler-master/src/test/resources/application.yaml
  dolphinscheduler-standalone-server/src/main/resources/application.yaml
  dolphinscheduler-worker/src/main/resources/application.yaml
Labels: backend, test, CI&CD, document, priority:high, chore

#17038 [Fix-17030] Fix one task might be duplicate trigger if exist multiple predecessors
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/IWorkflowExecutionGraph.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowExecutionGraph.java
Labels: bug, backend, priority:high, 3.3.0

#17039 [Fix-17036] Fix kerberos will not refresh in HdfsStorageOperator
  dolphinscheduler-storage-plugin/dolphinscheduler-storage-hdfs/src/main/java/org/apache/dolphinscheduler/plugin/storage/hdfs/HdfsStorageOperator.java
Labels: bug, backend, priority:high

#17051 [Fix-17050][Master] Fix workflow graph topology logical error
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowGraphTopologyLogicalVisitor.java
Labels: bug, backend, priority:high, 3.3.0

#17054 [Fix-17055] Fix nextBranch is empty in switch task
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/switchtask/SwitchLogicTask.java
  dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/SuccessorFlowAdjuster.java
  dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java
  dolphinscheduler-master/src/test/resources/it/start/workflow_with_one_failed_switch_two_fake_task.yaml
  dolphinscheduler-master/src/test/resources/it/start/workflow_with_one_success_switch_two_fake_task.yaml
Labels: bug, backend, test, priority:high

#17053 [Fix-17052][UI]fix ui-setting route with the same name
  dolphinscheduler-ui/src/router/modules/ui-setting.ts
Labels: bug, UI, priority:high, ready-to-merge

#17069 [Chore] Enable discussions in .asf.yaml
  .asf.yaml
Labels: CI&CD, chore

#17075 [Chore] Add notification in asf.yaml
  .asf.yaml
Labels: chore

#17076 [Chore] recover issue buttom in asf.yaml
  .asf.yaml
Labels: chore

#17072 [Fix-17071][UI] correct datasource list id
  dolphinscheduler-ui/src/views/datasource/list/use-columns.ts
Labels: bug, UI

#17070 [Fix-17023] Fix split and remove comment error in Doris task.
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/main/java/org/apache/dolphinscheduler/plugin/doris/param/DorisDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-doris/src/test/java/org/apache/dolphinscheduler/plugin/doris/param/DorisDataSourceProcessorTest.java
Labels: bug, first time contributor, backend, test

#17068 [Improvement-17065][UI][TASK] Improvement custom parameters read-only mode show
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-aliyun-serverless-spark.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasync.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dinky.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-dms.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-hive-cli.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-java.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-jupyter.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-k8s.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-kubeflow.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-openmldb.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-procedure.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-pytorch.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-remote-shell.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sagemaker.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-shell.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-spark.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-sql.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-zeppelin.ts
Labels: UI, improvement, 3.3.0

#17080 [Fix-17078] Revert 11726
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-presto/src/main/java/org/apache/dolphinscheduler/plugin/datasource/presto/param/PrestoDataSourceProcessor.java
Labels: bug, backend, priority:high

#17064 [Improvement-17063][UI][DATASYNC] Improvement datasync json parameter validate
  dolphinscheduler-ui/src/locales/en_US/project.ts
  dolphinscheduler-ui/src/locales/zh_CN/project.ts
  dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-datasync.ts
Labels: UI, improvement

#17081 [Fix-17073]Fix DataSource/JDBC connection failure
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-kyuubi/src/main/java/org/apache/dolphinscheduler/plugin/datasource/kyuubi/param/KyuubiDataSourceProcessor.java
  dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-kyuubi/src/test/java/org/apache/dolphinscheduler/plugin/datasource/kyuubi/param/KyuubiDataSourceProcessorTest.java
Labels: bug, first time contributor, backend, test

#17084 [Chore] Remove channelsLock on onChannelInactive to avoid deadlock
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/main/java/org/apache/dolphinscheduler/extract/base/client/NettyClientHandler.java
  dolphinscheduler-extract/dolphinscheduler-extract-base/src/main/java/org/apache/dolphinscheduler/extract/base/client/NettyRemotingClient.java
Labels: bug, backend, chore

#17095 [Chore] Fix release process
  .github/workflows/publish-nexus.yaml
  .github/workflows/publish-nexus/release-asf-settings.xml
  .github/workflows/publish-nexus/snapshot-asf-settings.xml
  docs/docs/en/contribute/release.md
  docs/docs/zh/contribute/release.md
  pom.xml
Labels: CI&CD, document, chore
